### ISSUE TITLE
Attempted to assign to readonly property in Safari OSX

### ISSUE THREAD

**Issue by jesperlandberg** [nuxt/nuxt.js#2895] opened 2018-02-24 18:44 UTC
Hi,

I have built a site/spa with nuxt and it works fine everywhere but Safari on Mac. I keep getting the error "attempted to assign to readonly property". Not sure if it is something with my code or with nuxt?

The error logs are pretty vague
![image](https://user-images.githubusercontent.com/3479734/36633744-fa26c4d6-199a-11e8-9b10-cf32a77dbee4.png)
![image](https://user-images.githubusercontent.com/3479734/36633747-07e5fe20-199b-11e8-81bf-e0e0a487b8d4.png)

Any idea what might be causing this?
The site is twotwentytwo.se

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2516">#c2516</a>)</em></sub></div>

**Comment by paulgv** [comment] 2018-02-24 20:34
Please provide some code to reproduce the issue.

**Comment by randyhoulahan** [comment] 2018-04-09 15:46
I have the same issue.  
https://coral.staging.cbd.int/
https://github.com/scbd/coral/blob/stg/nuxt.config.js
Any console.xx is an error.  I have attempted my own fix in the head.script however it appears to be out of scope or not run in time.

the error i get is:
        "serviceWorker" in navigator ? navigator.serviceWorker.register("/sw.js", {
            scope: "/"
        }).then(function(e) {
            window.$sw = e
        }).catch(function(e) {
            console.error("Service worker registration failed:", e)
        }) : console.warn("Service workers are not supported.")
On the console calls here.

**Comment by galvez** [comment] 2018-08-18 10:03
@jesperlandberg Close this as it seems to be a [known Safari bug][1]. Please also consider the [pwa module](https://github.com/nuxt-community/pwa-module) which handles most of this stuff for you. 

[1]: https://www.google.com.br/search?q=service+worker+%22to+assign+to+readonly+property%22+-nuxt

Please reopen the issue if you have more info.

**Closed by galvez** 2018-08-18 10:03 UTC
