### ISSUE TITLE
Error when run : npm run generate

### ISSUE THREAD

**Issue by gin280** [nuxt/nuxt.js#3004] opened 2018-03-13 09:12 UTC
Resource file path error message 404

**Comment by husayt** [comment] 2018-03-13 12:11
closing as there is not enough details. Please, provide more info to reopen

**Closed by husayt** 2018-03-13 12:11 UTC

**Comment by Pumpe** [comment] 2018-03-16 06:16
I kown @gin280 means; not a bug, this question at "urlJoin" Function, if you fix this, need use "replace" generate THML file`s resource file path by '/' to './'
