### ISSUE TITLE
Memory Exhaustion and/or Maximum Callstack using Nuxt SSR (universal) with a global Vue mixin and Vuetify

### ISSUE THREAD

**Issue by centerorbit** [nuxt/nuxt.js#7414] opened 2020-05-25 12:07 UTC
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://github.com/centerorbit/nuxt-plugin-mixin-memory-example](https://github.com/centerorbit/nuxt-plugin-mixin-memory-example)

### Steps to reproduce

Checkout the repro, start running a dev build with `npm run dev` in "universal" mode. Refresh the page about ~25 times.

In my bigger application, where I discovered this, refreshing about 3x does it, so the problem is worse the bigger your project.

The code uses file `./plugins/global.js` to register a simple global mixin that's used on `./pages/index.vue`

### What is expected ?

Server never crashes

### What is actually happening?

In this repro, server memory is exhausted and node crashes.

In my personal project it is used in a loop, and it causes an unrecoverable "Maximum call stack exceeded" error, which requires a node restart to recover.

### Additional comments?

I suspect this is an issue with Vuetify & Nuxt SSR... I created a vanilla-vanilla install, and wasn't able to readily reproduce, but it might be because the project is so slim that it would take an excessive amount of time to exhaust the memory. Vanilla here (https://github.com/centerorbit/nuxt-plugin-mixin-memory-example/tree/vanilla)

I'm not sure how to approach debugging this problem, so I'm open to suggestions and help!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10700">#c10700</a>)</em></sub></div>

**Comment by manniL** [comment] 2020-05-25 14:16
Duplicate of https://github.com/nuxt/nuxt.js/issues/7207

**Closed by manniL** 2020-05-25 14:16 UTC
Labels: cmty:bug-report
