### ISSUE TITLE
vue-template-compiler update

### ISSUE THREAD

**Issue by yuchonghua** [nuxt/nuxt.js#2321] opened 2017-12-05 00:55 UTC
Update vue-template-compiler when can it
Publish the [next version](https://github.com/nuxt/nuxt.js/issues/2142)

**Comment by yuchonghua** [comment] 2017-12-05 00:56
![image](https://user-images.githubusercontent.com/17898715/33584400-27abf7aa-d99a-11e7-8b5c-f3416998e848.png)
![image](https://user-images.githubusercontent.com/17898715/33584412-332d5bbe-d99a-11e7-88f1-020a5bed8318.png)

**Comment by yuchonghua** [comment] 2017-12-05 00:59
Because it is too much needed next version
，[a issues vue-template-compiler ](https://github.com/nuxt/nuxt.js/issues/2196)

**Comment by yeziZ** [comment] 2017-12-05 01:07
Look forward to more support
/ping @pimlie @alexchopin

**Comment by clarkdo** [comment] 2017-12-11 09:02
Thank you for your attention on Nuxt.js, we will try our best to release the new version asap!
Duplicate of 2142.

**Closed by clarkdo** 2017-12-11 09:02 UTC
