### ISSUE TITLE
bug(csr): error page layout not correctly applied

### ISSUE THREAD

**Issue by ac88** [nuxt/nuxt.js#2537] opened 2018-01-09 07:43 UTC
```javascript
//layouts\error.vue
{
layout: 'empty'
}

```

route to a 404 page.the error page layout is right

![error1](https://user-images.githubusercontent.com/20198303/34709829-da64d20c-f553-11e7-88e1-2970f0ef5ff1.jpg)

but  a page component has code error.

![error2](https://user-images.githubusercontent.com/20198303/34709838-e119e286-f553-11e7-8d85-b5d4cda36df6.jpg)

when route to this page.

the error page layout is  `layouts\default.vue`  not `layouts\error.vue`

```

```

at nuxt@v1.0.0-rc11 not this problem.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2205">#c2205</a>)</em></sub></div>

**Comment by unr** [comment] 2018-01-09 16:41
I'm having this same issue since upgrading to 1.0

**Comment by joealden** [comment] 2018-01-09 18:07
I am having the same issue.

I have two layouts in my `layout` directory, `default.vue` and `error.vue`.
The default layout is named `default-layout` and the error layout is named `nuxt-error`

When an error occurs, nuxt is rendering the error layout inside of the default layout as seen here:

![Screenshot](https://user-images.githubusercontent.com/10297243/34735499-9e3395f2-f567-11e7-99a6-774fc790645b.png)

**Comment by cesasol** [comment] 2018-01-10 08:09
Is an undocumented change, the error layout is no longer a layout and it works like a page

**Comment by joealden** [comment] 2018-01-10 08:15
@cesasol Oh really? Could you point me to the PR that was merged of this change please?

If you are right, it would have been nice to have that in the release notes, as I would consider it a breaking change!

**Comment by cesasol** [comment] 2018-01-10 09:33
I don't know, I upgraded, noted this and updated my code accordingly, yes it should be on the release notes but maybe not as a breaking change.

**Comment by joealden** [comment] 2018-01-10 10:19
@cesasol I did the same, and it all works fine, but it's not the best way to experience a change. I've had a quick look through merged PRs and none stood out to me that were linked to this, which still makes me doubt whether this is an intentional change or a regression.

Also, I would myself consider this breaking, as it broke my error page.

If someone can give me evidence that this is an intentional change, I'll be more than happy to make a PR updating the docs with this.

**Comment by husayt** [comment] 2018-03-08 16:36
This seems to be resolved now. Closing. Reopen if still happens.

**Comment by ac88** [comment] 2018-03-29 07:06
@husayt  it sitll happens at nuxt 1.4.0

**Comment by moltar** [comment] 2018-04-30 19:51
Get the same error.

If refreshing the URL with 404, the correct layout is applied.

If visiting the URL via a broken link within the same state, then the layout remains from the previous page (e.g. with nav and all).

**Comment by sinsong** [comment] 2018-06-29 14:55
I think we need a function that don't use any layout.

**Comment by luisfavila** [comment] 2018-12-05 15:19
> If refreshing the URL with 404, the correct layout is applied.
> If visiting the URL via a broken link within the same state, then the layout remains from the previous page (e.g. with nav and all).

I'm using nuxt-edge 2.4.0 and this still happens.

**Comment by saeed-bagheri** [comment] 2019-05-05 08:16
#5654

**Comment by saeed-bagheri** [comment] 2019-06-01 10:54
@Atinux  @pi0 
any news on this ?

**Comment by Leskd** [comment] 2019-07-04 07:42
any news on this ?

**Comment by louisluu** [comment] 2019-09-15 06:05
Encountered this issue in Nuxt 2.8.1

Any update?

**Comment by JulienAramino** [comment] 2019-09-16 08:06
Same on 2.9.2
The page 200.html is not generate properly

**Comment by KleinMaximus** [comment] 2019-09-17 22:05
Same on 2.9.2

**Comment by manniL** [comment] 2019-09-28 09:20
@clarkdo I've reassigned you here and closed #5654 as duplicate.

**Closed** 2019-09-30 08:44 UTC
Labels: bug, cmty:bug-report, pending

**Comment by vincent-kean** [comment] 2020-02-12 03:58
Still having the problem.. any update guys?

**Comment by rmirabelle** [comment] 2020-07-16 18:52
Still have this problem. SPA mode.  When calling `$nuxt.error`, the `error.vue` page is rendered inside the `default.vue` layout, ignoring the `empty` layout specified in the `error.vue` page itself.

pages/test.vue
```javascript
export default {
	name: 'test',
	async fetch() {
		try {
			//get some bad URL
		} catch(e) {
			this.$nuxt.error('This will render the error as a route within default.vue, ignoring the error page layout')
		}
	}
}
```

layouts/error.vue
```javascript
export default {
		layout: 'empty', //ignored
		props: {
			error: {
				type: Object,
				default: null
			}
		}
	}
```

layouts/empty.vue
```html
<template>
	<nuxt/>
</template>
```

**Comment by TimoTheus27** [comment] 2020-08-12 12:04
> Still have this problem. SPA mode. When calling `$nuxt.error`, the `error.vue` page is rendered inside the `default.vue` layout, ignoring the `empty` layout specified in the `error.vue` page itself.
> 
> pages/test.vue
> 
> ```js
> export default {
> 	name: 'test',
> 	async fetch() {
> 		try {
> 			//get some bad URL
> 		} catch(e) {
> 			this.$nuxt.error('This will render the error as a route within default.vue, ignoring the error page layout')
> 		}
> 	}
> }
> ```
> 
> layouts/error.vue
> 
> ```js
> export default {
> 		layout: 'empty', //ignored
> 		props: {
> 			error: {
> 				type: Object,
> 				default: null
> 			}
> 		}
> 	}
> ```
> 
> layouts/empty.vue
> 
> ```
> <template>
> 	<nuxt/>
> </template>
> ```

having exactly the same problem. if error is thrown the default layout applies and ```layout: 'empty'``` is ignored

**Comment by Menark** [comment] 2021-02-26 11:23
+1

**Comment by Menark** [comment] 2021-02-26 11:26
Still the same. Nuxt 2.13.0. Mode `universal`.

**Comment by clarkdo** [comment] 2021-02-26 12:20
Sorry for the late reply, the original fix is 2 years ago, so it might be some other root cause, can you open a new issue with mininal codebase ? We’ll look into it.

**Comment by Menark** [comment] 2021-03-05 17:43
Sorry, seems like i was wrong. Clean nuxt `2.13.0` project reprodution works fine, in contradistinction to my project. If i find the reason that will be not my code, i will create new issue.
