### ISSUE TITLE
Nuxt Dev Runner Using Almost 50% of Ram

### ISSUE THREAD

**Issue by ScarVite** [nuxt/nuxt.js#8209] opened 2020-10-15 06:19 UTC
### Versions

- nuxt: 2.14.6
- node: 14.13.1

### Reproduction
This is The Current [Version ](https://github.com/ScarVite/scarvite.de/tree/rewrite) Running on The Site.

### Steps to reproduce
Fork my Website Linked above, `npm run dev`, leave it unattended and unchaged for a bit and come back later and check ram usage via htop/ ps

### What is Expected?
Nuxt Running on About 200-300Mb (According to some Docs and Messages i found online)

### What is actually happening?
Nuxt is Starting and Showing that it is using about 200-300Mb of Ram.
I left it Unattended for a Day or Two and came back to see this
Nuxt is Using Almost 50% of my Server Ram.
My Server only has 4GB, so its not that big of a deal, but i still think it's way too much.
Here The Output of `ps aux --sort -rss` :
![Ram-Usage](https://user-images.githubusercontent.com/43887376/96083698-04151e00-0ebe-11eb-9b76-b4b2b5779222.png)
Here The `htop` Output:
![Htop](https://user-images.githubusercontent.com/43887376/96083964-869ddd80-0ebe-11eb-8d20-d66e77897e1e.png)

**Comment by manniL** [comment] 2020-10-15 06:59
Duplicate of https://github.com/nuxt/nuxt.js/issues/7412

**Closed by manniL** 2020-10-15 06:59 UTC
Labels: bug-report
