### ISSUE TITLE
Error with v-text

### ISSUE THREAD

**Issue by Exitialis** [nuxt/nuxt.js#1638] opened 2017-09-11 11:54 UTC
When i use v-text and refresh page i get an error "Cannot read property 'replace' of undefined"

![image](https://user-images.githubusercontent.com/7029837/30273159-7148dfd6-9700-11e7-9224-770c740757f2.png)
![image](https://user-images.githubusercontent.com/7029837/30273252-e42aa9d0-9700-11e7-9329-4df200038aba.png)

When I turn to this page with any other, then everything is ok. And when i change v-text to v-html everything is fine.

**Comment by Exitialis** [comment] 2017-09-11 12:22
@alexchopin I do not need help, it's a bug

**Comment by NicoPennec** [comment] 2017-09-11 13:48
Set a default value to `s` param: 
```
function escape(s= "") { 
...
}

```

**Comment by Exitialis** [comment] 2017-09-11 14:04
@NicoPennec i think you should say this to the developers nuxt, because this is not a bug in my code. As you can see, this error in node_modules folder.

**Comment by NicoPennec** [comment] 2017-09-11 14:32
`vue-server-renderer` module come from Vue Core: https://github.com/vuejs/vue/tree/dev/packages/vue-server-renderer

Can you share your complete `components/forms/vinput.vue` file? the template is truncated on your screenshoot...

**Comment by NicoPennec** [comment] 2017-09-11 14:33
link to https://github.com/nuxt/nuxt.js/issues/1327

**Comment by Exitialis** [comment] 2017-09-11 15:04
@NicoPennec 

vinput.vue file.

![image](https://user-images.githubusercontent.com/7029837/30281599-8717bd12-971b-11e7-86ad-1b204b530f33.png)

as I said, the problem is solved, when replacing the v-text with v-html, but still, it's a bug

**Comment by NicoPennec** [comment] 2017-09-11 16:48
It seems that the bug is probably on your side.

if `errors` is an empty array, then `errors[0]` will be undefined, because the `v-if` condition is true => `errors` is not null...

retry with `v-if="errors.lenght" v-text="errors[0]"`

**Comment by Exitialis** [comment] 2017-09-11 17:08
@NicoPennec 

Okay, but in other places where I also use v-text, I get same error. And as you wrote before, to fix this bug, you need to fix the build.js file in nuxt core and add 
```
function escape(s = "") { 
  ...
}
```

**Comment by Exitialis** [comment] 2017-09-11 17:13
@NicoPennec 

And if you don't know, how Vue.js and Nuxt.js works, please don't answer. You've already recommended that I fix the file in the node_modules folder, and if i change my condition in v-if, nothing will change. Thanks.

**Comment by pi0** [comment] 2017-09-11 18:02
> vue-server-renderer module come from Vue Core

I think you @NicoPennec is in a right direction. If we ever should consider not "handling `null` values with `v-text`" directive as a bug, we need to make minimal a reproduction code and report it to the correct repository ([vuejs/vue](https://github.com/vuejs/vue) in this case) not here, as it is not directly something with Nuxt. I'll try to make a PR fix for this soon.

**Comment by alexchopin** [comment] 2017-09-12 08:17
@Exitialis 
You are right, the label "help wanted" is a not good choice for your issue.
People (like @NicoPennec) from the Vue.js/Nuxt.js community should not spent their free time to resolve your issue posted in the wrong repository.

**Comment by Exitialis** [comment] 2017-09-12 08:36
@NicoPennec @alexchopin @pi0 
I did not want to offend anyone, and I also did not know that it was a bug with vue.js, since before updating the version of Nuxt to the RC version, everything worked fine. I apologize if I offended anyone.

**Comment by Atinux** [comment] 2017-09-12 09:05
Closing since it's related to Vue-Server-Renderer directly (https://github.com/vuejs/vue/issues/6572), in the meantime, make sure to not use `null` value into `v-text` @Exitialis by using a computed property.

Thanks to @NicoPennec for his help on this issue.

**Closed by Atinux** 2017-09-12 09:05 UTC
Labels: help wanted
