### ISSUE TITLE
TypeError: Cannot read property 'getMappings' of undefined

### ISSUE THREAD

**Issue by galvez** [nuxt/nuxt.js#1415] opened 2017-08-18 12:06 UTC
@pi0 @Atinux @alexchopin codebase works in latest stable, trying to update it to 1.0.0rc4. I updated all paths (`~components => ~/components` etc) and am getting this cryptic error.

<img width="997" alt="screen shot 2017-08-18 at 9 04 09 am" src="https://user-images.githubusercontent.com/12291/29458256-8c1f7c76-83f4-11e7-970e-08bd5107d81b.png">

**Comment by pi0** [comment] 2017-08-18 12:10
Hi. Please provide you project's repository or a glitch example to reproduce this error. But certainly is not a bug with nuxt itself as rc4 is being tested by many users...

**Comment by galvez** [comment] 2017-08-18 12:14
@pi0 Gotcha -- will do some more testing here. BTW I reached out to you over at pooya@pi0.ir (listed on your GH profile)

**Comment by alexchopin** [comment] 2017-10-28 12:42
Should be fixed with the last release

**Closed by alexchopin** 2017-10-28 12:42 UTC
Labels: need repro
