### ISSUE TITLE
Should generate dynamic route with required param

### ISSUE THREAD

**Issue by muhammad-abubakkar** [nuxt/nuxt.js#6092] opened 2019-07-19 13:12 UTC
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/muhammad-abubakkar/nuxtjs-router-bug](https://github.com/muhammad-abubakkar/nuxtjs-router-bug)

### Steps to reproduce

1. Clone repo
2. Install dependencies
3. run server
4. view .nuxt/router.js file

### What is expected ?

Expecting to generate required route
/space/:_id
/space/:_id/dashboard

### What is actually happening?

Generated routes
/space/:_id?
/space/:_id?/dashboard

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9510">#c9510</a>)</em></sub></div>

**Comment by pimlie** [comment] 2019-07-23 07:23
If the `_id` needs to be required for those components you have to provide a fallback for the `/space` route by eg adding `/pages/space.vue`. You can then redirect that to another page in eg asyncData if you dont need a seprate /space route.

This is just a feature of nuxt route building from page files on the file system. See #5874 for a bit more discussion.

Closing this as duplicate of #5874

**Closed by pimlie** 2019-07-23 07:23 UTC
Labels: cmty:bug-report
