### ISSUE TITLE
SyntaxError: nuxt/router.js: Support for the experimental syntax 'dynamicImport' isn't currently enabled

### ISSUE THREAD

**Issue by virskor** [nuxt/nuxt.js#6151] opened 2019-07-28 12:31 UTC
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/virskor/clodraForumFE](https://github.com/virskor/clodraForumFE)

### Steps to reproduce

yarn install
yarn dev

### What is expected ?

after update to 2.8.1, my NuxtJS application occurs problem.  it's running well before that.
my NodeJS version is v11.
and i am using yarn.

.barbelrc
{
  "env": {
    "test": {
      "presets": [
        [
          "@babel/preset-env",
          {
            "targets": {
              "node": "current"
            }
          }
        ]
      ]
    }
  }
}

after adding @babel/plugin-syntax-dynamic-import, problems still exsting.

### What is actually happening?

ERROR in ./.nuxt/router.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/virs/clodraForumFE/.nuxt/router.js: Support for the experimental syntax 'dynamicImport' isn't currently enabled (5:40):

  3 | import { interopDefault } from './utils'
  4 | 
> 5 | const _40f7591f = () => interopDefault(import('../pages/callback.vue' /* webpackChunkName: "pages/callback" */))
    |                                        ^
  6 | const _1216da14 = () => interopDefault(import('../pages/categories.vue' /* webpackChunkName: "pages/categories" */))
  7 | const _26c888f9 = () => interopDefault(import('../pages/categories/index.vue' /* webpackChunkName: "pages/categories/index" */))
  8 | const _06a675a1 = () => interopDefault(import('../pages/categories/_id.vue'

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9571">#c9571</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-07-28 12:49
Duplicate of https://github.com/nuxt/nuxt.js/issues/4839

**Closed by manniL** 2019-07-28 12:49 UTC
Labels: cmty:bug-report
