### ISSUE TITLE
Bug: Nuxt broke Enter transition

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1766] opened 2017-10-01 13:37 UTC
Hello guys. I am struggling with strange issue. It appears only in Nuxt, when using Vue without SSR all works fine!

I am using CleaveJS to mask my input and detect Credit Card type. Then I show animated Credit Card logo. When using Nuxt Enter transition is broken!!!

Here, try to type `34` or `44` or `22` - http://coordinated-color.surge.sh
This transition is broken ONLY on first appear. If you delete input and try to type it again - transition works just fine.
And the worst part that it appears only after I build and deploy this app! If you ran it locally all is working. 
First I thought it can be because image doesn't loaded in browser but transition triggered, but this is not true. Without SSR all working fine! 
Here's my code - https://github.com/iamdubx/cc-nuxt-issue

**Comment by iamdubx** [comment] 2017-10-01 16:43
Here's identical code with vue-cli, and it's working properly - http://broad-lead.surge.sh

**Comment by iamdubx** [comment] 2017-10-01 17:33
I just tried this scenario without any external libraries - and this is 100% Nuxt issue.

It's pure bug, guys. Here - http://coordinated-color.surge.sh/pure/
Try write `amex` or `visa`. No transition on Enter!!! With vue-cli all working like a charm!

I updated repo - https://github.com/iamdubx/cc-nuxt-issue

**Comment by joshuabryant** [comment] 2017-10-02 12:48
@iamdubx This might be a dumb suggestion, but could your issue actually be caused by the delay on initial image load? Once I've got the credit card images in cache, I don't have any issues with the transition.

As a test, maybe try putting the images elsewhere the page (to load them prior to the transition).

**Comment by iamdubx** [comment] 2017-10-02 13:01
@joshuabryant it could be. But the fact that without SSR all working properly, Vue waits until image load, then trigger transition. I guess Nuxt broke this waiting when server render it.

UPD. You right. If I put image on page, so they already loaded, then transition plays well. 
Any suggestion how to make Nuxt wait until image load? Without SSR it's working for some reason.

**Comment by iamdubx** [comment] 2017-10-02 13:05
I think I know why it's working with vue-cli. It inline images as data URI. 

For what reason Nuxt is not inline them? I thought it's configured to automaticly doing this.

**Comment by joshuabryant** [comment] 2017-10-02 13:37
I think it depends on the size of the asset. Also, I'm not sure about property values in the `style` attribute.

One option: you could move those SVG assets into Vue components (effectively inlining them).

**Comment by Atinux** [comment] 2017-11-02 10:42
![](https://github.trello.services/images/mini-trello-icon.png) [#1766](https://trello.com/c/zX0SJNQw/24-1766)

**Comment by Atinux** [comment] 2017-11-02 17:10
Closing since no-reproduction has been found

**Closed by Atinux** 2017-11-02 17:10 UTC
Labels: bug

**Comment by iamdubx** [comment] 2017-11-26 20:47
@Atinux but Alex told taht it's a known bug? https://github.com/nuxt/nuxt.js/issues/1796

I can make a reproduction, but it pretty straight forward. When I hit 404 template page there's no transition on Enter and Leave.

**Comment by iamdubx** [comment] 2017-11-26 20:48
But this particular issue is not related with 404 page transition, I don't know why @alexchopin  refer to it. Please close this issue again - https://github.com/nuxt/nuxt.js/issues/1796
