### ISSUE TITLE
[2.14.12] query params incorrectly decoded

### ISSUE THREAD

**Issue by awronski** [nuxt/nuxt.js#8550] opened 2020-12-24 13:45 UTC
### Versions

- nuxt: 2.14.12

### Reproduction

<details open>
After this fix #8494 urls are incorectly decoded.
</details>

### Steps to reproduce
https://1csq9.sse.codesandbox.io/?email=some%2Bv1%40email.com&token=DvtiwbIzry319e6KWimopA%3D%3D

### What is Expected?
Output:
```
DvtiwbIzry319e6KWimopA==
some+v1@email.com
```

### What is actually happening?
Output:
```
DvtiwbIzry319e6KWimopA
some v1@email.com
```

**Comment by awronski** [comment] 2020-12-24 14:01
one more broader example:

```
"%20!%22%23%24%25%26'()*%2B%2C-.%2F0123456789%3A%3B%3C%3D%3E%3F%40ABCDEFGHIJKLMNOPQRSTUVWXYZ%5B%5C%5D%5E_%60abcdefghijklmnopqrstuvwxyz%7B%7C%7D~"
```

Should be decoded to:
```
" !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~"
```

**Comment by awronski** [comment] 2020-12-24 14:14
It is quite interesting: `A%2B%3DB` is decoded to `A` insted of `A+=B`.
It truncates the parameter.

**Comment by awronski** [comment] 2020-12-24 15:38
@pi0 not ony `+` sign. Other signs are decoded incorectly too, like `=#$%&` and many many more.

**Comment by pi0** [comment] 2020-12-24 16:09
Hi @awronski thanks for reproduction. I can confirm the bug but still investigating where double encoding is happening. 


Also FYI  logic behind `+` behavior is in vue-router-next: https://github.com/vuejs/vue-router-next/blob/master/src/encoding.ts (ufo backported it but i currently disabled + behavior to be compatible with whatwg spec)

## Updates

- Tests with current version of ufo seem normalizing correctly for both cases: https://runkit.com/pi0/5fe4bb12df778f001a656d2d
- Disabling patch in `createRouter` still reproduces same bug
- fresh installation of nuxt < 2.14 throws warning `Error decoding "%%23%24%%26%2B,%2F%3A%3B%3D%3F%40". Leaving it intact` and not decoding

**Comment by awronski** [comment] 2020-12-24 16:17
@pi0 Thanks for you help.

Before `2.14.12` the `+` and `=` were working correct.

I did not test other characters, only did it now when investigating the problem. I just checked all ascii characters.

**Comment by awronski** [comment] 2020-12-26 10:22
@pi0 I created a test case for ufo. If I did everything correctly it fails for dozen characters:
https://runkit.com/awronski/5fe709480d6579001d2be3e6

**Comment by pi0** [comment] 2020-12-26 19:25
@awronski normalizeURL actually does encoding and seems normal :) (results should be compared to whatwg fetch using `new URL(..).href) `

**Comment by awronski** [comment] 2020-12-27 07:46
@pi0 I dont get it :)

`normalizeURL - Ensures URL is properly encoded`

So why it doesn't encode for example this?

`normalizeURL('test?query=A=B#hash')`
Result: `"test?query=A#hash"`

**Comment by pdl** [comment] 2021-01-06 16:26
@pi0 I don't see why encodeQueryValue should be implemented as anything other than encodeURIComponent, which is used elsewhere in ufo. You say "results should be compared to whatwg fetch using `new URL(..).href`" which is what ufo's normalize.test.ts does, so here's a patch which demonstrates the behaviour failing. Having encodeQueryValue simply `return encodeURIComponent(text);` causes this test to pass.

```
diff --git a/test/normalize.test.ts b/test/normalize.test.ts
index 128e5d5..99cd264 100644
--- a/test/normalize.test.ts
+++ b/test/normalize.test.ts
@@ -1,6 +1,8 @@
 // @ts-nocheck
 import { normalizeURL, withoutTrailingSlash } from '../src'

+const charactersBelow7F = Array.from(new Array(127)).map((_, i) => String.fromCharCode(i)).join('')
+
 describe('normalizeURL', () => {
   const tests = {
     'http://foo.com': 'http://foo.com',
@@ -62,7 +64,9 @@ describe('normalizeURL', () => {
     // 'http://-.~_!$&\'() * +,;=:% 40: 80 % 2f:::::: @example.com',
     'http://1337.net',
     'http://a.b-c.de',
-    'http://223.255.255.254'
+    'http://223.255.255.254',
+    'http://foo.com/foo?u=https%3A%2F%2Fexample.com%2Fpath%3Fq%3Dstring',
+    'http://foo.com/foo?x=' + encodeURIComponent(charactersBelow7F)
   ]

   for (const input in tests) {
```

**Comment by gabrielrobert** [comment] 2021-01-06 16:27
Some query strings are also removed: https://runkit.com/gabrielrobert/5ff5e3e629a0c2001334ae6a

In this example, `1234` should be preserved.

**Comment by pi0** [comment] 2021-01-06 17:31
@gabrielrobert Thanks for reproduction. Issue with query parsing (when value contains `=` char) resolved in 0.5.3 (/cc @awronski i believe this also solves your question re `'test?query=A=B#hash'` case)

@pdl Percent encoding set for query value is different than `encodeURIComponent` (see [spec](https://url.spec.whatwg.org/#query-percent-encode-set))

Update: `token` fixed ([sandbox](https://7yf7h.sse.codesandbox.io/?email=some%2Bv1%40email.com&token=DvtiwbIzry319e6KWimopA%3D%3D)) trying to figure out issue with `+` to `space`...

**Comment by pdl** [comment] 2021-01-07 08:32
@pi0 I don't believe you are correctly interpreting the spec. The *query percent-encode set* is the set of things which must be encoded in the query string as a whole, i.e. from the `?` to the end of the url or the fragment (indicated with `#`). It does not include `&?=`, all of which for web browsers have special meaning within the query string. In particular, your implementation will still break for a parameter with a value containing `&` .

**Comment by awronski** [comment] 2021-01-07 09:03
@pi0 In version  0.5.3 the plus sign is not encoded

`console.log(normalizeURL('test?query=A+B'))` returns "test?query=A+B"

Shouldn't it be `test?query=A%2BB`

**Comment by jeffalo** [comment] 2021-01-07 12:02
i can repro this on `2.14.6`, when fetching on client my plus signs are decoded properly, however on the server somewhere down the line they become spaces.

**Comment by pi0** [comment] 2021-01-07 13:17
@awronski Actually having plus (`+`) in query value is valid by both whatwg/rfc3986 and that's why ufo is doing so. But since vue-router uses plus as a shorthand for space ([src](https://github.com/vuejs/vue-router/blob/484d43a05138f2bff75ac858bf51a92b1a91362a/src/util/query.js#L62)), it makes problems.

I've enabled plus encoding back in 0.5.4 (https://github.com/nuxt-contrib/ufo/commit/82ab3f17de0088529bb25f1b0ed31ab09443ed26) to resolve this conflict with vue-router...

Updated sandbox: https://7yf7h.sse.codesandbox.io/?email=some%2Bv1%40email.com&token=DvtiwbIzry319e6KWimopA%3D%3D

Please use `yarn upgrade nuxt` | `npm up nuxt` to get the fix and if still other problems exist, use a new issue with reproduction to track.

**Closed by pi0** 2021-01-07 13:17 UTC
Labels: bug-report

**Comment by pedrolages-hotmart** [comment] 2021-01-25 13:46
@pi0 Hi! I'm currently having issues related to the "%20" caractere in the URL, the  " " is automatically turning into "+". I've just tested it on your sandbox(https://7yf7h.sse.codesandbox.io/?email=some%20aemail.com&token=DvtiwbIzry319e6KWimopA%3D%3D) and is also happening, so thats probably not a problem with my nuxt config. Can you help me?

**Comment by pi0** [comment] 2021-01-25 15:31
Issue to track: https://github.com/nuxt/nuxt.js/issues/8692
