### ISSUE TITLE
Refresh page on when clicking same page router link.

### ISSUE THREAD

**Issue by alanaasmaa** [nuxt/nuxt.js#4667] opened 2019-01-02 07:22 UTC
### What problem does this feature solve?

Hello,

I have tried to fight with this issue couple of times for now.

I have a page running on default layout.
The page contains a form that will switch form with success page after filling.

Sometimes users would like to refresh the page by clicking the logo/router-link.

But when current page is active the router wont refresh the page.
How could i do that?

I have tried to add :key to everywhere.
I found this but not working => https://github.com/nuxt/nuxt.js/issues/2285

### What does the proposed changes look like?

I think it would be good to have a option for template. That by default wont allow refreshing/reloading and when re clicking it reloads.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8391">#c8391</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-01-02 19:01
Duplicate of https://github.com/nuxt/nuxt.js/issues/2285

**Closed by manniL** 2019-01-02 19:01 UTC
Labels: cmty:feature-request
