### ISSUE TITLE
when async the withCredentials is flase

### ISSUE THREAD

**Issue by ajavaer** [nuxt/nuxt.js#4846] opened 2019-01-24 07:43 UTC
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/issues/new](https://github.com/nuxt/nuxt.js/issues/new)

### Steps to reproduce

.

### What is expected ?

when async send axios data  the withCredentials is flase
bug in client  it is true

### What is actually happening?

when async send axios data  the withCredentials is flase
bug in client  it is true

### Additional comments?

when async send axios data  the withCredentials is flase
bug in client  it is true

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8539">#c8539</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-01-24 11:01
@ajavaer Please provide more details and add a reproduction.

**Comment by PJLindsay** [comment] 2019-02-04 20:58
I think I am having an issue with this too. I have project using server session cookie (not jwt) on nuxt with an external API server. My Auth completely stopped working (it's completely broken) after I upgraded nuxt. It is not passing credentials to the server any more. I am not near my computer now but i will check later to see what version was working. I believe it broke when I upgraded

**Comment by PJLindsay** [comment] 2019-02-07 20:34
This is my config...

I believe this *was* working in nuxt v2.3.1 and now it is not working. I'm not 100% certain because I have a lot of nuxt projects, and I was in the middle of upgrading some from nuxt 1.x to nuxt 2.x -- when I go back through my git history for this project, it was set to nuxt-latest.... 

This is a bit speculative on my part about a possible bug with withCredentials, but I do know my Cookie Login flow used to work on this project and now it is completely broken.

I've tried rolling back to 2.3.1 (deleted node_modules & package-lock) and reset my package.json to point to nuxt 2.3.1, but the builder is showing 2.4.3 -- not sure how to roll the nuxt builder back to 2.3.1 -- it is also possible that I was running 1.44 (or newer)... 

```
    strategies: {
      local: {
        endpoints: {
          login: { url: '/login', method: 'post' },
          logout: { url: '/logout', method: 'post' },
          user: { url: '/user', method: 'get' }
        }
      },
      tokenRequired: false,
      tokenType: false
    }
...

  axios: {
    credentials: true, 
    proxy: true,
  },

  proxy: {
    '/api': { target: 'http://localhost:3000/api/v1', pathRewrite: {'^/api/': ''} },
    '/accounts': { target: 'https://accounts.mydomain.com/api/check-access/....' },
  }

```

**Comment by PJLindsay** [comment] 2019-02-07 20:48
@manniL if you want me to open a new issue with better detail, please let me know. I'd love to help to resolve this, and would definitely like to help to "tidy up" the documentation wrt Cookie Login flow (I find that the documentation is not explicit enough on what differences are needed for Cookie Login flow vs JWT login flow.

**Comment by PJLindsay** [comment] 2019-02-07 21:01
ok - so I rolled back to nuxt v1.4.4 (and made some small nuxt config changes for the build) and BOOM! my project is running again. I seriously think there's some sort of issue with Cookie Login flow on nuxt 2.x

**Comment by PJLindsay** [comment] 2019-02-15 17:00
is this issue reported in the wrong repo? perhaps it should be put in "auth-module" repo? https://github.com/nuxt-community/auth-module/issues @manniL let me know and I can make a new issue over there if you prefer (then we can close this) - I do know that without changing any code, withCredentials works in nuxt 1.4.4 but not in at least 3 versions of nuxt 2.x

**Comment by manniL** [comment] 2019-02-16 13:26
You are right! I think it would fit better in the repo of the auth module.

Don't forget that there are huge internal changes between 1.x and 2.x

**Closed by manniL** 2019-02-16 13:26 UTC
Labels: cmty:bug-report, status: need info, status: need repro
