### ISSUE TITLE
The resource declaration on the <head> tag was repeated

### ISSUE THREAD

**Issue by anhvandev** [nuxt/nuxt.js#6528] opened 2019-10-08 09:04 UTC
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[http://nolink](http://nolink)

### Steps to reproduce

npx create-nuxt-app web_005
cd web_005
yarn dev
![Screenshot_2.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/a3679ee0-e9aa-11e9-890d-916bbcbf48a6.png)

### What is expected ?

Give a reason and clear explanation for this phenomenon, if it is an error then fix it.

### What is actually happening?

The resources declared in the <head> tag such as css resources, scripts, etc. are being displayed repeatedly by the compiler. This causes resources to overwrite and reload multiple times, overloading low-profile devices.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9874">#c9874</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-10-08 09:44
Duplicate of https://github.com/nuxt/vue-meta/issues/465

**Closed by manniL** 2019-10-08 09:44 UTC
Labels: cmty:bug-report

**Comment by anhvandev** [comment] 2019-10-08 09:54
okay, copy that
