### ISSUE TITLE
I ask question again - for what is good such framework/technology?

### ISSUE THREAD

**Issue by nuxtdev** [nuxt/nuxt.js#9036] opened 2021-03-23 16:01 UTC
### Versions

- nuxt: 
- node: 

### Reproduction

Install standard hello world example.
Run ab -c 500 -n 2000 http://localhost:3000/
Get 250 requests per second. It is good result?
I ask question again - for what is good such framework/technology?
Only for blog?

This is ApacheBench, Version 2.3 <$Revision: 1879490 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 200 requests
Completed 400 requests
Completed 600 requests
Completed 800 requests
Completed 1000 requests
Completed 1200 requests
Completed 1400 requests
Completed 1600 requests
Completed 1800 requests
Completed 2000 requests
Finished 2000 requests

Server Software:        
Server Hostname:        localhost
Server Port:            3000

Document Path:          /
Document Length:        1367 bytes

Concurrency Level:      500
Time taken for tests:   7.812 seconds
Complete requests:      2000
Failed requests:        0
Total transferred:      3178000 bytes
HTML transferred:       2734000 bytes
Requests per second:    256.01 [#/sec] (mean)
Time per request:       1953.034 [ms] (mean)
Time per request:       3.906 [ms] (mean, across all concurrent requests)
Transfer rate:          397.27 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0   13   6.6     13      26
Processing:    69 1930  54.6   1947    2000
Waiting:        5 1016 497.7   1011    1922
Total:         69 1943  55.4   1963    2000

Percentage of the requests served within a certain time (ms)
  50%   1963
  66%   1968
  75%   1970
  80%   1971
  90%   1978
  95%   1982
  98%   1985
  99%   1986
 100%   2000 (longest request)

<details open>
<summary>Additional Details</summary>
<br>

</details>

**Comment by manniL** [comment] 2021-03-23 16:06
Duplicate of https://github.com/nuxt/nuxt.js/issues/9022

**Closed by manniL** 2021-03-23 16:06 UTC
Labels: bug-report
