### ISSUE TITLE
BrowserslistError: Unknown browser query `android all`

### ISSUE THREAD

**Issue by lenvonsam** [nuxt/nuxt.js#5952] opened 2019-06-18 07:38 UTC
just flower the offical doc to use the create-nuxt-app to create new project
```bash
npx create-nuxt-app pc-server
```
then 
```bash
cd pc-server
$ npm install
$ npm run dev
```
after this command, the nuxt occurs the errors
![image](https://user-images.githubusercontent.com/10168476/59662157-ed35bd00-91de-11e9-94e2-e2080801d742.png)

env:
npx ^6.9.0
node v10.8.0
npm ^6.9.0

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9378">#c9378</a>)</em></sub></div>

**Comment by Kinzi** [comment] 2019-06-18 08:27
I have the same issue - please reopen :)

**Comment by ClementLmn** [comment] 2019-06-18 08:33
Same here 👍

**Comment by asiainfoliwei** [comment] 2019-06-18 08:48
the same

**Comment by roywuyy** [comment] 2019-06-18 08:48
the same

**Comment by linchengzzz** [comment] 2019-06-18 08:49
the same

**Comment by Veerpool** [comment] 2019-06-18 08:52
it is a problem with caniuse-lite https://github.com/browserslist/browserslist/issues/382#issuecomment-503009048

**Comment by pi0** [comment] 2019-06-18 08:54
please use +1: reaction in the first comment instead of `the same`.

**Comment by pimlie** [comment] 2019-06-18 08:58
Quick fix for now is to add the following to your `package.json` to revert to an older caniuse-lite version:

```js
  "resolutions": {
    "caniuse-lite": "1.0.30000974"
  },
```

Only works with yarn, not with npm

**Comment by Veerpool** [comment] 2019-06-18 09:09
`Only works with yarn, not with npm` if it work in yarn, for npm can try use https://www.npmjs.com/package/npm-force-resolutions

**Comment by eep2019** [comment] 2019-06-18 09:12
same problem. need to fix

**Comment by Veerpool** [comment] 2019-06-18 09:12
https://github.com/browserslist/browserslist/issues/382#issuecomment-503019002

**Comment by Veerpool** [comment] 2019-06-18 09:20
Try to update Browserlist, it works with 2.8.1

**Comment by MartinBalerio** [comment] 2019-06-18 09:21
As mentioned by @albertleigh the issue is with the [caniuse-lite](https://www.npmjs.com/package/caniuse-lite/v/1.0.30000975) new version, resolutions fix the issue with yarn and `npm install caniuse-lite@1.0.30000974 --save-dev --save-exact` fixes the issue with NPM for now.

**Comment by ai** [comment] 2019-06-18 09:23
We made a dirty fix in Browserslist 4.6.3 to fix the problem:

https://twitter.com/Browserslist/status/1140911400304467968

**Comment by pi0** [comment] 2019-06-18 13:04
[consola@2.8.0](https://github.com/nuxt/consola/releases/tag/v2.8.0) released which prevents lots of warnings in the console:

![image](https://user-images.githubusercontent.com/5158436/59684366-18c0a380-91ef-11e9-8e82-63bf55e4062d.png)

**Comment by DereKEasH** [comment] 2019-06-18 13:14
![Snipaste_2019-06-18_21-12-47](https://user-images.githubusercontent.com/22338522/59685005-c5118280-920d-11e9-8c25-2158fe2050a9.png)
Does this issue affect the project? How to solve it? My God～！

**Comment by DereKEasH** [comment] 2019-06-18 13:21
> 刚开始使用create-nuxt-app来创建新项目的官方文档
> 
> ```shell
> npx create-nuxt-app pc-server
> ```
> 
> 然后
> 
> ```shell
> cd pc-server
> $ npm安装
> $ npm run dev
> ```
> 
> 在此命令之后，nuxt发生错误
> ![图片](https://user-images.githubusercontent.com/10168476/59662157-ed35bd00-91de-11e9-94e2-e2080801d742.png)
> 
> env： npx 
> ^ 6.9.0 
> node v10.8.0 
> npm ^ 6.9.0
> 
> _这个问题可在[Nuxt](https://cmty.app/nuxt)社区获得（[＃c9378](https://cmty.app/nuxt/nuxt.js/issues/c9378)）_

The same situation of my project. I don’t know if it will affect the projects that have been deployed online. Only God knows.

**Comment by DereKEasH** [comment] 2019-06-18 13:22
> just flower the offical doc to use the create-nuxt-app to create new project
> 
> ```shell
> npx create-nuxt-app pc-server
> ```
> 
> then
> 
> ```shell
> cd pc-server
> $ npm install
> $ npm run dev
> ```
> 
> after this command, the nuxt occurs the errors
> ![image](https://user-images.githubusercontent.com/10168476/59662157-ed35bd00-91de-11e9-94e2-e2080801d742.png)
> 
> env:
> npx ^6.9.0
> node v10.8.0
> npm ^6.9.0
> 
> _This question is available on [Nuxt](https://cmty.app/nuxt) community ([#c9378](https://cmty.app/nuxt/nuxt.js/issues/c9378))_

The same situation of my project. I don’t know if it will affect the projects that have been deployed online. Only God knows.

**Comment by ai** [comment] 2019-06-18 13:47
We will have warning until postcss-preset-env will not be fixed properly inside. We need just wait.

**Comment by pi0** [comment] 2019-06-18 14:01
@DereKEasH use standard nuxt server `yarn nuxt dev` instead :) Custom server does not register consola wrapper

**Comment by DereKEasH** [comment] 2019-06-18 15:02
> @DereKEasH use standard nuxt server `yarn nuxt dev` instead :) Custom server does not register consola wrapper

I used npm to create the project, but this has not happened in the past few days.

**Comment by renestalder** [comment] 2019-06-27 07:29
You don't have to downgrade anymore. The latest versions of caniuse-lite now also does no longer show the error. Installing it manually is still required, but you can use the latest version.

Yarn (tested):

Add to package.json.
```
"resolutions": {
  "caniuse-lite": "1.0.30000977"
}
```

npm (untested):
Install directly
```
npm install caniuse-lite@1.0.30000977 --save-dev --save-exact
```

**Comment by pi0** [comment] 2019-06-27 10:58
Pinning version in package.json (as of browser list maintainer also suggested) is not a good idea. Would be better to recreate lock-file or use yarn/npm upgrade. 

Closing as regression is fixed.

**Closed** 2019-06-27 10:58 UTC
Labels: bug, dependency regression, waiting for dependency
