### ISSUE TITLE
Unexpected token '...'. Expected a property name in Safari

### ISSUE THREAD

**Issue by yariksav** [nuxt/nuxt.js#5065] opened 2019-02-19 13:16 UTC
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[http://prntscr.com/mn65uj](http://prntscr.com/mn65uj)
[https://codesandbox.io/s/jk63v43ww](https://codesandbox.io/s/jk63v43ww)
### Steps to reproduce

Please help to get clarity of problem. Application falls down at loading

### What is expected ?

 Safari doesn't support spread in destructuring

### What is actually happening?

1) @nuxt/webpack uses extract-css-chunks-webpack-plugin version 3.3.2
2)  extract-css-chunks-webpack-plugin  uses normalize-url package
3) normalize-url/index.js has untransposed destruction operator	
{
	...options
}
4) If I comment "...options" in file 
./node_modules/extract-css-chunks-webpack-plugin/node_modules/normalize-url/index.js at 22 line everything works ok

https://github.com/sindresorhus/normalize-url/blob/b4201b4dc647cfb6dc3f70acd7d38630ecf18d3e/index.js#L22

### Additional comments?

Maybe package extract-css-chunks-webpack-plugin shuldn't get to vendors.app.js?
Thank you for helping!

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8688">#c8688</a>)</em></sub></div>

**Comment by yariksav** [comment] 2019-02-19 13:24
![image](https://user-images.githubusercontent.com/2553313/53018215-7835bf00-345a-11e9-8e24-f6c8a9848def.png)

**Comment by manniL** [comment] 2019-02-19 13:40
`extract-css-chunks-webpack-plugin` should never be part of your bundle as it is a webpack plugin 🤔

**Comment by yariksav** [comment] 2019-02-19 13:58
Thank you, @manniL for answering. I have this bug in dev mode
I even don't realize how this module was added to vendor. 
If you need to see addition information, configuration or files - let me know

**Comment by manniL** [comment] 2019-02-19 14:02
@yariksav Can you spin up a reproduction CodeSandbox? (via https://template.nuxtjs.org/)

**Comment by yariksav** [comment] 2019-02-19 15:12
Seems to I've reproduced this bug in codesandbox
https://codesandbox.io/s/jk63v43ww
Just use latest nuxt 2.4.3 and mode: spa, and open it in Safari
![image](https://user-images.githubusercontent.com/2553313/53025403-8939fc80-3469-11e9-8ce5-5697842ca330.png)

**Comment by clarkdo** [comment] 2019-02-19 17:17
@manniL extract-css-chunks-webpack-plugin may be partially in the bundle since it needs some code to inject the style

**Comment by yariksav** [comment] 2019-02-19 19:02
@clarkdo , thanks for answer. Can you show example how to add `extract-css-chunks-webpack-plugin` in `transpile`
because if i put it to nuxt.config.js to 
  build: {
    transpile: ['extract-css-chunks-webpack-plugin']
  ...  
}
It totally crashes application
![image](https://user-images.githubusercontent.com/2553313/53040233-923ac600-3489-11e9-93ed-42211559c1f4.png)

**Comment by clarkdo** [comment] 2019-02-19 20:01
@yariksav Your config should be fine, could you provide a repo ?

**Comment by yariksav** [comment] 2019-02-19 20:22
@clarkdo  repo - https://codesandbox.io/s/6jryy5pyvn
![image](https://user-images.githubusercontent.com/2553313/53044834-ca93d180-3494-11e9-83d3-4deafc6b1d1f.png)
And `transpile: ['normalize-url']` also is not working :(

**Comment by clarkdo** [comment] 2019-02-19 22:11
@yariksav It's a conflict that `babel preset useBuiltIns: usage` make `normalize-url` a harmony module and webpack runtime module doesn't work with harmony module.

You can use `babel.preset` to set `useBuiltIns: 'entry'` by:

```js
    babel: {
      presets: ({ isServer }) => {
        return [[
          '@nuxt/babel-preset-app',
          {
            buildTarget: isServer ? 'server' : 'client', // for auto import polyfill
            useBuiltIns: 'entry'
          }
        ]]
      }
    },
    transpile: ['normalize-url']
```

It would be better that open an issue in `extract-css-chunks-webpack-plugin` or turn off `extractCSS` in dev mode

**Comment by javialon26** [comment] 2019-02-21 04:41
I have the same issue with the [wpapi](https://www.npmjs.com/package/wpapi) package. If I don't use the babel config provided by @clarkdo, the code added to the vendor app file has the spread operator and fail in many browsers.

This behavior started with NuxtJs 2.4.3. With 1.4 this just works out of the box.

**Comment by husayt** [comment] 2019-02-27 11:48
I have the same in 2.4.3 and 2.4.5, causing issues on IE11

**Comment by clarkdo** [comment] 2019-03-04 20:15
Fixed in extract-css-chunks-webpack-plugin, dependency has been upgraded in dev branch, I’ll pick it into next  patch release

**Closed** 2019-03-04 20:15 UTC
Labels: :clock1:Pending, cmty:bug-report

**Comment by drewbaker** [comment] 2019-07-23 19:27
Did this get put into a release of Nuxt? I'm seeing the same error on Safari 10.1. Perhaps not related `extract-css-chunks-webpack-plugin`, it's hard to test exclusively via browserstack.

**Comment by clarkdo** [comment] 2019-07-23 19:37
@drewbaker It has been fixed since https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/releases/tag/v3.3.3 , could you double confirm the package  version in node_moudles, if it’s correct, could you provide a reproducible repo ?

**Comment by drewbaker** [comment] 2019-07-23 19:56
Yes, I created a code sandbox here: https://zqxk0lw813.sse.codesandbox.io/

See screenshot from Safari 10.1.2 via browserstack. You get two errors, the first one in start.js is maybe a browserstack JS error based on their code inspector tools, but the second `unexpected token` error is seems related to Nuxt in some way. I'm trying to find a computer in the wild running 10.1.2 of Safari, a client is reporting errors on a site we built, and I think this is the error.

**Comment by clarkdo** [comment] 2019-07-23 20:01
Sorry that I cannot look into this unit next week since my laptop is broken and I’m using mobile for commenting.

I’ll try to get back to you ASAP.

BTY, could you try latest nuxt-edge, there is another safari fix on it which hasn’t been released yet.

**Comment by drewbaker** [comment] 2019-07-23 20:05
Yes, just tried `nuxt-edge` and get the same errors: https://meqns.sse.codesandbox.io/

**Comment by clarkdo** [comment] 2019-07-23 20:08
I suppose it may be related your dependency which includes  spread operator, if you can find it, then add it into transpile should fix the problem.

**Comment by drewbaker** [comment] 2019-07-23 20:10
Thanks @clarkdo but those code sandboxes have no code from me, those are just the default installs. So it's no dependency from me.

**Comment by clarkdo** [comment] 2019-07-23 20:12
OK, could find which package is the error source code from ?

**Comment by drewbaker** [comment] 2019-07-23 20:17
I attached two screenshots with the two errors. 

![Screen Shot 2019-07-23 at 1 15 45 PM](https://user-images.githubusercontent.com/475015/61744384-0553ab80-ad4c-11e9-844a-b78f85c09a9b.png)
![Screen Shot 2019-07-23 at 1 15 22 PM](https://user-images.githubusercontent.com/475015/61744411-156b8b00-ad4c-11e9-8a99-5bb3522519ca.png)

**Comment by clarkdo** [comment] 2019-07-23 20:24
Which package is using deepMerge and localContentScripts ?

**Comment by drewbaker** [comment] 2019-07-23 20:26
No idea, I'm guessing `localContentScripts` is a browserstack thing (based on it being part of a script that looks to be related to firebug - which is weird on Safari), so maybe don't worry about that one yet. 

`deepMerge` I have no idea, I don't know Nuxt core construction that well.

**Comment by clarkdo** [comment] 2019-07-23 21:00
OK, I’ll look into it as soon as my device gets repaired

**Comment by drewbaker** [comment] 2019-07-23 21:59
Thanks @clarkdo I submitted a paid-support ticket for this too, I'll let you know if that gets fixed sooner.

**Comment by pi0** [comment] 2019-07-24 11:34
Upgrading to [http@0.3.3](https://github.com/nuxt/http/releases/tag/v0.3.3) should fix it for you @drewbaker. (nuxt/http#61)

**IMPORTANT:** Other users facing this problem, that may not be this bug. Any untranspiled lib should be a reason. As a general fix, you may to add incompatible lib to `build.transpile`:

```js
{
  build: {
        transpile: [
            'package name'
        ]
  }
}
```
