### ISSUE TITLE
bundle export should be a function when using { runInNewContext: false }

### ISSUE THREAD

**Issue by pirmax** [nuxt/nuxt.js#3519] opened 2018-07-11 07:05 UTC
### Steps to reproduce

You need NestJS, NuxtJS and Vue.

https://github.com/pirmax/nuxt-and-nest

### What is expected ?

When I go to the NuxtJS page, I get this error:

```{ Error: bundle export should be a function when using { runInNewContext: false }.
    at /home/maxence/Divers/Perso/nuxt-and-nest/node_modules/vue-server-renderer/build.js:8401:17
    at new Promise (<anonymous>)
    at /home/maxence/Divers/Perso/nuxt-and-nest/node_modules/vue-server-renderer/build.js:8388:14
    at Object.renderToString (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/vue-server-renderer/build.js:8564:9)
    at Renderer.renderRoute (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/nuxt/lib/core/renderer.js:344:41)
    at Renderer.nuxtMiddleware (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/nuxt/lib/core/middleware/nuxt.js:12:31)
    at call (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/connect/index.js:239:7)
    at next (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/connect/index.js:183:5)
    at SendStream.error (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:421:12)
    at next (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:764:28)
    at /home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:772:23
    at FSReqWrap.oncomplete (fs.js:152:21) statusCode: 500, name: 'NuxtServerError' }```

When I refresh page, the error is not the same:

```{ TypeError: runner is not a function
    at /home/maxence/Divers/Perso/nuxt-and-nest/node_modules/vue-server-renderer/build.js:8426:15
    at new Promise (<anonymous>)
    at /home/maxence/Divers/Perso/nuxt-and-nest/node_modules/vue-server-renderer/build.js:8388:14
    at Object.renderToString (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/vue-server-renderer/build.js:8564:9)
    at Renderer.renderRoute (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/nuxt/lib/core/renderer.js:344:41)
    at Renderer.nuxtMiddleware (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/nuxt/lib/core/middleware/nuxt.js:12:31)
    at call (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/connect/index.js:239:7)
    at next (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/connect/index.js:183:5)
    at SendStream.error (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:116:13)
    at SendStream.emit (events.js:211:7)
    at SendStream.error (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:421:12)
    at next (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:764:28)
    at /home/maxence/Divers/Perso/nuxt-and-nest/node_modules/send/index.js:772:23
    at FSReqWrap.oncomplete (fs.js:152:21) statusCode: 500, name: 'TypeError' }```

### What is actually happening?

Error on page:

`bundle export should be a function when using { runInNewContext: false }.`

Error on refreshed page:

`runner is not a function`

<!--cmty-->
<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7366">#c7366</a>)</em></sub></div>

**Comment by vaskevich** [comment] 2018-07-15 23:05
I ran into this issue too and fixed it by changing `"module": "commonjs"` in `tsconfig.json` to `"es2015"`.

**Comment by pirmax** [comment] 2018-07-16 07:09
@vaskevich If I change module commonjs to es2015, I've this error:

```
/home/maxence/Divers/Perso/nuxt-and-nest/src/server/main.ts:9
import { NestFactory } from "@nestjs/core";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module.m._compile (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/ts-node/src/index.ts:422:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/maxence/Divers/Perso/nuxt-and-nest/node_modules/ts-node/src/index.ts:425:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

**Comment by manniL** [comment] 2018-08-12 10:26
@pirmax  Could you try your setup with the latest `nuxt-edge` version?

**Comment by manniL** [comment] 2018-08-12 20:08
Duplicate of https://github.com/nuxt/nuxt.js/issues/3080

**Closed by manniL** 2018-08-12 20:08 UTC
Labels: cmty:bug-report
