### ISSUE TITLE
A Message raises: DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead

### ISSUE THREAD

**Issue by mcdmaster** [nuxt/nuxt.js#7910] opened 2020-08-13 14:12 UTC
### Is your feature request related to a problem? Please describe.
Yes. I would like `Tapable.plugin`'s replaced with some kind of `Hooks`, at least within `@nuxt/webpack` type library.

It simply seems that this error may prevent my going through with `Nuxt` building procedure.

### Describe the solution you'd like
Grep `Tapable.plugin`'s in `Webpack` files, directories and subdirectories and then replace them to "`Webpack.Plugin`".

### Describe alternatives you've considered
I do not have any other way to replace `Nuxt` because the project budget cannot afford with the replacement.

### Additional context
None but screenshot below. Thanks.
![スクリーンショット 2020-08-13 231044](https://user-images.githubusercontent.com/10361533/90144858-4df85f80-ddba-11ea-8946-4ceeaece178b.png)

**Comment by manniL** [comment] 2020-08-13 19:21
Likely a duplicate of https://github.com/nuxt/create-nuxt-app/issues/185#issuecomment-466757262

**Closed by manniL** 2020-08-13 19:21 UTC
Labels: feature-request
