### ISSUE TITLE
open the page directly 'asyncData' fail  and you can successfully navigate to the page through other pages

### ISSUE THREAD

**Issue by fengjiel** [nuxt/nuxt.js#1239] opened 2017-08-01 02:01 UTC
![2017-08-01_094919](https://user-images.githubusercontent.com/19583816/28806066-896313d2-76a0-11e7-8874-8e0261bb9329.jpg)
![2017-08-01_100120](https://user-images.githubusercontent.com/19583816/28806073-9025203e-76a0-11e7-80b2-3d1052c44754.jpg)

**Comment by Atinux** [comment] 2017-08-01 13:09
Are you using `process.SERVER_BUILD` or `process.CLIENT_BUILD`?

If so, first rename them to `process.server` and `process.client` and check if the error is still happening

**Comment by fengjiel** [comment] 2017-08-03 09:59
I think this is the version reason。When I use^0.10.7 。it worked。 @ @Atinux

**Comment by Atinux** [comment] 2017-08-03 11:46
@fengjiel please look at https://github.com/nuxt/nuxt.js/releases/tag/1.0.0-rc3 breaking changes and update your code accordingly.

**Comment by mdreizin** [comment] 2017-08-04 09:19
@Atinux I also have the same issue:

- go to page which uses `asyncData`;
- go to another page and hit refresh button;
- go back to the previous page and see that sate was lost;

![kapture 2017-08-04 at 12 18 42](https://user-images.githubusercontent.com/279122/28962684-20e38226-790f-11e7-95e4-d61399b30d6d.gif)

Maybe it happens by design, but could you please explain how to use only server-side rendering for specific page?

```js
async asyncData({ store }) {
    if (process.server) {
        await store.dispatch('getRepos');
    }
}
```

**Comment by fengjiel** [comment] 2017-08-05 10:54
I think you can get rid of it  ‘if (process.server) ’ ； @mdreizin  I tried  and it worked

**Comment by mdreizin** [comment] 2017-08-05 18:46
@fengjiel Good for you, but in my case state was gone after client-side navigation (see steps for reproduce above).

@atinux any thoughts/suggestions?

**Comment by alexchopin** [comment] 2017-10-28 12:14
Fixed in the next release

**Closed by alexchopin** 2017-10-28 12:14 UTC
Labels: breaking change: documentation in process, help wanted
