### ISSUE TITLE
IE11 gets a syntax error after set `extractCSS: true` to build config

### ISSUE THREAD

**Issue by wangxingkai** [nuxt/nuxt.js#5205] opened 2019-03-12 03:09 UTC
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://codesandbox.io/s/oxoq331z26](https://codesandbox.io/s/oxoq331z26)

### Steps to reproduce

- Use `create-nuxt-app` create a new Nuxt.js app.
- Add `extractCSS: true,` to `build` section in `nuxt.config.js`.
- Run the app in IE11.
- In the console, will see a syntax error. If the app runs in spa mode, it cannot start correctly.

### What is expected ?

No error in IE11. The app can start correctly.

### What is actually happening?

There is an error occurs in IE11. The app cannot start. Seems like ES6 syntax has not compiled to ES5.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8808">#c8808</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-03-12 09:13
Thanks but this is a 
Duplicate of #5065

**Closed by manniL** 2019-03-12 09:13 UTC
Labels: cmty:bug-report
