### ISSUE TITLE
Nuxt not auto-reloading server middleware in typescript

### ISSUE THREAD

**Issue by georgyfarniev** [nuxt/nuxt.js#6444] opened 2019-09-20 02:40 UTC
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://github.com/georgyfarniev/nuxt_bug_reproduction](https://github.com/georgyfarniev/nuxt_bug_reproduction)

### Steps to reproduce

- Clone repository from repro link
- npm install
- npm run dev
- load localhost:3000 in browser, check console output. You will see 11111111111111111 in logs
- Edit api/sample.ts and replace 11111111111111111 with 22222222222222222222
- Save changes
- Reload page on localhost:3000
- Check console output and still see 11111111111111111 instead of 22222222222222222222 despite fact that server was rebuilt by nuxt (with showing progress bar)

### What is expected ?

serverMiddleware auto reloaded on save

### What is actually happening?

serverMiddleware NOT auto reloaded on save (compare outputs)

### Additional comments?

This issue causes significant time efforts to restart server manually and should have high priority as it's not only takes time to reload, but also very confusing, because people have to figure out that this issue actually exists. I wasted a lot of time figuring out why my middleware doesn't work properly, because server restarts on saving serverMiddleware and everything looks good from console.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9798">#c9798</a>)</em></sub></div>

**Comment by pimlie** [comment] 2019-10-02 14:28
Duplicate of #6232, fixed in `v2.10` by #6490

**Closed by pimlie** 2019-10-02 14:28 UTC
Labels: cmty:bug-report
