### ISSUE TITLE
Weird glitch on page change (Firefox)

### ISSUE THREAD

**Issue by manniL** [nuxt/nuxt.js#2794] opened 2018-02-08 00:34 UTC
## Issue Description:
While building my own website (https://lichter.io/) I've recognized that when changing pages, the (already loaded) footer will be displayed before the page content kicks in. The glitch does not occur on the first load, only on page change.

## System information:
Browser: **Firefox** (tested on version 58.0.1 (64-bit) Ubuntu 17.10), Chrome and iOS Safari ran fine.
NuxtJS mode: production mode
NuxtJS version: 1.4 (but also occurred on previous versions)

## How does the glitch look like

Firefox 58.0.1 (64-bit) Ubuntu 17.10:
![ff](https://user-images.githubusercontent.com/640208/35949067-febf1f8a-0c6f-11e8-87b1-069f712e970f.gif)

Chrome  64.0.3282.140 (Official Build) (64-bit) Ubuntu 17.10:
![chrome](https://user-images.githubusercontent.com/640208/35949101-2a170aa8-0c70-11e8-81d9-5716c60529a8.gif)

Recording from @JGJP: https://jgarcia.jp/nuxt-glitch/demo.mp4

### Repositories 
[Repo of the gifs](https://github.com/manniL/lichter.io) (live at https://lichter.io)

[Repo from @JGJP](https://github.com/JGJP/nuxt-glitch) (live at https://jgarcia.jp/nuxt-glitch/)

### Steps to reproduce

1. Use Firefox 58.0.1 (64-bit) Ubuntu 17.10
2. Enter one of the sites linked above
3. Switch pages back and forth

## Possibly related issues

https://github.com/nuxt/nuxt.js/issues/1002

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2422">#c2422</a>)</em></sub></div>

**Comment by abellion** [comment] 2018-02-08 09:41
Same issue here !

**Comment by iamdubx** [comment] 2018-02-08 17:46
Yes, there's issue in FF, I wrote about it too. As far as I understand, it's a specific FF issue (I hope), so I get used to it. But if it can be fix it would be cool.

**Comment by BonnieDoug** [comment] 2018-02-09 07:51
Seems it's probably a css issue more than a nuxt issue? Is it possibly related to this?

https://stackoverflow.com/questions/41837540/footer-not-staying-at-the-bottom-in-firefox

**Comment by manniL** [comment] 2018-02-09 16:55
@BonnieDoug Well, the footer stays at the bottom when the site is fully loaded, so I don't think it's a CSS issue. 🤔

**Comment by BonnieDoug** [comment] 2018-02-09 18:30
@manniL but once the page is loaded, there is content pushing the footer to the bottom. While you are waiting for the page to load there is nothing there to keep it down so it jumps up probably ignoring some sort of `height: 100%` styling on the containing div, but I can only guess, as I've not seen your code.

**Comment by manniL** [comment] 2018-02-09 19:10
@BonnieDoug This doesn't happen in other browsers (e.g. chrome), so the only reason I could imagine is that the (cached) page loads faster on chrome than FF, so you don't see that footer flashing.

The weird thing is, that the Nuxt.js app is **not** running in SPA mode, so everything should be rendered serverside and that issue shouldn't be related to CSS at all.

**Comment by JGJP** [comment] 2018-02-28 08:51
I'm having the same problem, what it looks like to me is that the `<nuxt>` component within the layout gets added to the DOM after other elements in the layout like the footer. If you comment out  `<nuxt>` you'll see what the split second flash is. I've kind of worked around this for now by putting my footer in all my page components instead, but this defeats the purpose of using a layout, IMO.

Hoping there can be a fix for this.

**Comment by qm3ster** [comment] 2018-02-28 13:36
Is this in production (`build` + `start`) or in dev?

**Comment by manniL** [comment] 2018-02-28 13:37
@qm3ster In production. Would it be in dev only, it wouldn't be an issue at all. :)

**Comment by qm3ster** [comment] 2018-03-01 15:50
Couldn't reproduce even after disabling service worker.
HOWEVER...
Have you noticed that the 2px progress bar stays at the top of the page, so there is a gap between the header and the browser controls?

**Comment by manniL** [comment] 2018-03-01 16:07
Which browser and OS did you use for your reproduction attempts? 

Funny, I haven't noticed it by now. But it seems like it's a visual bug, because it's style is `width: 0%; height: 2px; background-color: rgb(227, 52, 47); opacity: 0;`

**Comment by qm3ster** [comment] 2018-03-01 18:17
:b:irefox 58.0.2 (64-bit) on :b:u:b:untu 17.10 GNOME.

**Comment by manniL** [comment] 2018-03-01 19:42
Weird... I'm using the same Browser and System, but the issue persists. Will cross-check on another PC tomorrow.

**Comment by qm3ster** [comment] 2018-03-02 00:41
nvidia proprietary driver?

**Comment by JGJP** [comment] 2018-03-02 03:15
I made a simple project that demonstrates this issue, here's a screen recording:
https://jgarcia.jp/nuxt-glitch/demo.mp4

[try the site yourself](https://jgarcia.jp/nuxt-glitch/)

[repo](https://github.com/JGJP/nuxt-glitch)

**Comment by manniL** [comment] 2018-03-02 11:01
@qm3ster Yes!
@JGJP Thanks, I'll add the links to the issue!

**Comment by qm3ster** [comment] 2018-03-03 18:40
I can't see it :(
Guess something is wrong with me.

**Comment by hackuun** [comment] 2018-03-03 18:58
I have this bug without Nvidia. 
Anyway, Firefox is horrible. I dropped following his way and suggest you to do the same. For example, today I discovered another issue in Firefox - translateZ transition doesn't work right.

**Comment by hackuun** [comment] 2018-03-03 19:00
@qm3ster dude, it's right in the video. You trolling us, stop it :smile:

**Comment by qm3ster** [comment] 2018-03-04 15:56
@hackuun I meant I can't reproduce it even with the garish oversimplified example provided by @JGJP where I don't have to fight a webworker.
On my machine it refuses to happen.

I can obviously see it in the video, I don't have 7fps vision disease.

**Comment by campope** [comment] 2018-03-22 16:32
Yep also seeing the same issue only on firefox.

**Comment by icehaunter** [comment] 2018-04-02 09:01
Also the same problem

**Comment by EmixMaxime** [comment] 2018-05-10 14:04
Same problem :(

**Comment by manniL** [comment] 2018-08-08 14:41
Tested it again with latest FF and it seems to be fixed.

**Closed** 2018-08-08 14:42 UTC
Labels: cmty:bug-report
