### ISSUE TITLE
npm run build failed [Unable to update lock within the stale threshold]

### ISSUE THREAD

**Issue by vijayshukla30** [nuxt/nuxt.js#5331] opened 2019-03-22 04:19 UTC
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://nuxtjs.org](https://nuxtjs.org)

### Steps to reproduce

I am using CodeBuild for our deployment from last 2 months. But when I build today then it gets failed. I tried many times. Here is the log for the same:
> nuxt build
 [04:17:14] [FATAL] Lock is already released
 at callback (node_modules/proper-lockfile/lib/lockfile.js:241:60)
 at Promise (node_modules/proper-lockfile/lib/adapter.js:39:9)
 at new Promise (<anonymous>)
 at args (node_modules/proper-lockfile/lib/adapter.js:30:25)
 at NuxtCommand.lockRelease [as _lockRelease] (node_modules/@nuxt/utils/dist/utils.js:139:11)
 at NuxtCommand.releaseLock (node_modules/@nuxt/cli/dist/cli-chunk.js:244:18)
 at NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-chunk.js:159:18)
 at <anonymous>
 ╭─────────────────────────────────────╮
 │ │
 │ ✖ Nuxt Fatal Error │
 │ │
 │ Error: Lock is already released │
 │ │
 ╰─────────────────────────────────────╯
 npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Fund@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Fund@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-03-22T04_17_14_897Z-debug.log

### What is expected ?

Since It was working earlier but not now.

### What is actually happening?

Since It was working earlier but not now.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8893">#c8893</a>)</em></sub></div>

**Comment by vijayshukla30** [comment] 2019-03-22 05:53
This is really weird when I deleted my local node_moudule and npm install; npm run build failed. I tried 2.4.0, 2.4.5, 2.5.1. Please do needful I have some released to do.

![Screenshot from 2019-03-22 11-21-55](https://user-images.githubusercontent.com/11537372/54803260-caa20f80-4c94-11e9-8703-67aabdbcf669.png)

**Comment by cyberbound** [comment] 2019-03-22 19:20
This have been driving me crazy for the last two hours and I've been looking for someone with the same issue. Following.

**Comment by sullivanpt** [comment] 2019-03-22 21:37
I've got this too, but I can work-around it with "nuxt build --no-lock"

**Comment by manniL** [comment] 2019-03-23 08:25
> I've got this too, but I can work-around it with "nuxt build --no-lock"

This is a valid workaround for now.

https://github.com/nuxt/nuxt.js/pull/5347 and https://github.com/nuxt/nuxt.js/pull/5320 might have fixed that ☺️ 

cc @pimlie

**Comment by pimlie** [comment] 2019-03-23 08:52
This is a duplicate of #5324

The pr's @manniL links to only removes the fatal error, but the lock could still become compromised which would show a warning. Why this happens so often is still not really clear, but from what I have been able to debug it could be anything like:
- _using Node <=v9_
v10/v11 have seen major performance improvements, but v10 is LTS so for production env its advised to run that. I have successfully reproduced that a lock always fails with v9, but never with v10/v11
- slow IO performance (possibly)
When during the webpack build the system is busy it looks like the stale check on the lock can fail. I have been unable to reproduce this consistently as it seems to be quite hard to limit/block IO for a process while debugging. At first I thought it might have to do with high cpu-usage, but I was unable to trigger the lock compromised warning while blocking the webpack build with a while loop for 1 minute. So cpu iowaits are still a suspect of causing the lock warning to show

**Comment by manniL** [comment] 2019-03-23 10:23
Duplicate of #5324

**Closed by manniL** 2019-03-23 10:23 UTC
Labels: cmty:bug-report

**Comment by Alhamou** [comment] 2020-04-30 12:35
i have the same issue on ubuntu 18 server :(
is there any solution ?
