### ISSUE TITLE
query parmeters discarded on server render

### ISSUE THREAD

**Issue by alexpetroni** [nuxt/nuxt.js#8096] opened 2020-09-19 11:19 UTC
Hi, 

The 'context.query' in asyncData is an empty object on a server render (despite query params presents in URL).  

### Versions

- nuxt: 2.14.5
- node: v12.18.3

### Reproduction
https://codesandbox.io/s/rough-frost-w510y

<details open>
<summary>Additional Details</summary>
On   
asyncData ({params, query}) {
    return {
      id: params.id, 
      query: query,
    }
  }

'query' is an empty object.
<br>

</details>

### Steps to reproduce
Click on the "Test Link" and the 'params' and 'query' are passed and printed in page correctly.
Reload the page  '/user/100?v=simple' and only the 'params' are present.

### What is Expected?
The 'query' params to be available

### What is actually happening?
The 'query' is an empty object.

**Comment by farnabaz** [comment] 2020-09-21 12:11
It is expected behavior because you are targeting static. In the static target `$route.query` will always be equal to `{}` on server-side rendering. find more about [full static projects](https://nuxtjs.org/blog/going-full-static#new-config-option-target)

I close the issue but feel free to ask any question 🙂

**Closed by farnabaz** 2020-09-21 12:11 UTC
