### ISSUE TITLE
Long hot reload due to SASS processing

### ISSUE THREAD

**Issue by LordGuard** [nuxt/nuxt.js#3994] opened 2018-09-27 20:10 UTC
### Version

[v2.0.0](https://github.com/nuxt.js/releases/tag/v2.0.0)

### Reproduction link

[https://nuxtjs.org](https://nuxtjs.org)

### Steps to reproduce

Upgrade a large project to Nuxt 2.0.0.

### What is expected ?

Fast hot reload

### What is actually happening?

After updating the project to nuxt 2.0 hot reload started to work very slowly. At any change, the sass-loader processes styles in all .vue files. It takes more than 30 seconds.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7850">#c7850</a>)</em></sub></div>

**Comment by AndrewBogdanovTSS** [comment] 2018-10-06 08:05
Yeah, I've started to get same issues recently, especially on relatively big vue files (+100 lines of code). It sometimes takes more than a minute to recompile and sometimes the process just shut down with a memory overflow error

**Comment by LordGuard** [comment] 2018-10-10 07:13
Still up to date. Sass is re-processed in all files even if the change did not affect the styles at all.

**Comment by AndrewBogdanovTSS** [comment] 2018-10-11 11:41
Is it possible to do a partial recompile of only those parts that were changed?

**Comment by XavierLeTohic** [comment] 2018-10-11 15:49
Running `nuxt dev` it takes 122s before the app become available. 
Node-sass is extremely slow, we are customizing element-ui sass variables and using a theme.

**Comment by manniL** [comment] 2018-10-11 16:37
Related: https://github.com/webpack-contrib/sass-loader/issues/296

**Comment by manniL** [comment] 2018-10-11 18:34
After digging through a lot of material I don't see much we can do. `sass-loader` does not cache imports/partials and will recompile everything. You could try https://github.com/yibn2008/fast-sass-loader or enabling the experimental options `parallel` and `cache` (https://nuxtjs.org/api/configuration-build#parallel).

Also things like `sourcemap` compilation slows down the build as well.

**Comment by LordGuard** [comment] 2018-10-11 18:46
> After digging through a lot of material I don't see much we can do. `sass-loader` does not cache imports/partials and will recompile everything. You could try https://github.com/yibn2008/fast-sass-loader or enabling the experimental options `parallel` and `cache` (https://nuxtjs.org/api/configuration-build#parallel).
> 
> Also things like `sourcemap` compilation slows down the build as well.

But why did it work much faster before nuxt 2.0?

**Comment by manniL** [comment] 2018-10-11 18:47
@LordGuard That's hard to tell without a reproduction repository :frowning_face:

**Comment by XavierLeTohic** [comment] 2018-10-16 10:53
We have successfully removed sass-loader from Nuxt and using fast-sass-loader instead, our build went down from 102s to 42s.

Here is the code to replace sass-loader with fast-sass-loader in `nuxt.config.js`

```javascript
// Replace all occurences of sass-loader with fast-sass-loader as Nuxt keep
      // use both during the build
      config.module.rules = config.module.rules.map(rule => {
        // sass-loader is only inside "oneOf" attribute
        if (!rule.oneOf) {
          return rule;
        }
        const newRule = rule;
        newRule.oneOf.map(r => {
          if (!r.use.some(l => l.loader === 'sass-loader')) {
            return r;
          }
          const newLoaders = r;
          newLoaders.use = newLoaders.use.reduce((loaderAcc, loader) => {
            if (loader.loader !== 'sass-loader') {
              return [...loaderAcc, ...[loader]];
            }
            return [...loaderAcc, ...[{
              loader: 'fast-sass-loader',
              options: loader.options,
            }]];
          }, []);
          return newLoaders;
        });
        return newRule;
      });
```

**Comment by AndrewBogdanovTSS** [comment] 2018-10-16 11:51
@Atinux @manniL will this code be added to Nuxt official code at some point?

**Comment by pi0** [comment] 2018-10-16 11:56
I will try fast-sass-loader on a project afternoon. If it really worth, we can write an official module 😊

**Comment by manniL** [comment] 2018-10-16 12:39
@pi0 Something in the style of https://github.com/Developmint/nuxt-svg-loader comes to my mind. I guess I'll create one 🙊

**Comment by XavierLeTohic** [comment] 2018-10-16 13:15
Be careful `fast-sass-loader` have issues with custom aliases using Nuxt such as `@` or `$` but work well with the default `~`. 
There is already a lot of issues on fast-sass-loader repository about it.

**Comment by AndrewBogdanovTSS** [comment] 2018-10-17 09:45
@XavierLeTohic in scss/sass files `$` should be reserved to defining a variable so I don't think there is any possibility to use it for Nuxt specific purposes. Speaking about `@` it's also doesn't work currently when used inside scss context. The only place it's used is inside js imports afaik so I don't think it's a show stopper

**Comment by XavierLeTohic** [comment] 2018-10-17 10:29
Yeah sorry it was just an example, I forgot that case with sass. I should have say "With any custom aliases"

**Comment by AndrewBogdanovTSS** [comment] 2018-10-25 13:51
@pi0 any updates on this one?

**Comment by AndrewBogdanovTSS** [comment] 2018-10-29 19:46
Guys, I've came across very disturbing issue. It's related to using `build.styleResources` option that built into Nuxt. When it's enabled all dependent sass modules are being recompiled twice on every change even if the change happened in some unrelated js file. In my project I have quite a lot of resources I need to inject into Vue files so just give you some numbers.
`build.styleResources` - `off`: hot reload time 1 sec
`build.styleResources` - `on`: hot reload time 1 MINUTE
Although when I use plugin with similar functionality [nuxt-sass-resources-loader](https://github.com/anteriovieira/nuxt-sass-resources-loader) build speed is back to normal with the same setup
I plan to add a separate bug about this, but just wanted to drop it quickly here because I think this stuff is related to the problem described here

**Comment by AndrewBogdanovTSS** [comment] 2018-10-29 20:05
@XavierLeTohic I tried your config with `fast-sass-loader` but I didn't notice any significant build speed increase. For my project it was even slower, 49s - `sass-loader` 50s - `fast-sass-loader` (though I also have a lot of SCSS assets)
What I did notice is that your config doesn't play nice when `nuxt-sass-resources-loader` is in use maybe because it also uses `sass-loader`
I'm getting 
```
Error: Mixin transition is missing argument $transition-time.
```
from building Bootstrap default assets

**Comment by falstack** [comment] 2018-11-01 09:31
Has there been any progress in this matter?

**Comment by sergiocastrovale** [comment] 2018-11-06 18:39
> Is it possible to do a partial recompile of only those parts that were changed?

This would definitely be the better option. To be honest, I went back to picking Laravel in a recent project solely because of how frustrating the wait is. Having to wait 20-30 seconds _every time you save_ is a huge deal breaker.

What are the alternatives we can use as of now?

**Comment by manniL** [comment] 2018-11-07 00:18
Hey folks! :wave: 

For anyone having problems, could you please:

1. Run `yarn build --profile` (or the npm equivalent) and drop the stats in here?
2. Provide a reproduction repository (if possible, I know not everyone can share code)

**Comment by aldarund** [comment] 2018-11-07 11:41
@melrefaie so in your case when u save in dev its longer than  build? if so - do u have a component\page with a lot of nested tags?

**Comment by sergiocastrovale** [comment] 2018-11-07 12:40
@manniL I'm not able to share the code but the use case is pretty simple:

1. I have a _variables.scss file which I need to load on a bunch of components in order to get access to scss vars like $dark, $light, $header_gradient, etc.

2. I can do so manually (include + full path) or use something like [sass-resources-loader](https://github.com/shakacode/sass-resources-loader)

3. Every time I save a file, `npm run dev` seems to recompile those scss dependencies on EVERY file, which is silly in most cases (i.e. I'm saving nuxt.config.js and it starts rebuilding all my .vue components)

**Comment by melrefaie** [comment] 2018-11-07 12:45
in your case when u save in dev its longer than build? 
Yes it takes longer time than build.

I don't have a lot of nested tags. but i have: 
186 pages
75 component

I don't face this problem with small projects. but in large projects its nightmare to work with .

**Comment by sergiocastrovale** [comment] 2018-11-07 13:20
> in large projects its nightmare to work with

@melrefaie  Is your issue similar to mine? Are you injecting SCSS into those components?

**Comment by melrefaie** [comment] 2018-11-07 14:06
> @melrefaie Is your issue similar to mine? Are you injecting SCSS into those components?

@sergiocastrovale 

I inject stylus in layouts,  i use 
<style lang="stylus"> 
inside pages and components and global file includes variables and mixins file inside nuxt.config

**Comment by manniL** [comment] 2018-11-07 14:12
@melrefaie do you use `style-resources-loader`?

**Comment by manniL** [comment] 2018-11-07 14:39
@melrefaie Could you try out something like https://github.com/BKWLD/nuxt-stylus-resources-loader as substitute?

**Comment by melrefaie** [comment] 2018-11-07 14:41
@manniL ok i will try it

**Comment by Pinegin** [comment] 2018-11-07 14:56
@manniL 

faced the same problem.

Just tried instead:
`
styleResources: {
      scss: './assets/scss/all.scss',
    },
`

use:
`  modules: [
    ['nuxt-sass-resources-loader', '@/assets/scss/all.scss'],
  ],`

speed has increased many times.

**Comment by manniL** [comment] 2018-11-07 14:57
@Pinegin Thanks for the ping back!

**Comment by AndrewBogdanovTSS** [comment] 2018-11-07 15:05
@manniL that is the exact issue we were discussing some time ago. `styleResources` are not usable at this point due to some severe internal bug though external libs for same functionality handles it well! 
The requirements for `styleResources` 
1. It should cache the result of injection and only rebuild when it's really necessary
2. It should not compile code at all, only inject variables, functions and mixins, otherwise we can and up with a bunch of garbage in Vue files that we don't need

**Comment by manniL** [comment] 2018-11-07 15:07
@AndrewBogdanovTSS Yeah, I saw you comment above too. I might have a solution for that ☺️

**Comment by melrefaie** [comment] 2018-11-07 15:15
@manniL Wow thank you.

Using [nuxt-stylus-resources-loader](https://github.com/BKWLD/nuxt-stylus-resources-loader) solve my save time problem form 2.30 min on save to 1 or 2 second.

```
modules: [
    [
      'nuxt-stylus-resources-loader',
      resolve(__dirname, '~assets/css/vars.styl')
    ]
]
```
To any one see this comment don't use styleResources.

**Comment by manniL** [comment] 2018-11-07 15:20
@melrefaie I'm working on a module to overcome all perf issues for that ☺️ (Supporting SCSS, LESS and Stylus)

**Comment by manniL** [comment] 2018-11-07 18:34
Will release a module as drop-in replacement that should be faster than the current solution 📦 🙌

**Comment by AndrewBogdanovTSS** [comment] 2018-11-07 21:48
@manniL waiting for it! :) Will it be any different from `nuxt-stylus-resources-loader` or `sass-resource-loeader` ?

**Comment by manniL** [comment] 2018-11-07 21:49
@AndrewBogdanovTSS It uses `sass-resource-loader` under the hood, but not exclusively :)

**Comment by falstack** [comment] 2018-11-08 02:19
should upgrade nuxt to v2.2.1, use nuxt-stylus-resources-loader as default?

**Comment by sh** [comment] 2018-11-08 04:51
@manniL looking forward to your module 🎉 

I ran into #4278 when making changes to our `_vars.scss`, `fast-sass-loader` fixed this but it is still taking around 50-70s. 

I've replaced `style-resources-loader` with `sass-resources-loader@2.0.0` (note: not `nuxt-sass-resources-loader`), but it seems to have issues with threads / webpack on the second change to vars.scss the whole process broke with an error.

We ended up replacing `sass-loader` and `style-resources-loader` with `fast-sass-loader` with the approach below.

It is still far from optimal and i believe that something is leaking somewhere when you do a change to a sass resource file that triggers a rebuild of all vue components.

We're using bootstrap (scss only) and have ~100 components (pages/components).

Our `nuxt.config.js` that allows us to avoid `style-resources-loader`:
```js

  build: {
    loaders: {
      scss: {
        includePaths: [__dirname],
        data: `@import "assets/scss/style-resources.scss";`,
      },
    },
```

from [@XavierLeTohic comment](https://github.com/nuxt/nuxt.js/issues/3994#issuecomment-430192622)
```js
    extend(config, { isDev, isClient, loaders }) {
      // use fast-sass-loader instead of sass-loader for now
      config.module.rules = config.module.rules.map(rule => {
        // sass-loader is only inside "oneOf" attribute
        if (!rule.oneOf) {
          return rule
        }
        const newRule = rule
        newRule.oneOf.map(r => {
          if (!r.use.some(l => l.loader === "sass-loader")) {
            return r
          }
          const newLoaders = r
          newLoaders.use = newLoaders.use.reduce((loaderAcc, loader) => {
            if (loader.loader !== "sass-loader") {
              return [...loaderAcc, ...[loader]]
            }
            return [
              ...loaderAcc,
              ...[
                {
                  loader: "fast-sass-loader",
                  options: loader.options,
                },
              ],
            ]
          }, [])
          return newLoaders
        })
        return newRule
      })
```

**Comment by manniL** [comment] 2018-11-08 15:47
Everyone who used `style-resources-loader` can try out https://github.com/nuxt-community/style-resources-module ☺️ Feedback very welcome!

**Comment by AndrewBogdanovTSS** [comment] 2018-11-08 16:09
@manniL not working for me. 
```
× fatal file:///.../node_modules/@nuxtjs/style-resources/lib/module.js:1
  TypeError: require(...).withTag is not a function
  at Object.<anonymous> (file:///C:/Projects/Kare/front-end/node_modules/@nuxtjs/style-resources/lib/module.js:2:35)
  at Generator.next (<anonymous>)
```

**Comment by manniL** [comment] 2018-11-08 16:15
@AndrewBogdanovTSS Ah, consola. Hmm. 1 sec. will update the pkg version and upgrade consola

**Comment by AndrewBogdanovTSS** [comment] 2018-11-08 16:16
After I replaced `withTag` with `withScope` I'm proceeding to this error:
```
× fatal TypeError: Cannot read property 'resolveAlias' of undefined
  at normalizedObject.(anonymous function).wrappedValue.reduce (...\node_modules\@nuxtjs\style-resources\lib\module.js:30:35)
  at Array.reduce (<anonymous>)
  at styleResourcesEntries.reduce (...\node_modules\@nuxtjs\style-resources\lib\module.js:28:44)
  at Array.reduce (<anonymous>)
  at retrieveStyleArrays (...\node_modules\@nuxtjs\style-resources\lib\module.js:26:27)
  at ModuleContainer.nuxtStyledResources (...\node_modules\@nuxtjs\style-resources\lib\module.js:39:60)
  at Promise (C:\Projects\Kare\front-end\node_modules\nuxt\dist\nuxt.js:628:30
  at new Promise (<anonymous>)
  at ModuleContainer.addModule (...\node_modules\nuxt\d
  at promise.then (...\node_modules\nuxt\dist\nuxt.js:1
  at process._tickCallback (internal/process/next_tick.js:68:7)
  at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
  at startup (internal/bootstrap/node.js:285:19)
  at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
Nuxt Fatal Error :(
error Command failed with exit code 1.
```

**Comment by manniL** [comment] 2018-11-08 16:17
@AndrewBogdanovTSS 0.0.2 released with upgraded consola.

You try it with Nuxt 2.2, right?
Could you try it with `nuxt-edge`?

**Comment by AndrewBogdanovTSS** [comment] 2018-11-08 16:18
Yes, I'm trying with Nuxt 2.2
You got quite a lot of outdated dependencies http://take.ms/o0lWs

**Comment by AndrewBogdanovTSS** [comment] 2018-11-08 18:36
Can confirm that this package only work with Nuxt 2.3 (edge) as of now

**Comment by AndrewBogdanovTSS** [comment] 2018-11-08 18:37
Can't provide comparisons of speed since `--profile` mode is currently broken in Nuxt 2.3

**Comment by manniL** [comment] 2018-11-08 18:38
Works with `2.2` as well since `v0.1.1`

**Comment by manniL** [comment] 2018-11-11 18:14
I'll close this issue and suggest everyone that uses `build.styleResources` to switch to https://github.com/nuxt-community/style-resources-module/ instead. `build.styleResources` will be deprecated in 2.3 and likely removed/made optional in 3.0.

All other perf problems with preprocessors should be addressed in a new issue.

**Closed by manniL** 2018-11-11 18:14 UTC
Labels: cmty:bug-report, status: in progress

**Comment by konstantinsteinmiller** [comment] 2018-11-30 13:45
> @manniL
> 
> Some times when i save in dev it takes 2.30 min to save !!
> Here is my build stats
> 
> Stats by Ext
> 
> Ext	Requests	Time	Time/Request	Description
> js	223	757ms	3ms	JavaScript files
> vue	2582	16s	6ms	Vue Single File components
> css	43	337ms	8ms	css files
> styl	9	1s	126ms	styl files
> eot	36	12ms	341μs	eot files
> woff	11	796μs	72μs	woff files
> woff2	11	874μs	79μs	woff2 files
> ttf	11	213ms	19ms	ttf files
> svg	40	23ms	578μs	svg files
> Total	2966	18s		
> Stats by Loader
> 
> Loader	Requests	Time	Time/Request	Description
> babel-loader	821	2s	3ms	Babel Loader
> vue-loader	4238	31s	7ms	Vue Loader
> vue-style-loader	171	69ms	405μs	Vue Style Loader
> css-loader	844	14s	16ms	Css Loader
> postcss-loader	844	14s	16ms	Postcss Loader
> pug-plain-loader	606	2s	3ms	Pug Plain Loader
> stylus-loader	793	13s	17ms	Stylus Loader
> style-resources-loader	793	13s	17ms	Style Resources Loader
> url-loader	109	250ms	2ms	Url Loader
> Total	9219	1m		
> Hash: e55ce7f2580becbca517
> Version: webpack 4.20.2
> Time: 20755ms
> 
> server-bundle.json 12.8 MiB [emitted]
> Entrypoint app = server-bundle.js
> ✨ Done in 83.09s.

Hey,
how did you make this report? Cause I would like to analyse where our long compile times coming from.

**Comment by manniL** [comment] 2018-11-30 14:01
@konstantinsteinmiller  https://twitter.com/TheAlexLichter/status/1059398193186832385
