### ISSUE TITLE
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by luckymichaln** [nuxt/nuxt.js#7958] opened 2020-08-23 13:38 UTC
Hi all, I have a tough issue with my nuxt app builded on Netlify while try to use Netlify's form integration. I'm using universal mode both locally and on server side. To build static sites on serves I use `yarn generate`. Locally everything works perfect but on the server *DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.* error occurs. 

I tried to follow that article: https://www.netlify.com/blog/2018/09/07/how-to-integrate-netlify-forms-in-a-vue-app/?_ga=2.208078290.1546153797.1598189808-1759093818.1589822987 and it seems to work but only locally

What I understand - while build on the server, Netlify injects it's hidden input to recognize wheter a request comes from my website or not. Somehow during this process there's some kind or error.

A form tag has to be visible during the rendering so Netlify can find it's tag in the form and inject it's hidden input. So I've changed:

```
<transition name="modal-contact" mode="out-in">
    <modalContact v-if="modalOpened.contact" />
</transition>
```
(Now everything work's perfect, except actually working form with Netlify connection)

to 

```
<transition name="modal-contact" mode="out-in">
    <modalContact v-show="modalOpened.contact" />
</transition>
```

(Now error occurs but if I open the form manually it's kinda work. The website is still broken tho)

### Questions

What should I do to make it work as it should? I've searched the internet by this error but didn't found any solution that would might help.

### Versions

- nuxt: "^2.4.0"
- node: 9.5.0

### Reproduction

Go to the website and see dev tools errors -> https://objective-edison-d01121.netlify.app/. There's missing header and footer component combined with overall not working JS. (Locally everything works perfect).

### What is Expected?
Website should behave normally and my form should still work as I expect.

### What is actually happening?
Website's broken (missing header, footer and overall JS).

**Comment by manniL** [comment] 2020-08-24 10:21
Hey 👋🏻

This is a so-called hydration error which has been discussed in a couple of issues, e.g. #7203 or #7874. [This blog post about hydration errors](https://blog.lichter.io/posts/vue-hydration-error/) might be helpful as well.

In your case, you might want to wrap the forms in a `ClientOnly` tag.

Duplicate of #7874

**Closed by manniL** 2020-08-24 10:21 UTC
Labels: bug-report
