### ISSUE TITLE
Duplicate html "lang" attribute on page redirect from SSR

### ISSUE THREAD

**Issue by njam** [nuxt/nuxt.js#7370] opened 2020-05-15 15:43 UTC
### Version

[v2.12.2](https://github.com/nuxt.js/releases/tag/v2.12.2)

### Reproduction link

[https://gitlab.com/njam/repro-nuxt-html-lang](https://gitlab.com/njam/repro-nuxt-html-lang)

### Steps to reproduce

1: Clone the repro repo:
```
git clone https://gitlab.com/njam/repro-nuxt-html-lang
cd repro-nuxt-html-lang
```
(relevant commit: https://gitlab.com/njam/repro-nuxt-html-lang/-/commit/be48fd82f0fdfd8197dbf7870a4cb9d74778a09f)

2: Build the static files, and serve them
```
yarn install
yarn run generate
npx serve ./dist
```

3: Open the page in the browser: http://localhost:5000

### What is expected ?

The browser redirects to "/foo", and the html-tag has the attribute `lang="de"`

### What is actually happening?

The browser redirects to "/foo", and the html-tag has the attribute `lang="de de"`

Open the browser's dev tools to inspec the "lang" attribute:  
![Screenshot from 2020-05-15 17-39-14.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/412f4460-96c2-11ea-b870-53697c3e5221.png)

### Additional comments?

Maybe vue-meta cannot correctly detect that the previous "lang"-value is coming from a server-rendered file when redirecting?

This vue-meta ticket might be related: https://github.com/nuxt/vue-meta/issues/404

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10664">#c10664</a>)</em></sub></div>

**Comment by pimlie** [comment] 2020-05-16 15:57
Thanks for the report, this is a duplicate of https://github.com/nuxt/vue-meta/issues/541

**Closed by pimlie** 2020-05-16 15:57 UTC
Labels: cmty:bug-report
