### ISSUE TITLE
[rc1] Cannot find module 'es6-promise/auto'

### ISSUE THREAD

**Issue by jsnick** [nuxt/nuxt.js#1169] opened 2017-07-27 05:57 UTC
by https://github.com/nuxt/nuxt.js/issues/1162,
I provided fully resolved path to plugins then, nuxt build is ok!
but I think the files in `plugins/` is not compiled by babel-loader.

```
Nuxt.js Error:

/path/to/project/plugins/apollo.js:1
(function (exports, require, module, __filename, __dirname) { import ApolloClient, { createNetworkInterface } from 'apollo-client'
SyntaxError: Unexpected token import
...
...
```
There is a `import` keyword.

## Update 
This is maybe not a problem about `plugins/`, .

Error occur in default middleware.

### nuxt.config.js
```
{
  ...
  plugins: [
    './plugins/element-ui',
    './plugins/vue-apollo',
    {
      src: './plugins/custom-element',
      ssr: false,
    },
    {
      src: './plugins/https-redirection',
      ssr: false,
    },
    './plugins/getProjectVersion',
  ],
  router: {
    middleware: 'default',
  }
}
```

### middleware/default.js
```
1: import { networkInterface } from '~/plugins/apollo'
2: ...
3: ...
```

If I change the error line, `'~/plugins/apollo'` => `'../plugins/apollo'`,
then error message is changed to below.
```
Error: Cannot find module 'es6-promise/auto' from '/path/to/project'
    at Function.module.exports [as sync] (/path/to/project/node_modules/resolve/lib/sync.js:40:15)
    at r (/path/to/project/node_modules/vue-server-renderer/build.js:7741:44)
    at Object.<anonymous> (webpack:/external "es6-promise/auto":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap b13c1d9e6771c0e8f306:25:0)
    at Object.<anonymous> (.nuxt/index.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap b13c1d9e6771c0e8f306:25:0)
    at Object.<anonymous> (.nuxt/server.js:6:0)
    at __webpack_require__ (webpack:/webpack/bootstrap b13c1d9e6771c0e8f306:25:0)
    at server-bundle.js:92:18
    at Object.<anonymous> (server-bundle.js:95:10)
    at evaluateModule (/path/to/project/node_modules/vue-server-renderer/build.js:7747:21)
    at /path/to/project/node_modules/vue-server-renderer/build.js:7805:18
    at /path/to/project/node_modules/vue-server-renderer/build.js:7797:14
    at Object.renderToString (/path/to/project/node_modules/vue-server-renderer/build.js:7951:9)
    at P (/path/to/project/node_modules/nuxt/node_modules/pify/index.js:49:6)
    at Object.<anonymous> (/path/to/project/node_modules/nuxt/node_modules/pify/index.js:11:9)
    at Object.ret [as renderToString] (/path/to/project/node_modules/nuxt/node_modules/pify/index.js:72:32)
    at Renderer._callee7$ (/path/to/project/node_modules/nuxt/lib/core/renderer.js:325:41)
    at tryCatch (/path/to/project/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/path/to/project/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/path/to/project/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/path/to/project/node_modules/nuxt/dist/nuxt.js:851:30)
    at /path/to/project/node_modules/nuxt/dist/nuxt.js:869:14
    at Renderer.<anonymous> (/path/to/project/node_modules/nuxt/dist/nuxt.js:848:12)
    at Renderer.renderRoute (/path/to/project/node_modules/nuxt/dist/nuxt.js:2289:22)
    at Renderer._callee5$ (/path/to/project/node_modules/nuxt/lib/core/renderer.js:225:69)
    at tryCatch (/path/to/project/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/path/to/project/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/path/to/project/node_modules/nuxt/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/path/to/project/node_modules/nuxt/dist/nuxt.js:851:30)
    at /path/to/project/node_modules/nuxt/dist/nuxt.js:869:14
    at Renderer.<anonymous> (/path/to/project/node_modules/nuxt/dist/nuxt.js:848:12)
    at Renderer.nuxtMiddleware (/path/to/project/node_modules/nuxt/dist/nuxt.js:2131:22)
    at call (/path/to/project/node_modules/connect/index.js:239:7)
    at next (/path/to/project/node_modules/connect/index.js:183:5)
    at SendStream.error (/path/to/project/node_modules/serve-static/index.js:121:7)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:191:7)
    at SendStream.error (/path/to/project/node_modules/serve-static/node_modules/send/index.js:282:17)
    at SendStream.onStatError (/path/to/project/node_modules/serve-static/node_modules/send/index.js:433:12)
    at next (/path/to/project/node_modules/serve-static/node_modules/send/index.js:771:28)
    at /path/to/project/node_modules/serve-static/node_modules/send/index.js:779:23
    at FSReqWrap.oncomplete (fs.js:114:15)
```

This project don't have es6-promise/auto. (this is maybe in nuxt)
And My working pervious nuxt version is `1.0.0-alpha1`.

**Comment by pi0** [comment] 2017-07-27 07:42
Hi. Are you using nuxt with `npm/yarn link` ?

**Comment by jsnick** [comment] 2017-07-27 08:02
No, I have never used `yarn link`.
I just commanded `rm -rf node_modules` and again `yarn` for nuxt version-up.

**Comment by pi0** [comment] 2017-07-27 08:08
That's strange. Because es6-promise is already in [package.json](https://github.com/nuxt/nuxt.js/blob/dev/package.json#L83). Would you please remove `yarn.lock` file as well?

**Comment by jsnick** [comment] 2017-07-27 08:16
Error still show T^T.
I command 'rm -f yarn.lock` , `rm -rf node_modules` , `yarn`.

**Comment by pi0** [comment] 2017-07-27 08:31
I can't reproduce it with RC1 :( Does disabling `middleware` makes any change?

**Comment by mgesmundo** [comment] 2017-07-27 09:11
Hi @jsnick,
I solved a similar issue with:
```bash
npm install url-loader --save
```
I hope this solve your problem.
Regards.

**Comment by pi0** [comment] 2017-07-27 09:14
@mgesmundo Thanks for your suggestion. Would you please explain more why `url-loader` was needed?

**Comment by mgesmundo** [comment] 2017-07-27 09:33
@pi0 This is reported running <code>npm install</code> inside <code>nuxt</code> folder:
```bash
...
generated nuxt-start@1.0.0-rc1
npm WARN url-loader@0.5.9 requires a peer of file-loader@* but none was installed.
...
```

**Comment by pi0** [comment] 2017-07-27 09:42
OK i've added it back. (BTW I think this is not the problem with this issue as rc1 is shipping with `file-loader` too :) )

**Comment by jsnick** [comment] 2017-07-27 11:10
`npm install url-loader --save` is not a solution.
Only If I add `es6-promise`, then it works.

**Comment by pi0** [comment] 2017-07-27 11:17
I will close this issue as it may be a temporary problem with only `rc1` and Nuxt `package.json` explicitly requires `ex6-promise` as a dependency. Please report back if there was same problem with next releases.

**Comment by midori-tooyama** [comment] 2017-07-28 02:38
I'm using `"nuxt": "1.0.0-rc2",` and

```bash
npm --version
5.3.0

yarn --version
0.28.4
```

If I install dependencies by `yarn`, it will missing `es6-promise/auto` but it's in the `yarn.lock`:

```
es6-promise@^4.1.1:
  version "4.1.1"
  resolved "http://registry.npm.taobao.org/es6-promise/download/es6-promise-4.1.1.tgz#8811e90915d9a0dba36274f0b242dbda78f9c92a"
```

While using 'npm i', everything works fine.

**Comment by Alex-Sokolov** [comment] 2017-07-28 06:27
@midori-tooyama same problem, but `npm i` didn't help

**Comment by josantana** [comment] 2017-08-07 20:13
Same problem here, using `rc3`.

Tried everything, like removing `node_modules` and `.nuxt` folders and lock files, starting in a new project... only `yarn add es6-promise` resolved.

Strange, 'cause `es6-promise` is indeed listed on `nuxt` dependencies.

I'm using _Yarn_, btw.

**Comment by pi0** [comment] 2017-08-07 20:38
@josantana Can you locally replicate that `es6-promise` again? I'm curious about output of `yarn why es6-promise` and also generated `yarn.lock` file contents.

**Comment by josantana** [comment] 2017-08-08 21:09
Hi @pi0, thanks for the tip. Here it is the output of `yarn why es6-promise`:

![yarn-why-es6-promise](https://user-images.githubusercontent.com/5032844/29094674-861c6ede-7c64-11e7-85d5-3a6e8aa35d67.png)

My problem was related to the `nodemon`. After its removal, Nuxt started working fine again.

Thanks for your assistance!

**Comment by marcosgallardo** [comment] 2017-08-12 21:08
Same problem here after update to `nuxt@1.0.0-rc4`

I'm using

    node v6.11.0
    npm 3.10.10
    vue-cli 2.8.2

package.json

    ...
    "dependencies": {
      "@nuxtjs/pwa": "^0.2.0",
      "nuxt": "^1.0.0-rc3"
    },
    "devDependencies": {
      "babel-eslint": "^7.2.3",
      "eslint": "^4.3.0",
      "eslint-config-standard": "^10.2.1",
      "eslint-loader": "^1.9.0",
      "eslint-plugin-html": "^3.1.1",
      "eslint-plugin-import": "^2.7.0",
      "eslint-plugin-node": "^5.1.1",
      "eslint-plugin-promise": "^3.5.0",
      "eslint-plugin-standard": "^3.0.1"
    }

nuxt.config.js

    ...
    modules: [
      '@nuxtjs/pwa'
    ]

`npm install` output: [here](https://pastebin.com/tH6Mq2MS)

Browser error:

![image](https://user-images.githubusercontent.com/4549886/29244210-f6748f0a-7f88-11e7-980d-1ddb62b0beb9.png)

**Comment by pi0** [comment] 2017-08-12 21:11
This problem will be fixed soon in rc5 (127155d61a2c6543d698a969f6d06daf43109fe6) corrently the simples approach is manually npm/yarn install `es6-promise` for your project.

**Comment by marcosgallardo** [comment] 2017-08-12 21:15
@pi0, yes it worked, thank you!

And just in case you would like to see the terminal output

    PS F:\projects\nuxt> npm install --save es6-promise
    cms@1.0.0 F:\projects\nuxt
    +-- @nuxtjs/pwa@0.2.0
    | `-- @nuxtjs/icon@1.0.1
    |   `-- jimp@0.2.28
    |     `-- es6-promise@3.3.1  // <- This is shown highlighted
    `-- es6-promise@4.1.1

**Closed** 2017-08-13 22:11 UTC
Labels: available soon

**Comment by husayt** [comment] 2018-03-31 09:13
@pi0 I have the same problem with nuxt-edge now

**Comment by pi0** [comment] 2018-03-31 09:32
@husayt But it is inside dependencies. Would you clean up node_modules and lock files and try installing things again? If you are sure this problem is happening please open a new issue.

**Comment by husayt** [comment] 2018-03-31 09:57
I reset lock files and it is ok now. thanks .

@pi0 by the way I am running nuxt-edge on my pet project https://www.sozler.im
Works great. Trying to figure out how to minimise amount of inline css which is served with the page, will try purge css to see if helps. Otherwise works all fine.
