### ISSUE TITLE
Calling `this.$route` in layout `head` method causes huge flickering

### ISSUE THREAD

**Issue by antoinerey** [nuxt/nuxt.js#4945] opened 2019-02-04 13:53 UTC
### Version

[v2.4.1](https://github.com/nuxt.js/releases/tag/v2.4.1)

### Reproduction link

[https://codesandbox.io/s/14qm9krom7](https://codesandbox.io/s/14qm9krom7)

### Steps to reproduce

1. Navigate back and forth between the home and about pages. Everything works properly, and there is no flickering at all.
2. Open  the `layouts/default.vue` file, uncomment `console.log(this.$route)`.
3. Navigate again between the home and about pages. When leaving the home page (using the `default` layout under the hood), a big flickering happens.

_Note that the exact opposite happens when adding `console.log(this.$route)` in `layouts/random.vue` instead._

### What is expected ?

No flickering at all.

### What is actually happening?

Some huge flickering.

### Additional comments?

For some reason, I need to disable a JS script based on a query parameter. Accessing `/` should load the script, but accessing `/?script=false` should prevent the script to load. So, I needed to access `this.$route`, and ran into this bug.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8604">#c8604</a>)</em></sub></div>

**Comment by pimlie** [comment] 2019-02-11 21:20
This is not a Nuxt issue but a Vue-Meta one, could you please create an issue in the vue-meta repo and refer to this one? https://github.com/nuxt/vue-meta/

The problem is that `head()` is transformed into a computed property, and by adding `this.$route` that computed property updates when the route changes. Also meta updates are protected from running at the same time, but they can still run instantly after each other without any time in between. 

So what happens is:
- you click button
- route changes
- head() is called to update metaInfo
- metaInfo is updated
- new page component is mounted which triggers an update
- metaInfo is updated
- the old page component is destroyed
- metaInfo is updated

Eg if I force to have 100ms between metaInfo updates then the page does not flicker because metaInfo is only updated once.

**Comment by antoinerey** [comment] 2019-02-12 09:27
cc https://github.com/nuxt/vue-meta/issues/320

**Comment by manniL** [comment] 2019-02-12 10:10
Closing here in favor of the linked ☺️

**Closed by manniL** 2019-02-12 10:10 UTC
Labels: cmty:bug-report
