### ISSUE TITLE
Error page not work on Nuxt Server Error

### ISSUE THREAD

**Issue by retep0214** [nuxt/nuxt.js#5903] opened 2019-06-10 06:25 UTC
### Version

[2.4.0](https://github.com/nuxt.js/releases/tag/2.4.0)

### Reproduction link

[http://local](http://local)

### Steps to reproduce

1)  Create the `layout/error.vue`
2)  Create the page which will call Axios via Vuex
3)  When calling API via Axios, the API return 404/500

### What is expected ?

The error will pass to the custom Error page.

### What is actually happening?

If user use nuxt-router to change the page (not SSR), the custom error page shown.
But if I refresh and view the SSR Page. The NuxtServerError Page will be shown in dev mode (yarn dev) and the default Server Error page when yarn start.

### Additional comments?

Here is my Axios Helper
```
import axios from 'axios'
const myAxios = axios.create({
  headers: { 'Accept': 'application/json' }
})

myAxios.interceptors.response.use((response) => {
  return response
}, (error) => {

  const { response } = error
  const { status, statusText } = response
  if (process.client) {
    $nuxt.error({ message: statusText, statusCode: status })
  } else {
    // Any solution can access the $nuxt here?
  }
  return Promise.reject(error)
})

export default myAxios
```

The page

```
import myAxios from 'PATH/TO/THIS/HELPER'
..
...
..

myAxios.get('http://example.com')
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9331">#c9331</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-06-10 09:36
Duplicate of https://github.com/nuxt/nuxt.js/issues/5904

**Closed by manniL** 2019-06-10 09:36 UTC
Labels: cmty:bug-report
