### ISSUE TITLE
Nuxt.js server responds very slow after a lot of connections.

### ISSUE THREAD

**Issue by nallown** [nuxt/nuxt.js#3566] opened 2018-07-20 20:03 UTC
### Version

[v1.4.0](https://github.com/nuxt.js/releases/tag/v1.4.0)

### Reproduction link

-

### Steps to reproduce

You can reproduce this problem by running the nuxt server and testing it with a lot of fresh requests. The more fresh requests you get, the slower the Nuxt app responds. When I restart the Nuxt.js server it responds in 2 seconds but after 200,000 requests, it responds in 8 seconds. The more requests I get, the slower it responds. I have to restart the nuxt.js app every night so that it doesn't get too slow.

### What is expected ?

The server shouldn't slow down after a lot of requests

### What is actually happening?

The server just gets slower every time another requests gets made.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7420">#c7420</a>)</em></sub></div>

**Comment by paolog22** [comment] 2018-07-27 02:58
i can relate to this issue .. hope this will be fix soon .

**Comment by paolog22** [comment] 2018-08-01 19:03
@Atinux @pi0 @clarkdo please help :) hope you seen this thanks

**Comment by Atinux** [comment] 2018-08-01 19:46
Hi, could you show us what do you use to make all these fresh requests?
Also, is it reproductible with the minimal starter template?

**Comment by paolog22** [comment] 2018-08-02 04:27
> Steps to reproduce
You can reproduce this problem by running the nuxt server and testing it with a lot of fresh requests. The more fresh requests you get, the slower the Nuxt app responds. When I restart the Nuxt.js server it responds in 2 seconds but after 200,000 requests, it responds in 8 seconds. The more requests I get, the slower it responds. I have to restart the nuxt.js app every night so that it doesn't get too slow.

**Comment by nallown** [comment] 2018-08-02 07:16
@Atinux I'm not creating any fake requests it happens naturally with real users on my site. I can a shift in loading times after the site responds to a lot of requests.

**Comment by hartmut-co-uk** [comment] 2018-08-02 15:09
@Atinux good old simple [Apache Bench](https://httpd.apache.org/docs/2.4/programs/ab.html) may help to get started
https://www.netguru.co/blog/load-testing-apache-bench

**Comment by hartmut-co-uk** [comment] 2018-08-02 15:11
@nallown @paolog22 did you attempt to reproduce with _vue_ itself?

**Comment by paolog22** [comment] 2018-08-02 16:06
not yet.. i will try.  you can also try using this [https://locust.io/](url)

**Comment by nallown** [comment] 2018-08-02 20:18
@hartmut-co-uk do you mean with Vanilla Vue SSR instead of Nuxt for the SSR? If so then I haven't cus idk how to setup my project with it since its so big right now.

**Comment by Atinux** [comment] 2018-08-08 00:17
That would be great if you could beta test with nuxt-edge directly @nallown 

We made more improvements into it and I don't think you will have breaking changes with it, it will be faster for me to help you on this.

**Comment by nallown** [comment] 2018-08-08 00:41
So far I don't see any problem with nuxt-edge, I'll think about pushing the nuxt-edge version to production soon. I'll keep you updated.

**Comment by Atinux** [comment] 2018-08-08 00:42
Nice, I'm closing the issue, but please re-open it if it happens again and mention me to make sure I will receive an email :)

**Comment by paolog22** [comment] 2018-08-08 03:18
@Atinux can you please let us know what happen ? Thanks for the fix

**Comment by Atinux** [comment] 2018-08-08 09:18
We made a lot of fixes on 2.0 so right now O can’t tell you which one is it. Sometimes it can be related to a small refacto, the beauty of programming :)

**Comment by paolog22** [comment] 2018-08-08 11:15
oh so nuxt 2 is officially out ? @Atinux

**Comment by Atinux** [comment] 2018-08-08 14:02
No but you can use `nuxt-edge` @paolog22 

We are fixing pending issue before release.

**Comment by nallown** [comment] 2018-09-04 08:02
@Atinux the server still slows down over time, even after the nuxt-edge update. I can give you repo access if you need to take a look at my code to figure out why its going on.

**Comment by Atinux** [comment] 2018-09-04 11:09
@nallown sure, I can take a look at, make sure you don't start any timer into `created` hook for example to avoid any kind of memory leak.

**Comment by Atinux** [comment] 2018-09-04 12:07
Could you join our Discord (https://discord.gg/N9mvU2q) and ping me please @nallown ?

**Comment by aldarund** [comment] 2018-09-23 12:54
i can reproduce it locally with apache bench. But not sure if it nuxt fault, or just tcp stack got exhaust.

**Comment by aldarund** [comment] 2018-09-29 20:10
Actually after some more testing i see that it happens when there memory leaks. With vanilla nuxt i cant reproduce it.
@Timkor do u have a reproduction example?

**Comment by Timkor** [comment] 2018-09-30 12:38
@aldarund 
Thank you for your reply. It is at production only and I can't seem to simulate it locally. I just ran it using the `blocket-at` package, like this:
```javascript
const blocked = require('blocked-at');

blocked(function(time, stack){
  console.log(`Blocked for ${time}ms, operation started here:`, stack)
}, { threshold: 1000});
```
What I see in the console, using node --inspect, is a increasing blocking server side render:

```
Blocked for 1095.253135986328ms, operation started here: 
0: "    at Promise.then (<anonymous>)"
1: "    at Object.renderToString (/var/wwwnode/ig-fr-prod/node_modules/vue-server-renderer/build.js:8578:12)"
2: "    at Renderer.renderRoute (/var/wwwnode/ig-fr-prod/node_modules/nuxt/dist/nuxt.js:1999:41)"
3: "    at Renderer.nuxtMiddleware (/var/wwwnode/ig-fr-prod/node_modules/nuxt/dist/nuxt.js:1555:31)"
4: "    at call (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:239:7)"
5: "    at next (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:183:5)"
6: "    at next (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:161:14)"
7: "    at next (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:161:14)"
8: "    at /var/wwwnode/ig-fr-prod/node_modules/express/lib/router/index.js:635:15"
9: "    at next (/var/wwwnode/ig-fr-prod/node_modules/express/lib/router/index.js:260:14)"
10: "    at expressInit (/var/wwwnode/ig-fr-prod/node_modules/express/lib/middleware/init.js:40:5)"
11: "    at Layer.handle [as handle_request] (/var/wwwnode/ig-fr-prod/node_modules/express/lib/router/layer.js:95:5)"
12: "    at trim_prefix (/var/wwwnode/ig-fr-prod/node_modules/express/lib/router/index.js:317:13)"
13: "    at /var/wwwnode/ig-fr-prod/node_modules/express/lib/router/index.js:284:7"
14: "    at Function.process_params (/var/wwwnode/ig-fr-prod/node_modules/express/lib/router/index.js:335:12)"
15: "    at next (/var/wwwnode/ig-fr-prod/node_modules/express/lib/router/index.js:275:10)"
16: "    at query (/var/wwwnode/ig-fr-prod/node_modules/express/lib/middleware/query.js:45:5)"
17: "    at Layer.handle [as handle_request] (/var/wwwnode/ig-fr-prod/node_modules/express/lib/router/layer.js:95:5)"
18: "    at trim_prefix (/var/wwwnode/ig-fr-prod/node_modules/express/lib/router/index.js:317:13)"
19: "    at /var/wwwnode/ig-fr-prod/node_modules/express/lib/router/index.js:284:7"
20: "    at Function.process_params (/var/wwwnode/ig-fr-prod/node_modules/express/lib/router/index.js:335:12)"
21: "    at next (/var/wwwnode/ig-fr-prod/node_modules/express/lib/router/index.js:275:10)"
22: "    at Function.handle (/var/wwwnode/ig-fr-prod/node_modules/express/lib/router/index.js:174:3)"
23: "    at Function.handle (/var/wwwnode/ig-fr-prod/node_modules/express/lib/application.js:174:10)"
24: "    at handle (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:91:14)"
25: "    at call (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:239:7)"
26: "    at next (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:183:5)"
27: "    at module.exports (/var/wwwnode/ig-fr-prod/server/middleware/shopping.js:70:9)"
28: "    at call (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:239:7)"
29: "    at next (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:183:5)"
30: "    at module.exports (/var/wwwnode/ig-fr-prod/server/middleware/referrer.js:85:5)"
31: "    at call (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:239:7)"
32: "    at next (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:183:5)"
33: "    at module.exports (/var/wwwnode/ig-fr-prod/server/middleware/session.js:11:5)"
34: "    at call (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:239:7)"
35: "    at next (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:183:5)"
36: "    at module.exports (/var/wwwnode/ig-fr-prod/server/middleware/redirect.js:20:9)"
37: "    at call (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:239:7)"
38: "    at Immediate.next (/var/wwwnode/ig-fr-prod/node_modules/connect/index.js:183:5)"
39: "    at Immediate.<anonymous> (/var/wwwnode/ig-fr-prod/node_modules/express/lib/router/index.js:635:15)"
40: "    at runCallback (timers.js:791:20)"
41: "    at tryOnImmediate (timers.js:751:5)"
42: "    at processImmediate [as _immediateCallback] (timers.js:722:5)"
```

The longer the application runs, the larger the blocking time.

**Comment by cg-rsands** [comment] 2018-10-16 22:17
We are facing same issue on Nuxt 2.0 - SSR is very slow and cannot cope with 3 requests per second
Really keen to try and solve this

**Comment by aldarund** [comment] 2018-10-16 22:58
@cg-rsands check your app for memory leaks. Check global mixins, plugins etc

**Comment by emokhles** [comment] 2018-10-29 12:35
any updates? I use only axios a plugin

**Comment by Timkor** [comment] 2018-10-29 12:40
@emokhles 
How do you inject axios as plugin to the Nuxt `app` context and Vue context?

I fixed my memory leaks bij injecting it using the `inject` method:

```
// plugins/axios.js
import axios from 'axios;

export default (context, inject) {
    inject('axios', axios);
}

```

Memory leaks were causing this issue in my case.

**Comment by emokhles** [comment] 2018-10-29 12:43
So you're not using the nuxt's axios

**Comment by emokhles** [comment] 2018-10-29 12:46
This is my plugin code

```
export default function ({ $axios, redirect }) {

    $axios.onError(error => {
        const code = parseInt(error.response && error.response.status);
        console.error('Erreur axios ' + code);
        if(error.code === 500) {
            redirect('/sorry')
        }
    })

}
```

**Comment by aldarund** [comment] 2018-10-29 13:00
@emokhles mixins? directives? something causing leak in your app.

**Comment by emokhles** [comment] 2018-10-29 13:18
How can i test if a have memory leak or not? because I am not really adding a lot of code to the starter code

**Comment by Timkor** [comment] 2018-10-29 14:04
The code I posted was an example for any plugin, not axios related. I actually use Nuxt's axios module which works for me without leaking.

For fixing memory leaks:
https://medium.com/tech-tajawal/memory-leaks-in-nodejs-quick-overview-988c23b24dba

You need to run your application using node --inspect. That means you cannot use `nuxt` command-line.
You will need a file for starting nuxt programmatically like this:
https://nuxtjs.org/api/nuxt-render

Try to clean the garbage collector (--expose-gc) before monitoring. And do several of the same requests over again.

**Comment by emokhles** [comment] 2018-10-29 16:46
![capture du 2018-10-29 17-40-57](https://user-images.githubusercontent.com/41120590/47665919-97a29680-dba2-11e8-8a0a-7dcb1599cbfd.png)
Does this prove that i have memory leak ?

**Comment by manniL** [comment] 2018-12-03 08:31
Closing this as we have a perf-related issue at #3956. Other memory leak issues are mostly unrelated to Nuxt itself but to own code. If that's *not* the case, please open a new issue

**Closed by manniL** 2018-12-03 08:31 UTC
Labels: :clock1:Pending, cmty:bug-report
