### ISSUE TITLE
Abstract hard-coded url-loader limits into a configurable option

### ISSUE THREAD

**Issue by moltar** [nuxt/nuxt.js#3785] opened 2018-08-22 13:11 UTC
### What problem does this feature solve?

This feature will allow users to easily override the hard-coded limits.

### What does the proposed changes look like?

Currently all `url-loader` rules hard-code the limit value to 1000 bytes. Arguably, this default limit is not universal and often needs changing. E.g. there are no fonts that are 1000 bytes, unless it is an icon font, with maybe a couple of icons. So that rule is not useful by default.

An abstracted setting for `nuxt.config.js` file, that would allow user to override this value would be very helpful.

It should probably be granular for each individual `url-loader` rule.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7616">#c7616</a>)</em></sub></div>

**Comment by moltar** [comment] 2018-08-22 13:12
Example: https://github.com/nuxt/nuxt.js/blob/820f0fae1a94793a2b9cf75e398531ab77e5bc8c/lib/builder/webpack/base.js#L197

**Comment by clarkdo** [comment] 2018-08-24 16:00
Hi @moltar , thank you for the proposal, we're discussing about a proper solution for loaders customized config.

**Comment by manniL** [comment] 2018-09-10 10:34
@moltar As #3799 has been merged, I'll close this. If the issue is still (somewhat) present, please ping me

**Closed by manniL** 2018-09-10 10:34 UTC
Labels: cmty:feature-request
