### ISSUE TITLE
When registering a dynamic store, there is no access to it.

### ISSUE THREAD

**Issue by avil13** [nuxt/nuxt.js#4395] opened 2018-11-24 02:23 UTC
### Version

[v2.3.2](https://github.com/nuxt.js/releases/tag/v2.3.2)

### Reproduction link

[https://codesandbox.io/s/2wq4w9mm3r](https://codesandbox.io/s/2wq4w9mm3r)

### Steps to reproduce

Hi.
After upgrading to Nuxt v2, there were problems with the dynamic addition of the store.

In version v1, everything worked perfectly.

### What is expected ?

Correct work
`this.$store.registerModule` and `this.$store.unregisterModule` 
methods.

### What is actually happening?

`this.$store.registerModule` does not add a new store

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8196">#c8196</a>)</em></sub></div>

**Comment by manniL** [comment] 2018-11-24 23:59
Duplicate of https://github.com/nuxt/nuxt.js/issues/4370

**Closed by manniL** 2018-11-24 23:59 UTC
Labels: cmty:bug-report
