### ISSUE TITLE
trying to require 'ws' only on server side code

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#984] opened 2017-06-28 02:08 UTC
Hello
I'm failing in require only WebSocket for server side code:
```
plugin/apolloClient.js
  if (process.SERVER_BUILD) {
    const ws = require('ws')
    wsClient = new SubscriptionClient(wsUri, {
      reconnect: true
    }, ws)
  } else {
    wsClient = new SubscriptionClient(wsUri, {
      reconnect: true
    })
  }

nuxt.config.js
extend (config, {dev, isServer}) {
      if (!isServer) {
        config.node = {
          fs: 'empty',
          tls: 'empty'
        }
      }
    },
```

I receive following error warning / client and server side:
```
 WARNING  Compiled with 2 warnings                                                                                                                                                                  10:06:46

 warning  in ./~/bindings/bindings.js

76:22-40 Critical dependency: the request of a dependency is an expression

 warning  in ./~/bindings/bindings.js

76:43-53 Critical dependency: the request of a dependency is an expression
```

**Comment by MatthieuHPP** [comment] 2017-10-15 07:55
hello,

I am using node 6.11, Nuxt V1 RC11 and Ubuntu 16.04
I am also having the same warning messages with the "ws" module (coming from "simplewebrtc" in my case).
It seems to be due to webpack : https://github.com/webpack/webpack/issues/196
I do not know webpack at all...

To reproduce this error, just add the package "ws" to the main package.json

Matthieu

**Comment by husayt** [comment] 2018-03-08 14:16
This seems to be resolved now. Closing. Reopen if still happens.

**Closed by husayt** 2018-03-08 14:16 UTC
Labels: status: need repro, type: help wanted
