### ISSUE TITLE
Methods / @Click not working on NUXT static generator

### ISSUE THREAD

**Issue by jsaberon** [nuxt/nuxt.js#6393] opened 2019-09-11 01:33 UTC
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://jsaberon.github.io](https://jsaberon.github.io)

### Steps to reproduce

Hit the about link on the navbar then go down about 100vh then click the other links

### What is expected ?

When link the link in about on the 2nd section, I want to trigger the active class or the active value on my navigation and the content on the right side not changing

### What is actually happening?

when I click the navigation nothing happens.

### Additional comments?

why method and @click not working on static generated site. Should I create another vanilla Javascript after generation?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9755">#c9755</a>)</em></sub></div>

**Comment by danielroe** [comment] 2019-09-11 19:08
@jsaberon The problem is that your JavaScript files can't be downloaded - they are returning 404 errors - so your generated site is not hydrated. For example, try [this link](https://jsaberon.github.io/_nuxt/5abcf0d2e53817e2e103.js). I would suspect something has gone awry with the deployment.

**Comment by jsaberon** [comment] 2019-09-12 00:23
@danielroe https://jsaberon.github.io this is the repo of my code.

When I run it in my computer I change the initial code for about page. I am using prettier so I can reformat the generated code. I also change the path of my code:

```
<link rel="preload" href="/_nuxt/e8e6805c616a0739f432.js" as="script" />
<link rel="preload" href="/_nuxt/725071e83c0a71a48942.js" as="script" />
<link rel="preload" href="/_nuxt/b1731a955fca3418a279.js" as="script" />
<link rel="preload" href="/_nuxt/4d9f75ccf9b467a07057.js" as="script" />

<script src="/_nuxt/e8e6805c616a0739f432.js" defer></script>
<script src="/_nuxt/4d9f75ccf9b467a07057.js" defer></script>
<script src="/_nuxt/725071e83c0a71a48942.js" defer></script>
<script src="/_nuxt/b1731a955fca3418a279.js" defer></script>
```
To this: 

```
<link rel="preload" href="../_nuxt/e8e6805c616a0739f432.js" as="script" />
<link rel="preload" href="../_nuxt/725071e83c0a71a48942.js" as="script" />
<link rel="preload" href="../_nuxt/b1731a955fca3418a279.js" as="script" />
<link rel="preload" href="../_nuxt/4d9f75ccf9b467a07057.js" as="script" />

<script src="../_nuxt/e8e6805c616a0739f432.js" defer></script>
<script src="../_nuxt/4d9f75ccf9b467a07057.js" defer></script>
<script src="../_nuxt/725071e83c0a71a48942.js" defer></script>
<script src="../_nuxt/b1731a955fca3418a279.js" defer></script>
```

**Comment by danielroe** [comment] 2019-09-12 01:16
https://nuxtjs.org/faq/github-pages/#deploying-to-github-pages-for-repository

**Comment by manniL** [comment] 2019-09-13 11:36
Loading is fine now, but now you have an error in your code 
![image](https://user-images.githubusercontent.com/640208/64859788-7f593000-d62b-11e9-9dfb-a622794dcb75.png)

Not a Nuxt issue, closing here.

PS: I'd highly suggest not to use jQuery in a Nuxt project ☺️

**Closed by manniL** 2019-09-13 11:36 UTC
Labels: cmty:bug-report
