### ISSUE TITLE
Inconsistent scrollToTop behaviour after update to 1.3.0

### ISSUE THREAD

**Issue by davidpmccormick** [nuxt/nuxt.js#2738] opened 2018-02-01 15:15 UTC
Certain pages that were (correctly) jumping to the top of the page after the route changed in 1.1.2 have stopped doing so in the latest release.

### Steps to reproduce
1. scroll down this page: http://next.btmat.org.uk/2012
2. click on an article excerpt link
3. see the article render half way down the page

[Here's the repo](https://github.com/davidpmccormick/btmat-nuxt)

Both the [`from` page](https://github.com/davidpmccormick/btmat-nuxt/blob/master/pages/_year.vue) and the [`to` page](https://github.com/davidpmccormick/btmat-nuxt/blob/master/pages/_year/_month/_pageSlug.vue) include `scrollToTop: true`.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2378">#c2378</a>)</em></sub></div>

**Comment by davision** [comment] 2018-02-02 09:46
I've noticed the same thing! Thank you @javialon26 for your snippet!

**Comment by javialon26** [comment] 2018-02-02 13:28
@davision this snippet is for 1.3.0 version not for 1.1.3

**Comment by davidpmccormick** [comment] 2018-02-02 13:53
Yep, sorry – I had the wrong version number in the ticket title. Have updated it to 1.3.0.

**Comment by davision** [comment] 2018-02-02 17:06
In all version since 1.0

**Comment by dohomi** [comment] 2018-02-26 09:31
I'm facing the same issue. But the workaround of @javialon26 does not do anything in my setup. I have a custom route on '*' and if the path changes I don't see any possibility of route change.

**Comment by bovas85** [comment] 2018-03-01 16:15
Same issue here

**Comment by atmar** [comment] 2018-03-06 23:58
Same here, not scrolling back to top on newest versions

**Comment by dohomi** [comment] 2018-03-07 00:58
In my opinion the issue is present if you are changing routes on the same page component via params or query value.

If the route change changes in between different page components the page scrolls up correctly and on history back the scroll position is persisted as well.

**Comment by bovas85** [comment] 2018-03-07 07:30
@dohomi your opinion is valuable, but wrong.
I have 1.4.0 and only use regular nuxt links to navigate between routes. The position of the page is an issue so when clicking on a footer link to the contact page, the contact page will have the scroll position of the previous

**Comment by sunlei4076** [comment] 2018-03-07 09:01
i copy default(https://nuxtjs.org/api/configuration-router) to nuxt.config.js
i found it ok 
nuxt1.4.0

`router: {
    scrollBehavior: function (to, from, savedPosition) {
      if (savedPosition) {
        return savedPosition
      } else {
        let position = {}
        // 目标页面子组件少于两个
        if (to.matched.length < 2) {
          // 滚动至页面顶部
          position = { x: 0, y: 0 }
        }
        else if (to.matched.some((r) => r.components.default.options.scrollToTop)) {
          // 如果目标页面子组件中存在配置了scrollToTop为true
          position = { x: 0, y: 0 }
        }
        // 如果目标页面的url有锚点,  则滚动至锚点所在的位置
        if (to.hash) {
          position = { selector: to.hash }
        }
        return position
      }
    }
  }`
![2018-03-07 4 56 14](https://user-images.githubusercontent.com/13211268/37083003-186bd224-2229-11e8-8c96-7d596e2fd3ec.png)

**Comment by onlyurei** [comment] 2018-03-10 06:39
@sunlei4076 thanks for sharing. This version of `scrollBehavior` worked for me too.

`nuxt.config.js`:
```js
 router: {
    scrollBehavior(to, from, savedPosition) {
      if (savedPosition) {
        return savedPosition
      } else {
        let position = {}
        if (to.matched.length < 2) {
          position = { x: 0, y: 0 }
        } else if (to.matched.some(r => r.components.default.options.scrollToTop)) {
          position = { x: 0, y: 0 }
        }
        if (to.hash) {
          position = { selector: to.hash }
        }
        return position
      }
    }
  }
```

**Comment by leadream** [comment] 2018-03-14 03:51
same issue

**Comment by angelika94** [comment] 2018-04-02 12:08
same issue

**Comment by robyedlin** [comment] 2018-04-07 18:31
This code does not run when a layout is changed. Think this is a bug.

```
    window.$nuxt.$once('triggerScroll', () => {
      // coords will be used if no selector is provided,
      // or if the selector didn't match any element.
      console.log('Triggered')
      if (to.hash && document.querySelector(to.hash)) {
        // scroll to anchor by returning the selector
        position = { selector: to.hash }
      }
      resolve(position)
    })
```

**Comment by rdunk** [comment] 2018-05-03 09:40
As far as I can see none of the suggested workarounds here take into account page transitions.

**Comment by xtranophilist** [comment] 2018-06-19 14:47
The issue with dyanmic routes where the page doesn't scroll to top when route param changes can be fixed by using `:key` on the top level element.

**Comment by xtranophilist** [comment] 2018-06-19 15:08
Using `:key` on top level element in the page component with dynamic routes fixes scrolling to top when route param changes.

**Comment by davision** [comment] 2018-06-19 21:35
I have it and it doesn't help :/. In my page component I'm having: 

```
<template>
  <div :key="$route.params.slug">
```

Still coming off the page component with a dynamic route to a static one,  the page is positioned somewhere in the middle.

I am currently solving with `v-scroll-to="{el: '#__nuxt' }"` in the <nuxt-link> which is ugly but I still didn't find a better solution. How do you guys solving this? To mention, on this page with dynamic rout I am sourcing markdown content with markdown-it plugin. Could that be the case?

**Comment by lzq920** [comment] 2018-07-26 09:22
same issue

**Comment by galvez** [comment] 2018-08-25 06:04
@Atinux is this still an issue?

**Comment by bovas85** [comment] 2018-08-25 06:27
I've been using nuxt Edge and it is an issue usually

**Comment by Coletrane** [comment] 2018-08-29 13:26
I'm using some of the fixes on this thread and `savedPosition` works after the first navigation, then on a subsequent one the value is the max scroll of the page.

**Comment by bovas85** [comment] 2018-09-22 12:26
I spoke yesterday with @Atinux  on this and the real issue is vue-router implementation here.

I think we should close / pause this and reference a bug on their side.

**Comment by galvez** [comment] 2018-10-21 10:40
@Atinux @pi0 @clarkdo do you know if this is still an issue?

**Comment by aldarund** [comment] 2018-10-21 12:39
@galvez yes it is

**Comment by jsonwen** [comment] 2018-10-22 12:37
Experiencing same issue. None of the workarounds above worked for me.
`scrollBehavior (to, from, savedPosition) {
  if (savedPosition) {
    return savedPosition
  } else {
    return { x: 0, y: 0 }
  }
}`

This part works as intended on vue without nuxt.

**Comment by davidpmccormick** [comment] 2018-11-15 17:54
I'd be sad if this fell off the radar – I'm still looking for a solution.

**Comment by davision** [comment] 2018-11-16 09:46
The only acceptable solution for me right now is to use a vue-scrollto plugin. On a default template or _slug I'm having: 

```javascript
mounted() {
    vueScroll.scrollTo('body')
}
```

It's ugly hack but currently, the only way to go, sadly.

**Comment by davision** [comment] 2018-11-16 13:47
The case is, that you are on one page, scroll down, click on some link in the footer, you go to another page positioned at the bottom. You should come to the top of that new page. But you don't.

**Comment by bovas85** [comment] 2018-11-16 13:50
Can you not use window.scrollTo(0, 0) then?

**Comment by davision** [comment] 2018-11-18 10:51
That could also work, but then you'll have quite an ugly jump from the bottom of the page to the top.

**Comment by manniL** [comment] 2018-11-24 16:17
All: can you try it with updated node modules (`npm update`/`yarn upgrade`)? Vue Router had released a new version.

**Comment by davidpmccormick** [comment] 2018-11-24 16:30
Thanks @manniL – I just upgraded, but sadly the issue is still present (same steps as in the initial post).

**Comment by bovas85** [comment] 2018-11-24 16:33
I don't think nuxt uses vue-router from your node_modules. I think it's internally built in?
Or perhaps try installing it in your dependancies

**Comment by manniL** [comment] 2018-11-24 16:55
@bovas85 Nuxt depends on vue-router

**Comment by bovas85** [comment] 2018-11-24 19:04
interesting, looks fixed for me

**Comment by manniL** [comment] 2018-11-24 19:11
@bovas85 Same here, though https://github.com/nuxt/nuxt.js/issues/4080 is still there

**Comment by bovas85** [comment] 2018-11-24 21:40
I'll try that.

**Comment by manniL** [comment] 2018-11-24 23:10
Problem is still reproducable. My guess is because of `nuxt-child` usage:

```html
<div class="news">
    <NewsList :articleStubs="articleStubs" v-if="$route.name === 'year'" />
    <nuxt-child v-else />
</div>
```

**Comment by manniL** [comment] 2018-11-25 00:05
As the majority of the problems of this mega-issue is solved, I'll close hear and open a specific one for the problem related to the reproduction of @davidpmccormick

**Closed by manniL** 2018-11-25 00:05 UTC
Labels: :clock1:Pending, cmty:bug-report
