### ISSUE TITLE
New Nuxt.js versions don't render <style/> tags in the template area

### ISSUE THREAD

**Issue by Coder911th** [nuxt/nuxt.js#6819] opened 2019-12-21 14:56 UTC
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://github.com/Coder911th/nuxt-ssr-styles-example](https://github.com/Coder911th/nuxt-ssr-styles-example)

### Steps to reproduce

git clone https://github.com/Coder911th/nuxt-ssr-styles-example
cd nuxt-ssr-styles-example

cd 2.9.2
npm i
npm run build
npm start
Open http://localhost:3000
The rectangle is red.

cd ../
cd 2.11.0
npm i
npm run build
npm start
Open http://localhost:3000
The rectangle is white.

### What is expected ?

The red rectangle is expected for version 2.11.0

### What is actually happening?

Actually <style/> is not rendered in version 2.11.0, therefore the rectangle is white.

### Additional comments?

The error appeared in version 2.10.0

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10146">#c10146</a>)</em></sub></div>

**Comment by daliborgogic** [comment] 2019-12-21 16:20
@Coder911th  Why do you need style in template? Use css variables:

```html
<template>
  <div :style="style" />
</template>

<script>
export default {
  computed: {
    style () {
      const color = 'tomato' // Get somehow e.g. from store.
      return {
        '--color': color
      }
    }
  }
}
</script>

<style>
div {
  width: 200px;
  height: 100px;
  background-color: var(--color);
}
</style>

```

**Comment by aldarund** [comment] 2019-12-22 15:39
I didnt checked repos, but it shouldnt work at all even in older version of nuxt. https://stackoverflow.com/a/57331310/239354

**Comment by manniL** [comment] 2019-12-22 15:58
Duplicate of https://github.com/nuxt/nuxt.js/issues/6645

**Closed by manniL** 2019-12-22 15:58 UTC
Labels: cmty:bug-report
