### ISSUE TITLE
Store: Add Dynamic Module Registration support

### ISSUE THREAD

**Issue by HapLifeMan** [nuxt/nuxt.js#4466] opened 2018-12-02 00:04 UTC
Hi, do you have any plan to support Dynamic Module Registration as said in a previous issue? #3162

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8260">#c8260</a>)</em></sub></div>

**Comment by aldarund** [comment] 2018-12-02 10:00
As said in previous issue you can do it already. What kind of support do u expect?

**Comment by HapLifeMan** [comment] 2018-12-02 16:57
I tried to register a module when a component is created, it works well but I the state of the module is undefined when I try to commit some modifications from actions/mutations...

It throws an error `Cannot set property 'config' of undefined`, what I'm doing:

In my component:
 ```javascript
import myModule from '../../store/modules/myModule'

export default {
  // Some code...
  async created() {
    this.$store.registerModule('myModule', myModule)
    this.$store.dispatch('myModule/init', config)
  }
  // Some code...
}
```

Then in my module's store:
```javascript
const state = {
  config: null
}

const actions = {
  init({ commit }, config) {
    commit('initConfig', config)
  }
}

const mutations = {
  initConfig(state, config) {
    state.config = config
  }
}

export default { state, actions, mutations }
```

As said previously, `state` is undefined when trying to update the state from mutation...

**Comment by begueradj** [comment] 2018-12-02 17:03
@HapLifeMan 
Welcome.
This is a bug tracker, if you have a question, this is not the right place.
You can for instance ask on StackOverflow
Thanks.

**Comment by manniL** [comment] 2018-12-07 21:47
Duplicate of #4370

**Closed by manniL** 2018-12-07 21:47 UTC
Labels: cmty:question
