### ISSUE TITLE
Nuxt Build Error ， when I use Typescript and ElementUI

### ISSUE THREAD

**Issue by zhangxuchuan827** [nuxt/nuxt.js#7765] opened 2020-07-24 09:07 UTC
I created the project using Nuxt-App CLI, TypeScript and ElementUI, but when I built, it reported an error
### Versions

- nuxt: v2.13.0 
- node: v14.5.0

### Reproduction
https://github.com/nuxt/nuxt.js/

```
119:18 Interface 'NuxtApp' incorrectly extends interface 'Vue'.
  Types of property '$loading' are incompatible.
    Type 'NuxtLoading' is not assignable to type '(options: LoadingServiceOptions) => ElLoadingComponent'.
      Type 'DefaultNuxtLoading' is not assignable to type '(options: LoadingServiceOptions) => ElLoadingComponent'.
        Type 'DefaultNuxtLoading' provides no match for the signature '(options: LoadingServiceOptions): ElLoadingComponent'.
    117 | }
    118 | 
  > 119 | export interface NuxtApp extends Vue {
        |                  ^
    120 |   $options: NuxtAppOptions
    121 |   $loading: NuxtLoading
    122 |   context: Context

 FATAL  Nuxt build error   
  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5472:21)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5421:5)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5629:5)
  at Object.run (node_modules/@nuxt/cli/dist/cli-build.js:107:7)
  at NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2798:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps to reproduce

yarn create nuxt-app ssr-test
-----------------------
✨  Generating Nuxt.js project in ssr-test
? Project name: ssr-test
? Programming language: TypeScript
? Package manager: Yarn
? UI framework: Element
? Nuxt.js modules: (Press <space> to select, <a> to toggle all, <i> to invert se
lection)
? Linting tools: ESLint, StyleLint
-----------------------
cd nuxt-app ssr-test

yarn build

### What is Expected?

I need it to work

### What is actually happening?
Is it because ElementUI conflicts with the NuxtJS definition of $message?

**Comment by zhangxuchuan827** [comment] 2020-07-24 09:15
sorry ,   it is ``$loading``

**Comment by zhangxuchuan827** [comment] 2020-07-24 09:20
```index.d.ts```
```
export interface NuxtApp extends Vue {
  $options: NuxtAppOptions
  $loading: NuxtLoading  // This field is already defined by ElementUI
  context: Context
  error(params: NuxtError): void
  isOffline: boolean
  isOnline: boolean
  layout: any // TBD
  layoutName: string
  loadLayout(layout: string): Promise<any> // TBD
  refresh(): Promise<void>
  setLayout(layout: string): any // TBD
}
```

**Comment by aldarund** [comment] 2020-07-24 12:32
ElementUi defined $loading prop as a global to Vue while we have nuxt $loading in $nuxt and so it conflicts

**Comment by zhangxuchuan827** [comment] 2020-07-25 02:42
Yes, but how do we solve it now? Is the community ready to release a fix?

**Comment by danielroe** [comment] 2020-07-27 11:12
See https://github.com/nuxt/typescript/issues/49 for more details.

**Comment by kevinmarrec** [comment] 2020-07-27 11:12
Duplicate of #7679

**Closed** 2020-07-27 11:12 UTC
Labels: bug-report, types
