### ISSUE TITLE
Non-scoped styles inside unused layouts get applied anyway

### ISSUE THREAD

**Issue by jaredreich** [nuxt/nuxt.js#4559] opened 2018-12-15 03:46 UTC
### Version

[2.3.4](https://github.com/nuxt.js/releases/tag/2.3.4)

### Reproduction link

[https://codesandbox.io/s/1vm41pzp1l](https://codesandbox.io/s/1vm41pzp1l)

### Steps to reproduce

You can see that there is an `html { ... }` style declaration in the layout file `layouts/test.vue`... even though that layout is never used anywhere, the style is still applied.

Shouldn't styles (non-scoped too) declared in a layout only be applied when the layout is in use? Is this possible?

### What is expected ?

Styles declared in a layout should only apply when the layout is in use.

### What is actually happening?

Styles declared in a layout are applied even when the layout is not in use.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8313">#c8313</a>)</em></sub></div>

**Comment by jaredreich** [comment] 2018-12-16 23:07
Related to nuxt.js/issues/1801? This definitely feels like an unresolved bug.

**Comment by manniL** [comment] 2018-12-17 10:55
Duplicate of https://github.com/nuxt/nuxt.js/issues/3877

**Closed by manniL** 2018-12-17 10:55 UTC
Labels: cmty:bug-report
