### ISSUE TITLE
Nuxt 2 - Can not load font (.woff) file

### ISSUE THREAD

**Issue by nghiepit** [nuxt/nuxt.js#5042] opened 2019-02-15 06:40 UTC
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://user-images.githubusercontent.com/4768095/52838878-ba8f9100-3126-11e9-9dea-8c6f2d98bf1d.png](https://user-images.githubusercontent.com/4768095/52838878-ba8f9100-3126-11e9-9dea-8c6f2d98bf1d.png)

### Steps to reproduce

Hi guys,

I'm using ElementUI and [custom-theme](https://element.eleme.io/#/en-US/component/custom-theme)

But I saw error with file font.

![image](https://user-images.githubusercontent.com/4768095/52838878-ba8f9100-3126-11e9-9dea-8c6f2d98bf1d.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8666">#c8666</a>)</em></sub></div>

**Comment by husayt** [comment] 2019-02-15 15:38
@nghiepit there is not enough details here. Where is your code?

**Comment by nghiepit** [comment] 2019-02-15 15:57
@husayt 

Thanks for your response.
This is my repo https://github.com/nghiepit/nuxt2-element-ui-bug

**Comment by manniL** [comment] 2019-02-18 14:53
Duplicate of #4060

The bug fix isn't released yet as it seems, so switching over to `nuxt-edge` or waiting for the release should do the trick!

**Closed by manniL** 2019-02-18 14:53 UTC
Labels: cmty:bug-report
