### ISSUE TITLE
Cannot resolve '@' in serverMiddleware

### ISSUE THREAD

**Issue by payalord** [nuxt/nuxt.js#7017] opened 2020-02-27 18:30 UTC
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

[https://codesandbox.io/s/servermiddleware-resolve-problem-hqtbw](https://codesandbox.io/s/servermiddleware-resolve-problem-hqtbw)

### Steps to reproduce

1. Create server middleware
2. import custom object from any custom js file with `@` in path, that must start pointing from root of the project.

### What is expected ?

`@` to point to root as it does in nuxt normally.

### What is actually happening?

```
Error: Cannot find module '@/api/routes/users'
Error: Cannot find module '@/models/user'
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10323">#c10323</a>)</em></sub></div>

**Comment by matteo-rigon** [comment] 2020-02-28 11:17
'@' is a Webpack alias for the project root. Server middleware are loaded by Node, you must use relative paths.

**Comment by payalord** [comment] 2020-02-28 12:42
@matteo-rigon No way to implement same in Node?

**Comment by pi0** [comment] 2020-02-28 12:46
@payalord Not official way but you can try [better-module-alias](https://www.npmjs.com/package/better-module-alias). I started working on a better POC [aliaz](https://github.com/jsless/aliaz) but not stable. 

As you may have heard, we are working on Nuxt functions which make API development much easier for nuxt :)

**Comment by pi0** [comment] 2020-02-28 12:47
A detailed gist discussing different Node alias methods: https://gist.github.com/branneman/8048520

**Comment by payalord** [comment] 2020-02-28 16:26
@pi0 you guys doing great job, big thanks for all of you for that. I will try to implement in serverMiddleware `better-module-alias`. And will check your project too. Thanks.

**Comment by manniL** [comment] 2020-02-29 18:05
Duplicate of #4580

**Closed by manniL** 2020-02-29 18:05 UTC
Labels: cmty:feature-request, cmty:question

**Comment by payalord** [comment] 2020-03-11 06:55
Fixed it like this:
```javascript
// File: `/api/index.js` <-- my nuxt serverMiddleware
const moduleAlias = require('module-alias')
moduleAlias.addAliases({
  '@'  : __dirname + '/../'
})
module.exports = require('./app')
```

```javascript
// File: `/api/app.js`
import express from 'express'
import routes from './routes'

const app = express()

// Import API Routes
app.use(routes)

// Export the server middleware
export default {
  path: '/api',
  handler: app
}
```

```javascript
// File: `/api/routes.js`
import User from '@/models/user' // <-- works fine
...
```

```javascript
// File: `/models/user.js`
export default function User () {...}
```
