### ISSUE TITLE
Memory leak, JS out of memory in production

### ISSUE THREAD

**Issue by erkand-imeri** [nuxt/nuxt.js#10768] opened 2022-10-19 12:28 UTC
```js 
{
  "name": "app-name",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "NODE_ENV=production nuxt start",
    "generate": "nuxt generate",
    "test": "jest",
    "test:snapshot": "jest --updateSnapshot"
  },
  "dependencies": {
    "@babel/preset-env": "^7.18.9",
    "@datadog/browser-logs": "^4.6.0",
    "@nuxtjs/axios": "^5.13.6",
    "@nuxtjs/dotenv": "^1.4.1",
    "@nuxtjs/i18n": "^7.2.2",
    "app-config": "*",
    "core-js": "^3.19.3",
    "jest-serializer-vue": "^2.0.2",
    "nuxt": "^2.15.8",
    "vue": "^2.6.14",
    "vue-server-renderer": "^2.6.14",
    "vue-template-compiler": "^2.6.14",
    "webpack": "^4.46.0"
  },
  "devDependencies": {
    "@nuxtjs/style-resources": "^1.2.1",
    "@vue/test-utils": "^1.3.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^28.1.3",
    "jest": "^28.1.3",
    "jest-environment-jsdom": "^28.1.3",
    "jsdom-worker": "^0.2.1",
    "node-sass": "^7.0.1",
    "nuxt-compress": "^5.0.0",
    "sass": "^1.53.0",
    "sass-loader": "^10",
    "vue-jest": "^3.0.4"
  }
}


```

```js
import i18n from './config/i18n';

export default {
  ssr: false,
  loading: false,
  router: {
    base: '/appname',
    prefetchLinks: false
  },
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'app-name',
    htmlAttrs: {
      lang: 'en'
    },
    script: [
      {
        src: '',
        async: false,
      },
    ],
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
      { name: 'format-detection', content: 'telephone=no' }
    ],
    link: [
      {rel: '' },
    ]
  },

  server: {
    host: '0',
    port: 3002
  },
  generate: {
    crawler: false,
  },
  publicRuntimeConfig: {
    eventLoggerServiceEndpoint: process.env.EVENT_LOGGER_API
  },
  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [
  ],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [
    { src: '~/plugins/zaf-library.js', mode: 'client'},
    { src: '~/plugins/event-logger.js', mode: 'client' },
    { src: '~/plugins/datadog-logger.js', mode: 'client' },
  ],
  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    '@nuxtjs/dotenv',
    '@nuxtjs/style-resources'
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
    modules: [
      '@nuxtjs/axios',
    [
    '@nuxtjs/i18n',
    {
      vueI18nLoader: true,
      strategy: 'no_prefix',
      defaultLocale: 'en',
      skipSettingLocaleOnNavigate: true,
      locales: [
        {
          code: 'en',
          name: 'English'
        }
      ],
      vueI18n: i18n
    }
  ],
  [
      "nuxt-compress",
      {
        gzip: {
          cache: true
        },
        brotli: {
          threshold: 10240
        }
      }
    ]
    ],
  dev: process.env.NODE_ENV !== 'production',
  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    watch: ['api/**/*.js']
  },

  serverMiddleware: [
    '~/api/index.js'
  ],
}

```
### What is actually happening?

I am having memory leak, i deploy Nuxt.js as containerized app in K8, the container memory keeps growing until it's being restarted by K8, i have been following graphana graphs and the memory keeps growing constantly. The same app in Laravel/Vue.js is quite stable and constant.

**Comment by danielroe** [comment] 2022-10-19 12:37
A memory leak can be due to many things, including your own code or libraries you are depending upon. It is impossible to diagnose without a minimal reproduction, so I'm closing this. Feel free to comment with a minimal reproduction and I'll be very happy to investigate further.

**Closed by danielroe** 2022-10-19 12:37 UTC
Labels: bug-report

**Comment by erkand-imeri** [comment] 2022-10-19 12:40
@danielroe i don't think it's fair that you are closing immediately, a lot of people are complaining about the same stuff. You must have a list of reasons why, i can tell you that i can deduce that the memory leak is not due to the app code, because it's happening with two different apps with separate codebases, and before refactoring to Nuxt.js this was not the case with old Vue.js codebase which is almost identical logical-wise in Nuxt.js.

So, can you list a number of reasons/dependencies (i listed) which it might affect Nuxt.js memory leak in production? Otherwise i think it's due to the framework itself since most of the questions opened remained unsolved.

**Comment by erkand-imeri** [comment] 2022-10-19 12:43
There is no apparent reason of reproduction, it happens after we deploy and our end-users start using the app, memory keeps growing linearly until it hits to an error.

```js
[28:0x7f2a249233c0] 118531583 ms: Mark-sweep 251.1 (258.8) -> 249.8 (258.8) MB, 681.1 / 0.0 ms  (average mu = 0.974, current mu = 0.973) allocation failure scavenge might not succeed

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

```

**Comment by danielroe** [comment] 2022-10-19 13:24
Start by removing piece by piece of your app. Remove as much of you can as still exhibits the behaviour. It should have no dependencies but Nuxt. Then commit to a repository with some steps to reproduce. It's fine if behaviour takes a while to reproduce or requires running under high load.

**Comment by Mobeidat** [comment] 2023-01-04 07:15
@erkand-imeri  How did you resolve this?

I'm facing the same issue without any luck to find a solution
