### ISSUE TITLE
warnings while creating fresh app

### ISSUE THREAD

**Issue by ctfrancia** [nuxt/nuxt.js#6670] opened 2019-11-08 15:28 UTC
### Version

[v2.10.2](https://github.com/nuxt.js/releases/tag/v2.10.2)

### Reproduction link

[https://www.example.com](https://www.example.com)

### Steps to reproduce

run `$ yarn create nuxt-app <project name>`

### What is expected ?

for the app to be created

### What is actually happening?

 nuxt > @nuxt/webpack > webpack > watchpack > chokidar > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents
 v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
warning babel-jest > @jest/transform > jest-haste-map > fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1)
Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.

### Additional comments?

I know that jest has the warning that won't go away till next major update, however, with the rest I don't know why I am getting these errors.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10003">#c10003</a>)</em></sub></div>

**Comment by SyloRei** [comment] 2019-11-11 08:14
Hi, @ctfrancia
Can you provide more information about the created application? What creation options were chosen?

**Comment by SyloRei** [comment] 2019-11-11 08:32
It seems the problem is only with yarn.

**Comment by manniL** [comment] 2019-11-11 09:32
Slight duplicate of https://github.com/nuxt/nuxt.js/issues/6675

Nothing we can do on our end as it's related to dependencies of dependencies.
Your app should run anyway.

**Closed by manniL** 2019-11-11 09:32 UTC
Labels: cmty:bug-report
