### ISSUE TITLE
Couldn't find package "@nuxt/builder@2.14.1" required by "nuxt@^2.14.0" on the "npm" registry

### ISSUE THREAD

**Issue by jornwildenbeest** [nuxt/nuxt.js#7871] opened 2020-08-06 11:10 UTC
When I tried to upgrade from nuxt 2.13 to 2.14, it caused this error:

`Couldn't find package "@nuxt/builder@2.14.1" required by "nuxt@^2.14.0" on the "npm" registry.`

After trying to install a fresh installation with 

`yarn create nuxt-app <project-name>`

![image](https://user-images.githubusercontent.com/25662412/89520821-bd7cb680-d7de-11ea-8496-fb38626f1cfe.png)

### Versions

- nuxt: 
- node: 

### Reproduction

Execute: 

`yarn create nuxt-app testv14`

<details open>
<summary>Additional Details</summary>
<br>

</details>

### What is Expected?

A fresh nuxt installation

### What is actually happening?

Error's

**Comment by gevglevskiy** [comment] 2020-08-06 11:12
same issue

**Comment by danielroe** [comment] 2020-08-06 11:16
@epsy-me This is not a Nuxt issue. There are currently issues accessing npmjs.com and installing scoped packages.

https://status.npmjs.org/incidents/cksjqc1w11v5?u=yjqzk11ky282

Duplicate of #7870, #7869 and #7868

**Comment by mkosmen** [comment] 2020-08-06 11:17
same issue . all nuxt dependencies gives E404 error

![powershell_Ku4W5oRZS0](https://user-images.githubusercontent.com/3495912/89525774-63382180-d7ef-11ea-82d8-cadb99ffad32.png)

**Closed by danielroe** 2020-08-06 11:16 UTC
Labels: bug-report

**Comment by youssefkhouili** [comment] 2020-08-06 11:38
hi @jornwildenbeest have you fixed the issue i have the same problem

**Comment by jornwildenbeest** [comment] 2020-08-06 11:42
@youssefkhouili Nope, i think there is still some issues going on at npmjs.com

**Comment by youssefkhouili** [comment] 2020-08-06 11:49
@jornwildenbeest ok thanks and i hope to be fixed soon
