### ISSUE TITLE
Issue with cache and extractCSS options

### ISSUE THREAD

**Issue by Snack-X** [nuxt/nuxt.js#8048] opened 2020-09-10 10:11 UTC
### Versions

- nuxt: 2.14.4 (Latest at the time)
- node: 12.18.3 (Latest LTS at the time)

### Steps to reproduce

1. Create a new project with `npx create-nuxt-app`
2. Add `cache: true` and `extractCSS: true` under `build` property of `nuxt.config.js` 
3. Run `npm run build` multiple times

### What is Expected?

Same build output should be produced every time.

### What is actually happening?

CSS files are not built properly after first build.

---

This issue is same as previously reported #7446, which got no attention at all and got closed.

On the first build:

```
$ rm -rf .nuxt node_modules/.cache
$ tail -n 5 nuxt.config.js
  build: {
    cache: true,
    extractCSS: true
  }
}

$ npm run build

(...)

Hash: 059da7bbc63505e52e5e
Version: webpack 4.44.1
Time: 3829ms
                         Asset       Size  Chunks                         Chunk Names
../server/client.manifest.json   7.19 KiB          [emitted]
                      LICENSES  389 bytes          [emitted]
               app.b005f86.css   1.64 KiB       0  [emitted] [immutable]  app
                app.ec4cf0e.js   45.5 KiB       0  [emitted] [immutable]  app
        pages/index.5cbdd89.js   1.95 KiB       1  [emitted] [immutable]  pages/index
       pages/index.cd53d7b.css  578 bytes       1  [emitted] [immutable]  pages/index
            runtime.3fb7b6d.js   3.16 KiB       2  [emitted] [immutable]  runtime
    vendors/commons.d3d3735.js    155 KiB       3  [emitted] [immutable]  vendors/commons
 + 2 hidden assets
Entrypoint app = runtime.3fb7b6d.js vendors/commons.d3d3735.js app.b005f86.css app.ec4cf0e.js

Hash: 574eca768c51ad9846fa
Version: webpack 4.44.1
Time: 437ms
               Asset       Size  Chunks             Chunk Names
      pages/index.js   10.5 KiB       1  [emitted]  pages/index
           server.js   71.8 KiB       0  [emitted]  app
server.manifest.json  207 bytes          [emitted]
 + 2 hidden assets
Entrypoint app = server.js server.js.map
ℹ Ready to run nuxt start

$ find .nuxt/dist/client
.nuxt/dist/client
.nuxt/dist/client/runtime.3fb7b6d.js
.nuxt/dist/client/vendors
.nuxt/dist/client/vendors/commons.d3d3735.js
.nuxt/dist/client/app.b005f86.css
.nuxt/dist/client/pages
.nuxt/dist/client/pages/index.5cbdd89.js
.nuxt/dist/client/pages/index.cd53d7b.css
.nuxt/dist/client/LICENSES
.nuxt/dist/client/app.ec4cf0e.js
```

Everything is working correctly and CSS files are built as it should.

But if I try the same command again:

```
$ npm run build

(...)

Hash: 6594ece4dd75438b891b
Version: webpack 4.44.1
Time: 2823ms
                         Asset       Size  Chunks                         Chunk Names
../server/client.manifest.json    6.9 KiB          [emitted]
                      LICENSES  389 bytes          [emitted]
               app.7a3f40f.css  942 bytes       0  [emitted] [immutable]  app
                app.ec4cf0e.js   45.5 KiB       0  [emitted] [immutable]  app
        pages/index.5cbdd89.js   1.95 KiB       1  [emitted] [immutable]  pages/index
            runtime.d6e71fc.js   2.32 KiB       2  [emitted] [immutable]  runtime
    vendors/commons.d3d3735.js    155 KiB       3  [emitted] [immutable]  vendors/commons
 + 2 hidden assets
Entrypoint app = runtime.d6e71fc.js vendors/commons.d3d3735.js app.7a3f40f.css app.ec4cf0e.js

Hash: 574eca768c51ad9846fa
Version: webpack 4.44.1
Time: 434ms
               Asset       Size  Chunks             Chunk Names
      pages/index.js   10.5 KiB       1  [emitted]  pages/index
           server.js   71.8 KiB       0  [emitted]  app
server.manifest.json  207 bytes          [emitted]
 + 2 hidden assets
Entrypoint app = server.js server.js.map
ℹ Ready to run nuxt start

$ find .nuxt/dist/client
.nuxt/dist/client
.nuxt/dist/client/vendors
.nuxt/dist/client/vendors/commons.d3d3735.js
.nuxt/dist/client/pages
.nuxt/dist/client/pages/index.5cbdd89.js
.nuxt/dist/client/runtime.d6e71fc.js
.nuxt/dist/client/app.7a3f40f.css
.nuxt/dist/client/LICENSES
.nuxt/dist/client/app.ec4cf0e.js
```

JS files are okay and identical to the previous build, but only one CSS file has been generated.

Using only `cache` or `extractCSS` is fine, but combining two options causes an issue.

**Comment by superbiche** [comment] 2020-09-17 16:55
Having the same issue with same versions.  
`build.parallel` outputs an useful error: `WARN  extractCSS cannot work with parallel build due to limited work pool in thread-loader` 
I guess it would be enough to raise the same warning for the `cache` option.

**Comment by superbiche** [comment] 2020-10-17 23:49
The problem is still here

**Comment by VRuzhentsov** [comment] 2020-11-23 13:05
Still can reproduce

**Comment by clarkdo** [comment] 2020-11-29 20:07
This is duplicate of https://github.com/nuxt/nuxt.js/issues/8061. Please see my comment https://github.com/nuxt/nuxt.js/issues/8061#issuecomment-735446447

**Closed by clarkdo** 2020-11-29 20:07 UTC
Labels: bug-report
