### ISSUE TITLE
Layout should be able to extend another layout ("layout nesting"?)

### ISSUE THREAD

**Issue by dugajean** [nuxt/nuxt.js#6104] opened 2019-07-21 12:27 UTC
### What problem does this feature solve?

This would allow for DRY layouts, without having to copy content over from another base layout which a new layout might be extending. A new layout should be able to simply extend another existing layout and the hook layout's contents into the base layout's `<nuxt />`. These are just implementation details, but you probably get the gist of this.

### What does the proposed changes look like?

Layout 1 (Base layout, `layouts/generic.vue`)

```
<template>
    <div class="flex flex-col min-h-screen">
        <Header :menu="mainMenu" :is-white="navWhite" />

        <div class="flex-1">
            <nuxt />
        </div>

        <Footer :menu="mainMenu" :pages="pages" />
    </div>
</template>

<script>
    import { mapGetters } from 'vuex'
    import Header from '~/components/Header'
    import Footer from '~/components/Footer'

    export default {
        components: { Header, Footer },

        computed: {
            ...mapGetters(['mainMenu', 'pages', 'navWhite'])
        }
    }
</script>
```

Layout 2 (Layout that relies in the base layout for some info, `layouts/blog.vue`)

```
<template>
    <div class="flex justify-center w-full md:w-11/12 lg:w-10/12 xl:w-9/12 py-12 px-4 mx-auto">
        <main class="flex flex-col-reverse lg:flex-row lg:-mx-6">
            <nuxt />

            <section class="w-full lg:w-2/6 px-6">
                <form action="" @submit.prevent="handleSearch">
                    <FormField
                        type="search"
                        name="search"
                        placeholder="Search all blog..."
                    />
                </form>
                <ul class="mt-5 border rounded text-gray-700 text-sm">
                    <li
                            v-for="(category, index) of categories"
                            :key="`cat-${index}`"
                            class="border-b"
                    >
                        <nuxt-link
                            :to="`/blog/${category.slug}`"
                            class="py-4 px-5 flex justify-between items-center hover:bg-gray-200"
                        >
                            <div class="flex items-center ">
                                <fa icon="angle-right" class="mr-3" />
                                <div class="category" v-text="category.name"></div>
                            </div>
                            <span
                                class="px-2 py-1 bg-blue-500 text-white rounded-full text-xs"
                                v-text="category.postCount"
                            ></span>
                        </nuxt-link>
                    </li>
                </ul>
                <div class="mt-4 flex flex-wrap">
                    <nuxt-link
                            v-for="tag of tags"
                            :key="tag"
                            :to="`/blog/tags/${tag}`"
                            class="block py-1 px-2 rounded bg-gray-700 hover:bg-our-blue text-white mr-1 mt-1"
                            v-text="tag"
                    ></nuxt-link>
                </div>
            </section>
        </main>
    </div>
</template>

<script>
    import { mapGetters } from 'vuex'
    import FormField from '~/components/FormField'

    export default {
        components: { FormField },

        layout: 'generic',

        computed: {
            ...mapGetters({
                categories: 'blog/categories',
                tags: 'blog/tags',
            })
        },

        methods: {
            handleSearch() {
                // cool stuff here
            }
        }
    }
</script>
```

This approach enabled me to simply use the `generic.vue` layout as a base and then I didn't have to worry about copying over the Header, Footer and PageBanner components. Right now I'm forced to copy over all the contents of `generic.vue` into `blog.vue` which is definitely not following DRY. If I were to need to change something, I'd need to replicate the change in 2 places and that's definitely not neat.

Hopefully you will consider this. I have read around the internet about this problem and people were arguing that "Next.js doesn't have it"... Well, why does that matter? Nuxt.js doesn't have to completely copy everything the Next.js is doing.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9524">#c9524</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-07-21 19:26
duplicate of https://github.com/nuxt/nuxt.js/issues/3099

**Closed by manniL** 2019-07-21 19:26 UTC
Labels: cmty:feature-request
