### ISSUE TITLE
Update meta title with Asyncdata not work on generated

### ISSUE THREAD

**Issue by Ichalle** [nuxt/nuxt.js#8393] opened 2020-11-25 10:20 UTC
### Versions

- nuxt: v2.14.0

### Steps to reproduce
I want to use asyncData in dynamic meta title, it's working in `run dev` but not working when `run generate`.

```
async asyncData ({ route, store }) {
    const { id } = route.params
    try {
        const user_data = await store.dispatch('user/getdata', { id: id})
        return {
            user_data
        }
    } catch (error) {
        console.log(error)
    }
},

head () {
    return {
        title: this.user_data ? this.user_data.Fullname : process.env.PAGE_TITLE,
    }
},
```

### What is Expected?
meta title updated

### What is actually happening?
meta title default

**Comment by pperzyna** [comment] 2020-12-09 00:09
@pi0 Is this nuxt issue or vue-meta? It is kind of crucial because it worked before :sweat_smile:

**Comment by ngochangjelly** [comment] 2021-01-20 15:12
> @pperzyna I can't reproduce this.
> 
> See https://codesandbox.io/s/frosty-sunset-h9d7m

Did you reproduce in generate mode? in codesandbox I guess you run on dev mode, right?. I have this issue when running :

- nuxt generate
- nuxt start

the head function does not work so there is no meta data in page head 😢

**Comment by danielroe** [comment] 2021-01-20 15:14
@ngochangjelly In fact, I set up that CodeSandbox to run `nuxt generate && nuxt start` - and it does not reproduce your issue.

**Comment by danielroe** [comment] 2021-01-20 15:50
@ngochangjelly Thank you for sharing your repo with me (directly).

The issue is that you are defining `head()` within the `methods` part of your Vue instance, whereas it is not within methods but is a separate hook (like `mounted`).

**Comment by ngochangjelly** [comment] 2021-01-20 15:59
@danielpost  Oops, this is truly my mistake, after moving to head independent function, metadata is successfully created!
I can't thank you enough for your quick response sir !!

**Closed** 2021-01-20 16:02 UTC
Labels: bug-report, pending-repro
