### ISSUE TITLE
Is it possible for middleware to be executed only on client side ?

### ISSUE THREAD

**Issue by fbrbovic** [nuxt/nuxt.js#2653] opened 2018-01-21 02:12 UTC
When running an universal app, which means that SSR is active, and using middleware on a layout it seems like middleware always only executes on server side. This is happening on initial page load. 

Is it possible for middleware to be executed on client side as well ? or only on client side ?

Thanks

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2308">#c2308</a>)</em></sub></div>

**Comment by fbrbovic** [comment] 2018-01-28 21:16
Well what I wanted to say is to ensure that it always gets executed on client side.  Right now it seems that if it's executed on server side first it doesn't get called on client side as well. 
It would be great if you can always ensure it gets called on client side as well, or event better control so that it only gets executed on client side. 
Reason for this is that certain libraries will only work on client side so you can't use them in middleware.

**Comment by NicoPennec** [comment] 2018-01-31 02:10
You can create a middleware and check inside if you are on server side or client side.

`middleware/example.js`
```js
export default function () {
  if (!process.server) {
    console.log("middleware from client side");
  }
}
```

**Comment by fbrbovic** [comment] 2018-01-31 03:29
No I know that I can check for it but like I said that does no good if you have a library that only works on client side since it seems like you can't guarantee middleware  to be always executed on client side as well.  
So what I am really looking for is for a setting for middleware to always be called on client side. 

Or maybe we need clientside only middleware ?

**Comment by anoChick** [comment] 2018-02-03 02:30
When you start up in spa mode, middleware will be executed only on the client side.

https://github.com/nuxt/nuxt.js/blob/604dfc95de348efb8d5f939f96ce6b533cc27d98/examples/spa/nuxt.config.js#L6

**Comment by fbrbovic** [comment] 2018-02-03 16:46
@anoChick Tx I'm familiar with that since I need my app to run in SSR mode it would not work for me.

**Comment by weotch** [comment] 2018-02-13 05:58
Ran into this too.  My use case is a middleware that wants to check if the user is authenticated using Firebase.auth().  On first request, the middleware *only* fires once, during SSR.  It needs to also fire fire on the client for the `context.isClient` to trigger the authentication check.

**Comment by lmj0011** [comment] 2018-02-17 05:39
@weotch I have a similar situation where I'm trying to authenticate a user with my backend app on initial page load.

I have my `auth-check` middleware set in the default layout of the nuxt app.

**middleware/auth-check.js**
```js
export default function ({ app, store }) {

  if (!process.server) {
    return app.$axios.$get('/auth-check')
    .then(res => {

      if (res.auth && res.auth.user){
        // set the user, to authenticate the app
        return store.commit('setAuthUser', res.auth.user)
      }
    })
    .catch(err => {
      console.error(err)
    })
  }
}
```

what @NicoPennec proposed doesn't work in this case. It just prevents the middleware from running on the server, and it still doesn't run on the client-side.

**Comment by lmj0011** [comment] 2018-02-24 01:32
https://github.com/nuxt/nuxt.js/blob/dev/lib/app/client.js#L171

ok, it looks like middleware should be applied **globally**, meaning in your `nuxt.config.js` file, if you want it run client-side every time.

I will assume this is true, and report back after I test it out.

refs:
https://nuxtjs.org/guide/routing#middleware

https://github.com/nuxt/example-auth0

**Comment by lmj0011** [comment] 2018-02-24 08:19
https://github.com/nuxt/nuxt.js/issues/2653#issuecomment-368185508

this didn't work for me. I think because I'm using Session Cookies for authentication and not JWT

the [example-auth0] example uses JWT and also takes advantage of LocalStorage to store auth tokens.
[example-auth0]: https://github.com/nuxt/example-auth0

**Comment by o1lab** [comment] 2018-03-19 12:38
Have run into this and I am using vuex-persistedstate to store state in localstorage.

Im building social authorization and on successful authorization the user object is in 'req' which I am unable to access in either middleware or vuex-persistedstate plugin on 'THE CLIENT SIDE'. I have vuex-persistedstate plugin set to ssr:false in nuxt.config.js.

Problem seems to be 'req' object is not accessible on either middleware or plugin on client side!

Commiting from [nuxtServerInit](https://nuxtjs.org/examples/auth-routes#using-express-and-sessions) doesn;t get reflected on localStorage when using vuex-persistedstate.

Any help much appreciated.

**Comment by aldarund** [comment] 2018-05-20 21:57
+1 same situation. I need access to localstorage on one page, so the code must be always executed on clientside.
No one have a solution?

**Comment by clarkdo** [comment] 2018-05-21 08:29
@fbrbovic 
Currently you may combine `client plugin` with `client middleware` to implement this.

For example:

```js
// nuxt.config.js
export default {
  plugins: [
    // ssr: false to only include it on client-side
    { src: '~/plugins/init.js', ssr: false }
  ],
  router: {
    middleware: ['midd']
  }
}

// middleware/midd.js
export default function () {
  if (!process.server) {
    // ...
  }
}
```

But it may not reach your expectation, we can have a discussion with @Atinux @pi0 to figure out if there is a better way.

**Comment by clarkdo** [comment] 2018-05-21 08:30
@fbrbovic 
Currently you may combine `client plugin` with `client middleware` to implement this.

For example:

```js
// nuxt.config.js
export default {
  plugins: [
    // ssr: false to only include it on client-side
    { src: '~/plugins/init.js', ssr: false }
  ],
  router: {
    middleware: ['midd']
  }
}

// middleware/midd.js
export default function () {
  if (!process.server) {
    // ...
  }
}
```

But it may not reach your expectation, we can have a discussion with @Atinux @pi0 to figure out if there is a better way.

**Comment by aldarund** [comment] 2018-06-20 17:35
@clarkdo what about usecase when middleware must be called on client always. With you example on first page load middleware will be executed only on server without client.

**Comment by husayt** [comment] 2018-07-03 14:04
@Atinux @pi0 and @clarkdo I see this question coming a lot recently and wanted to add this to FAQs.  I was wondering if there is a better/approved pattern to suggest users.

**Comment by Atinux** [comment] 2018-07-06 20:16
Using process.client or process.server in middleware is the way. This is a great idea @husayt, if you want to make a PR that would be awesome!

**Comment by aldarund** [comment] 2018-07-06 20:17
@Atinux what about usecase when middleware must be called on client always ?  On first load middleware will be executed only on server so using process.client or process.server wont help.

**Comment by Atinux** [comment] 2018-07-24 10:44
So you need to use a `plugin` if you want to run it on client-side before hydration but it's not recommended since it could change the HTML before hydrating and create a mismatch with the server-rendered version.

**Comment by aldarund** [comment] 2018-07-24 11:04
I dont need before hydration. I just need middleware to be run on client always. E.g. for example to retrieve token from localstorage

**Comment by Atinux** [comment] 2018-07-24 11:06
This is the point, on server-side, you won't know that the user is connected for example. So you will render the navbar as if the user is disconnected.

You need to use the `spa` mode if you want the middleware to run always on client-side. But you will loose server-side rendering.

**Comment by aldarund** [comment] 2018-07-24 11:07
Yes, thats the point. I want middleware to always run on client but i dont want to lose ssr.

**Comment by Atinux** [comment] 2018-07-24 11:11
It's not possible, you will need to create a plugin on client-side only to do so.

**Comment by aldarund** [comment] 2018-07-24 11:15
well, i know its not possible rn. But the point is that would be good if it will be possible, there clearly cases for for such behaviour as seen in this topic

**Comment by johnyluyte** [comment] 2018-08-21 05:11
Run into the same problem today. I was doing something like this:


    [middleware/myMiddleware.js]
    export default function(context) {
       // do something that should be done at Client side, not Server Side.
    }

    [layout/myLayout.vue]
    middleware: "myMiddleware",

    [page/pageA.vue]
    layout: "myLayout",

    [page/pageB.vue]
    layout: "myLayout",


And just like the above discussion, this does not work. 

But after thinking again, I realize that I probably don't need `Middleware` at all. Here's how I solve my problem with `Mixin`: 

    [mixins/myMixin.js]
    export default {
        mounted(){
            // do something that should be done at Client side, not Server Side.
        }
    }
    
    [layout/myLayout.vue]
    import myMixin from "@/mixins/myMixin.js";
    mixins: [myMixin],
    
    [page/pageA.vue]
    layout: "myLayout",
    
    [page/pageB.vue]
    layout: "myLayout",

The mounted() is only executed at Client side, good for me.

The problem is that the user will feel the delay if there are async code inside mounted(). But I actually don't care in this case haha. 

Hope this helps

**Comment by galvez** [comment] 2018-08-26 21:55
Closing this as all possible solutions have been discussed.

**Closed by galvez** 2018-08-26 21:55 UTC
Labels: cmty:feature-request
