### ISSUE TITLE
Error in layouts with middleware

### ISSUE THREAD

**Issue by cawa-93** [nuxt/nuxt.js#763] opened 2017-05-23 07:45 UTC
I'm using a layout that relies on the state of the vuex:
```vue
<template>
  <div>
    <p>{{user.name}}</p>
    <nuxt/>
  </div>
</template>

<script>
import { mapState } from 'vuex'
export default {
  middleware: ['auth'],
  computed: {
    ...mapState({
      user: state => state.currentUser, // or null in user not authenticated
    }),
  },
}
</script>
```
Middleware `auth` check `state.currentUser` and redirect to login page if it's `null`
```js
export default function ({ store, redirect }) {
  console.log('\nCheck user data ...\n')
  if (!store.state.currentUser) {
    return redirect('/login')
  }
}
```
So, now, if I'm not authorized and trying to load a page with this template, I get an error in the server console:
```
Check user data ...

[Vue warn]: Error in render function: 
(found in <Sidebar> at /run/media/alex/LinWin/Develop/fb-scaner/resources/layouts/sidebar.vue)
TypeError: Cannot read property 'name' of null
    at Proxy.render (resources/layouts/sidebar.vue?7fdc:2:0)
    at VueComponent.Vue._render (/run/media/alex/LinWin/Develop/fb-scaner/node_modules/vue/dist/vue.runtime.common.js:3605:22)
    at renderComponent (/run/media/alex/LinWin/Develop/fb-scaner/node_modules/vue-server-renderer/build.js:6698:25)
    at RenderContext.renderNode (/run/media/alex/LinWin/Develop/fb-scaner/node_modules/vue-server-renderer/build.js:6681:7)
    at RenderContext.next (/run/media/alex/LinWin/Develop/fb-scaner/node_modules/vue-server-renderer/build.js:169:14)
    at RenderContext.next (/run/media/alex/LinWin/Develop/fb-scaner/node_modules/vue-server-renderer/build.js:178:12)
    at cachedWrite (/run/media/alex/LinWin/Develop/fb-scaner/node_modules/vue-server-renderer/build.js:30:9)
    at renderElement (/run/media/alex/LinWin/Develop/fb-scaner/node_modules/vue-server-renderer/build.js:6732:5)
    at renderNode (/run/media/alex/LinWin/Develop/fb-scaner/node_modules/vue-server-renderer/build.js:6685:7)
    at renderComponent (/run/media/alex/LinWin/Develop/fb-scaner/node_modules/vue-server-renderer/build.js:6704:3)
```
The code of the page itself is very simple.
```vue
<template>
  <pre>
    Home page
  </pre>
</template>

<script>
  export default {
    layout: 'sidebar',
  }
</script>
```

**Comment by ruslankonev** [comment] 2017-05-23 08:51
Yes, this or the same error will reproduce with use store state as function.
All components on which use a state as a function will be broken and I don't know how to fix that. Maybe guys know how to fix that?

![image](https://cloud.githubusercontent.com/assets/2588730/26346190/18ed5ea6-3fae-11e7-9041-9e4d8ff49ead.png)

**Comment by KonstantinVlasov** [comment] 2017-05-23 09:04
Hi, @cawa-93!

I think nuxt render layouts despite any middlewares. In my project, I just add v-if for components that used in layouts.

**Comment by cawa-93** [comment] 2017-05-23 09:17
@KonstantinVlasov However, in the console I see a message about the execution of the Middleware. And after the error, there is a redirect. But I do not understand why an error occurs, if redirection is to be performed prior to rendering.

**Comment by KonstantinVlasov** [comment] 2017-05-23 09:34
As I understand its prior to page rendering, but not layout rendering. Looks like it is intended. But maybe not :)

**Comment by dohomi** [comment] 2017-06-04 14:01
@cawa-93 are you using 2 different layouts, one for logged-in and one for logged-out users?

**Comment by Atinux** [comment] 2017-06-04 18:02
@cawa-93 This commit fix the issue: https://github.com/nuxt/nuxt.js/commit/ce69c3be0f544afa9b36b23b9e106631c9c51f70

It will be in the next release (alpha4).

**Comment by cawa-93** [comment] 2017-07-10 13:54
@Atinux Yes In alpha4, no problem was observed. Today, I used alpha5 and the problem returned again.

**Comment by Atinux** [comment] 2017-08-01 09:01
Closing it since `rc3` is out

**Closed by Atinux** 2017-08-01 09:01 UTC
Labels: available soon, bug

**Comment by Atinux** [comment] 2017-11-02 10:34
![](https://github.trello.services/images/mini-trello-icon.png) [Test layouts middleware](https://trello.com/c/kkmNu32f/14-test-layouts-middleware)
