### ISSUE TITLE
css flash problem

### ISSUE THREAD

**Issue by ummo** [nuxt/nuxt.js#1652] opened 2017-09-14 03:19 UTC
I updated nuxt to the lastest version and found a new problem, my page flash for one second after page refresh, it seems like css is not loaded before page render, but css is already existed before html tags.
![screen](https://user-images.githubusercontent.com/4112019/30410406-6e717d60-993d-11e7-9357-0e3cb61aa15d.gif)

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1477">#c1477</a>)</em></sub></div>

**Comment by moldray** [comment] 2017-09-14 03:32
I have the same problem in rc11

**Comment by NicoPennec** [comment] 2017-09-14 05:38
@ummo @moldray 

It's due to Webpack HMR (in dev mode only) 

Read the FAQ 😉  https://nuxtjs.org/faq/css-flash

**Comment by ummo** [comment] 2017-09-14 06:11
@NicoPennec
There is no HMR, I use express server and nuxt as middleware, css flash does exist.
Try your nuxt-express demo.

**Comment by moldray** [comment] 2017-09-14 06:12
@NicoPennec 

I know the case you refered. but the problem i met is something different. my app runs well yesterday. when i upgrade nuxt to rc11 the problem come out.

of course， i modified some code, but i am uncertain what cause this. what i found until now is that the js loaded different from before.

right case：

![image](https://user-images.githubusercontent.com/6896887/30414455-51ef81f0-9956-11e7-88a2-442f6e6d5252.png)

error case：
![image](https://user-images.githubusercontent.com/6896887/30414472-62e1ac40-9956-11e7-8e81-2f1b1991f611.png)

in the end, forgive my poor english

thank you!

**Comment by moldray** [comment] 2017-09-14 06:19
i rollback nuxt, but it is not work. i guess it is relevant to "prefetch" or "preload".

**Comment by moldray** [comment] 2017-09-14 08:23
![image](https://user-images.githubusercontent.com/6896887/30419355-a13a7b68-9968-11e7-870e-0f09fe06366a.png)

I talked with @ummo and found that nuxt depended webpack  has upgrade. may this be useful.

PS: I use nuxt as middleware of koa2

**Comment by vadimsg** [comment] 2017-09-14 08:46
We use express with nuxt and now we have also a flashing style problem in dev and in prod.

**Comment by bimohxh** [comment] 2017-09-14 09:09
nuxt page  flash is always exist, I not resolve this untill now

**Comment by wargt** [comment] 2017-09-14 12:52
i have css flash problem in prod mode. I use 1.0.0-rc11  and express middleware 
[link](https://github.com/nuxt/nuxt.js/blob/dev/examples/custom-server/server.js)

pls help

**Comment by f15gdsy** [comment] 2017-09-14 16:04
Have the same issue here.
I'm using Nuxt starter template and Nuxt rc-11, and in production mode, but the CSS flash exists even when extractCSS set to true.

I had other projects running on older version of Nuxt: alpha.3 and alpha.4 and rc-9, and they works great in production and dev mode.

**Comment by f15gdsy** [comment] 2017-09-15 02:08
Rolling back to rc 9 fixed the problem.

**Comment by christophwolff** [comment] 2017-09-15 21:17
i have the same issue. Please solve. Thank you!

**Comment by christophwolff** [comment] 2017-09-16 08:57
I rolled back to rc9. CSS Flash still happens.

**Comment by bimohxh** [comment] 2017-09-16 12:14
It‘s not the nuxt version, every version has this problem

**Comment by christophwolff** [comment] 2017-09-16 12:26
@bimohxh i fixed it by creating a new stater project with vue-cli and copying all my files over. Now it works.

**Comment by ummo** [comment] 2017-09-18 02:35
@NicoPennec 
I get stuck because this issue, do you have any plan to fix it?

**Comment by christophwolff** [comment] 2017-09-18 06:49
@ummo create a new project bring all your files and config over. Should work then. I have no idea why. Should be fixed, yes.

**Comment by homerjam** [comment] 2017-09-19 09:35
Rolling back to rc9 worked for me. I looked back through the commits since then and couldn't spot anything obvious though, planning to look further into it when I can.

**Comment by matthew-dean** [comment] 2017-09-20 18:01
@NicoPennec This isn't because of HMR. This also happens when running `nuxt generate`. The link / style tags or whatever one would expect to prevent this are not generated in `<head/>`.

**Comment by matthew-dean** [comment] 2017-09-20 18:13
Based on the suggestion, I rolled back to RC9 and ran `nuxt generate` again. This time, inline style blocks were injected into all my generated HTML pages. So definitely a major bug was introduced before RC9 and RC11. Please fix this!

**Comment by valeriosillari** [comment] 2017-09-25 21:27
i am newbie to nuxt.js but i also facing this problem.
checking on vue.js official documentation and find v-cloak option:
https://vuejs.org/v2/api/#v-cloak

nobody is talking about it, it could be useful or I am just probably checking on the wrong direction?

**Comment by rlam3** [comment] 2017-09-25 21:38
Has anybody found out what the problem is? I'm getting this annoying error of refreshing and loading the page where the css is not appearing... Thanks! 

Something really doesn't seem right... I tried rc8 rc9 and they don't work either. Along with rc11.

After going to changing to another page, and refreshing, the css is gone. The only page that is consistent with the css is that of the index.vue. 

https://nuxtjs.org/faq/css-flash <<< not sure if this is right...

**Comment by mnishihan** [comment] 2017-10-03 23:46
Looks like it's not an issue of nuxt.js itself. Instead, in my finding, it is an issue with vue-server-renderer@2.4.3 which has been fixed in vue-server-renderer@2.4.4

So, if you have 2.4.3 version of vue-server-renderer installed as a dependency of nuxt@1.0.0-rc11, when you upgraded nuxt, you might experience this FOUC issue, as I did also. In my case, I've fixed this issue in my existing workspace, by executing following commands:
```
yarn remove nuxt
yarn add nuxt
```
If you are using `npm` for package installation, instead of  `yarn`, the above commands would be:
```
npm remove nuxt
npm install nuxt
```

**Comment by gwildu** [comment] 2017-10-04 05:08
In my case what solved the issue is to specify the nuxt version in package.json explicitly to rc11 like: `"nuxt": "1.0.0-rc11",` that forced yarn / npm to install the correct version and the correct dependencies. with `"nuxt": "`^1.0.0-rc11",` i got rc9 installed  with vue 2.4.4 and vue-server-renderer 2.4.3.
Both node and yarn do not take care about the increase in the pre-release part of the version so I would say the proper way to version a pre-1 version would be to use 0.x.x which is actually also the recommendation of semver. A pre-release version in my opinion should never end up as result of a generator as it might lead to this inconsitent behavior. As soon as version 1 is released, the prerease versioning can be used again as there is already a stable major version around to use in the generator like "^1.x.x".
So I would say it is a nuxt issue.

**Comment by mnishihan** [comment] 2017-10-04 11:28
@gwildu in broader sense, yes it's nuxt versioning issue and I fully agree with what you said.

But anyway, I was just saying that, the sudden FOUC after nuxt upgrade is actually not caused due to changes in nuxt code. Instead, it was nuxt dependencies, that causes functionally to break in nuxt, as nuxt is essentially a wrapper over other libraries. 

IMHO, what nuxt developers can/should do is define explicit versions of dependencies in nuxt's package.json (that they're developing & testing with), instead of allowing a range of even minor or patch versions to be different in different installations. That way, lots of dependency related issues like issues will disappear.

**Comment by rlam3** [comment] 2017-10-04 20:48
@mnishihan Maybe we could start like a markdown table of which packages break or work with which versions? But this would require a lot of testing.

**Comment by gwildu** [comment] 2017-10-04 21:07
@mnishihan I agree, if, e.g., vue-server-renderer and vue needs to have the exact same version to be able to work together I think explicit versions is the only way to avoid such issues. Not all dependencies have that restrictions, usually such cross-module dependencies should be avoided, but if there are some of them, they should be handled explicitly. It might be a bit of manual work to do when updating to a new version but it probably will save time in answering such issues like this one.

**Comment by Atinux** [comment] 2017-11-02 10:59
![](https://github.trello.services/images/mini-trello-icon.png) [#1652](https://trello.com/c/2OFGAYtt/31-1652)

**Comment by DaftMonk** [comment] 2017-11-07 19:24
I was experiencing this issue because we are using a custom `app.html` file, and we were missing  {{ HEAD }} from our template.

**Comment by 1hakr** [comment] 2018-06-23 17:54
I believe this issue still exist when ```extractCSS``` is enabled and all css is extracted along with critical css in separate files. extractCSS is not working as intended. Can anyone else confirm this?

**Comment by itsmichaeldiego** [comment] 2018-06-26 07:02
I am having the same issue while using [vue-styled-components](https://github.com/styled-components/vue-styled-components) together with Nuxt.js. 

I've an image that is originally _960x960px_, when rendered in my website I want to re-size it to _245x245px_, but instead of being 245px at the beginning, the un-styled image flashes first.

Live example here: https://itsmichaeldiego.github.io/website/

My component looks like:

```
<template>
  <Wrapper src="mike_alfa.png" />
</template>

<script>
  import styled from 'vue-styled-components';

  const Wrapper = styled.img`
    margin: 15px;
    width: 245px;
    height: 245px;
  `;

  export default {
    components: {
      Wrapper
    }
  };
</script>
```

Here is a quick gif reproducing the issue:

![screen recording 2018-06-26 at 09 57 am](https://user-images.githubusercontent.com/6419886/41894484-b0c6d064-7927-11e8-9819-04bced0bdc0f.gif)

**Comment by galvez** [comment] 2018-08-26 23:26
Closing this as there's been no updates over 90 days.

**Closed by galvez** 2018-08-26 23:26 UTC
Labels: type: bug
