### ISSUE TITLE
nuxtServerInit triggers twice 

### ISSUE THREAD

**Issue by cayaner** [nuxt/nuxt.js#1863] opened 2017-10-15 13:06 UTC
```js
nuxtServerInit({ dispatch, commit  }, { req, isServer }) {
    if (req.session && req.session.access_token) {
      if (isServer) {
        return dispatch('user', req.session.access_token)
    } else {
      delete req.session.access_token
      return commit('destroy')
    }
  }
}
```
this is triggering the user action twice ... 

note: the user action is returning a promise.

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1674">#c1674</a>)</em></sub></div>

**Comment by Atinux** [comment] 2017-10-16 12:27
Hi @cayaner 

It's not possible that `nuxtServerInit` is called twice on server-side.

Please check your code, or create a small repository to reproduce this issue, then re-open this issue.

**Comment by eseceve** [comment] 2018-09-25 00:00
You can reproduce this issue using https://github.com/nuxt/hackernews and update it to nuxt 2 doesn't solve it

##### git diff
```
diff --git a/store/index.js b/store/index.js
index 374fe3d..44f0d3c 100644
--- a/store/index.js
+++ b/store/index.js
@@ -73,6 +73,9 @@ export default {
         () => this.$axios.$get(`/api/user/${id}.json`),
         Object.assign({ id, loading: true }, state.users[id])
       )
+    },
+    nuxtServerInit() {
+      console.log('nuxtServerInit')
     }
   },
   // =================================================
(END)
```

**Comment by aldarund** [comment] 2018-09-25 00:36
@eseceve is it happening in dev mode or in production build?

**Comment by eseceve** [comment] 2018-09-25 04:01
@aldarund both

**Comment by hdriqi** [comment] 2018-09-26 15:58
yes i can confirm it, my nuxt app is also calling nuxtServerInit twice

**Comment by solonik1** [comment] 2018-10-06 19:56
Same issue here. Please reopen

**Comment by aldarund** [comment] 2018-10-06 20:07
@solonik1 could be caused by this -> https://github.com/nuxt/nuxt.js/issues/4016

**Comment by solonik1** [comment] 2018-10-06 20:28
@aldarund thank you:)

**Comment by xpuu** [comment] 2018-10-25 18:59
as it states in this [comment](https://github.com/nuxt/nuxt.js/issues/4087#issuecomment-428971143) it only happens when developers tools are opened

**Comment by AndrewBogdanovTSS** [comment] 2018-10-26 09:47
Why this issue is marked as closed? It's still reproducible with Nuxt 2.2.0 when the console is opened.  Please, reopen. Console should not affect Nuxt internal behavior.

**Comment by ben-richardson-moneysmart** [comment] 2018-11-10 08:03
I had this issue where my NuxtServerInit was being called twice when I was loading up a page. The first call had the correct query params I was trying to load, the second call did not. When I had the dev tools open I had 3 calls. 1 with the query params of the page I was opening, 2 without.

After viewing more of the `context` too see what was going on. I realised the additional call was for an image, but my image was 404'ing so Nuxt was returning the 404 page on that request, which explains why I was getting a second request going through the NuxtServerInit call. My 404 image was returning the full 404 page.

I think it might be a similar situation when the dev tools is open. Chrome may be making a secondary server call to get the source of the page, or other things regarding the Network tab. If this is the case, Nuxt would be functioning exactly as normal.

**Comment by P4sca1** [comment] 2018-11-10 08:43
I also noticed having dev tools open is causing about 20-30 request. Ist loads things from the node_modules and _nuxt folder. I am wondering whether these requests for static ressources really require to call nuxtServerInit?

**Closed** 2018-11-14 19:32 UTC
Labels: cmty:bug-report
