### ISSUE TITLE
how to add meta in routers?

### ISSUE THREAD

**Issue by EasonShen1989** [nuxt/nuxt.js#1964] opened 2017-10-27 07:08 UTC

**Comment by clarkdo** [comment] 2017-10-27 08:17
Any detailed information? Routers in Nuxt.js should be generated dynamically and implicitly, where do you need to add meta ?

**Comment by EasonShen1989** [comment] 2017-10-27 08:41
set crumbs，for example
 {
            path: '/...',
            component: ...,
            meta: {
                crumbs: [{
                    name: '...',
                }]
            }
} @clarkdo

**Comment by clarkdo** [comment] 2017-10-27 08:54
Every component in `pages` is route, you can define meta inside the component.
```js
  head () {
    return {
      title: this.title,
      meta: [
        { hid: 'description', name: 'description', content: 'My custom description' }
      ]
    }
  }
```
Refer [Pages Head](https://nuxtjs.org/api/pages-head)

**Comment by zhouyu1993** [comment] 2017-10-27 09:01
vue-meta

**Comment by Atinux** [comment] 2017-10-28 13:47
Duplicate of https://github.com/nuxt/nuxt.js/issues/1687#issuecomment-331870619

**Closed by Atinux** 2017-10-28 13:47 UTC

**Comment by iamdubx** [comment] 2017-11-10 00:25
Dynamic meta tags doesn't work properly in Nuxt. This is huge issue.
