### ISSUE TITLE
"HTMLElement is not defined" on start of a new project (fresh install)

### ISSUE THREAD

**Issue by wsw70** [nuxt/nuxt.js#5768] opened 2019-05-20 07:54 UTC
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[http://localhost:3000/](http://localhost:3000/)

### Steps to reproduce

Current version of Nuxt (2.7.1) on Windows 10. 

```
npx create-nuxt-app test1
cd test1
npm run dev
```

The application is built (with one error: ` ERROR  (node:22396) DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead` but I do not think it is relevant)

Opening a browser on `http://localhost:3000`

### What is expected ?

A demo page

### What is actually happening?

An error page with `ReferenceError: HTMLElement is not defined`.

Error is apparently in `node_modules/element-ui/lib/element-ui.common.jsopen` on line 36822 (the one defining `scrollContainer`:

```
props: {
    src: String,
    fit: String,
    lazy: Boolean,
    scrollContainer: [String, HTMLElement],
    alt: String
  },

  data: function data() {
    return {
``` 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9241">#c9241</a>)</em></sub></div>

**Comment by clarkdo** [comment] 2019-05-20 11:36
Duplicate of #5622

https://github.com/nuxt/nuxt.js/issues/5622#issuecomment-492213789

**Closed by clarkdo** 2019-05-20 11:36 UTC
Labels: cmty:bug-report
