### ISSUE TITLE
I have to reset server when create new pages

### ISSUE THREAD

**Issue by njtnestor** [nuxt/nuxt.js#6450] opened 2019-09-22 18:35 UTC
### Version

[v2.9.2](https://github.com/nuxt.js/releases/tag/v2.9.2)

### Reproduction link

[https://codepen.io](https://codepen.io)

### Steps to reproduce

1. Create a new universal nuxt proyect.
2. Add new page called for example: "new.vue"
3. Check .nuxt/router.js and server console

### What is expected ?

Server console should compile and .nuxt/router.js should contains the new route for the "new.vue" page.

### What is actually happening?

Console server doesn't show new changes(no compile) therefore .nuxt/router.js doesn't contain the new route for "new.vue" page.
I need reset the nuxt server for get the new route.

### Additional comments?

SO: Windows 10

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9806">#c9806</a>)</em></sub></div>

**Comment by kazulu** [comment] 2019-09-22 19:05
Same problem using Windows 10 Pro and Node JS 10.16.3

**Comment by tonyDevCro** [comment] 2019-09-23 20:15
Same here. Windows and Ubuntu (Ubuntu show route in router.js, but won't output page). And ofc, this is my first project with Nuxt.js

**Comment by pimlie** [comment] 2019-09-25 07:17
Can confirm the behaviour on Linux, have looked into this already with regards to the following pr but havent been able to put my finger on it yet: https://github.com/nuxt/nuxt.js/pull/6448

/cc @clarkdo

**Comment by alxy** [comment] 2019-09-25 20:58
I can also conform this bug on Windows 10, NPM 6.9.0, node 10.16.0

**Comment by Nefiron** [comment] 2019-09-27 14:10
Confirmed on newly scaffolded Nuxt 2.9.2

Windows 10
Node 10.16.0
NPM 6.9.0

**Comment by pimlie** [comment] 2019-09-27 14:42
With the latest nuxt-edge I cannot reproduce this anymore. It seems that webpack's [pause/resume](https://github.com/webpack/webpack/pull/9214) was the culprit somehow (fyi @pi0 )

**Comment by pi0** [comment] 2019-09-27 17:26
So at least giod news it is not being used anymore for next release :)

**Comment by Maadtin** [comment] 2019-09-28 20:29
hello, is there any fix for this? happening to me right now. node 10.15.1 npm 6.11.3 created with the project with npx create-nuxt-app

**Comment by Nefiron** [comment] 2019-09-28 20:34
If you install nuxt-edge and use that in Development until 2.10.0 gets
released, you should be fine. :)

lør. d. 28. sep. 2019 22.29 skrev Martin <notifications@github.com>:

**Comment by Maadtin** [comment] 2019-09-28 20:36
don't know what nuxt edge is

**Comment by manniL** [comment] 2019-09-29 09:31
@Maadtin `yarn remove nuxt && yarn add nuxt-edge`. It's the nightly build of nuxt.

**Comment by pimlie** [comment] 2019-10-02 14:26
Closing this issue as `v2.10` has been released, please create a new issue if you still experience issues

**Closed by pimlie** 2019-10-02 14:26 UTC
Labels: bug, cmty:bug-report
