### ISSUE TITLE
App freezes while using nuxt-link and nested routes with redirect

### ISSUE THREAD

**Issue by bazitur** [nuxt/nuxt.js#2896] opened 2018-02-25 12:12 UTC
Hello,
Been writing an app and found a bug: [here is an example](https://github.com/bazitur/nuxtjs-bug).
Clicking on any of the links at the index freezes app.
Any help would be appreciated.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2517">#c2517</a>)</em></sub></div>

**Comment by laSinteZ** [comment] 2018-02-25 18:27
@bazitur 
I guess the problem is in file `_id.vue` and folder `_id`: router doesn't know where to go and freezes (it is my interpretation and I guess it could be not accurate).

I've tried moving `_id.vue` into folder `_id` and renaming it into `index.vue` and the links work now. But you'll never get to `index.vue` anyway because there is redirect in this page, which sends you to `/_id/info`

**Comment by galvez** [comment] 2018-08-18 09:58
This question has been answered by @laSinteZ -- closing now.

**Closed by galvez** 2018-08-18 09:58 UTC
