### ISSUE TITLE
Seamless and Almost Invisible App Update

### ISSUE THREAD

**Issue by c5n8** [nuxt/nuxt.js#8407] opened 2020-11-28 17:46 UTC
### Is your feature request related to a problem? Please describe.

Web app with only server side rendering has an advantage to update itself in real time, meaning that users always have the latest version of it, after every action, like opening pages and submitting form. This has been possible since the dawn of the web. One problem that web app with client side rendering is that sometimes users will use stale version, until they reload the page.

### Describe the solution you'd like

Inspired by [this talk](https://www.youtube.com/watch?v=Hzxy6ml-FYE&feature=youtu.be&t=659), I would like to reduce time of users using stale version by reloading the page when there is an opportunity to do so, like after users did something that would make significant layout change. This would make updating more seamless and almost invisible to users.

The implementation may come in two flavors:
1. An optional property of `NuxtLink` similar to `replace` property, which makes clicking the link will reload the page first before proceeding to destination link.
2. A hook/composition function that returns a function in some way, maybe standalone or wrapped in an object or wrapped in an array, and expects a destination link as parameter. This function will reload the page when and open destination link. This will be useful in actions like submitting a form.

### Describe alternatives you've considered

Another alternative would be an update notification in the form of popup. But this will interrupt user experience and require users' attention. Imagine a user got update notification while filling a long form, this will distract users from their goal. Compared to updating the app after submitting said form.

### Additional context

- Require a mechanism of pushing update notification from the developer to the app in the background.
I imagine every build has version, for example a timestamp. After app succesfully deployed to hosting or server, it will send a request to a webhook with that build timestamp, and the webhook will push the timestamp to clients. When client receives this timestamp, it will compare it with its own build timestamp, if its timestamp is behind, then it will mark itself as stale and save it in a local persisted state. If either flavor of implementations above met, it will check that stale mark, then reload or not reload depending on that stale mark.
- Ideally must be accompanied with the ability to restore app state after full reload, I suppose this will provide a set of significant challenges.

**Comment by danielroe** [comment] 2020-11-28 18:24
I think this is probably a duplicate of #8368 - please feel free to add comments to that issue so we collect them in a single place :slightly_smiling_face:

**Closed by danielroe** 2020-11-28 18:24 UTC
Labels: feature-request
