### ISSUE TITLE
The generated html , lunched on nginx server, can not works when url contains ```.html```

### ISSUE THREAD

**Issue by wikieswan** [nuxt/nuxt.js#5077] opened 2019-02-20 15:57 UTC
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://github.com/nuxt/nuxt.js/issues/5076](https://github.com/nuxt/nuxt.js/issues/5076)

### Steps to reproduce

My project dir like this:

    nuxt-demo/
        ****
        pages/
            home.vue
        ***

I build and generate html with commond

    npm run build && npm run generate

Then I will get static html in ```./dist/home/index.html``` dir

Now, I put all file in ```./dist``` in to a nginx server path; and type url in browser;

If the url is ```localhost/home/```, erveything goes right;

But if the url is ```localhost/home/index.html```, i can get html and other static assets , but the code I write in ```home.vue``` will never run.

### What is expected ?

if url is ```localhost/home/index.html```, page will work fine

### What is actually happening?

if the url is ```localhost/home/index.html```,  the code I write in ```home.vue``` will never run.

### Additional comments?

I am confused if this is the vue-router not math ```localhost/home/index.html```.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8698">#c8698</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-02-20 16:09
Duplicate of https://github.com/nuxt/nuxt.js/issues/4540

Could you give us a reproduction?

**Closed** 2019-03-04 08:16 UTC
Labels: cmty:bug-report, status: need repro
