### ISSUE TITLE
Plugin is not found , windows, glob 7.2.2

### ISSUE THREAD

**Issue by inu1255** [nuxt/nuxt.js#10440] opened 2022-05-14 07:01 UTC
### Versions

- nuxt: 2.15.8
- node:  12.21

### Steps to reproduce

create a new nuxt project, the dependency: glob will upgrade to [7.2.2 ](https://github.com/isaacs/node-glob/issues/468)
``` bash
npm start
```
error at `node_modules\@nuxt\builder\dist\builder.js:741:10`
`Plugin is not found` 

### What is Expected?

start nuxt

### What is actually happening?

cannot start nuxt

**Comment by MeAndRhythm** [comment] 2022-05-14 07:55
刚刚也发现了这个bug

**Comment by Gumbraise** [comment] 2022-05-14 12:01
Same here. Please help ! I have customers who want their project monday

**Comment by SzymonLisowiec** [comment] 2022-05-14 13:12
The error is caused by a new version of `glob` used by `@nuxt/builder`. Use `npm i --save glob@7.2.0` to fix it for the moment.

**Comment by halwesit** [comment] 2022-05-14 13:44
@SzymonLisowiec Thank you so much. saved my day. <3

**Comment by akr4m** [comment] 2022-05-14 13:50
It's because of glob.
Unsupported version 8 is released.

So install older one
```ssh
npm i --save glob@7.2.2
```

**Comment by jsuddsjr** [comment] 2022-05-15 01:16
glob@7.2.2 is the problem. You need glob@7.2.0

**Comment by zihaopang** [comment] 2022-05-15 02:18
> npm i --save glob@7

> 找了半天，终于找到了解决办法，泪目

**Comment by sigma207** [comment] 2022-05-15 06:48
Temporary solution:
Add  glob 7.2.0 resolution in your package.json and install it.
```json
"resolutions": {
  "glob": "7.2.0"
}
```

**Comment by isaacs** [comment] 2022-05-15 18:36
Should be fixed by glob@7.2.3.  If it isn't, please post a new issue at https://github.com/isaacs/node-glob/issues, ideally with a reproduction case.  Thanks!

**Closed** 2022-05-15 20:50 UTC
Labels: bug-report

**Comment by Ifure** [comment] 2022-07-02 09:04
I've installed glob@7.2.0 but still not working

**Comment by danielroe** [comment] 2022-07-04 22:45
@Ifure Please see https://github.com/nuxt/nuxt.js/issues/10440#issuecomment-1126993346.

**Comment by LordRawl** [comment] 2023-03-22 10:18
In my case, renaming the project folder helped. It was `C:\User\-----\[test-nuxt]\`. After renaming it, it became `C:\User\-----\test-nuxt\`

**Comment by chihiro7793** [comment] 2023-09-10 18:35
I'm facing the same problem. and adding globe didn't help. Do you have any suggestion why?

Nuxt 2.15.8, Node 14.7.3, Windows 11

![image](https://github.com/nuxt/nuxt/assets/69468978/c4e20321-bb85-41eb-946d-ed06153a2505)

**Comment by zillahmwimali** [comment] 2023-09-25 12:27
Solved the problem by running "npm i --legacy-peer-deps"

**Comment by floydfdes** [comment] 2023-11-11 05:40
> In my case, renaming the project folder helped. It was `C:\User\-----\[test-nuxt]\`. After renaming it, it became `C:\User\-----\test-nuxt\`

Interesting , this helped me after strugling for more than a  day. I had recently seen a youtube video about having these type of folder naming convention ( [00] Apps in my case) and my co developer had warned me these could cause issues in some projects
