### ISSUE TITLE
nuxt errors on a new project (depreciation, mix bigint, and chokidar)

### ISSUE THREAD

**Issue by JasonCubic** [nuxt/nuxt.js#6035] opened 2019-07-06 04:20 UTC
When I create a new nuxt project on windows 10 I see some errors but the project seems to work.    I ran chkdsk on my computer, upgraded node to v10.16, rebooted, etc,

What is going on? What are the errors at the bottom?

Here is what I did to recreate the error:

`
C:\node_sandbox
λ npx create-nuxt-app nuxt-error-test
npx: installed 379 in 24.104s
create-nuxt-app v2.8.0
✨  Generating Nuxt.js project in C:\node_sandbox\nuxt-error-test
? Project name nuxt-error-test
? Project description My stupendous Nuxt.js project
? Author name Jason
? Choose the package manager Npm
? Choose UI framework None
? Choose custom server framework Express
? Choose Nuxt.js modules (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Choose linting tools (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Choose test framework None
? Choose rendering mode Universal (SSR)

�  Successfully created project nuxt-error-test

  To get started:

        cd nuxt-error-test
        npm run dev

  To build & start for production:

        cd nuxt-error-test
        npm run build
        npm run start

C:\node_sandbox
λ cd nuxt-error-test\

C:\node_sandbox\nuxt-error-test (master -> origin)
λ npm run dev

> nuxt-error-test@1.0.0 dev C:\node_sandbox\nuxt-error-test
> cross-env NODE_ENV=development nodemon server/index.js --watch server

[nodemon] 1.19.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: C:\node_sandbox\nuxt-error-test\server/**/*
[nodemon] starting `node server/index.js`
i Preparing project for development                                                                                                                                                   21:14:44
i Initial build may take a while                                                                                                                                                      21:14:44
√ Builder initialized                                                                                                                                                                 21:14:44
√ Nuxt files generated                                                                                                                                                                21:14:44

√ Client
  Compiled successfully in 5.43s

√ Server
  Compiled successfully in 4.85s

i Waiting for file changes                                                                                                                                                            21:14:52

 READY  Server listening on http://localhost:3000                                                                                                                                     21:14:52

(node:5912) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (C:\node_sandbox\nuxt-error-test\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (C:\node_sandbox\nuxt-error-test\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (C:\node_sandbox\nuxt-error-test\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (C:\node_sandbox\nuxt-error-test\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (C:\node_sandbox\nuxt-error-test\node_modules\readdirp\index.js:163:23)
(node:5912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5912) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5912) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (C:\node_sandbox\nuxt-error-test\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (C:\node_sandbox\nuxt-error-test\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (C:\node_sandbox\nuxt-error-test\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (C:\node_sandbox\nuxt-error-test\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (C:\node_sandbox\nuxt-error-test\node_modules\readdirp\index.js:163:23)
(node:5912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5912) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (C:\node_sandbox\nuxt-error-test\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (C:\node_sandbox\nuxt-error-test\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (C:\node_sandbox\nuxt-error-test\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (C:\node_sandbox\nuxt-error-test\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (C:\node_sandbox\nuxt-error-test\node_modules\readdirp\index.js:163:23)
(node:5912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:5912) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions
    at FSWatcher._hasReadPermissions (C:\node_sandbox\nuxt-error-test\node_modules\chokidar\index.js:775:36)
    at WatchHelper.filterPath (C:\node_sandbox\nuxt-error-test\node_modules\chokidar\index.js:191:16)
    at ReaddirpStream.fileFilter [as _fileFilter] (C:\node_sandbox\nuxt-error-test\node_modules\chokidar\lib\nodefs-handler.js:405:29)
    at ReaddirpStream._isFileAndMatchesFilter (C:\node_sandbox\nuxt-error-test\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (C:\node_sandbox\nuxt-error-test\node_modules\readdirp\index.js:163:23)
(node:5912) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

`

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9457">#c9457</a>)</em></sub></div>

**Comment by toonimoadi** [comment] 2019-07-06 11:35
I can reproduce on 
OS: Windows 10.
Node: 10.16.0
using NPM 

Any project I scaffold throw the same exception (same as the OPs)

**Comment by VoltaVX** [comment] 2019-07-06 17:02
Same thing is happening on my current project after upgrading nuxt to version 2.8.1

OS: Windows 10 Pro for Workstations
Node: v12.3.1
Using: Yarn

Here's the exact error I get: 
 ERROR  Cannot mix BigInt and other types, use explicit conversions                                                12:58:19

  at FSWatcher._hasReadPermissions (node_modules\@nuxt\builder\node_modules\chokidar\index.js:775:36)
  at WatchHelper.filterPath (node_modules\@nuxt\builder\node_modules\chokidar\index.js:191:16)
  at ReaddirpStream.fileFilter [as _fileFilter] (node_modules\@nuxt\builder\node_modules\chokidar\lib\nodefs-handler.js:405:29)
  at ReaddirpStream._isFileAndMatchesFilter (node_modules\@nuxt\builder\node_modules\readdirp\index.js:234:31)
  at ReaddirpStream._exploreDirectory (node_modules\@nuxt\builder\node_modules\readdirp\index.js:163

**Comment by StevePotts** [comment] 2019-07-07 01:15
Same for me. create new nuxt app, boom fail  on npm run dev.
Node V 11
Win 10 pro.

 
ERROR  Cannot mix BigInt and other types, use explicit conversions                                           00:14:31

  at FSWatcher._hasReadPermissions (node_modules\chokidar\index.js:775:36)
  at WatchHelper.filterPath (node_modules\chokidar\index.js:191:16)
  at ReaddirpStream.fileFilter [as _fileFilter] (node_modules\chokidar\lib\nodefs-handler.js:405:29)
  at ReaddirpStream._isFileAndMatchesFilter (node_modules\readdirp\index.js:234:31)
  at ReaddirpStream._exploreDirectory (node_modules\readdirp\index.js:163:23)

**Comment by aldarund** [comment] 2019-07-07 11:09
I cant repro it on my win 10 insider build.
In first message there is a express server used, is everyone else also using express?

**Comment by aldarund** [comment] 2019-07-07 12:07
It seems to be already fixed in lates chokidar release https://github.com/paulmillr/chokidar/issues/868 
https://github.com/paulmillr/chokidar/releases/tag/3.0.2

**Closed by aldarund** 2019-07-07 12:07 UTC
Labels: cmty:question
