### ISSUE TITLE
Nested Dynamic Route change causes parent route to re-render

### ISSUE THREAD

**Issue by carrickjason** [nuxt/nuxt.js#1408] opened 2017-08-18 01:09 UTC
First off, huge thanks for Nuxt.  I love it!  

I have a project with a simple folder structure similar to the following:

```
pages/
--items.vue
--items/
----_id.vue
```

I have included a `<nuxt-child/>` inside `items.vue` along with a list of items that link to different id's.  `_id.vue` simply renders a modal that displays info based on the id passed as a param.

This is all working and rendering properly except that each time an item is clicked, the `items.vue` component re-renders causing it reset its state and lose the users scroll position.

Is this expected behavior?  Is it possible to have dynamic nested routes without re-rendering their parent with each route change?

**Comment by ydnar** [comment] 2017-08-31 15:22
Curiously, with `1.0.0-rc8` I observe the *opposite* behavior. I have a project with nested views:

```
pages/
--index.vue
--index/
----_id.vue
```

The outer/root view (`index.vue`) displays search results, keying off a query string parameter (`?q=<terms>`). `<nuxt-link>` links that change the query string parameter, e.g.:

> /?q=foo
> /?q=bar

**…do *not* cause the outer view to re-render.** The `asyncData`, `fetch`, and `mounted` hooks do not fire after the initial render.

Is this as-designed? Is there a way to specify that query string parameters affect a route and should cause a re-render?

**Comment by dotneet** [comment] 2017-10-06 03:40
I think this issue is related to #1761 . 
fixPrepatch() resets a parent view's state.

https://github.com/nuxt/nuxt.js/blob/dev/lib/app/client.js#L359

I'm not sure why fixPrepatch() is needed.

**Comment by dotneet** [comment] 2017-10-06 04:10
@Atinux Thank your for creating great useful framework. If you have a time, could you tell me what situation needs fixPrepatch().

**Comment by wuyongzhi** [comment] 2017-10-13 05:58
i have the same problem, how to  solve it?

**Comment by Atinux** [comment] 2017-10-13 09:02
Actually, fixPrepatch is there to merge the result of `asyncData` when we are on a dynamic route without having to watch `$route`, I will investigate on it, but It will help me a lot to have a small reproduction repo please.

**Comment by dotneet** [comment] 2017-10-13 09:40
Hi @Atinux,
small reproduction repo is here:
https://github.com/dotneet/nuxt-issue-1408

**Comment by dotneet** [comment] 2017-10-19 13:06
Hi @Atinux,

Do you think this patch is worth to PR?
using `getChangedComponentsInstances()` instead of `getMatchedComponentsInstances()` in client.js, We can get around this problem I think.

getMatchedComponentsInstances() returns all components thats is matched to new path.
This is root cause of this problem. To solve the problem, nuxt should apply a fixPrepatch() to components that will be changed by moving path.

```js
export function getRouteRecordWithParamNames (route) {
  return route.matched.map(m => {
    let paramNames = m.path.match(new RegExp(':[^\\/]+$', 'g'))
    let paramName = null
    if (paramNames !== null && paramNames.length > 0) {
      paramName = paramNames[paramNames.length - 1].substring(1)
    }
    return {
      routeRecord: m,
      paramName: paramName
    }
  })
}

export function getChangedComponentsInstances (to, from) {
  let t = getRouteRecordWithParamNames(to)
  let f = getRouteRecordWithParamNames(from)
  let r = []
  let parentChange = false
  for (var i = 0; i < t.length; i++ ) {
    var paramName = t[i].paramName
    var instances = t[i].routeRecord.instances
    instances = Object.keys(instances).map(function (key) {
      return instances[key]
    })
    if (parentChange) {
      r = [].concat(r, instances)
    } else if (paramName !== null) {
      if (to.params[paramName] !== from.params[paramName]) {
        parentChange = true
        r = [].concat(r, instances)
      }
    }
  }
  return r
}
```

**Comment by Atinux** [comment] 2017-10-31 14:06
PR merged

**Closed by Atinux** 2017-10-31 14:06 UTC
Labels: bug, need repro
