### ISSUE TITLE
Query in the path affect the execution of the life cycle

### ISSUE THREAD

**Issue by Wulawa** [nuxt/nuxt.js#5083] opened 2019-02-21 11:31 UTC
### Version

[v2.4.3](https://github.com/nuxt.js/releases/tag/v2.4.3)

### Reproduction link

[https://codesandbox.io/s/z3rj536wxm](https://codesandbox.io/s/z3rj536wxm)

### Steps to reproduce

When the sub-route changes, if there is a query in the path, then the parent route is data, asyncData will execute, but it will not be created and mounted.
If there is no query in the path, data, asyncData will not execute.

### What is expected ?

When data, asyncData is executed, created and mounted is executed together.

### What is actually happening?

''

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8703">#c8703</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-02-21 12:03
Could you please improve your issue description? I'm not sure what the actual problem is as the expectation / actual result isn't clear to me.

Please provide steps (for the codesandbox) like:

1. Go to route XYZ
2. See ABC in the console
3. Expected result: UVW in the console

**Comment by Wulawa** [comment] 2019-02-21 12:15
1.
https://z3rj536wxm.sse.codesandbox.io/news/intro?query=123  
The page mounted is initially true
2. 
click the 'go detail' button
Mounted as false
Created  function not executed

**Comment by Wulawa** [comment] 2019-02-21 12:20
When the sub-route changes，parent router data、asyncdata not executed

**Comment by manniL** [comment] 2019-02-21 13:58
That's indeed a bug! 👍

**Comment by Wulawa** [comment] 2019-02-22 03:23
@manniL Expectation: Sub-route changes the life cycle of the parent route without any updates 🙏

**Comment by barankyle** [comment] 2019-06-10 22:37
I'll add that I see this bug even if there isn't any query in the path. I have an app that has routes /settings/people, /settings/people/create, and /settings/people/_id. They all use the same components, with differences in state determining what gets rendered. If I'm on /settings/people and navigate to one of the sub-routes via router.push, with no query on any of those paths, 'mounted' in the shared main component does not fire (possibly other lifecycle events too, but that's the only one I use in these pages).

In the interim, I ended up changing the two sub-routes to /settings/person/create and /settings/person/_id to work around this issue.

**Comment by Atinux** [comment] 2019-08-09 09:34
I just tried with Nuxt v2.8.1 on https://codesandbox.io/s/z3rj536wxm and I cannot reproduce the issue.

Closing now, please re-open if it's still reproductible.

**Closed by Atinux** 2019-08-09 09:34 UTC
Labels: cmty:bug-report, pending
