### ISSUE TITLE
Double call nuxtServerInit

### ISSUE THREAD

**Issue by Pinegin** [nuxt/nuxt.js#4087] opened 2018-10-11 08:53 UTC
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://codesandbox.io/s/6v90v9wllr](https://codesandbox.io/s/6v90v9wllr)

### Steps to reproduce

import PortalVue from "portal-vue";

open browser concole

refresh page

### What is expected ?

Only call nuxtServerInit 

### What is actually happening?

Double call nuxtServerInit

### Additional comments?

Hi.

I apologize for the English.

I do not understand why when using the portal-vue, there is a double function call nuxtServerInit

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7948">#c7948</a>)</em></sub></div>

**Comment by manniL** [comment] 2018-10-11 09:10
I've forked your CSB and adapted the code so no shared state exists:
https://codesandbox.io/s/nwjwo0v6xj

Can't reproduce the problem anymore.

However, this is a duplicate of https://github.com/nuxt/nuxt.js/issues/1863
Likely https://github.com/nuxt/nuxt.js/issues/4016 is the cause most of the time this happens.

**Closed by manniL** 2018-10-11 09:10 UTC
Labels: cmty:bug-report

**Comment by Pinegin** [comment] 2018-10-11 13:11
> I've forked your CSB and adapted the code so no shared state exists:
> https://codesandbox.io/s/nwjwo0v6xj
> 
> Can't reproduce the problem anymore.
> 
> However, this is a duplicate of #1863
> Likely #4016 is the cause most of the time this happens.

If you look at the server console, it works out 2 times.
I have 2 requests in the project.

**Comment by manniL** [comment] 2018-10-11 13:39
If I reload the page I only see one "nuxtServerInit" in the console. The counter is at 1 as well 🤔

**Comment by aldarund** [comment] 2018-10-11 14:13
@manniL @Pinegin it do twice only if there chrome dev tools opened. Although counter will be at 1
