### ISSUE TITLE
beforeRouteEnter with redirect to sub-route causes nuxt-child to error

### ISSUE THREAD

**Issue by MartinMuzatko** [nuxt/nuxt.js#5857] opened 2019-06-03 07:11 UTC
### Version

[v2.8.0](https://github.com/nuxt.js/releases/tag/v2.8.0)

### Reproduction link

[https://codesandbox.io/embed/codesandboxnuxt-z4ovb](https://codesandbox.io/embed/codesandboxnuxt-z4ovb)

### Steps to reproduce

Open a page containing a nuxt-child with a beforeEnter route guard redirecting to a sub-page

### What is expected ?

When programmatically navigating there (e.g. by clicking a link) there is no error. If opening the page on first view, an error is thrown.

### What is actually happening?

Error aborting the view.
![nuxtchilderror.PNG](https://cmty.s3.eu-west-1.amazonaws.com/71995937/abbb3240-85ce-11e9-ae1e-11c9e5dffb23.PNG)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9303">#c9303</a>)</em></sub></div>

**Comment by pimlie** [comment] 2019-06-05 07:40
This exact error should be fixed in v2.8.1, but their might be another issue still. Eg with the nested-routes example I get a bailing hydration error. Can you please check if that happens for you too with 2.8.1?

**Comment by MartinMuzatko** [comment] 2019-06-05 11:33
Installing latest nuxt now, will let you know today :)

**Comment by MartinMuzatko** [comment] 2019-06-05 14:42
I think this problem is solved, but when I re-route to the parent page, then routeBeforeEnter is not triggered..

I get no more error but I still don't get redirected properly.
When navigating to the parent page while the subpage is open, the `beforeRouteEnter` hook does not get triggered. Not sure if this is a nuxt or vue-router bug :S

![nuxtbug](https://user-images.githubusercontent.com/2950505/58965411-df307700-87b0-11e9-9f48-e1ead7b096aa.gif)

**Comment by pimlie** [comment] 2019-06-05 14:45
Not a bug I think, it probably re-uses the same parent component so you also need to call `beforeRouteUpdate`

**Comment by MartinMuzatko** [comment] 2019-06-05 15:03
Also I have another problem: If I load `/assets` (the parent route) directly, I get a client-side hydration error:

![image](https://user-images.githubusercontent.com/2950505/58966931-7ac2e700-87b3-11e9-8532-47abb29c193e.png)

Even though the `<nuxt />` and `<nuxt-child />` element contains a div for testing. if I load `/assets/devices ` directly, I don't get this hydration problem :(

**Comment by pimlie** [comment] 2019-06-05 15:13
I looked into this earlier and I think this is what happens:

On the server:
- load url `/assets`
- redirect to `/assets/devices` in beforeRouteEnter
- render `/assets/devices` page
- return (ssr) data for `/assets/devices` page

Then next on the client the following:
- nuxt app created for url `/assets`
- loads `/assets` page component
- applies ssrData
- nuxt app is mounted
- redirect to `/assets/devices` in beforeRouteEnter
- load `/assets/device` component
- renders _without_ applying any ssrData 

Not sure if this is fixable, you could try to use redirect in asyncData of `/assets` instead. But if `/assets` needs to return asyncData as well you are probably out of luck.

**Comment by MartinMuzatko** [comment] 2019-06-06 07:49
I don't need asyncData in `/assets` _yet_. I think I will solve it like that. 👍

**Comment by MartinMuzatko** [comment] 2019-06-06 07:56
works perfectly! Thank you for your help :)
Then I would advise in the docs to only use asyncData redirects. 👍

**Comment by MartinMuzatko** [comment] 2019-06-06 08:03
The only problem I have now, is that when clicking on the parent page route again, the asyncData method is not used to redirect - maybe I have to use in combination with the route guard then, I will further try and report.

**Comment by MartinMuzatko** [comment] 2019-06-27 14:52
Just as a reminder, I still have this problem :/
Using in combination with the route guard does not work
Thanks for putting the pending label.
I will put up a sandbox

**Comment by Atinux** [comment] 2019-08-08 16:03
Hi @MartinMuzatko 

I recommend you to use the [middleware](https://nuxtjs.org/api/pages-middleware) instead for `beforeRouteEnter`, so Nuxt can call it when needed and correctly :)

See your demo updated to use the middleware: https://codesandbox.io/s/codesandbox-nuxt-p4knd

**Closed by Atinux** 2019-08-08 16:03 UTC
Labels: bug, cmty:bug-report, pending

**Comment by MartinMuzatko** [comment] 2019-08-09 08:42
This is brilliant! thank you so much @Atinux
