### ISSUE TITLE
fetch() method causes a weird error

### ISSUE THREAD

**Issue by mobayen** [nuxt/nuxt.js#10277] opened 2022-02-15 03:07 UTC
### Versions

- nuxt: v2.15.8
- node:  v14.17.1

I have an AlertModel that the <Alert> component accept instances as a prop

I am having a weird error message on the console.
It happens when I just include the fetch() method. An empty fetch method...
the error will be gone if I remove the fetch() method

![Screen Shot 2022-02-14 at 9 01 26 PM](https://user-images.githubusercontent.com/29548601/153984595-6b4e886d-4983-445b-82c1-887d9307512d.png)

```
The Vue page that throws the error:

<template>
  <div>
    <Alert :alert="alert" />
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

import AlertModel from '~/models/AlertModel'

export default Vue.extend({
  data () {
    return {
      alert: new AlertModel()
    }
  },

  fetch () {}
})
</script>

```

**Comment by danielroe** [comment] 2022-02-17 20:16
The issue is that if you use `fetch` in a component, the entire component state is stringified and transferred to client-side in the HTML. But this won't work for anything that isn't serialisable, like your class there.

**Closed by danielroe** 2022-02-17 20:16 UTC
Labels: bug-report
