### ISSUE TITLE
I have an error when I want to install nuxt via npm or npx 

### ISSUE THREAD

**Issue by youssefkhouili** [nuxt/nuxt.js#7870] opened 2020-08-06 10:32 UTC
when i try to install nuxt on my cli i'm facing this issue 

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nuxt%2fbuilder - Not found
npm ERR! 404
npm ERR! 404  '@nuxt/builder@2.14.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'nuxt'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2020-08-06T10_08_13_145Z-debug.log

C:\Users\Admin\AppData\Roaming\npm-cache\_npx\1940\node_modules\create-nuxt-app\node_modules\sao\lib\installPackages.js:108
        throw new SAOError(`Failed to install ${packageName} in ${cwd}`)
        ^

SAOError: Failed to install packages in c:\xampp\htdocs\laravel-nuxt\front-end
    at ChildProcess.<anonymous> (C:\Users\Admin\AppData\Roaming\npm-cache\_npx\1940\node_modules\create-nuxt-app\node_modules\sao\lib\installPackages.js:108:15)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (C:\Users\Admin\AppData\Roaming\npm-cache\_npx\1940\node_modules\create-nuxt-app\node_modules\sao\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  __sao: true
}

**Comment by danielroe** [comment] 2020-08-06 10:34
@epsy-me This is not a Nuxt issue. There are currently issues accessing npmjs.com and installing scoped packages.

https://status.npmjs.org/incidents/cksjqc1w11v5?u=yjqzk11ky282

Duplicate of #7869 and #7868

**Closed by danielroe** 2020-08-06 10:34 UTC
Labels: bug-report
