### ISSUE TITLE
Syntaxerror IE11 consola

### ISSUE THREAD

**Issue by jloewe** [nuxt/nuxt.js#5743] opened 2019-05-15 09:03 UTC
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[https://codesandbox.io/s/wy9wxpok5k](https://codesandbox.io/s/wy9wxpok5k)

### Steps to reproduce

1. Open Repro in IE11
2. IE gets a syntax error in `vendors.app.js`

### What is expected ?

Nuxt should work in IE11.
Consola should be transpiled to ES5

### What is actually happening?

```js
!*** ./node_modules/consola/dist/consola.browser.js ***!
...
class o{constructor(t={}){
...
```

ES6 class in `vendors.app.js` bundle

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9225">#c9225</a>)</em></sub></div>

**Comment by pi0** [comment] 2019-05-15 09:36
Please upgrade consola to `^2.6.2`

**Comment by foobarrio** [comment] 2019-09-03 15:04
I needed to add consola to [build.transpile](https://nuxtjs.org/api/configuration-build/#transpile) to address my IE11 issue.

**Comment by mrleblanc101** [comment] 2019-09-20 21:02
I have consola 2.9.0 and same error

**Comment by roryheaney** [comment] 2019-10-02 21:56
I'm on was on nuxt 2.10 and got this issue.  Went back down to nuxt 2.9.2 and works as it's supposed to for edge/ie11

**Comment by mrleblanc101** [comment] 2019-10-02 22:41
It's also present in 2.9.2, it's intermittent. I only have the error sometime when I refresh

**Comment by tarreislam** [comment] 2019-10-05 19:30
#### What is expected ?
Nuxt should work in IE11.
Consola should be transpiled to ES5

**Comment by manniL** [comment] 2019-10-08 14:49
Will be fixed with https://github.com/nuxt/nuxt.js/pull/6504

**Comment by mrleblanc101** [comment] 2019-10-08 16:18
So you completely removed consola ? Or just  disabled it on IE11 ?

**Comment by pi0** [comment] 2019-10-08 16:39
@mrleblanc We still have it server side so log objects are globally catched and normalized. Browser reporter removed (2.10.1+) to avoid any problems and have browser native DX :)

**Comment by mrleblanc101** [comment] 2019-10-08 19:34
So instead of fixing a bug that happened only in IE11, you completely removed consola from the client-bundle ? 
I liked the custom CSS from the log.

**Comment by pi0** [comment] 2019-10-08 20:02
@mrleblanc101 I liked it too :( But the problem is that we needed lots of polyfills to support consola for IE. If you like fancy badges in the browser, simply create a plugin like this: 

```js
import consola from 'consola'

consola.wrapConsole()
```

(PS: actually we still have a fancy badge for SSR group)

**Comment by manniL** [comment] 2019-10-09 11:12
Closing here as the issue has been resolved ☺️

**Closed by manniL** 2019-10-09 11:12 UTC
Labels: cmty:bug-report
