### ISSUE TITLE
Layout styles are loaded from another layout

### ISSUE THREAD

**Issue by blowsie** [nuxt/nuxt.js#6085] opened 2019-07-18 13:18 UTC
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://codesandbox.io/s/themeable-nuxt-kq5sy](https://codesandbox.io/s/themeable-nuxt-kq5sy)

### Steps to reproduce

- Visit the about page
- The background shoule be pink, not white, since its using the default layout not the red one

### What is expected ?

red layout not to be loaded

### What is actually happening?

red layout is loaded

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9505">#c9505</a>)</em></sub></div>

**Comment by aldarund** [comment] 2019-07-18 15:42
duplicate of https://github.com/nuxt/nuxt.js/issues/3877

**Closed by aldarund** 2019-07-18 15:42 UTC
Labels: cmty:bug-report
