### ISSUE TITLE
v2.15.8 breaks Vue components inside Nuxt Content

### ISSUE THREAD

**Issue by DerYeger** [nuxt/nuxt.js#9665] opened 2021-08-12 17:34 UTC
### Versions

- nuxt: v2.15.8
- node: v16.5.0

### Reproduction

After upgrading to Nuxt v.2.15.8, I encountered an issue where Vue components inside a Nuxt Content file stopped working.
However, this is only the case when statically generating the pages.
They work fine in dev mode.

See https://github.com/DerYeger/magdalena-jirku or https://github.com/DerYeger/jan-mueller for examples.
See https://github.com/DerYeger/jan-mueller/runs/3313688848 for the log of a failed build.

### Steps to reproduce

1. Include a Vue component inside a Nuxt Content file.
2. Run `nuxt generate`.

### What is Expected?

The build works.

### What is actually happening?

The error `Error: render function or template not defined in component: <component-name>` is thrown.

**Comment by zhaoyajie413** [comment] 2021-08-13 03:38
my question like your question.build in linux complete without error but render error。build in windows and copy .nuxt to the server is ok.

**Comment by pi0** [comment] 2021-08-13 11:27
Most likely regression related to https://github.com/nuxt/components/issues/223. The current workaround is pinning `"@nuxt/components"` to `"2.1.8"` in dependencies.

**Comment by barikhan1986** [comment] 2021-08-13 12:19
No issue in dev mode, but when you run it in production (npm run build) mode, it cannot load components when using capital letter, for example <Home-Slider /> is not working, but if you use <home-slider /> its working!
hope nuxt team will fix it soon in latest release.

**Comment by DerYeger** [comment] 2021-08-13 12:35
> No issue in dev mode, but when you run it in production (npm run build) mode, it cannot load components when using capital letter, for example `<Home-Slider />` is not working, but if you use `<home-slider />` its working!
> hope nuxt team will fix it soon in latest release.

I'm exclusively using kebab-case with lowercase letters and I still have this issue.

> Most likely regression related to [nuxt/components#223](https://github.com/nuxt/components/issues/223). The current workaround is pinning `"@nuxt/components"` to `"2.1.8"` in dependencies.

Thank you for the clarification and workaround!

**Comment by spacecowboy23** [comment] 2021-08-15 11:48
I can confirm this Bug. Using kebab-case with lowercase letters only.

Production Build fails for `target: 'static'`, working fine in dev-Environment.

I'm using dynamic Components like
```
<component
      :is="componentName"
    />
```

Downgrading `@nuxt/components` to `2.1.8` fixes this Bug

**Comment by zhaoyajie413** [comment] 2021-08-16 06:51
> Most likely regression related to [nuxt/components#223](https://github.com/nuxt/components/issues/223). The current workaround is pinning `"@nuxt/components"` to `"2.1.8"` in dependencies.

niu bi, it works.thanks.

**Comment by pi0** [comment] 2021-08-16 11:04
Sorry for inconveniences. Just remove `package-lock.json` (or `yarn.lock`) and reinstall dependencies. The issue is fixed in [components@2.2.1](https://github.com/nuxt/components/releases/tag/v2.2.1).

**Closed by pi0** 2021-08-16 11:04 UTC
Labels: bug-report

**Comment by florian-lefebvre** [comment] 2021-10-05 19:32
It also happens in a sample nuxt project, I think it would be worth mentionning it in the releases of nuxt 2.15.8 @pi0
