### ISSUE TITLE
Nuxtjs making an extra white-space only text node

### ISSUE THREAD

**Issue by andrasbacsai** [nuxt/nuxt.js#4910] opened 2019-01-31 08:44 UTC
### Version

[2.4.2](https://github.com/nuxt.js/releases/tag/2.4.2)

### Reproduction link

[https://github.com/coollabsio/nuxtjs-template](https://github.com/coollabsio/nuxtjs-template)

### Steps to reproduce

There is an extra white-space only text node on the frontend, which should not be there.

Start the project with 'npm run dev' or 'yarn dev' and check the page or build the page with 'npm run generate' or 'npm run build'.
Source code: https://github.com/coollabsio/nuxtjs-template
Built version https://cranky-bohr-b8d969.netlify.com/

![nuxtjs-bug.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/554c9150-2530-11e9-ac9a-e5676ad8d69a.png)

If I generate the same .vue files from a vue-cli template, the white-space only text node is not there.
Source code: https://github.com/coollabsio/vuecli-template
Built version https://condescending-clarke-28b34e.netlify.com/

### What is expected ?

No white-space only text node between the 2 buttons.

### What is actually happening?

White-space only text node between the 2 buttons.

### Additional comments?

Version 2.3 had this thing aswell, but currently I'm using 2.4.2.

Maybe the difference between the html minify process causing the issue in the built version? If yes, then I'm not sure why there is difference in the development, hot-reloading version.

If I'm using SPA in Nuxtjs as well as in the vue-cli template, the situation is the same.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8579">#c8579</a>)</em></sub></div>

**Comment by Nandiin** [comment] 2019-02-01 02:39
Duplicate of #4009, possibly.

**Comment by andrasbacsai** [comment] 2019-02-01 08:15
I've checked the suggested solution in #4009 , but it does not solve my problem.

**Closed** 2019-02-01 12:00 UTC
Labels: cmty:bug-report
