### ISSUE TITLE
Unexpected token export error in Production mode

### ISSUE THREAD

**Issue by pratiktmg19** [nuxt/nuxt.js#8426] opened 2020-12-02 09:14 UTC
Unexpected token export                                                                               14:43:39

  export default function setupIcons(preset) {
  ^^^^^^
  
  SyntaxError: Unexpected token export
  at new Script (vm.js:83:7)
  at createScript (vm.js:277:10)
  at Object.runInThisContext (vm.js:329:10)
  at Module._compile (internal/modules/cjs/loader.js:712:26)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
  at Module.load (internal/modules/cjs/loader.js:653:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
  at Function.Module._load (internal/modules/cjs/loader.js:585:3)
  at Module.require (internal/modules/cjs/loader.js:692:17)
  at require (internal/modules/cjs/helpers.js:25:18)

Can you please help me find out what am i missing

**Comment by danielroe** [comment] 2020-12-02 09:30
duplicate of #8427

**Closed by danielroe** 2020-12-02 09:30 UTC
Labels: feature-request
