### ISSUE TITLE
Function applyAsyncData covers data function N times and therefore wrong behaviour

### ISSUE THREAD

**Issue by yariksav** [nuxt/nuxt.js#4961] opened 2019-02-06 12:45 UTC
### Version

[v2.4.1](https://github.com/nuxt.js/releases/tag/v2.4.1)

### Reproduction link

[https://codesandbox.io/s/32m2m4j4kq](https://codesandbox.io/s/32m2m4j4kq)

### Steps to reproduce

1) go to https://codesandbox.io/s/32m2m4j4kq
2) click to Foo (work as expected)
3) click Back
4) click to Bar (unexpected param foo, witch returns form previous covered data!!! { "foo": "test", "bar": "test" })

### What is expected ?

after go to Foo then to Bar $data must be only
{ "bar": "test" }

### What is actually happening?

Function applyAsyncData covers data function many times and therefore if go to page several times - data will call N times

then if I use page with asyncData N times, function `data` will covered N times!!!!
https://github.com/nuxt/nuxt.js/blob/f319033928fc1463082666fce49a8f8304bf90a5/packages/vue-app/template/utils.js#L26-L43

### Additional comments?

when I put to applyAsyncData concole.log(data, asyncData) https://github.com/nuxt/nuxt.js/blob/f319033928fc1463082666fce49a8f8304bf90a5/packages/vue-app/template/utils.js#L38
it increase +1 console.log output every time when i go to page

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8613">#c8613</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-02-06 13:40
Duplicate of #4554

**Closed by manniL** 2019-02-06 13:40 UTC
Labels: cmty:bug-report
