### ISSUE TITLE
Store in custom plugin is not reactive

### ISSUE THREAD

**Issue by sa8ab** [nuxt/nuxt.js#8682] opened 2021-01-22 17:45 UTC
### Versions

- nuxt: "nuxt": "^2.14.6",
- node: 

### Reproduction
I am creating a custom plugin for axios so it will be injected to root and context ( please don't suggest me to use @nuxt/axios, I am using it as an example ) and in there I am using store as well as i18n.locale. It works fine until I make a change to the vuex state or change locale of i18n, the plugin does not update when any of these these are changed,
Sample code: @/plugins/axios.js

<details open>
<summary>Additional Details</summary>
<br>

</details>

### Steps to reproduce
```
import axios from "axios";
export default ({ app, store }, inject) => {
  const lang = app.i18n.locale;
  const token = store.getters["auth/token"]
  const baseAxios = axios.create({
    baseURL: "...",
    headers: {
      Authorization: `Bearer ${token}`,
      lang
    }
  });
  inject("axios", baseAxios);
};
```

### What is Expected?
I want the plugin to update to the lates state of vuex. (state of `token` in my case)

### What is actually happening?
It is not reactive to store changes

**Comment by danielroe** [comment] 2021-01-22 18:59
@sa8ab The store is reactive but you are just accessing it once - your code is working as you've written it. There are a number of ways of solving this including adding a Vuex plugin or setting the axios baseURL within the store whenever the new token is committed.

However, this is not a bug report so you should ask for support using Discord or GitHub discussions instead 🙃

**Closed by danielroe** 2021-01-22 18:59 UTC
