### ISSUE TITLE
feat: enable opting-in to breaking changes

### ISSUE THREAD

**Issue by danielroe** [nuxt/nuxt.js#8391] opened 2020-11-23 10:09 UTC
There are a number of breaking changes coming up - such as, for example, changing how `router.push` works (https://github.com/nuxt/nuxt.js/issues/8374)...

We could allow temporarily opting in to these changes of behaviour behind a flag (for example, as Tailwind CSS allowed users to opt in), e.g.
```js
export default {  
  future: {
    routerPushPromise: true
  }
}
```

This shouldn't pollute the code base too much, either, as when the actual breaking change comes, we will just remove the conditional code and the flag will no longer have an effect.

**Comment by pi0** [comment] 2020-11-23 10:35
It is a nice plan. Actually we shouldn't introduce breaking changes without opting-in. I believe issue with router.push is a regression.

closing this issue since it is a general accepted concept ;)

**Closed by pi0** 2020-11-23 10:35 UTC
Labels: feature-request
