### ISSUE TITLE
extractCSS problem

### ISSUE THREAD

**Issue by jochouen** [nuxt/nuxt.js#4441] opened 2018-11-28 09:43 UTC
### Version
v2.3.2 

### Reproduction link
https://nuxtjs.org

### Steps to reproduce
 I set extractCSS: true，generate
The result is like this
test.html
```
<link rel="stylesheet" href="/_nuxt/app.css">
<link rel="stylesheet" href="/_nuxt/pages/index.css">
<link rel="stylesheet" href="/_nuxt/pages/test.css">
<link rel="stylesheet" href="/_nuxt/pages/users/_id.css">
```

### What is expected ?

like this↓
test.html
```
<link rel="stylesheet" href="/_nuxt/app.css">              <- common
<link rel="stylesheet" href="/_nuxt/pages/test.css">   <- only for test.html
```

### What is actually happening?
please see Steps to reproduce

### Additional comments?
what should I do？
https://github.com/nuxt/nuxt.js/issues/4440

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8229">#c8229</a>)</em></sub></div>

**Comment by manniL** [comment] 2018-11-28 11:55
Duplicate of https://github.com/nuxt/nuxt.js/issues/3943

**Closed by manniL** 2018-11-28 11:55 UTC
Labels: cmty:bug-report
