### ISSUE TITLE
Publish a new release candidate

### ISSUE THREAD

**Issue by RSchwan** [nuxt/nuxt.js#2122] opened 2017-11-15 19:04 UTC
Would it be possible to release a new release candidate ?
I use some features which are currently only in the dev branch. If I install nuxt locally I have no problems but if I try to run my Dockerfile I always get an error. It seems like the Docker environment can't handle the local building of nuxt.
I'm also pretty sure other people who don't want to use the dev branch directly would appreciate a new release candidate.

BTW Nuxt is awesome. Thx for this great framework.

**Comment by uptownhr** [comment] 2017-11-15 20:18
@RSchwan I currently use the latest RC.11 on production and build using a Dockerfile. Can you share/describe your Dockerfile to debug?

**Comment by paulgv** [comment] 2017-11-15 20:34
We're using Nuxt with Docker too, no issue this far.

**Comment by RSchwan** [comment] 2017-11-15 20:52
I agree RC.11 works fine with docker. But I use the dev branch for my current Project. I have the following in my `package.json`: `"nuxt": "git://github.com/nuxt/nuxt.js.git#dev",`.
The problem now is that when you install nuxt like this nuxt has to be build locally. But for some reason this fails in Docker.

**Comment by uptownhr** [comment] 2017-11-16 05:03
Ah gotcha. Would help to see the error.

**Comment by RSchwan** [comment] 2017-11-16 09:34
My Dockerfile looks the following:
```Docker
FROM node:alpine

RUN apk add --update \
    git

WORKDIR app

COPY package.json ./
RUN yarn install

COPY . .
ARG GRAPHQL_ENDPOINT
ENV GRAPHQL_ENDPOINT ${GRAPHQL_ENDPOINT}
RUN yarn build

ENV HOST 0.0.0.0
ENV PORT 80

EXPOSE 80
CMD ["npm", "start"]
```
And I get following error:
```
Step 5/13 : RUN yarn install
 ---> Running in 933649232df7
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "ENOENT: no such file or directory, scandir '/usr/local/share/.cache/yarn/v1/npm-postcss-unique-selectors-2.0.2-981d57d29ddcb33e7b1dfe1fd43b8649f933ca1d'".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
events.js:246
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'listener', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function
    at _addListener (events.js:246:11)
    at WriteStream.addListener (events.js:306:10)
    at WriteStream.close (fs.js:2282:10)
    at /opt/yarn/lib/cli.js:67129:37
    at call (/opt/yarn/lib/cli.js:67139:3)
    at Array.forEach (<anonymous>)
    at /opt/yarn/lib/cli.js:67159:25
    at f (/opt/yarn/lib/cli.js:43203:25)
    at WriteStream.<anonymous> (/opt/yarn/lib/cli.js:67118:21)
    at WriteStream.f (/opt/yarn/lib/cli.js:43203:25)
```
I also tried npm instead of yarn but then I get following error:
```
Step 5/13 : RUN npm install
 ---> Running in 3b12e250a978

> node-sass@4.6.1 install /app/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.6.1/linux_musl-x64-59_binding.node
Download complete
Binary saved to /app/node_modules/node-sass/vendor/linux_musl-x64-59/binding.node
Caching binary to /root/.npm/node-sass/4.6.1/linux_musl-x64-59_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /app/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> bootstrap-vue@1.0.2 postinstall /app/node_modules/bootstrap-vue
> opencollective postinstall || exit 0


     *** Thank you for using bootstrap-vue! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/bootstrap-vue/donate

                    ***


> node-sass@4.6.1 postinstall /app/node_modules/node-sass
> node scripts/build.js

Binary found at /app/node_modules/node-sass/vendor/linux_musl-x64-59/binding.node
Testing binary
Binary is fine

> nuxt@1.0.0-rc11 postinstall /app/node_modules/nuxt
> opencollective postinstall || exit 0


     *** Thank you for using nuxt! ***

Please consider donating to our open collective
     to help us maintain this package.

  https://opencollective.com/nuxtjs/donate

                    ***

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN bootstrap@4.0.0-beta.2 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1274 packages in 119.067s
 ---> 2ad1af15a93e
Removing intermediate container 3b12e250a978
Step 6/13 : COPY . .
 ---> 693f87559b01
Step 7/13 : ARG GRAPHQL_ENDPOINT
 ---> Running in 5f44fbe680d0
 ---> 903919940b54
Removing intermediate container 5f44fbe680d0
Step 8/13 : ENV GRAPHQL_ENDPOINT ${GRAPHQL_ENDPOINT}
 ---> Running in ebc64474ec66
 ---> f2573052aca8
Removing intermediate container ebc64474ec66
Step 9/13 : RUN npm run build
 ---> Running in ad48aebf447e

> tool@1.0.0 build /app
> nuxt build

Error: Cannot find module './dist/nuxt'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/nuxt/index.js:16:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tool@1.0.0 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tool@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-16T09_29_46_916Z-debug.log
```

**Comment by dohomi** [comment] 2017-11-16 10:54
Are there any known limitations/changes of the current #dev branch? The last published version is over 3 months ago, I think a lot happened in between. Is there actually a reason why there aren't more frequent bugfix releases? Thanks for the heads up

**Comment by clarkdo** [comment] 2017-11-18 14:28
Duplicate of #2142, we are extremely working very hard on the new coming release, more details you may check #2142.

**Closed** 2017-11-18 14:29 UTC
