### ISSUE TITLE
Assets does not compiled at nuxt-edge:latest

### ISSUE THREAD

**Issue by jyqry** [nuxt/nuxt.js#3723] opened 2018-08-14 13:44 UTC
### Version

[nuxt-edge](https://github.com/nuxt.js/releases/tag/nuxt-edge)

### Reproduction link

[.](.)

### Steps to reproduce

I'm using nuxt-edge version "latest"

since I'm re-installed packages (node_modules),
this bug showed up.

so I'm guessing latest build has this bug 

### What is expected ?

`~assets/icon.svg`  (in style section)
should be turn into
 `data:image/svg+xml;base64 ...)`

### What is actually happening?

assets doesn't compiled.
for example) background-image: url(/assets/icon.svg)

### Additional comments?

Assets compiled with `2.0.0-25468832.6578bd7`
not compiled with latest build which `2.0.0-25569931.85a8af5`

I'm using nuxt starter template

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7565">#c7565</a>)</em></sub></div>

**Comment by manniL** [comment] 2018-08-15 07:35
Hey :wave: 

Have you tried `~/assets/..` vs. `~assets/.../`?

**Comment by jyqry** [comment] 2018-08-15 08:33
@manniL 
Thank you for your response :)

Ah sorry
I tried `~/assets/..`
not `~assets/..`

I just tried `~assets/..` in <style> and this works well.
and  `~/assets/..` /  `~assets/..` both works well in <template>

I'm wondering why doesn't work `~/assets/..` with <style> section.
is this a feature?

**Comment by jyqry** [comment] 2018-08-15 08:47
For more information,

### Steps to reproduce
1. `vue init nuxt-community/starter-template <project-name>`
2. `cd <project-name>`
3. `yarn`
4. `yarn add nuxt@npm:nuxt-edge`
- package.json changed to `"nuxt": "npm:nuxt-edge"` now.
5. add `icon.svg` in `/assets` folder
6. modify `/pages/index.vue` to
```vue
<template>
  <div>
    <img src="~/assets/icon.svg"> <!--// works fine-->
    <img src="~assets/icon.svg"> <!--// works fine too-->

    <div class="icon-1"></div> <!--// this tag styled in <style />-->
    <div class="icon-2"></div> <!--// this tag styled in <style />-->
  </div>
</template>
<style>
.icon-1 {
  width: 100px;
  height: 100px;
  background-image: url('~/assets/icon.svg'); /* this is NOT compiled. however, "2.0.0-25468832.6578bd7" version has no problem with compile */
}
.icon-2 {
  width: 100px;
  height: 100px;
  background-image: url('~assets/icon.svg');  /* this is compiled as expected. */
}
</style>
```

**Comment by jyqry** [comment] 2018-08-15 08:55
here is my screenshots

### 1. component
<img src="https://user-images.githubusercontent.com/12688732/44140067-f6a4cf4c-a0b3-11e8-8f37-59e44ef1bd21.png" width="50%">

### 2. http://localhost:3000/
![15343230351](https://user-images.githubusercontent.com/12688732/44140072-fa05611a-a0b3-11e8-8f0b-21c07e547407.png)

### 3. Not compiled
![15343231973](https://user-images.githubusercontent.com/12688732/44140147-29a11450-a0b4-11e8-8e29-8fc8507cd5ec.png)

### 4. compiled
![15343232064](https://user-images.githubusercontent.com/12688732/44140150-2b7bf92a-a0b4-11e8-8ea2-0b52a0346806.png)

**Comment by manniL** [comment] 2018-08-15 17:59
I don't think that it's the expected behavior. `~/assets` and `~assets` should both work IMO:

**Comment by clarkdo** [comment] 2018-08-15 18:12
Please use `~/assets` in `url()` resources, because `~` is a special indicator in css-loader, `~assets` will be resolved in modules

**Comment by jyqry** [comment] 2018-08-15 22:11
@clarkdo 
it has the same issue when I'm only using `~/assets` in `url()` resources.

I expected `~/assets` in `url()` resources are compiled.
but `nuxt-edge` latest build do not compile `~/assets` in `url()`  (tested in `2.0.0-25571241.61c0976` version)
I think this is a bug because this happens with starter template (I just added a single svg file)

**Comment by clarkdo** [comment] 2018-08-15 22:13
Could you please provide a repository?

**Comment by jyqry** [comment] 2018-08-15 22:28
here it is :)
https://github.com/jyqry/nuxt-loader-test

**Comment by clarkdo** [comment] 2018-08-15 22:30
My current time is midnight already, I’ll look into it tomorrow, sorry for the inconvenience.

**Comment by jyqry** [comment] 2018-08-15 22:33
okay good night💤

**Comment by clarkdo** [comment] 2018-08-16 09:30
The issue is related to https://github.com/webpack-contrib/css-loader/issues/750, `css-loader` removed the `alias` option and replaced with `loader-util` which will tread `~/` as absolute path. 
So please use `~assets` instead of `~/assets` for now. Or add `css-loader@0.28.11` manually.

@Atinux Do we need to downgrade the css-loader or change doc or release note as a reminding ?

**Comment by clarkdo** [comment] 2018-08-16 11:05
Downgrade css-loader for now, https://github.com/nuxt/nuxt.js/commit/6bfa68d6fdef9fba0079d9a3d0ee3bf5146ca79f

**Closed by clarkdo** 2018-08-16 11:05 UTC
Labels: cmty:bug-report
