### ISSUE TITLE
page fetch and action/dispatch redirect not working.

### ISSUE THREAD

**Issue by Mikeysax** [nuxt/nuxt.js#2735] opened 2018-02-01 01:35 UTC
I'm trying to redirect inside of a Vuex action.

1) It initially renders the page it is going to redirect to, but the URL does not change.
2) It ends up rendering the original page that it was redirecting from.
3) It throws a hydration error:
```
Parent:  
<div class="form-container" data-v-58d7984c="">
vue.runtime.esm.js:5940
Mismatching childNodes vs. VNodes:  
NodeList [ form ]
 
Array [ {…} ]
vue.runtime.esm.js:5941
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

Here is the code for the action:
```js
export async function EDIT_TEACHER({ dispatch, commit, state }, { id }) {
  try {
    const { data } = await this.$axios({
      url: `/teachers/${id}/edit`,
      method: 'get'
    });
    commit('SET_TEACHER', data.teacher);
  } catch ({ response }) {
     dispatch('PROMPT_SIGN_IN');
  }
}
```
PROMPT_SIGN_IN will redirect.

 Here is where I call it:
```js
async fetch({ store, params }) {
    if (Object.keys(store.state.teacher.data).length <= 0)
      await store.dispatch('EDIT_TEACHER', { id: params.teacher });
  } 
```
Any idea on this?

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2375">#c2375</a>)</em></sub></div>

**Comment by clarkdo** [comment] 2018-02-01 04:22
`fetch` doesn't support `async`, maybe you can try `asyncData` :).

**Comment by Mikeysax** [comment] 2018-02-01 04:31
Doesn't it?

According to my testing and my previously accepted PR to modify the documentation, it does support async.

Also, it has only worked on refresh if I use async await.

**Comment by clarkdo** [comment] 2018-02-01 04:47
You are right, it's my fault, can you provide a repo?

**Comment by Mikeysax** [comment] 2018-02-01 04:54
Unfortunately, I can't provide the full example of the code as it is private.

**Comment by furyscript** [comment] 2018-06-01 14:54
Same issue for me. Redirect works but it's render back page...

**Comment by galvez** [comment] 2018-08-26 11:11
Unable to reproduce. Closing this as there's been no updates over 90 days.

**Closed by galvez** 2018-08-26 11:11 UTC
