### ISSUE TITLE
Pug not working in Nuxt.2.0

### ISSUE THREAD

**Issue by NextStepGuru** [nuxt/nuxt.js#3469] opened 2018-06-23 17:51 UTC
### Version

[v2.0](https://github.com/nuxt.js/releases/tag/v2.0)

### Reproduction link

[https://github.com/nuxt/nuxt.js/tree/dev/examples/markdownit](https://github.com/nuxt/nuxt.js/tree/dev/examples/markdownit)

### Steps to reproduce

Make sure to install nuxt-edge as the current dev version has the nuxt package.

i removed all modules from nuxt.config.js as md throws an error as well

### What is expected ?

pug should render

### What is actually happening?

This relative module was not found:

* ./pug.vue?vue&type=template&id=6fbf9768&lang=pug in ./pages/pug.vue

### Additional comments?

i have another larger nuxt project that i'm trying to convert to nuxt2.0 with hundreds of pug files. i'm consistently getting relative module not found in all of them.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7278">#c7278</a>)</em></sub></div>

**Comment by NextStepGuru** [comment] 2018-06-23 17:56
after alot of hacking around - i got pug to work by installing "pug-plain-loader"

**Comment by manniL** [comment] 2018-07-20 14:01
duplicate of #3161

**Closed** 2018-08-08 09:39 UTC
Labels: cmty:bug-report

**Comment by manniL** [comment] 2018-11-25 11:02
https://github.com/nuxt/nuxt.js/pull/4409

Pug works out of the box again :relaxed:
