### ISSUE TITLE
No access to locally loaded javascript via head()

### ISSUE THREAD

**Issue by abh153k** [nuxt/nuxt.js#5594] opened 2019-04-24 12:14 UTC
### Version

[v2.6.2](https://github.com/nuxt.js/releases/tag/v2.6.2)

### Reproduction link

[https://codesandbox.io/s/vzxv41wry](https://codesandbox.io/s/vzxv41wry)

### Steps to reproduce

Please check this: https://codesandbox.io/s/vzxv41wry Note that inside `about.vue`, I have loaded javascript (as instructed here: https://nuxtjs.org/faq/#local-settings ) But if I visit /about, the app throws an error saying `$ is not defined`. Is this a bug?

### What is expected ?

/about should have access to $

### What is actually happening?

/about throws an error saying $ is not defined

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9098">#c9098</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-04-24 12:23
Duplicate of #5052

**Closed by manniL** 2019-04-24 12:23 UTC
Labels: cmty:bug-report
