### ISSUE TITLE
How to keep routers name for father. 

### ISSUE THREAD

**Issue by barom** [nuxt/nuxt.js#119] opened 2017-01-11 08:01 UTC
![image](https://cloud.githubusercontent.com/assets/13477381/21840209/3b651522-d817-11e6-93eb-5bee2107cd04.png)

**Comment by barom** [comment] 2017-01-11 08:09
Like this 
![image](https://cloud.githubusercontent.com/assets/13477381/21840417/6139b16c-d818-11e6-9e09-03b2c2128856.png)

**Comment by Atinux** [comment] 2017-01-11 08:36
I will take a look and come back to you @barom but it seems to be a bug.

**Comment by barom** [comment] 2017-01-11 08:41
Thank you very much ~

**Comment by alexchopin** [comment] 2017-01-11 11:58
It's fixed, it will be working in the next release.

**Comment by barom** [comment] 2017-01-12 01:14
Thanks @Atinux @alexchopin . But how long will it take to have the next . because  I'm going to use this on the line line

**Comment by Atinux** [comment] 2017-01-12 09:15
It should be pretty soon, we have to fix other issues before.

In the meantime @barom, you can link to `/:projectname` with `<nuxt-link :to="'/'+projectname">{{ projectname }}</nuxt-link>`.

**Comment by barom** [comment] 2017-01-13 06:02
Thanks.
I'm trying to do this. 
however , all of the sub routes jump to the father's component.
They are independent pages.
Do you know what I mean.

**Comment by alexchopin** [comment] 2017-01-13 09:14
@barom, what are you trying to do?
Can you post some code lines or screenshots, please?

**Comment by barom** [comment] 2017-01-13 09:42
![image](https://cloud.githubusercontent.com/assets/13477381/21925193/531c4acc-d9b7-11e6-8ade-d8159615341f.png)
This site is the father of the page Jump.

**Comment by barom** [comment] 2017-01-13 09:48
In fact, I don't want my route to be nested because they are separate pages

**Comment by barom** [comment] 2017-01-13 09:52
Hello, @alexchopin  are you there.

**Comment by alexchopin** [comment] 2017-01-13 10:00
Hi, 
I'm not sure to understand your project structure but, if you don't want to use nested routes you should not create the parent _projectname.vue file.

**Comment by barom** [comment] 2017-01-13 10:03
I need this match.

**Comment by alexchopin** [comment] 2017-01-13 10:05
Can you go to [gitter](https://gitter.im/nuxt/nuxt.js) please it will be more easy.

**Comment by barom** [comment] 2017-01-13 10:08
I use nuxt . So can I Custom routing

**Comment by alexchopin** [comment] 2017-01-13 10:26
Here just a recap of the documentation.

To create a [custom/dynamic route](https://nuxtjs.org/guide/dynamic-routes):
- Create a .vue file OR a folder prefixed by an underscore with an index.vue. (example: _project.vue OR _project/index.vue)
- Nuxt will create a route /:project

To create a [nested route](https://nuxtjs.org/guide/nested-routes):
- Create a.vue file AND a folder with the same name. (example: posts.vue AND posts/)
- Nuxt considers that posts.vue is the parent and file/folder inside posts/ folder are children

**Comment by Atinux** [comment] 2017-01-13 10:41
@barom if you don't want to use children, your directory structure should be like this:

```bash
pages/
-| _projectname/
----| list/
------| _newsType.vue
------| index.vue
----| _newid.vue
----| index.vue
-| index.vue
```

This will generate:
```js
{
	path: "/",
	component: _fa389168,
	name: "index"
},
{
	path: "/:projectname",
	component: _25dd869e,
	name: "projectname"
},
{
	path: "/:projectname/list",
	component: _b75ff2f6,
	name: "projectname-list"
},
{
	path: "/:projectname/:newid",
	component: _1445c8a0,
	name: "projectname-newid"
},
{
	path: "/:projectname/list/:newsType",
	component: _35116d82,
	name: "projectname-list-newsType"
}
```

I will close this issue since it was not a bug but just another way to structure your directory.

**Closed by Atinux** 2017-01-13 10:41 UTC
Labels: bug, help wanted
