### ISSUE TITLE
Problem with mongoose

### ISSUE THREAD

**Issue by gen4sp** [nuxt/nuxt.js#3285] opened 2018-04-29 21:04 UTC
### Version

[v1.4.0](https://github.com/nuxt/nuxt.js/releases/tag/v1.4.0)

### Steps to reproduce

1) add 'import "mongoose"' line

### What is expected ?

mongoose should be imported with no problem.

### What is actually happening?

getting error:

```
These dependencies were not found:

* dns in ./node_modules/mongodb-core/lib/uri_parser.js, ./node_modules/mongodb/lib/url_parser.js
* fs in ./node_modules/mongodb/lib/gridfs/grid_store.js, ./node_modules/require_optional/index.js
* module in ./node_modules/require_optional/node_modules/resolve-from/index.js
* net in ./node_modules/mongodb-core/lib/connection/connection.js
* tls in ./node_modules/mongodb-core/lib/connection/connection.js
```

### Additional comments?

I've tried v1.0 and v1.4
I've tried to wrap importing within 'process.server ' condition - doen't help. Error appears on compilation step, not on requesting endpoint.

What could be wrong? Please, help.
Thank you

<div align="right"><sub><em>This bug report is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c6999">#c6999</a>)</em></sub></div>

**Comment by gen4sp** [comment] 2018-04-30 15:40
Any ideas, guys? 
I am really stuck (

**Comment by manniL** [comment] 2018-05-02 10:43
It could help to provide a reproduction repository ;)

**Comment by uptownhr** [comment] 2018-05-02 11:09
i've done a few searches on google and found issues with webpack and mongoose. https://github.com/webpack/webpack/issues/3404 https://github.com/Automattic/mongoose/issues/4996

For this particular issue though, I believe this is due to the webpack target of browser and not node. The libraries that are not resolving, I believe are only available in the node core environment.

**Comment by ecseley** [comment] 2018-06-13 21:40
@gen4sp did you ever figure this out? This is driving me crazy.

**Comment by manniL** [comment] 2018-08-08 07:16
You shouldn't import `mongoose` in your nuxt components/plugins directly.
Better use an extra API endpoint or a `serverMiddleware` for that.

**Closed** 2018-08-08 09:41 UTC
Labels: cmty:bug-report
