### ISSUE TITLE
asyncData called multiple times in nested routes 

### ISSUE THREAD

**Issue by msacar** [nuxt/nuxt.js#5468] opened 2019-04-05 07:13 UTC
### Version

[v2.6.0](https://github.com/nuxt.js/releases/tag/v2.6.0)

### Reproduction link

[https://codesandbox.io/embed/w04l29nmm7](https://codesandbox.io/embed/w04l29nmm7)

### Steps to reproduce

Hello im having problems with nested dynamic routes
here is a sandbox example https://codesandbox.io/embed/w04l29nmm7
i applied this documentation to sandbox https://nuxtjs.org/guide/routing#dynamic-nested-routes

pages/
--| _category/
-----| _subCategory/
--------| _id.vue
--------| index.vue
-----| _subCategory.vue
-----| index.vue
--| _category.vue
--| index.vue

for category route asyncData called 2 times
for category/subcategory route asyncData called 3 times

### What is expected ?

asyncData called once for single page

### What is actually happening?

asyncData called multiple times for single page

### Additional comments?

for category route asyncData called 2 times
for category/subcategory route asyncData called 3 times

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9000">#c9000</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-04-05 08:02
Duplicate of https://github.com/nuxt/nuxt.js/issues/4008

**Closed by manniL** 2019-04-05 08:02 UTC
Labels: cmty:bug-report
