### ISSUE TITLE
trailingSlash:true corrupts payloads

### ISSUE THREAD

**Issue by Djules** [nuxt/nuxt.js#8476] opened 2020-12-11 17:20 UTC
### Versions

- nuxt: 2.14.11
- node: 12.18.2

### Steps to reproduce

I'm using `generate` with `{ target: 'static' }` in my config to get a fully-static website.

I'm using `asyncData` to retrieve content from Prismic API.

And I'm using `{ router: { trailingSlash: true } }` in Nuxt config to add trailing slash all URLs.

### What is actually happening?

Problem is, the generated payload files don't have a trailing slash in their keys, so pages's data remains blank, and new calls to API are made on each route change.

**Comment by visini** [comment] 2020-12-11 19:20
Thank you for your insight, I faced the same issue without realizing that it's related to the trailing slash this whole afternoon... However, I can confirm that when setting `trailingSlash: false`, the issue now no longer seems to appear. Good job tracking down this issue, and looking forward to a fix.

**Comment by Timkor** [comment] 2020-12-13 09:04
Any update on this one?

**Comment by zwakheid** [comment] 2020-12-14 11:23
ETA for a fix?

**Comment by realityfilter** [comment] 2020-12-16 20:40
We ran into the same problem. But we have the default setting of `trailingSlash`, which is undefined. How is this valid case handled? Wouldn't it be possible to change the loader to ask for a chunkId with a trailing slash in this "mixed" mode as fallback?

**Comment by danielroe** [comment] 2020-12-16 22:53
@realityfilter In #8489, we remove trailing slashes if `trailingSlash: false` but otherwise leave them as the route is rendered because there are some scenarios where `trailingSlash` should make a difference. For example, see [the docs](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-router#example-behaviour-with-child-routes) though note that behaviour won't match docs fully until https://github.com/nuxt/nuxt.js/pull/8423 is merged.

**Closed** 2020-12-17 11:51 UTC
Labels: bug-report

**Comment by kreba** [comment] 2020-12-17 12:14
What a great improvement, thank you!
