### ISSUE TITLE
Build cycle?

### ISSUE THREAD

**Issue by breeswish** [nuxt/nuxt.js#400] opened 2017-03-18 08:00 UTC
```bash
$ vue init nuxt/starter nuxt-test
$ cd nuxt-test
$ npm install
$ npm dev
> nuxt-test@1.0.0 dev /Users/Breezewish/Development/nuxt-test
> nuxt

  nuxt:build App root: /Users/Breezewish/Development/nuxt-test +0ms
  nuxt:build Generating .nuxt/ files... +2ms
Ready on http://localhost:3000
  nuxt:build Generating routes... +12ms
  nuxt:build Generating files... +14ms
  nuxt:build Adding webpack middleware... +17ms
  build [==                  ] 10%(node:15297) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Build completed in 5.33s

webpack built c992d1d89258e456757a in 5335ms
webpack building...

Build completed in 0.239s

webpack built c992d1d89258e456757a in 240ms
webpack building...

Build completed in 0.245s

webpack built c992d1d89258e456757a in 245ms
webpack building...

Build completed in 0.245s

webpack built c992d1d89258e456757a in 245ms
webpack building...

Build completed in 0.237s

webpack built c992d1d89258e456757a in 238ms
webpack building...

Build completed in 0.235s

webpack built c992d1d89258e456757a in 235ms
webpack building...

Build completed in 0.23s

webpack built c992d1d89258e456757a in 225ms
webpack building...

Build completed in 0.202s

webpack built c992d1d89258e456757a in 203ms
webpack building...

Build completed in 0.194s

webpack built c992d1d89258e456757a in 194ms
webpack building...

Build completed in 0.109s

webpack built c992d1d89258e456757a in 110ms
```

nuxt rebuilt several times after initial build. Is it intentional or a bug?

**Comment by Atinux** [comment] 2017-03-18 10:48
Duplicate of #324

**Closed by Atinux** 2017-03-18 10:48 UTC
