### ISSUE TITLE
JS error with default installation

### ISSUE THREAD

**Issue by azurinspire** [nuxt/nuxt.js#5285] opened 2019-03-19 21:24 UTC
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://nuxtjs.org/guide/installation](https://nuxtjs.org/guide/installation)

### Steps to reproduce

npx create-nuxt-app first-nuxt

? Project name first-nuxt
? Project description My fantastic Nuxt.js project
? Use a custom server framework none
? Choose features to install Linter / Formatter, Prettier, Axios
? Use a custom UI framework tailwind
? Use a custom test framework jest
? Choose rendering mode Universal
? Author name My Name
? Choose a package manager npm

cd first-nuxt && npm run dev

### What is expected ?

New application opens without errors

### What is actually happening?

ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/.../Projects/training/first-nuxt/.nuxt/client.js: Cannot find module '@babel/preset-env/data/built-ins.json' (While processing: "/Users/.../Projects/training/first-nuxt/node_modules/@nuxt/babel-preset-app/src/index.js")

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8868">#c8868</a>)</em></sub></div>

**Comment by GeorgeSG** [comment] 2019-03-19 22:06
I'm having the same issue. It can be reproduced with a very minimal setup, just a `package.json:

```
{
  "dependencies": {
    "nuxt": "latest"
  },
  "scripts": {
    "dev": "nuxt"
  }
}

```

and `npm run dev`.

I don't think the problem is not in nuxt itself though, it occurs in any previous version.

As far as I can tell, it seems to be a problem with `@babel/preset-env` - `data/built-ins.json` is missing. It got removed in [this commit](https://github.com/babel/babel/commit/3303b079c596e56909adff4b834f098f5f1d8e2a#diff-e4c6f611bca3dd87af2a2d4551529f72) and `v7.4.0` of `@babel/preset-env` (which was realeased... 2 hours ago?).

**Comment by tobiashanl** [comment] 2019-03-19 22:31
Same problem here. Manually changing the line in `@nuxt/babel-preset-app/src/index.js` to use `built-in-modules.json` instead of `built-ins.json` seems to fix this problem.

However, if you do this you run into the next problem: `isPluginRequired` is no longer exported from `babel-preset-env.` There is already an open issue in the babel repository to fix this: https://github.com/babel/babel/issues/9707

The only workaround I found until this gets fixed is manually running `npm i @babel/preset-env@7.3.4` after creating the nuxt app. Afterwards, everything works as expected.

**Comment by cwirz** [comment] 2019-03-19 22:49
Still getting the same `isPluginRequired` error even if i downgrade the `@babel/preset-env` to `7.3.4`. Any ideas?

**Comment by azurinspire** [comment] 2019-03-20 07:31
For me `npm i @babel/preset-env@7.3.4` fixed the problem.

**Comment by manniL** [comment] 2019-03-20 10:57
Duplicate of #5286

**Closed by manniL** 2019-03-20 10:57 UTC
Labels: cmty:bug-report
