### ISSUE TITLE
The last Layout override all other layouts.

### ISSUE THREAD

**Issue by bat79a** [nuxt/nuxt.js#5225] opened 2019-03-13 11:22 UTC
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://jsfiddle.net/xtj6sdz8/](https://jsfiddle.net/xtj6sdz8/)

### Steps to reproduce

Create a page named UI, with a new layout assigned to it : aaa.vue
Create a new layout : zzz.vue

The UI page will have a 200px margin from the zzz.vue layout and not the aaa.vue layout assigned in the page with a 1px margin.

### What is expected ?

UI page with a 1px margin from the aaa.vue layout assigned to this page.

### What is actually happening?

UI page with a 100px margin from the zzz.vue layout.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8822">#c8822</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-03-13 11:24
Is this a duplicate of #3877?

**Comment by bat79a** [comment] 2019-03-13 11:30
May be yes. I haven't test to include other CSS element. 
But for sure the last alphabetic layout override the css element defined in the layout of the page.

**Comment by manniL** [comment] 2019-04-02 11:56
Duplicate of #3877

**Closed by manniL** 2019-04-02 11:56 UTC
Labels: cmty:bug-report
