### ISSUE TITLE
Nuxt application page is empty while npm run builld is running

### ISSUE THREAD

**Issue by jariesdev** [nuxt/nuxt.js#7737] opened 2020-07-18 10:35 UTC
The nuxt application is running using `npm start` and its fine until you run `npm run build` is run on the background then the page will become empty (plain white page). Im using pm2 to supervise the application and restart when terminated and manually restart after build is finished (application will work again after restart). Then problem is the build time taking so long users may see empty page.

My question is, is this intended behavior? If yes, please let me know has to properly address it. thank you very much.

### Versions

- nuxt: v2.13.3
- node: v10.18.1

### Steps to reproduce
run `npm start` on 1st terminal then `npm run build` on 2nd terminal and visit any page.

### What is Expected?
The application should maintain running and use the previous build files

### What is actually happening?
I think the reason is the build is being removed from the server and browser cant get the requested page (404).

**Comment by danielroe** [comment] 2020-07-18 10:54
@jariesdev Yes, when the new build starts it deletes the last build's files. I'd suggest copying them to another directory in a Nuxt build hook and then serving that directory, assuming you want to use the pattern you've suggested.

**Comment by jariesdev** [comment] 2020-07-18 11:25
@danielroe Thank you for quit response and for the suggestion I will try that. On the other hand, Im thinking of using cache such as `nuxt-ssr-cache` and I assume it will serve the cached files even i run build. I will try the build hook.

**Comment by aldarund** [comment] 2020-07-21 22:53
It is intended. You are not supposed to really run build on server for any production grade app. Use ci/cd, docker, etc

**Comment by frontwero** [comment] 2020-07-27 06:27
I walked in the same issue (kind of) with version v2.13.3. If you create a production version of your project (nuxt build) and then run it, it can't find a .xxxxxx.js file in the /dist/commons/ directory, but if you look in the directory the file is there. Maybe it's something with rights because of the dot before the file it's a hidden file. For now, we switched back to v2.13.2

**Comment by danielroe** [comment] 2020-07-27 06:32
@frontwero That is a different issue and will be fixed in 2.14 with https://github.com/nuxt/nuxt.js/pull/7667

**Comment by danielroe** [comment] 2020-07-27 09:57
@jariesdev I'm closing this as this is intended behaviour - but thanks for raising it! Feel free to get in touch on the Discord server if you have any more questions.

**Closed by danielroe** 2020-07-27 09:57 UTC
Labels: bug-report
