### ISSUE TITLE
Add Firebase Custom Server Integration Causing Error

### ISSUE THREAD

**Issue by jefrydco** [nuxt/nuxt.js#2844] opened 2018-02-17 06:27 UTC
I tried to restructure the Nuxt project folder so that it can be deployed to Firebase, take a look this repository [Nuxt Firebase Vuetify](https://github.com/jefrydco/nuxt-firebase-vuetify).

Everything is working fine, but a problem occurred when I use custom component from UI framework like Vuetify. The browser console displays an error like this,

> The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside &lt;p&gt;, or missing . Bailing hydration and performing full client-side render.

I changed `buildDir` config to `../functions/.nuxt` so that it can be run inside `functions` directory. And I think this is the cause. Any idea or maybe I missed some configuration on that project?

Btw, that project is generated by `create-nuxt-app` that I have modified, take a look also to this pull request, [Add Firebase Custom Server Integration](https://github.com/nuxt-community/create-nuxt-app/pull/37)

**Comment by jefrydco** [comment] 2018-02-19 14:29
Any idea sir @Atinux? :smile:

**Comment by Atinux** [comment] 2018-02-19 14:36
Actually I let @posva help you on this, I have no experience on Firebase and he is the author of VueFire and VuexFire.

**Comment by jefrydco** [comment] 2018-02-19 14:58
Hi @Atinux 

Thanks for replying, it seems not the problem with Firebase itself. My point is if I made custom location for `buildDir`, it can't recognize third party custom component like Vuetify.

On my repo above, I made the buildDir into `../funtions/.nuxt` when I run dev it display an error like this,

![error](https://user-images.githubusercontent.com/20434351/36383219-145c4564-15be-11e8-8cf6-5e7a5f1784b7.png)

![error](https://user-images.githubusercontent.com/20434351/36383814-e911cd1e-15bf-11e8-9a0b-a02a42fcfde0.png)

At the first second of loaded page, it render the Vuetify normally and the next second it display an error like that. I also has include node_modules which contains all dependencies for Nuxt and Vuetify in that folder.

**Comment by Atinux** [comment] 2018-02-19 15:10
You may want to use the `modulesDir` property to specify where is the `node_modules` directory.

It would ne better if you can provide a small reproduction link to GitHub so we can investigate on the issue.

**Comment by jefrydco** [comment] 2018-02-19 15:13
I've included the reproduction project above sir, this is the link https://github.com/jefrydco/nuxt-firebase-vuetify

**Comment by posva** [comment] 2018-02-19 15:19
If you're using Vuetify, make sure you're correctly using their components, some of them requires some special treatment for SSR to work correctly 🙂

**Comment by jefrydco** [comment] 2018-02-19 15:23
I used components and layout copied from https://github.com/vuetifyjs/nuxt, I also have tried custom project from that repo too, but it still didn't worked.

**Comment by husayt** [comment] 2018-03-08 16:25
Closing this, as it is not nuxt issue, but rather vuetify related.

**Closed by husayt** 2018-03-08 16:25 UTC

**Comment by WeAspireDev** [comment] 2018-09-09 10:26
I request you to open this issue and please give me the direction.

I think this is more about nuxt configuration than vuetify, because if you try to view page source one can see the vuetify components are rendered correctly but then client side doesn't understand these component so it can not convert these component to html which server was able to do.
Now Vue sees two different Dom structure so it throws this error.

Please reconsider opening this issue. 
Thank you!

**Comment by WeAspireDev** [comment] 2018-09-09 12:01
> To my understanding, this issue is caused due to the vue module, which is a dependency of Nuxt, being installed inside the functions folder. When you run Nuxt with the buildDir set to functions/.nuxt and import Vue from 'vue' in your plugins, you get another Vue-class than the one being used by Nuxt. This is a bug in Nuxt, as far as I know.


I got this solution from
https://stackoverflow.com/questions/48839593/nuxt-ssr-with-firebase-integration

Is there any better way to fix this?
