### ISSUE TITLE
error  Generator.afterGenerate (node_modules/@nuxt/generator/dist/generator.js:168:43)

### ISSUE THREAD

**Issue by jjhesk** [nuxt/nuxt.js#6514] opened 2019-10-04 12:29 UTC
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://nolinks](https://nolinks)

### Steps to reproduce

https://bug.nuxtjs.org/ 

Have the same issue as well. Just install 2.10.0 and the problem started acting. Node v10.15.3, and all projects with different nuxt version will have this error message.

### What is expected ?

no errors during compile

### What is actually happening?

stop here

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9863">#c9863</a>)</em></sub></div>

**Comment by jjhesk** [comment] 2019-10-04 12:30
please also refer to report https://github.com/nuxt/nuxt.js/issues/6513

**Comment by benliq** [comment] 2019-10-04 20:30
I encountered the same problem after updating nuxt to 2.10.0 on a project. Then afterGenerate / renderroute problem was triggered on each build in spa mode, and for ALL my local 's nuxtjs projects in spa mode...
I finally solved this by running a "npm clean cache --force" and npm install.
Looks like update to 2.10.0 did corrupt my npm cache.. Hope this helps

**Comment by aldarund** [comment] 2019-10-04 20:32
Try to delete lock file and node modules and reinstall. If the error still happens - please provide a reproduction repo with lock file where this error happens for you.

**Comment by benliq** [comment] 2019-10-04 20:35
I already tried, but deleting lock file and node modules did not work for me, the solution was to use the "npm clean cache"

**Comment by aldarund** [comment] 2019-10-04 20:38
i suggest to use yarn, it has less of this kind of problems

**Comment by benliq** [comment] 2019-10-04 20:43
> i suggest to use yarn, it has less of this kind of problems

yes i confirm, i tried a fresh yarn install and added all my dependencies to test and everything was fine, that's how i found that my package and scripts was correct but, the npm cache was corrupted

**Comment by vinayakkulkarni** [comment] 2019-10-05 11:08
I tried with yarn, same error!

```js
ERROR   /dashboard

TypeError: Cannot read property 'renderRoute' of undefined
    at Generator.generateRoute (/frontend/node_modules/@nuxt/generator/dist/generator.js:222:42)
    at Promise.all.routes.splice.map (/frontend/node_modules/@nuxt/generator/dist/generator.js:120:24)
```

**Comment by aldarund** [comment] 2019-10-05 14:11
@vinayakkulkarni please provide a full reproduction with lock files

**Comment by vinayakkulkarni** [comment] 2019-10-06 13:29
@aldarund : #6519

**Comment by dkade** [comment] 2019-10-07 08:39
Yes same with yarn, removed * nodes-modules and package-lock.json, did a clean yarn install, and when running yarn run build, I get exactly the same error.

**Comment by kajcula** [comment] 2019-10-07 11:03
Instead 'npm run build' use 'npm run generate' - for me works fine

**Comment by jjhesk** [comment] 2019-10-07 13:19
run generate works but we still need to resolve the build issue.

**Comment by jjhesk** [comment] 2019-10-07 13:21
related #6519

**Comment by carlosesquivel-katoo** [comment] 2019-10-07 15:08
Tested with both yarn and npm (deleted node_modules and lock file) build doesn't work

**Comment by aldarund** [comment] 2019-10-08 08:39
@carlosesquivel-katoo if your issue different from https://github.com/nuxt/nuxt.js/issues/6519 please provide a full reproduction

**Comment by vinayakkulkarni** [comment] 2019-10-08 08:42
It's probably the same issue as #6519 @aldarund

**Comment by vinayakkulkarni** [comment] 2019-10-08 08:43
#6514 can be closed after this fix is deployed: https://github.com/nuxt/nuxt.js/commit/136777de1d7924f052c803c6397530de80bdea50

**Comment by carlosesquivel-katoo** [comment] 2019-10-08 09:49
> It's probably the same issue as #6519 @aldarund

It's the same, just emphasizing that using yarn or npm was the same. I'll wait for the fix to be deployed.

Thanks!!!

**Comment by manniL** [comment] 2019-10-08 10:00
Duplicate of https://github.com/nuxt/nuxt.js/issues/6519

**Closed by manniL** 2019-10-08 10:00 UTC
Labels: cmty:bug-report
