### ISSUE TITLE
[nuxt] Error while initializing app DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.

### ISSUE THREAD

**Issue by atmar** [nuxt/nuxt.js#2004] opened 2017-11-01 19:49 UTC
I'm having a lot of trouble getting my dev environment to work in production. The latest error I'm receiving is 
```[nuxt] Error while initializing app DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method."```
 on a specific page when I reload the page ( don't have it while navigating).

```
<template>
  <div class="ui two column stackable grid">
      <div class="ten wide column">
        <div class="ui row requirements">/div>
      </div>
  </div>
</template>
```

The very strange thing is that if I remove the class "ui row requirements", that I don't receive the error anymore. Which results into : 
```
<template>
  <div class="ui two column stackable grid">
    <div class="ten wide column">
    </div>
  </div>
</template>
```

I just use npm run build & npm run start to start the app in production on my live server.
Doing this on my local PC doesn't give me this erorr. Checked both npm, nodejs version & installed packages and they are all the same on both my PC and the live server. 
For what it matters, the live server uses nginx (https://engintron.com/).
I've searched the whole day and can't figure this one out.

**Comment by atmar** [comment] 2017-11-01 22:07
What I didn't mention is that this is a component of a page.
The page itself:
```
<template>
  <div v-if="product" id="product-page">
    <div v-if="product.product_bg" class="top-bg" :style="`background-image: url(${$store.state.imageUrl}${product.product_bg})`"></div>
    <div v-else class="top-bg" :style="`background-image: url(${$store.state.imageUrl}/assets/img/bg/top-bgs/bioshock.jpg)`"></div>

    <div class="row main" style="padding-top:10px">
      <h1 class="page-title product-title">{{ product.name }}</h1>

      <div class="sub-title">{{ $t('pages.product.workson' )}}:
        <span class="platforms_os">
          <i v-if="product.platforms.windows" class="windows icon"></i>
          <i v-if="product.platforms.mac" class="apple icon"></i>
          <i v-if="product.platforms.linux" class="linux icon"></i>
        </span>
        <span>| {{ $t('pages.product.redeemon' )}} {{ product.game_platform }}</span>
      </div>

        <game :product="product" @addCart="addToCartBtn" @addWishlist="addToWishlist" @removeWishlist="removeFromWishlist"></game>

      <recommended-products :products="recommended"></recommended-products>
	 
    </div>
    <v-dialog/>
  </div>
</template>
```

**Comment by atmar** [comment] 2017-11-01 23:32
Another strange this is that if I remove either the <game> or <recommended-products> component, the error is gone.

**Comment by Atinux** [comment] 2017-11-02 11:34
Duplicate of https://github.com/nuxt/nuxt.js/issues/1552

**Closed by Atinux** 2017-11-02 11:34 UTC
