### ISSUE TITLE
Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by mahiraltinkaya** [nuxt/nuxt.js#8619] opened 2021-01-11 12:46 UTC
Hi Guys lately I have been getting the following error frequently. Even if I tried some solutions, it didn't work.
Some;
When I wanted to see the error using SPA mode instead of Universal mode, I encountered a different error.
Changing the memory size for Node did not help.
Error details and configuration settings are shared below.

`{
  "name": "edust",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "node --max-old-space-size=4096 node_modules/nuxt/bin/nuxt.js",
    "build": "node --max-old-space-size=4096 node_modules/nuxt/bin/nuxt.js build",
    "start": "node --max-old-space-size=4096 node_modules/nuxt/bin/nuxt.js start",
    "generate": "nuxt --max-old-space-size=4096 node_modules/nuxt/bin/nuxt.js generate"
  },
  "dependencies": {
    "@nuxtjs/auth-next": "5.0.0-1610115973.9fdaa66",
    "@nuxtjs/axios": "^5.12.2",
    "@nuxtjs/recaptcha": "^0.6.2",
    "core-js": "^3.6.5",
    "nuxt": "^2.14.6",
    "nuxt-i18n": "^6.16.0",
    "swiper": "^6.4.5",
    "v-mask": "^2.2.3",
    "vue-awesome-swiper": "^4.1.1",
    "vue-inner-image-zoom": "^1.0.1",
    "vue-js-toggle-button": "^1.3.3",
    "vue-slick-carousel": "^1.0.6",
    "vue-suggestion": "^1.1.0",
    "vuex-persistedstate": "^4.0.0-beta.2"
  },
  "devDependencies": {
    "@aceforth/nuxt-optimized-images": "^1.4.0",
    "@nuxtjs/google-fonts": "^1.2.0",
    "@nuxtjs/vuetify": "^1.11.2"
  }
}
`

`
{
  "header": {
    "reportVersion": 1,
    "event": "Allocation failed - JavaScript heap out of memory",
    "trigger": "FatalError",
    "filename": "report.20210111.153919.8920.0.001.json",
    "dumpEventTime": "2021-01-11T15:39:19Z",
    "dumpEventTimeStamp": "1610368759861",
    "processId": 8920,
    "cwd": "C:\\Users\\maoth\\Desktop\\edupanya",
    "commandLine": [
      "C:\\Program Files\\nodejs\\node.exe",
      "--max-old-space-size=4096",
      "node_modules/nuxt/bin/nuxt.js"
    ],
    "nodejsVersion": "v12.13.0",
    "wordSize": 64,
    "arch": "x64",
    "platform": "win32",
    "componentVersions": {
      "node": "12.13.0",
      "v8": "7.7.299.13-node.12",
      "uv": "1.32.0",
      "zlib": "1.2.11",
      "brotli": "1.0.7",
      "ares": "1.15.0",
      "modules": "72",
      "nghttp2": "1.39.2",
      "napi": "5",
      "llhttp": "1.1.4",
      "http_parser": "2.8.0",
      "openssl": "1.1.1d",
      "cldr": "35.1",
      "icu": "64.2",
      "tz": "2019a",
      "unicode": "12.1"
    },
    "release": {
      "name": "node",
      "lts": "Erbium",
      "headersUrl": "https://nodejs.org/download/release/v12.13.0/node-v12.13.0-headers.tar.gz",
      "sourceUrl": "https://nodejs.org/download/release/v12.13.0/node-v12.13.0.tar.gz",
      "libUrl": "https://nodejs.org/download/release/v12.13.0/win-x64/node.lib"
    },
    "osName": "Windows_NT",
    "osRelease": "10.0.18363",
    "osVersion": "Windows 10 Home Single Language",
    "osMachine": "x86_64",
    "cpus": [
      {
        "model": "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz",
        "speed": 2394,
        "user": 1079703,
        "nice": 0,
        "sys": 778984,
        "idle": 7566093,
        "irq": 88250
      },
      {
        "model": "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz",
        "speed": 2394,
        "user": 917578,
        "nice": 0,
        "sys": 377593,
        "idle": 8129187,
        "irq": 8250
      },
      {
        "model": "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz",
        "speed": 2394,
        "user": 2083328,
        "nice": 0,
        "sys": 883109,
        "idle": 6457906,
        "irq": 13109
      },
      {
        "model": "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz",
        "speed": 2394,
        "user": 966218,
        "nice": 0,
        "sys": 356687,
        "idle": 8101421,
        "irq": 5906
      },
      {
        "model": "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz",
        "speed": 2394,
        "user": 1413468,
        "nice": 0,
        "sys": 632750,
        "idle": 7378125,
        "irq": 10671
      },
      {
        "model": "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz",
        "speed": 2394,
        "user": 1099781,
        "nice": 0,
        "sys": 601031,
        "idle": 7723531,
        "irq": 6281
      },
      {
        "model": "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz",
        "speed": 2394,
        "user": 1406250,
        "nice": 0,
        "sys": 613968,
        "idle": 7404125,
        "irq": 10328
      },
      {
        "model": "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz",
        "speed": 2394,
        "user": 1048921,
        "nice": 0,
        "sys": 446218,
        "idle": 7929203,
        "irq": 6078
      }
    ],
    "networkInterfaces": [
      {
        "name": "Wi-Fi",
        "internal": false,
        "mac": "60:6c:66:cb:94:0e",
        "address": "fe80::6c24:20b:1fe0:df50",
        "netmask": "ffff:ffff:ffff:ffff::",
        "family": "IPv6",
        "scopeid": 4
      },
      {
        "name": "Wi-Fi",
        "internal": false,
        "mac": "60:6c:66:cb:94:0e",
        "address": "192.168.1.4",
        "netmask": "255.255.255.0",
        "family": "IPv4"
      },
      {
        "name": "Loopback Pseudo-Interface 1",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "::1",
        "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
        "family": "IPv6",
        "scopeid": 0
      },
      {
        "name": "Loopback Pseudo-Interface 1",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "127.0.0.1",
        "netmask": "255.0.0.0",
        "family": "IPv4"
      },
      {
        "name": "vEthernet (WSL)",
        "internal": false,
        "mac": "00:15:5d:4e:c0:d3",
        "address": "fe80::fdf8:b869:1d8b:6ec4",
        "netmask": "ffff:ffff:ffff:ffff::",
        "family": "IPv6",
        "scopeid": 21
      },
      {
        "name": "vEthernet (WSL)",
        "internal": false,
        "mac": "00:15:5d:4e:c0:d3",
        "address": "172.18.15.145",
        "netmask": "255.255.255.240",
        "family": "IPv4"
      }
    ],
    "host": "DESKTOP-MUO3U7U"
  },
  "javascriptStack": {
    "message": "No stack.",
    "stack": [
      "Unavailable."
    ]
  },
  "nativeStack": [
    {
      "pc": "0x00007ff6a0731389",
      "symbol": "std::basic_ostream<char,std::char_traits<char> >::operator<<+10873"
    },
    {
      "pc": "0x00007ff6a07357cc",
      "symbol": "std::basic_ostream<char,std::char_traits<char> >::operator<<+28348"
    },
    {
      "pc": "0x00007ff6a0734778",
      "symbol": "std::basic_ostream<char,std::char_traits<char> >::operator<<+24168"
    },
    {
      "pc": "0x00007ff6a082332b",
      "symbol": "v8::base::CPU::has_sse+37723"
    },
    {
      "pc": "0x00007ff6a1026f4e",
      "symbol": "v8::Isolate::ReportExternalAllocationLimitReached+94"
    },
    {
      "pc": "0x00007ff6a100ef91",
      "symbol": "v8::SharedArrayBuffer::Externalize+833"
    },
    {
      "pc": "0x00007ff6a0edc85c",
      "symbol": "v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436"
    },
    {
      "pc": "0x00007ff6a0ee7c00",
      "symbol": "v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312"
    },
    {
      "pc": "0x00007ff6a0ee4734",
      "symbol": "v8::internal::Heap::PageFlagsAreConsistent+3204"
    },
    {
      "pc": "0x00007ff6a0ed9fc3",
      "symbol": "v8::internal::Heap::CollectGarbage+1283"
    },
    {
      "pc": "0x00007ff6a0ed8794",
      "symbol": "v8::internal::Heap::AddRetainedMap+2356"
    },
    {
      "pc": "0x00007ff6a0ef9a65",
      "symbol": "v8::internal::Factory::NewFillerObject+53"
    },
    {
      "pc": "0x00007ff6a0c66239",
      "symbol": "v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+4057"
    },
    {
      "pc": "0x00007ff6a1452c6d",
      "symbol": "v8::internal::SetupIsolateDelegate::SetupHeap+567949"
    },
    {
      "pc": "0x000001cdb8a8ed4e",
      "symbol": ""
    }
  ],
  "javascriptHeap": {
    "totalMemory": 4335673344,
    "totalCommittedMemory": 4335673344,
    "usedMemory": 4277991784,
    "availableMemory": 56060336,
    "memoryLimit": 4345298944,
    "heapSpaces": {
      "read_only_space": {
        "memorySize": 262144,
        "committedMemory": 262144,
        "capacity": 261872,
        "used": 32296,
        "available": 229576
      },
      "new_space": {
        "memorySize": 33554432,
        "committedMemory": 33554432,
        "capacity": 16759808,
        "used": 32488,
        "available": 16727320
      },
      "old_space": {
        "memorySize": 4093751296,
        "committedMemory": 4093751296,
        "capacity": 4087739624,
        "used": 4075021592,
        "available": 12718032
      },
      "code_space": {
        "memorySize": 4882432,
        "committedMemory": 4882432,
        "capacity": 4132640,
        "used": 4132640,
        "available": 0
      },
      "map_space": {
        "memorySize": 14422016,
        "committedMemory": 14422016,
        "capacity": 10437360,
        "used": 10437360,
        "available": 0
      },
      "large_object_space": {
        "memorySize": 187596800,
        "committedMemory": 187596800,
        "capacity": 187234992,
        "used": 187234992,
        "available": 0
      },
      "code_large_object_space": {
        "memorySize": 1204224,
        "committedMemory": 1204224,
        "capacity": 1100416,
        "used": 1100416,
        "available": 0
      },
      "new_large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 16759808,
        "used": 0,
        "available": 16759808
      }
    }
  },
  "resourceUsage": {
    "userCpuSeconds": 518.343,
    "kernelCpuSeconds": 15.781,
    "cpuConsumptionPercent": 18.0022,
    "maxRss": 4500860928,
    "pageFaults": {
      "IORequired": 3038566,
      "IONotRequired": 0
    },
    "fsActivity": {
      "reads": 14637,
      "writes": 200
    }
  },
  "libuv": [
  ],
  "environmentVariables": {
    "": "C:=C:\\Users\\maoth\\Desktop\\edupanya",
    "ALLUSERSPROFILE": "C:\\ProgramData",
    "APPDATA": "C:\\Users\\maoth\\AppData\\Roaming",
    "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_13140_LMNCKVNUMRLGXZYA",
    "COLORTERM": "truecolor",
    "CommonProgramFiles": "C:\\Program Files\\Common Files",
    "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
    "CommonProgramW6432": "C:\\Program Files\\Common Files",
    "COMPUTERNAME": "DESKTOP-MUO3U7U",
    "ComSpec": "C:\\WINDOWS\\system32\\cmd.exe",
    "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
    "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
    "FPS_BROWSER_USER_PROFILE_STRING": "Default",
    "GIT_ASKPASS": "c:\\Users\\maoth\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\git\\dist\\askpass.sh",
    "HOMEDRIVE": "C:",
    "HOMEPATH": "\\Users\\maoth",
    "INIT_CWD": "C:\\Users\\maoth\\Desktop\\edupanya",
    "LANG": "tr_TR.UTF-8",
    "LOCALAPPDATA": "C:\\Users\\maoth\\AppData\\Local",
    "LOGONSERVER": "\\\\DESKTOP-MUO3U7U",
    "NODE": "C:\\Program Files\\nodejs\\node.exe",
    "NODE_ENV": "development",
    "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"dev\"],\"original\":[\"dev\"]}",
    "npm_config_bin_links": "true",
    "npm_config_ignore_optional": "",
    "npm_config_ignore_scripts": "",
    "npm_config_init_license": "MIT",
    "npm_config_init_version": "1.0.0",
    "npm_config_registry": "https://registry.yarnpkg.com",
    "npm_config_save_prefix": "^",
    "npm_config_strict_ssl": "true",
    "npm_config_user_agent": "yarn/1.22.5 npm/? node/v12.13.0 win32 x64",
    "npm_config_version_commit_hooks": "true",
    "npm_config_version_git_message": "v%s",
    "npm_config_version_git_sign": "",
    "npm_config_version_git_tag": "true",
    "npm_config_version_tag_prefix": "v",
    "npm_execpath": "C:\\Program Files (x86)\\Yarn\\bin\\yarn.js",
    "npm_lifecycle_event": "dev",
    "npm_lifecycle_script": "node --max-old-space-size=4096 node_modules/nuxt/bin/nuxt.js",
    "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
    "npm_package_dependencies_core_js": "^3.6.5",
    "npm_package_dependencies_nuxt": "^2.14.6",
    "npm_package_dependencies_nuxt_i18n": "^6.16.0",
    "npm_package_dependencies_swiper": "^6.4.5",
    "npm_package_dependencies_vuex_persistedstate": "^4.0.0-beta.2",
    "npm_package_dependencies_vue_awesome_swiper": "^4.1.1",
    "npm_package_dependencies_vue_inner_image_zoom": "^1.0.1",
    "npm_package_dependencies_vue_js_toggle_button": "^1.3.3",
    "npm_package_dependencies_vue_slick_carousel": "^1.0.6",
    "npm_package_dependencies_vue_suggestion": "^1.1.0",
    "npm_package_dependencies_v_mask": "^2.2.3",
    "npm_package_dependencies__nuxtjs_auth_next": "5.0.0-1610115973.9fdaa66",
    "npm_package_dependencies__nuxtjs_axios": "^5.12.2",
    "npm_package_dependencies__nuxtjs_recaptcha": "^0.6.2",
    "npm_package_description": "## Build Setup",
    "npm_package_devDependencies__aceforth_nuxt_optimized_images": "^1.4.0",
    "npm_package_devDependencies__nuxtjs_google_fonts": "^1.2.0",
    "npm_package_devDependencies__nuxtjs_vuetify": "^1.11.2",
    "npm_package_name": "edust",
    "npm_package_private": "true",
    "npm_package_readmeFilename": "README.md",
    "npm_package_scripts_build": "node --max-old-space-size=4096 node_modules/nuxt/bin/nuxt.js build",
    "npm_package_scripts_dev": "node --max-old-space-size=4096 node_modules/nuxt/bin/nuxt.js",
    "npm_package_scripts_generate": "nuxt --max-old-space-size=4096 node_modules/nuxt/bin/nuxt.js generate",
    "npm_package_scripts_start": "node --max-old-space-size=4096 node_modules/nuxt/bin/nuxt.js start",
    "npm_package_version": "1.0.0",
    "NUMBER_OF_PROCESSORS": "8",
    "NUXT_ENV_APP_NAME": "Edupanya",
    "NUXT_ENV_BASE_URL": "http://localhost:3900",
    "OneDrive": "C:\\Users\\maoth\\OneDrive",
    "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
    "OS": "Windows_NT",
    "Path": "C:\\Users\\maoth\\AppData\\Local\\Temp\\yarn--1610365792732-0.21366893981763702;C:\\Users\\maoth\\Desktop\\edupanya\\node_modules\\.bin;C:\\Users\\maoth\\AppData\\Local\\Yarn\\Data\\link\\node_modules\\.bin;C:\\Program Files\\libexec\\lib\\node_modules\\npm\\bin\\node-gyp-bin;C:\\Program Files\\lib\\node_modules\\npm\\bin\\node-gyp-bin;C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Yarn\\bin\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Users\\maoth\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\maoth\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\bin;C:\\Users\\maoth\\AppData\\Local\\Yarn\\bin;C:\\Users\\maoth\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\maoth\\AppData\\Roaming\\npm",
    "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC",
    "PROCESSOR_ARCHITECTURE": "AMD64",
    "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 60 Stepping 3, GenuineIntel",
    "PROCESSOR_LEVEL": "6",
    "PROCESSOR_REVISION": "3c03",
    "ProgramData": "C:\\ProgramData",
    "ProgramFiles": "C:\\Program Files",
    "ProgramFiles(x86)": "C:\\Program Files (x86)",
    "ProgramW6432": "C:\\Program Files",
    "PROMPT": "$P$G",
    "PSModulePath": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
    "PUBLIC": "C:\\Users\\Public",
    "SESSIONNAME": "Console",
    "SystemDrive": "C:",
    "SystemRoot": "C:\\WINDOWS",
    "TEMP": "C:\\Users\\maoth\\AppData\\Local\\Temp",
    "TERM_PROGRAM": "vscode",
    "TERM_PROGRAM_VERSION": "1.53.0-insider",
    "TMP": "C:\\Users\\maoth\\AppData\\Local\\Temp",
    "USERDOMAIN": "DESKTOP-MUO3U7U",
    "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-MUO3U7U",
    "USERNAME": "maoth",
    "USERPROFILE": "C:\\Users\\maoth",
    "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\maoth\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
    "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\maoth\\AppData\\Local\\Programs\\Microsoft VS Code Insiders\\Code - Insiders.exe",
    "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-88134f38aa-sock",
    "VUE_ENV": "server",
    "windir": "C:\\WINDOWS",
    "YARN_WRAP_OUTPUT": "false",
    "_applied": "true",
    "_AXIOS_BASE_URL_": "http://localhost:9091/api/ecommerce"
  },
  "sharedObjects": [
    "C:\\Program Files\\nodejs\\node.exe",
    "C:\\WINDOWS\\SYSTEM32\\ntdll.dll",
    "C:\\WINDOWS\\System32\\KERNEL32.DLL",
    "C:\\WINDOWS\\System32\\KERNELBASE.dll",
    "C:\\WINDOWS\\System32\\WS2_32.dll",
    "C:\\WINDOWS\\System32\\RPCRT4.dll",
    "C:\\WINDOWS\\SYSTEM32\\dbghelp.dll",
    "C:\\WINDOWS\\System32\\ADVAPI32.dll",
    "C:\\WINDOWS\\System32\\ucrtbase.dll",
    "C:\\WINDOWS\\System32\\msvcrt.dll",
    "C:\\WINDOWS\\System32\\sechost.dll",
    "C:\\WINDOWS\\System32\\USER32.dll",
    "C:\\WINDOWS\\System32\\win32u.dll",
    "C:\\WINDOWS\\System32\\GDI32.dll",
    "C:\\WINDOWS\\System32\\gdi32full.dll",
    "C:\\WINDOWS\\System32\\msvcp_win.dll",
    "C:\\WINDOWS\\System32\\PSAPI.DLL",
    "C:\\WINDOWS\\System32\\CRYPT32.dll",
    "C:\\WINDOWS\\System32\\MSASN1.dll",
    "C:\\WINDOWS\\SYSTEM32\\IPHLPAPI.DLL",
    "C:\\WINDOWS\\System32\\bcrypt.dll",
    "C:\\WINDOWS\\SYSTEM32\\USERENV.dll",
    "C:\\WINDOWS\\System32\\profapi.dll",
    "C:\\WINDOWS\\SYSTEM32\\WINMM.dll",
    "C:\\WINDOWS\\SYSTEM32\\winmmbase.dll",
    "C:\\WINDOWS\\System32\\cfgmgr32.dll",
    "C:\\WINDOWS\\System32\\bcryptPrimitives.dll",
    "C:\\WINDOWS\\System32\\IMM32.DLL",
    "C:\\WINDOWS\\System32\\powrprof.dll",
    "C:\\WINDOWS\\System32\\UMPDC.dll",
    "C:\\WINDOWS\\system32\\uxtheme.dll",
    "C:\\WINDOWS\\System32\\combase.dll",
    "C:\\WINDOWS\\system32\\mswsock.dll",
    "C:\\WINDOWS\\System32\\kernel.appcore.dll",
    "C:\\WINDOWS\\SYSTEM32\\CRYPTBASE.DLL",
    "C:\\WINDOWS\\System32\\NSI.dll",
    "C:\\WINDOWS\\SYSTEM32\\dhcpcsvc6.DLL",
    "C:\\WINDOWS\\SYSTEM32\\dhcpcsvc.DLL",
    "C:\\WINDOWS\\SYSTEM32\\DNSAPI.dll",
    "C:\\WINDOWS\\system32\\napinsp.dll",
    "C:\\WINDOWS\\system32\\pnrpnsp.dll",
    "C:\\WINDOWS\\system32\\wshbth.dll",
    "C:\\WINDOWS\\system32\\NLAapi.dll",
    "C:\\WINDOWS\\System32\\winrnr.dll",
    "C:\\Windows\\System32\\rasadhlp.dll",
    "C:\\WINDOWS\\System32\\fwpuclnt.dll"
  ]
}`

**Comment by danielroe** [comment] 2021-01-11 16:41
@mahiraltinkaya Given that you are using Vuetify, this is likely a duplicate of #7855 - you might try the workaround in https://github.com/nuxt/nuxt.js/issues/7855#issuecomment-747007353.

If that doesn't solve things for you, would you set up a minimal reproduction on GitHub so we can look into this for you?

**Comment by mahiraltinkaya** [comment] 2021-01-11 16:53
> @mahiraltinkaya Given that you are using Vuetify, this is likely a duplicate of #7855 - you might try the workaround in [#7855 (comment)](https://github.com/nuxt/nuxt.js/issues/7855#issuecomment-747007353).
> 
> If that doesn't solve things for you, would you set up a minimal reproduction on GitHub so we can look into this for you?

Thank you @danielroe . 

I added the following lines. I will give information if I meet again. Thanks for your interest

`
 hooks: {
    'build:done'() {
      const modulesToClear = ['vue', 'vue/dist/vue.runtime.common.prod']
      modulesToClear.forEach((entry) => {
        delete require.cache[require.resolve(entry)]
      })
    },
  },
`

**Comment by danielroe** [comment] 2021-01-11 17:45
@mahiraltinkaya Great. I'll close this issue. Feel free to submit a new issue with a reproduction if it persists.

**Closed by danielroe** 2021-01-11 17:45 UTC
