### ISSUE TITLE
ExtractCSS to a single named file

### ISSUE THREAD

**Issue by mauxtin** [nuxt/nuxt.js#4926] opened 2019-02-01 20:16 UTC
### Version

[v2.4.1](https://github.com/nuxt.js/releases/tag/v2.4.1)

### Reproduction link

[https://codesandbox.io/s/wqwo31xz9l](https://codesandbox.io/s/wqwo31xz9l)

### Steps to reproduce

Just use this inside the build property
```
    extractCSS: true,

    optimization: {
      splitChunks: {
        cacheGroups: {
          styles: {
            name: "styles",
            test: /\.(css|vue)$/,
            chunks: "all",
            enforce: true
          }
        }
      }
    },

    filenames: {
      app: "[name].js?id=[chunkhash]",
      chunk: "[name]_vendor.js?id=[chunkhash]",
      css: "[name].css?id=[contenthash]"
    }
```

### What is expected ?

To extract all css to a single file and a certain name.

### What is actually happening?

Cannot find module 'pages/index_vendor.js?id=a263682744874cd3572a' from '/sandbox'

### Additional comments?

The goal is to always have a certain filename for my app and css with question mark hash to reload the file when updating. (This is the Laravel Mix default as well)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8591">#c8591</a>)</em></sub></div>

**Comment by mauxtin** [comment] 2019-02-01 20:19
Related: https://github.com/nuxt/nuxt.js/issues/3387, https://github.com/nuxt/nuxt.js/pull/4073

**Comment by manniL** [comment] 2019-02-12 14:08
Duplicate of #5006

**Closed by manniL** 2019-02-12 14:08 UTC
Labels: :clock1:Pending, cmty:bug-report
