### ISSUE TITLE
Allow possibility to change/remove div id=__layout and div id=__nuxt

### ISSUE THREAD

**Issue by 555ea** [nuxt/nuxt.js#3811] opened 2018-08-28 16:50 UTC
### What problem does this feature solve?

Readability of output html is sacrificed, since even if you put simplest implementation in default layout file you will have extra div's created
```
<template>
  <main><nuxt/></main>
</template>
```
will result in
```
<body data-n-head="">
  <div id="__nuxt">
    <div class="nuxt-progress"></div>
      <div id="__layout">
        <main>
          <div data-v-1b011d9c="">
            Hello!
          </div>
        </main>
      </div>
    </div>
</div>
```
I want to be able to remove extra div's like id="__nuxt" class="nuxt-progress" id="__layout" so that the output html is more readable to search engines and was easier to read.

### What does the proposed changes look like?

Since we already have possibility to override document, we should have more control on that like
```
<!DOCTYPE html>
<html {{ HTML_ATTRS }}>
  <head>
    {{ HEAD }}
  </head>
  <body {{ BODY_ATTRS }}>
    {{ APP }}
  </body>
</html>
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7645">#c7645</a>)</em></sub></div>

**Comment by manniL** [comment] 2018-08-31 17:05
Duplicate of https://github.com/nuxt/nuxt.js/issues/3811

**Closed by manniL** 2018-08-31 17:05 UTC
Labels: cmty:feature-request
