### ISSUE TITLE
error page layout not correctly applied

### ISSUE THREAD

**Issue by saeed-darestany** [nuxt/nuxt.js#5654] opened 2019-05-04 21:11 UTC
hi 
 "nuxt": "^2.4.0"

 my error component in layouts directory :

```
<template>
    <div class="__nuxt-error-page">
        <div class="error">
            {{message}}
        </div>
    </div>
</template>

<script>
    export default {
        layout: 'empty',
        name: 'error',
        props: {
            error: {
                type: Object,
                default: null
            }
        },

        computed: {
            statusCode() {
                return (this.error && this.error.statusCode) || 500
            },
            message() {
                return this.error.message || `Error`
            }
        }
    }
</script>
```

and empty layout : 

```

<template>
    <nuxt/>
</template>

<script>

    export default {
        name: "empty",
    }
</script>
```

but when i have error , error component use another layout .. for example, when I'm on the dashboard layout  and an error occurs, error component mount on dashboard layout

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9154">#c9154</a>)</em></sub></div>

**Comment by saeed-bagheri** [comment] 2019-05-31 08:53
hellooooo

**Comment by KleinMaximus** [comment] 2019-09-17 21:56
I have the same problem with v2.9.2

**Comment by KleinMaximus** [comment] 2019-09-17 21:58
@saeed-bagheri Have you found any solution for this?

**Comment by Tinayu0915** [comment] 2019-09-23 02:36
same question

**Comment by manniL** [comment] 2019-09-28 09:17
Duplicate of https://github.com/nuxt/nuxt.js/issues/2537

**Closed by manniL** 2019-09-28 09:17 UTC
Labels: cmty:question
