### ISSUE TITLE
nuxt.renderRoute hangs forever

### ISSUE THREAD

**Issue by p1pchenk0** [nuxt/nuxt.js#4144] opened 2018-10-18 13:28 UTC
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://github.com/p1pchenk0/nuxt-render-route-hangs](https://github.com/p1pchenk0/nuxt-render-route-hangs)

### Steps to reproduce

Please, read README.md file

### What is expected ?

`nuxt.renderRoute('/')` promise should be resolved

### What is actually happening?

app is hanging

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7998">#c7998</a>)</em></sub></div>

**Comment by p1pchenk0** [comment] 2018-10-18 13:45
Looks like this can be related to `ava` framework as if I do all building logic in simple file:
```javascript
const { Nuxt, Builder } = require('nuxt')

async function init() {
  let nuxt = new Nuxt({
    dev: false,
    mode: 'universal'
  })

  console.log('building')

  await new Builder(nuxt).build()

  console.log('built')

  await nuxt.listen(4000, 'localhost')

  console.log('listening...')

  const res = await nuxt.renderRoute('/')

  console.log(res)
}

init()
```

**Comment by manniL** [comment] 2018-10-18 14:53
@p1pchenk0 Thanks for sharing. closing this as not a bug then.

**Closed by manniL** 2018-10-18 14:53 UTC
Labels: cmty:bug-report
