### ISSUE TITLE
Setting 'extractCSS' to 'true' invalidates HMR

### ISSUE THREAD

**Issue by levemsan** [nuxt/nuxt.js#5386] opened 2019-03-26 13:00 UTC
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[CodeSandbox](https://codesandbox.io/s/v0j50l7rv7)

### Steps to reproduce

- Create new nuxt@^2.5.0
- Set extractCSS to true in the build property of nuxt.config.js

### What is expected ?

To work and reload style as expected

### What is actually happening?

The style does not change until the page is refreshed manually

### Additional comments?

- I have used 2.4.3 previously and everything worked like a charm
- When 'extractCSS' is not set, there is no problem

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8933">#c8933</a>)</em></sub></div>

**Comment by AndrewBogdanovTSS** [comment] 2019-03-26 14:23
Additionally `extractCSS` also brakes SourceMaps 
https://cmty.app/nuxt/nuxt.js/issues/c8936

**Comment by manniL** [comment] 2019-03-26 14:28
duplicate of #5390

**Closed by manniL** 2019-03-26 14:28 UTC
Labels: cmty:bug-report
