### ISSUE TITLE
Wrong layoutName

### ISSUE THREAD

**Issue by usb248** [nuxt/nuxt.js#7567] opened 2020-06-19 20:14 UTC
### Version

[v2.13.0](https://github.com/nuxt.js/releases/tag/v2.13.0)

### Reproduction link

[https://u1rpq.sse.codesandbox.io/](https://u1rpq.sse.codesandbox.io/)

### Steps to reproduce

Go to an error page (ex: https://u1rpq.sse.codesandbox.io/not-found), open your debug console, click on home link, see wrong layout. Do hard refresh (F5), layoutName is good now (SSR ok)...
It can be related to https://github.com/nuxt/nuxt.js/issues/5703, https://github.com/nuxt/nuxt.js/issues/7554....

### What is expected ?

layoutName should be : `front`

### What is actually happening?

layoutName value is: `default`, it displays `default` layout instead of `front` layout

### Additional comments?

I use layoutName in order to stylize, it's a very big issue which break all my app.....
I'm missing something ?

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10812">#c10812</a>)</em></sub></div>

**Comment by syropian** [comment] 2020-06-20 15:28
I'm also running into this, client-side renders only seem to render the default layout, while server-side renders seem to correctly render whatever is passed to the `layout` option.

**Comment by usb248** [comment] 2020-06-20 21:07
layoutName is always `default` even if `default.vue` layout doesn't exist. It's totally buggy...

**Comment by fikrivoxel** [comment] 2020-06-21 14:09
i think its version v2.13.0 make bug layout, maybe downgrade or wait for fix bug

**Comment by galvez** [comment] 2020-06-21 15:53
@usb248 thanks for the report, I'm looking into it.

**Comment by usb248** [comment] 2020-06-21 16:32
Thx @galvez , I look forward to the fix.

**Comment by Omarillo** [comment] 2020-06-21 20:39
yes, i have the same issue

**Comment by jackiboy** [comment] 2020-06-23 08:42
Same issue with me. The initial server side render uses the correct layout but once you start navigating through the app with client side routing it renders the default layout.
I have rolled back to v2.12.2 for now.

**Comment by Atinux** [comment] 2020-06-23 17:56
Let's closed when v2.13.1 lands, I am really sorry about this regression 😬

**Comment by gnuletik** [comment] 2020-06-24 02:02
Here's another flavour of @taras1313's workaround:
It's based on `nuxt-composition-api` and it handles destination page with another layout name than `'default'`.

```typescript
import {
  defineComponent,
  useContext,
  getCurrentInstance
} from 'nuxt-composition-api'

export default defineComponent ({
  layout: 'fullpage',
  props: {
    error: {
      type: Object,
      required: true
    }
  },
  setup () {
    const { route } = useContext()

    // FIXME: https://github.com/nuxt/nuxt.js/issues/7567
    onBeforeUnmount(() => {
      const vm = getCurrentInstance()
      if (!vm) {
        return
      }
      const matched = route.value.matched[0]
      vm.$nuxt.setLayout((matched?.components?.default as any)?.options?.layout || 'default')
    })
  }
})
```

Hope it helps until v2.13.1 gets released.

Thanks for the fix @Atinux !

**Comment by pi0** [comment] 2020-06-24 08:40
Hi! This should be fixed with [v2.13.1](https://github.com/nuxt/nuxt.js/releases/tag/v2.13.1).

**Comment by jonian** [comment] 2020-06-24 09:46
Hi @pi0, this issue is still present in 2.13.1. Using the workaround from @gnuletik or @taras1313 is not optimal as the layout change is visible (page components are loaded before the layout change). Is there a better workaround?

**Comment by usb248** [comment] 2020-06-24 09:51
There is someone of core team able to fix this issue please ... ?

**Comment by Atinux** [comment] 2020-06-24 10:07
@usb248 you codesandbox is working now with the latest version: https://u1rpq.sse.codesandbox.io/not-found and then navigate to home page

I am not sure to understand what's the issue now 🤔

**Comment by Atinux** [comment] 2020-06-24 10:17
@jonian could you provide a reproduction please?

It works perfectly for us: https://codesandbox.io/s/frosty-fog-homlr

**Comment by jonian** [comment] 2020-06-24 11:55
@Atinux, reproduction at https://codesandbox.io/s/fervent-hoover-bq5nq. I can also reproduce this with a new app locally. Home and About pages use the `default` layout. Error page/layout uses the `empty` layout.

What fixes the issue for me is replacing https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/client.js#L612

```js
if (this._hadError) {
  Vue.nextTick(() => {
    this.setLayout(layout)
  })
} else {
  this.setLayout(layout)
}
```

**Comment by jonian** [comment] 2020-06-24 12:21
@Atinux, when error page uses the `default` layout and Home, About use the `front` layout, it works as expected. Reproduction at https://codesandbox.io/s/pensive-glade-hkpfl. So it looks that the issue occurs when assigning a layout to the error page.

**Comment by piecedata** [comment] 2020-06-25 11:54
I do also have like @jonian

Homepage is using orange layout, error page is using empty layout. When I hit go to homepage link the layout is not updated to orange but remains empty. Im using nuxt 2.13.1

If I do not assign a layout to the error page, everything works as expected.

**Comment by pi0** [comment] 2020-06-25 12:00
Bug still exists. The issue is that [setLayout](https://github.com/nuxt/nuxt.js/blob/415d4083ca489d5e2e07d514e7fb6e01ad33e5dd/packages/vue-app/template/App.js#L48) is being called for error layout when navigating to `404` to `/`

![image](https://user-images.githubusercontent.com/5158436/85715832-235c2580-b6ec-11ea-8696-f459f91f65a3.png)

We are working to find a fix :)

**Comment by pi0** [comment] 2020-06-26 19:08
Hi. This should be (finally) fixed with [v2.13.2](https://github.com/nuxt/nuxt.js/releases/tag/v2.13.2) apologizes for all inconveniences due to this bug.

**Comment by usb248** [comment] 2020-06-26 21:38
Thanks, it's ok for me

**Comment by jonian** [comment] 2020-06-30 09:39
@pi0, @Atinux, PR #7606 causes wrong error layout when there are errors after the route is mounted (eg. 500 errors).

Reproduction at https://codesandbox.io/s/affectionate-johnson-1bzfy, error pages should use the `empty` layout, all other pages should use the `default` layout.

**Closed** 2020-07-02 16:22 UTC
Labels: available soon, bug-report
