### ISSUE TITLE
Nuxt.js cuts some css styles.

### ISSUE THREAD

**Issue by OperKH** [nuxt/nuxt.js#4555] opened 2018-12-14 16:12 UTC
### Version

[v2.3.4](https://github.com/nuxt.js/releases/tag/v2.3.4)

### Reproduction link

[https://github.com/OperKH/nuxt-css-bug](https://github.com/OperKH/nuxt-css-bug)

### Steps to reproduce

git clone https://github.com/OperKH/nuxt-css-bug.git
cd nuxt-css-bug
npm i
npm run devnpm run dev

### What is expected ?

div.text-start and div.text-end should have styles "text-align: start;" and "text-align: end;".
And "text-end" text should be on the right side, same as "text-right"

### What is actually happening?

Nuxt.js cuts "text-align: start;" and "text-align: end;" styles on dev and build.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8311">#c8311</a>)</em></sub></div>

**Comment by manniL** [comment] 2018-12-17 11:20
Reproducible with SSR and SPA mode

Can't reproduce with Vue only template.

**Comment by devyaz** [comment] 2018-12-19 20:04
here is how i do it in my Nuxt app served to ElectronJs
in your nuxt.config.js
``css: [
    '@/assets/css/global.css','@/assets/font-awesome-4.6.3/css/font-awesome.min.css','@assets/css/w3.css'
  ], ``  or your own CSS file in the assets folder this makes it global so you can call from anywhere
am using [w3.css](https://www.w3schools.com/w3css/) and font awesome its like bootstrap only easier and i can say in your case
```
<template>
  <div class="w3-row">
    <div class="w3-left">text-left</div>
    <div class="w3--center">text-center</div>
    <div class="tw3-right">text-right</div>
    <div class="w3-top">text-start</div>
    <div class="w3-bottom">text-end</div>
  </div>
</template>
```
 try and scope your css if you like which you have done in your example
``<style scoped>
</style>
``  if you don't want to go my way

**Comment by manniL** [comment] 2019-01-12 01:36
So, some more background!

The CSS will be converted and autoprefixed to:

```css
.text-left{text-align:left}
.text-center{text-align:center}
.text-right{text-align:right}
[dir=ltr] .text-start{text-align:left}
[dir=ltr] .text-end, [dir=rtl] .text-start{text-align:right}
[dir=rtl] .text-end{text-align:left}
```

Without setting the dir (via nuxt.config.js) the CSS won't properly work.

```js
export default {
 head: {
    htmlAttrs: {
      dir: 'ltr'
    }
  }
}

**Comment by manniL** [comment] 2019-01-12 02:00
(Closing here as the root cause is resolves)

**Closed by manniL** 2019-01-12 02:00 UTC
Labels: :clock1:Pending, cmty:bug-report

**Comment by OperKH** [comment] 2019-01-14 16:07
> So, some more background!
> 
> The CSS will be touched by Autoprefixer because **IE and Edge** both dont support `text-start`/`text-end` ([source](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align#Browser_compatibility)). The "transpiled" version will look like:
> 
> ```css
> .text-left{text-align:left}
> .text-center{text-align:center}
> .text-right{text-align:right}
> [dir=ltr] .text-start{text-align:left}
> [dir=ltr] .text-end, [dir=rtl] .text-start{text-align:right}
> [dir=rtl] .text-end{text-align:left}
> ```
> 
> Without setting the `dir` attribute to your HTML tag _or_ changing the minimum supported browser version (both via nuxt.config.js) the CSS won't properly work.
> 
> PS: I filed a PR to add `dir: ltr` as default.
> 
> ```js
> export default {
>  head: {
>     htmlAttrs: {
>       dir: 'ltr'
>     }
>   }
> }
> ```

@manniL, why I can't reproduce it on https://autoprefixer.github.io/ ?

**Comment by manniL** [comment] 2019-01-14 16:10
@OperKH ![](https://user-images.githubusercontent.com/640208/51072096-1318cd80-1653-11e9-8304-4c4875c8f2f9.png)
