### ISSUE TITLE
Module parse failed: webpackChunkName, loader, ... ?

### ISSUE THREAD

**Issue by lukasborawski** [nuxt/nuxt.js#5120] opened 2019-02-26 14:08 UTC
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[local](local)

### Steps to reproduce

Regular procedure to install the app locally:

```
npm i
npm run dev
```

### What is expected ?

Regular app build.

### What is actually happening?

Got an error during the dev build:

```
Module parse failed: Unexpected token (6:24)                                               friendly-errors 15:04:50
You may need an appropriate loader to handle this file type.
|
| var _5e2a29cc = function _5e2a29cc() {
>   return interopDefault(import('../pages/discussions/index.vue'
|   /* webpackChunkName: "pages/discussions/index" */
|   ));
                                                                                           friendly-errors 15:04:50
 @ ./.nuxt/index.js 8:0-43 76:19-31
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
```

Screenshoot of my actual tree:
<img width="276" alt="zrzut ekranu 2019-02-26 o 15 10 34" src="https://user-images.githubusercontent.com/1003999/53418742-c574dc00-39d8-11e9-8fe4-9a6286f3dbcb.png">

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8736">#c8736</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-02-26 14:23
Duplicate of #4839

**Closed by manniL** 2019-02-26 14:23 UTC
Labels: cmty:bug-report
