### ISSUE TITLE
Running nuxt generate works once, then causes 403 errors

### ISSUE THREAD

**Issue by sarahdayan** [nuxt/nuxt.js#5141] opened 2019-03-02 14:49 UTC
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://github.com/dinerojs/dinerojs.com](https://github.com/dinerojs/dinerojs.com)

### Steps to reproduce

- Install and run the API from [this repository](https://github.com/dinerojs/docs).
- Install and run the Nuxt-powered website from [this repository](https://github.com/dinerojs/dinerojs.com).
- Try running `yarn generate` once.
- Once the first generation has finished, try running `yarn generate` a second time.
- Potentially, try to run `yarn dev`.

### What is expected ?

I would expect the website to generate a second time without any issues, like on the first time.

Same when trying to serve the website locally after generating a first time, I expect it to run without any issues.

### What is actually happening?

 Generating the website a second time raises a bunch of 403 errors.

Same when trying to serve the website locally after generating a first time, this returns 403 errors at runtime.

### Additional comments?

Thanks for the hard work on this great framework!

I tried investigating this error but had no luck. The API running on port 4000 still works when getting the 403 errors, so the problem is unlikely to be on this front. I also tried clearing `/dist`, no success.

The problem disappears whenever I restart my computer, so I figure there's a faulty process somewhere that is still running, but I couldn't pinpoint which and where.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8762">#c8762</a>)</em></sub></div>

**Comment by pi0** [comment] 2019-03-02 20:00
Hi @sarahdayan. I've locally tried the build process. The problem is originating when `nuxtServerInit` tries to fetch releases from Github API which throws 403 error. Expect a PR soon for fix :)

**Comment by sarahdayan** [comment] 2019-03-02 20:23
Oooooh I totally forgot about the GitHub API. Thanks a lot for investigating (and the upcoming PR) 🙂

**Comment by manniL** [comment] 2019-03-02 20:31
Closing here as the issue has been resolved :relaxed:

**Closed by manniL** 2019-03-02 20:31 UTC
Labels: cmty:bug-report
