### ISSUE TITLE
use async code in beforeRouteEnter hook,it throw some error

### ISSUE THREAD

**Issue by ytudt** [nuxt/nuxt.js#3029] opened 2018-03-15 08:36 UTC
<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2627">#c2627</a>)</em></sub></div>

**Comment by ytudt** [comment] 2018-03-15 08:38
i fetch date in beforeRouteEnter,when and 'next()' when date is back.like below
   beforeRouteEnter(to, from, next) {
      axios.get(`https://kf.dianping.com/api/relations/listRecommendRelation`,{
        params: {
          bu: '美食',
          orderType: 'dealOrder',
          orderId: 4252500185,
          orderIdStr: "4252500185",
          userId: 787514285,
          subSource: "MT_APP",
          visitId: "480e6383-a8f7-40fb-b00c-bf85a1f16f6b"
        }
      })
        .then((res) => {
          next();
        });
    },

then vue warn like  'vue.runtime.esm.js:587 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.' 
what shoule i do?

**Comment by husayt** [comment] 2018-03-15 10:40
There is not enough detail here to be able to help you and also it is not really clear. The problem is not in the code you shared, but somewhere else.

**Comment by ytudt** [comment] 2018-03-17 10:08
when i use async code in beforeRouteEnter i can get the warn information like below
`  beforeRouteEnter(to, from , next){
      setTimeout(() => {
        next()
      }, 100)
    }`
<img width="1042" alt="1" src="https://user-images.githubusercontent.com/16434007/37554045-0005eb1a-2a0e-11e8-9597-139bbdda79f4.png">

**Comment by husayt** [comment] 2018-04-05 09:19
@ytudt still there is no enough detail to help you

**Comment by galvez** [comment] 2018-08-26 10:38
Closing this as there's been no updates over 90 days.

**Closed by galvez** 2018-08-26 10:38 UTC
