### ISSUE TITLE
Cannot use outer scope variables in router.scrollBehavior of nuxt.config.js

### ISSUE THREAD

**Issue by neutron63zf** [nuxt/nuxt.js#6182] opened 2019-08-04 17:49 UTC
### Version

[v2.8.1](https://github.com/nuxt.js/releases/tag/v2.8.1)

### Reproduction link

[https://github.com/neutron63zf/nuxt-config-variable-scope-repro](https://github.com/neutron63zf/nuxt-config-variable-scope-repro)

### Steps to reproduce

1. Run `yarn install && yarn dev`
2. Click `Test` button.

### What is expected ?

Page changes with console output `external function executed`

### What is actually happening?

Error page appears with console error `ReferenceError: someFunction is not defined`

### Additional comments?

It is very unusual behavior since it seems we cannot access variables in outer scope in router.scrollBehavior.
It's impossible to import and use outer functions in the config.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9600">#c9600</a>)</em></sub></div>

**Comment by manniL** [comment] 2019-08-07 08:20
Duplicate of https://github.com/nuxt/nuxt.js/issues/3767

**Closed by manniL** 2019-08-07 08:20 UTC
Labels: cmty:bug-report
