### ISSUE TITLE
Fresh install with Bootstrap crash at first run

### ISSUE THREAD

**Issue by Torone** [nuxt/nuxt.js#5822] opened 2019-05-27 16:41 UTC
### Version

[2.7.1](https://github.com/nuxt.js/releases/tag/2.7.1)

### Reproduction link

[http://localhost:3000/](http://localhost:3000/)

### Steps to reproduce

npx create-nuxt-app <project-name>

Go through the options by selecting Bootstrap, I also picked up Express Server, PWA, Axios, Jest and Universal app.

Run the app... Error.

### What is expected ?

TO see the initial nuxt page using Bootstrap-vue

### What is actually happening?

Error: SyntaxError. Unexpected identifier

### Additional comments?

Nothing to add, it is very easy to reproduce, I tried 3 different fresh installs, tried to load bootstrap-vue as a plugin, nothing worked.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9275">#c9275</a>)</em></sub></div>

**Comment by chettapong** [comment] 2019-05-27 17:28
I try downgrade bootstrap-vue to 2.0.0-rc.20 is work.

**Comment by pi0** [comment] 2019-05-27 17:36
Hi. We are investigating this with BootstrapVue core team. `es/` build now uses `export` syntax which seems unsupported by webpack when file is in `node_modules`!

**Comment by tmorehouse** [comment] 2019-05-28 03:55
BootstrapVue 2.0.0-rc.21 will be released shortly with the new fix.

**Comment by pimlie** [comment] 2019-06-05 16:23
Closing this as Bootstrap-vue rc.22 has been released and with rc.22 I cant reproduce the error anymore

**Closed by pimlie** 2019-06-05 16:23 UTC
Labels: cmty:bug-report, waiting for dependency
