### ISSUE TITLE
Layout not applied when middleware redirects to a page with different layout

### ISSUE THREAD

**Issue by JiriChara** [nuxt/nuxt.js#389] opened 2017-03-15 09:04 UTC
Hi,

I have an application with an authentication middleware that redirects user to a login page whenever she tries to access a restricted page. When I click on a link for a first time (from the default layout) then I am redirected to login page with a correct layout, but when I click on the link again (from the login layout), then I am redirected to login page with default layout applied, but it should use  login layout.

Simplified version of `middleware/auth.js`:
```js
export default function ({ route, redirect }) {
  if (route.name === 'secret') {
    redirect('/login');
  }
});
```

`layout/default.vue`:
```vue
<template>
  <div>
    <p>This is default layout</p>
    <router-link to="secret">Secret</router-link>
  </div>
</template>
```

`layout/login.vue`:
```vue
<template>
  <div>
    <p>This is login layout</p>
    <router-link to="secret">Secret</router-link>
  </div>
</template>
```

`pages/login.js`:
```vue
<template>
  <div>This is login page</div>
</template>

<script>
  export default {
    layout: 'login'
  };
</script>
```

`pages/secret.vue`:
```vue
<template>
  <div>
    <!-- uses default layout -->
    <p>Secret</p>
  </div>
</template>
```

`pages/index.vue`:
```vue
<template>
  <div>
    <p>Index</p>
  </div>
</template>
```

**Comment by JiriChara** [comment] 2017-03-15 09:09
Here is a screencast describing the current behavior: https://www.screencast.com/t/79ZUqxAXc59H

**Comment by skilFullGH** [comment] 2017-03-16 08:29
I'm not called middleware when redirect to pages with another layout from error layout

**Comment by JiriChara** [comment] 2017-03-16 13:35
Yes, you are right that seems to be an another bug - middleware is not called when navigating from the error layout to restricted page using <nuxt-link>

**Comment by Atinux** [comment] 2017-03-16 19:59
Hi @JiriChara @skilFullGH 

The middleware not called when navigating from the error layout will be fixed in the next release.

I could not reproduce your error @JiriChara 

Do you mind forking https://gomix.com/#!/project/nuxt-hello-world and trying to reproduce your behavior?

**Comment by JiriChara** [comment] 2017-03-17 11:14
I am not able to make layouts to work here: https://glitch.com/edit/#!/brainy-apparatus

However here is a repo where you can reproduce the bug: https://github.com/JiriChara/nuxt-middleware Just click on the link to the secret page 2 times. Login page will have a wrong layout then

**Comment by Atinux** [comment] 2017-03-17 14:29
Thank you for the reproduction @JiriChara, indeed, it does not work as expected in the last release.

Good news, I tried your example with the `0.10` and everything works as expected 🎊 

![screenflow](https://cloud.githubusercontent.com/assets/904724/24047559/633b4bba-0b26-11e7-8dcf-ed5532899ac1.gif)

I'll keep this issue open until the 0.10 release is out!

**Comment by JiriChara** [comment] 2017-03-17 15:37
Awesome! Can't wait for the next release :tada:

**Comment by Atinux** [comment] 2017-03-24 18:09
The [0.10](https://github.com/nuxt/nuxt.js/releases/tag/v0.10.0) release it out ✋

**Closed by Atinux** 2017-03-24 18:09 UTC
Labels: available soon, bug
