### ISSUE TITLE
Make '@' alias configurable 

### ISSUE THREAD

**Issue by AngelWayfarer** [nuxt/nuxt.js#5649] opened 2019-05-03 10:24 UTC
### What problem does this feature solve?

I have a project with huge codebase and we already use '@'
nuxt app folder will be used inside the main codebase so I need to use another alias like '@@' 
@ - for old code root
@@ - for new nuxt folder

Now '@' is hardcoded in the template folder:
For example middleware.js:
```
const middleware = {}
<% middleware.forEach(m => {
   const name = m.src.replace(new RegExp(`\\.(${extensions})$`), '')
%>
middleware['<%= name %>'] = require('@/<%= dir.middleware %>/<%= m.src %>');
middleware['<%= name %>'] = middleware['<%= name %>'].default || middleware['<%= name %>']
<% }) %>
export default middleware
```

### What does the proposed changes look like?

adding two props to nuxt.config 
```
{
   ...
   rootDirAlias:'@MyRootAlias@@@',
   srcDirAlias:'@~~~MysrcAlias@',
}
```

replace the hardcoded '@' in all files in the template folder

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9150">#c9150</a>)</em></sub></div>

**Comment by pi0** [comment] 2019-05-03 16:50
Hi. I think it is wrong to use `@` or `~` in nuxt internal templates. Can you please provide an example of generated `.nuxt/middleware.js` file?

**Comment by pi0** [comment] 2019-05-03 16:57
@AngelWayfarer Can you please elaborate more about your project requirement? Do you have a directory named `@` in it?

**Comment by AngelWayfarer** [comment] 2019-05-03 17:21
Hi!
I have old project with server-side .NET. We want to re-write project with nuxt but feature by feature.
We already use '@' alias in our webpack config, so I do not want to replace that alias in more than 200 files...

I have a necessity to reuse old components(all of them use '@' in imports).

So basically I need to have two root aliases in project (these are just webpack aliases).
But the issue the nuxt internal templates have  hardcoded '@' (the code in first snippet is taken from nuxt sorce repo(that repo))

**Comment by AngelWayfarer** [comment] 2019-05-03 17:28
> Hi. I think it is wrong to use `@` or `~` in nuxt internal templates.

I am not sure how wrong that is.. But if we could have the ability to change that alias - that would be great.

Also I found that `@` and `@@` are hardcoded in `packages/webpack/src/config/base.js`

```
alias() {
    const { srcDir, rootDir, dir: { assets: assetsDir, static: staticDir } } = this.buildContext.options

    return {
      '~': path.join(srcDir),
      '~~': path.join(rootDir),
      '@': path.join(srcDir),
      '@@': path.join(rootDir),
      [assetsDir]: path.join(srcDir, assetsDir),
      [staticDir]: path.join(srcDir, staticDir)
    }
  }
```

I think we could use similar approach like the `assetsDir` and `staticDir`

**Comment by pi0** [comment] 2019-05-03 19:55
I'll work on it.

**Comment by AngelWayfarer** [comment] 2019-05-04 11:22
Cool, thanks! I don't think that it will be complex to implement if you are familiar with sources.
Let me know if you need my help (info or tests).

**Comment by Austio** [comment] 2019-05-04 20:13
@pi0 would you be open to a community PR on this one?

**Comment by pi0** [comment] 2019-05-04 21:55
@Austio Yes. As always welcome. For this case, more investigation is required. `@` alias is not only used in the webpack config and the root cause of the issue can be resolved by avoiding using aliases in internal templates. (middleware, store)

**Closed** 2019-05-06 10:46 UTC
Labels: cmty:feature-request
