### ISSUE TITLE
Need better way to logs error on Server Error page?

### ISSUE THREAD

**Issue by chanlito** [nuxt/nuxt.js#2047] opened 2017-11-08 07:57 UTC
All I get is the below image, nothing else.

How can I know what went wrong?

![screen shot 2017-11-08 at 2 55 01 pm](https://user-images.githubusercontent.com/15667259/32537375-f390a106-c494-11e7-876f-78c6273f3792.png)

The following is my setup.
```js
const cors = require('cors')({ origin: true })
const express = require('express')
const functions = require('firebase-functions')
const fs = require('fs')
const path = require('path')
const { Nuxt } = require('nuxt')

const nuxtDir = path.resolve('.', 'nuxt')
if (fs.existsSync(nuxtDir)) {
  console.log('Nuxt directory exists.', nuxtDir)
} else {
  console.error('Nuxt directory does not exists.', nuxtDir)
}

const app = express()
const nuxt = new Nuxt({ dev: false, buildDir: 'nuxt' })

app.use(cors)
app.use(nuxt.render)

exports.render = functions.https.onRequest(app)

```

It works if i run firebase serve --only functions,hosting locally
But doesn't when i deploy it to firebase and show the above image.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c1816">#c1816</a>)</em></sub></div>

**Comment by atmar** [comment] 2017-11-08 17:19
Same question here but with different server code. How do I log the errors. Currently I'm facing an error that doesn't happen on the local build and I can't figure it out.
```
const { Nuxt, Builder } = require('nuxt')

const https = require('https')
const fs = require('fs')
const isProd = (process.env.NODE_ENV === 'production')
const port = process.env.PORT || 3000

// We instantiate nuxt.js with the options
const config = require('./nuxt.config.js')
config.dev = !isProd
const nuxt = new Nuxt(config)

// Render every route with Nuxt.js

// Build only in dev mode with hot-reloading
if (config.dev) {
  new Builder(nuxt).build()
  .then(listen)
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
}
else {
  listen()
}

function listen() {
	const options = {
key: fs.readFileSync('/home/certs/localhost.key'),
cert: fs.readFileSync('/home/certs/localhost.crt')
};
  // Listen the server
// Create the server
https
.createServer(options, nuxt.render)
.listen(port)
  console.log('Server listening on `localhost:' + port + '`.')
}
```

**Comment by danieloprado** [comment] 2017-11-22 22:17
Where is the logs?

**Comment by yoidotco** [comment] 2017-11-26 00:25
I also addressed the same problem.
adding the following code to `nuxt.config.js`, we were able to display error details in production as well.
@atmar thanks for the example!
( not native english :) )

```
process.env.DEBUG = 'nuxt:*'

module.exports = {
  debug: true,
...
```
<img width="1067" alt="error" src="https://user-images.githubusercontent.com/25121870/33235645-97eca0e0-d27f-11e7-8ddd-23266710b1e7.png">

In my case, I am getting better by adding a module.
```
yarn add regenerator-runtime
yarn add core-js
...
firebase deploy
```

**Comment by BruceHem** [comment] 2017-11-26 02:33
@yoidotco do you have a repo that I can look that?

**Comment by yoidotco** [comment] 2017-11-26 13:05
@BruceHem 
It is not yet.
If you have `nuxt.config.js` in your repository, please add `debug: true,` to it :)

<img width="455" alt="2017-11-26 22 04 10" src="https://user-images.githubusercontent.com/25121870/33240210-cb8f165a-d2f5-11e7-8839-bdd2bda9ff0e.png">
<img width="880" alt="2017-11-26 22 03 47" src="https://user-images.githubusercontent.com/25121870/33240213-cebc35e2-d2f5-11e7-846d-36ec441fda77.png">

**Comment by BruceHem** [comment] 2017-11-26 15:14
Ok, I can confirm that putting `debug: true` shows the error.

I had to install all nuxt dependencies manually, somehow specifying just `nuxt` in package.json is not enough.

**Comment by danieloprado** [comment] 2017-11-26 17:52
Please don't close this issue, debug: true is not a good solution because shows the error at the browser, we need an way to see the log without exposing the code!

**Comment by pi0** [comment] 2017-11-27 08:03
https://trello.com/c/rojBtVqz

**Comment by yoidotco** [comment] 2017-11-27 08:35
It may be able to use. for firebase functions(SSR).
`Winston (express.js middleware)` + `Stackdriver Trace`
https://cloud.google.com/nodejs/getting-started/logging-application-events
https://github.com/GoogleCloudPlatform/nodejs-getting-started/blob/master/5-logging/app.js

I'm going to try it out.
If it works, I will publish the source :)

**Comment by besnikh** [comment] 2017-12-23 21:29
@yoidotco is there any update on this ?

**Comment by CKGrafico** [comment] 2018-01-05 11:44
Working well here!

**Comment by davidroyer** [comment] 2018-02-15 08:39
@chanlito 

I was wondering the same thing. Any luck?

**Comment by chanlito** [comment] 2018-02-15 09:12
@davidroyer nope

**Comment by husayt** [comment] 2018-03-08 16:52
@danieloprado what is the latest on this? Can we close it?

**Comment by atmar** [comment] 2018-03-09 15:37
Please don't close it. There is still a need to  send the logs to a file instead of having to use 
module.exports = {
  debug: true
}
to show them on the website itself.

**Comment by bovas85** [comment] 2018-04-18 12:02
@pi0 @husayt any idea on how to solve this? The trello is archived but I can't see a solution

**Comment by atmar** [comment] 2018-06-30 17:42
@pi0  I'm pinging this thread again. This is a really important feature. Even today I had unexplained errors for users and there is no way for me to check. It says "check the logs" but there are no logs and I can't expose debug to true in production, that's a horrible solution

**Comment by aldarund** [comment] 2018-08-19 08:02
@atmar you could use nuxt/sentry module. Or look at it's code and write same module to send errors to file or to whatever you want to

**Comment by galvez** [comment] 2018-08-26 23:32
As @aldarund mentioned, [nuxt/sentry](https://github.com/nuxt-community/sentry-module) should provide all pointers needed for implementing similar functionality.

**Closed by galvez** 2018-08-26 23:32 UTC
Labels: type: question
