### ISSUE TITLE
The error in basic.generate.test/validate

### ISSUE THREAD

**Issue by qm3ster** [nuxt/nuxt.js#1705] opened 2017-09-22 00:45 UTC
`/validate` wrongly passes, it actually fails (which is expected) due to the same error as `/validate?valid=true` fails.
The actual error is `jsdom` trying to `getComputedStyle().WebkitTransitionDelay.split`, where the `WebkitTransitionDelay` is `undefined`
If you open the generated page with a real browser, it behaves correctly in both cases.
I am unsure why it's the validate routes that trigger this, probably because they cause a transition when they resolve to the validated page or error page.

What do we do about this? How to report to `jsdom`?

**Comment by Zirro** [comment] 2017-09-22 12:19
I'm quite familiar with jsdom, and the problem is located in the [CSSStyleDeclaration](https://github.com/chad3814/CSSStyleDeclaration) package which jsdom uses. You could file an issue there, but unfortunately it no longer seems to be under development.

I recently began work on a replacement, [css-object-model](https://github.com/Zirro/css-object-model), which should hopefully resolve the majority of CSS issues in jsdom when it is completed. Doing it all according to the spec is a huge task though, so I don't expect it to be ready for use in jsdom for another couple of months.

**Comment by qm3ster** [comment] 2017-09-22 14:29
Ok, so I see we have been having this error for a long time, it just wasn't leading to the body html not containing the valid string until layout transitions (#1620).
It was probably triggered by the irrelevant loading bar before.
Do you suggest any alternative for testing until then?

**Comment by pi0** [comment] 2017-10-06 23:40
I'm working on this strange failing test too. Just FYI, first this is not probably related to `split` warn with JSDom.

**The long story**

For faster tests I use this command:

```bash
yarn ava --serial test/basic.generate.test.js -m "/validate?valid=true"
```

I've first changed the test to something without JSDom like this:

```js
test('/validate?valid=true', async t => {
  const html = await rp(url('/validate?valid=true'))
  t.true(html.includes('I am valid</h1>'))
})
```

which is still failing with 404 But this time error differs. Before it was a fatal connect 404 error but now is handled by vue and rendered with `error.vue` layout.

I've then tried to manually revert all `app/*` related changes in dcf35933c07ce9b4348d751c80d03c8ca04c2747 but seems no luck again..

Adding `console.log(query)` to `test/fixtures/basic/pages/validate.vue` shows that query is empty `{}` But with `nuxt.renderAndGetWindow` it is one time empty and second time correct `{ valid: 'true' }`. Still no luck...

Next step by adding an infinity promise in tests for testing deeper:

```js
await new Promise(() => {})
```

Opening `http://localhost:4002/validate?valid=true` in the browser seems getting us closer. It redirects to `http://localhost:4002/validate/?valid=true` which is wrong!! Using curl for better debug:

```bash
curl -v "http://localhost:4002/validate?valid=true"
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 4002 (#0)
> GET /validate?valid=true HTTP/1.1
> Host: localhost:4002
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=UTF-8
< Content-Length: 197
< Content-Security-Policy: default-src 'self'
< X-Content-Type-Options: nosniff
< Location: /validate/?valid=true
< Date: Fri, 06 Oct 2017 23:30:08 GMT
< Connection: keep-alive
<
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting</title>
</head>
<body>
<pre>Redirecting to <a href="/validate/?valid=true">/validate/?valid=true</a></pre>
</body>
* Connection #0 to host localhost left intact
```

Just to ensure this is the right direction, let's start the same server but without tests:

```bash
bin/nuxt generate test/fixtures/basic
PORT=4002 bin/nuxt start test/fixtures/basic

curl -v "http://localhost:4002/validate?valid=true"
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 4002 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4002 (#0)
> GET /validate?valid=true HTTP/1.1
> Host: localhost:4002
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
```

And is working ... We are not making any redirect in nuxt so So let's see who is making that crazy 
redirect error. Let's do a grep:

```bash
grep -r "Redirecting to " node_modules
node_modules/encodeurl/README.md:  var body = '<p>Redirecting to new site: ' + escapeHtml(location) + '</p>'
node_modules/express/lib/response.js:      body = statuses[status] + '. Redirecting to ' + address
node_modules/express/lib/response.js:      body = '<p>' + statuses[status] + '. Redirecting to <a href="' + u + '">' + u + '</a></p>'
node_modules/send/index.js:  var doc = createHtmlDocument('Redirecting', 'Redirecting to <a href="' + escapeHtml(loc) + '">' +
node_modules/send/README.md:    res.end('Redirecting to ' + req.url + '/')
node_modules/serve-static/index.js:    var doc = createHtmlDocument('Redirecting', 'Redirecting to <a href="' + escapeHtml(loc) + '">' +
```

Two potential packages: [send](http://npmjs.com/package/send) and [serve-static](https://www.npmjs.com/package/serve-static)

**Comment by pi0** [comment] 2017-10-07 08:24
FYI this problem is not actually related to undefined `split` warning with JSDom nor something false-positive. The problem is that in generated version (which is being served as static `test/fixtures/basic/dist/` with this test) validate doesn't work as expected and throws 404s without rechecking query params. I'll temporarily disable this test as is probably not something much important to allow other commits and PRs passing tests meanwhile we find a fix :)

/cc @Atinux

**Comment by qm3ster** [comment] 2017-10-07 14:43
@pi0 Really? It didn't throw a 404 for me when I opened it with a real browser. It redirected me to the correct page if the query was valid.
The problem is that transitions were added (to nuxt), which means the fake browser returned the pre-transition state.

**Comment by pi0** [comment] 2017-10-07 14:51
@qm3ster I was confused with your situation for hours :)) For real testing i suggest adding a never resolved promise to the test like this:

```
await new Promise((resolve, reject) => { }))
```

Then try opening `http://localhost:4000/validate`  in the browser. This only happens when static generated files are being served not normal nuxt server ...

**Comment by pi0** [comment] 2017-10-07 14:55
BTW there are still problems with newly added layout transitions. We are working on it.

**Comment by qm3ster** [comment] 2017-10-07 15:01
I just disabled all cleanup and served the fixtures with http-serve.
Wouldn't not resolving cause a timeout?

**Comment by pi0** [comment] 2017-10-07 15:22
Yes that just was for test :)) Using http-serve is also ok. Are you getting validate error now?

**Comment by qm3ster** [comment] 2017-10-07 15:52
Yup, now it is actually broken.

**Comment by Atinux** [comment] 2017-10-28 20:41
FIxed in upcoming release.

**Closed by Atinux** 2017-10-28 20:41 UTC
Labels: bug
