### ISSUE TITLE
Compilation error: "Vue packages version mismatch"

### ISSUE THREAD

**Issue by ilovewine** [nuxt/nuxt.js#8815] opened 2021-02-11 20:11 UTC
### Versions

- nuxt: 2.14.12
- node: v15.8.0

### Steps to reproduce

- run `npm init nuxt-app test`
- `cd test`
- run `npm run dev`

### What is Expected?

Nuxt should compile successfully and display welcome page on _localhost:3000_

### What is actually happening?

An error occurs:
![Screenshot from 2021-02-11 21-06-12](https://user-images.githubusercontent.com/13457089/107692417-0d1bcd80-6cad-11eb-94bb-9132e0b9e29f.png)

### Additional notes:
- `rm -rf node_modules && rm package-lock.json && npm i` doesn't work
- installing `vue` and `vue-template-compiler` to the same version (either 2.5.22 or 2.6.12) doesn't fix the issue

I've seen similar issues created some time ago (#6823 and #1084), however they have been closed with a suggestion to reinstall packages using the command with identical output as the one I've made in the additional notes' section (therefore I'm opening this one).

**Comment by manniL** [comment] 2021-02-11 22:33
Duplicate of https://github.com/nuxt/nuxt.js/issues/6823

**Closed by manniL** 2021-02-11 22:33 UTC
Labels: bug-report, pending-repro
