### ISSUE TITLE
404 on refresh post

### ISSUE THREAD

**Issue by influx-agence** [nuxt/nuxt.js#3881] opened 2018-09-12 14:14 UTC
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/influx-agence/Nuxtlify](https://github.com/influx-agence/Nuxtlify)

### Steps to reproduce

1. Go to 'https://influx-agence.netlify.com/blog/'

2. Click on 'My second blog'

3. Look the web console network ( 2018.premier-posts.json )
https://user-images.githubusercontent.com/43016695/45427881-4c8afd80-b6a0-11e8-881d-337f3e3a15f7.png

4. Refresh page

5. The page is 404

6. Look web console network ( 2018.premier-posts..json )
https://user-images.githubusercontent.com/43016695/45428040-aab7e080-b6a0-11e8-81b3-4f6cad712be4.png

### What is expected ?

to work ( one point on GET JSON )

### What is actually happening?

2018.premier-posts..json

### Additional comments?

Hello,
That's my problem:
When I go to my blog, the list of articles is displayed well. 
Once I go to an article and refresh the page i find a 404 error.
Looking more ready the networks i realize that the .JSON normally called has two points after refreshment
( myurl.com/_nuxt/content/name..json )
Someone will have an idea where it might come from?
Thx for your rep

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7730">#c7730</a>)</em></sub></div>

**Comment by manniL** [comment] 2018-09-12 20:29
This does more sound like a `nuxtent` than a `nuxt` issue itself :thinking:

**Comment by influx-agence** [comment] 2018-09-13 09:42
i don't see

**Comment by manniL** [comment] 2018-09-17 19:47
@influx-agence can you try to create a *minimal* reproduction repo?

**Comment by influx-agence** [comment] 2018-09-17 23:30
That is to say ?

**Comment by manniL** [comment] 2018-09-17 23:45
@influx-agence The minimal code needed to see the problem/error. It makes it easier to debug or to find the root cause.

**Comment by influx-agence** [comment] 2018-09-18 00:12
I go through netlify to do the npm run generate
All the rest is available on the GITHUB.
Do you want the return .log of the deploy?

**Comment by influx-agence** [comment] 2018-09-18 00:13
https://github.com/influx-agence/Nuxtlify
https://influx-agence.netlify.com/blog/
`
2:01:33 AM: Build ready to start
2:01:34 AM: build-image version: 42bca793ccd33055023c56c4ca8510463a56d317
2:01:34 AM: buildbot version: 6bab8b64bbd90091082af19fedf16bf73d502e5e
2:01:34 AM: Fetching cached dependencies
2:01:34 AM: Starting to download cache of 101.7MB
2:01:35 AM: Finished downloading cache in 663.413005ms
2:01:35 AM: Starting to extract cache
2:01:39 AM: Finished extracting cache in 3.837257863s
2:01:39 AM: Finished fetching cache in 4.566990872s
2:01:39 AM: Starting to prepare the repo for build
2:01:39 AM: Preparing Git Reference refs/heads/master
2:01:40 AM: Starting build script
2:01:40 AM: Installing dependencies
2:01:41 AM: Started restoring cached node version
2:01:43 AM: Finished restoring cached node version
2:01:43 AM: v8.12.0 is already installed.
2:01:44 AM: Now using node v8.12.0 (npm v6.4.1)
2:01:44 AM: Attempting ruby version 2.3.6, read from environment
2:01:46 AM: Using ruby version 2.3.6
2:01:46 AM: Using PHP version 5.6
2:01:46 AM: Started restoring cached node modules
2:01:46 AM: Finished restoring cached node modules
2:01:46 AM: Started restoring cached go cache
2:01:46 AM: Finished restoring cached go cache
2:01:46 AM: unset GOOS;
2:01:46 AM: unset GOARCH;
2:01:46 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.10.linux.amd64';
2:01:46 AM: export PATH="/opt/buildhome/.gimme/versions/go1.10.linux.amd64/bin:${PATH}";
2:01:46 AM: go version >&2;
2:01:46 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.10.linux.amd64.env';
2:01:46 AM: go version go1.10 linux/amd64
2:01:46 AM: Installing missing commands
2:01:46 AM: Verify run directory
2:01:46 AM: Executing user command: npm run generate
2:01:46 AM: > influx-agence@0.0.2 generate /opt/build/repo
2:01:46 AM: > nuxt generate
2:01:48 AM: 2018-09-18T00:01:48.356Z nuxt:generate Generating...
2:01:48 AM: 2018-09-18T00:01:48.687Z nuxt: Call build:before hooks (2)
2:01:48 AM: starting build nuxtent
2:01:48 AM: [00:01:48] [NUXT:AXIOS] baseURL: /content-api
2:01:48 AM: [00:01:48] [NUXT:AXIOS] browserBaseURL: /_nuxt/content
2:01:48 AM: 2018-09-18T00:01:48.722Z nuxt:build App root: /opt/build/repo
2:01:48 AM: 2018-09-18T00:01:48.722Z nuxt:build Generating /opt/build/repo/.nuxt files...
2:01:48 AM: 2018-09-18T00:01:48.769Z nuxt:build Generating files...
2:01:48 AM: 2018-09-18T00:01:48.777Z nuxt:build Generating routes...
2:01:48 AM: 2018-09-18T00:01:48.805Z nuxt:build Building files...
2:01:49 AM: 2018-09-18T00:01:49.404Z nuxt: Call build:compile hooks (1)
2:02:18 AM:  WARNING  Compiled with 1 warnings00:02:18
2:02:18 AM:  warning
2:02:18 AM: asset size limit: The following asset(s) exceed the recommended size limit (300 kB).
2:02:18 AM: This can impact web performance.
2:02:18 AM: Assets:
2:02:18 AM:   img/mlh-works-2.5f320d5.jpg (347 kB)
2:02:18 AM:   img/fin-works-2.90115db.jpg (384 kB)
2:02:18 AM:   img/fin-works-4.ca3bc24.jpg (318 kB)
2:02:18 AM:   img/mlh-works-1.5a507a0.jpg (447 kB)
2:02:18 AM:   img/mlh-works-carou.499d38b.jpg (308 kB)
2:02:18 AM:   vendor.e17b0a1d529d065647fa.js (606 kB)
2:02:18 AM: Hash: 671522a5932f25b5bf36
2:02:18 AM: Version: webpack 3.12.0
2:02:18 AM: Time: 28607ms
2:02:18 AM:                                                           Asset       Size  Chunks                    Chunk Names
2:02:18 AM:                                     img/cdm-works-3.664587d.jpg     271 kB          [emitted]
2:02:18 AM:                                     img/mlh-works-2.5f320d5.jpg     347 kB          [emitted]  [big]
2:02:18 AM:                                 img/cdm-works-carou.f38b0bf.jpg     149 kB          [emitted]
2:02:18 AM:                                     img/fin-works-2.90115db.jpg     384 kB          [emitted]  [big]
2:02:18 AM:                                     img/mlh-works-4.6a24956.jpg     129 kB          [emitted]
2:02:18 AM:                                            img/logo.86ad181.svg    2.88 kB          [emitted]
2:02:18 AM:                                     img/fin-works-3.85feff4.jpg     241 kB          [emitted]
2:02:18 AM:                                  img/technique-mini.01b60f1.jpg    83.7 kB          [emitted]
2:02:18 AM:                            img/influx-expertise-bot.af380d1.jpg    96.8 kB          [emitted]
2:02:18 AM:                            img/influx-expertise-top.81ddc14.jpg      80 kB          [emitted]
2:02:18 AM:                                     img/art-works-4.6821503.jpg     286 kB          [emitted]
2:02:18 AM:                              img/communication-mini.1a31959.jpg    98.5 kB          [emitted]
2:02:18 AM:                                    img/conseil-mini.fbd15dd.jpg    87.9 kB          [emitted]
2:02:18 AM:                          img/influx-realisation-top.797aa78.jpg     183 kB          [emitted]
2:02:18 AM:                                    img/icon-conseil.27d227b.png    3.42 kB          [emitted]
2:02:18 AM:                               img/methodologie-mini.0a13dc2.jpg    76.5 kB          [emitted]
2:02:18 AM:                              img/influx-conseil-top.f78aee3.jpg     116 kB          [emitted]
2:02:18 AM:                                     img/fin-works-4.ca3bc24.jpg     318 kB          [emitted]  [big]
2:02:18 AM:                                 img/fin-works-carou.60c8f0b.jpg     142 kB          [emitted]
2:02:18 AM:                              img/icon-communication.eca80f9.png    7.21 kB          [emitted]
2:02:18 AM:                             img/influx-creation-top.dc35582.jpg     107 kB          [emitted]
2:02:18 AM:                               img/influx-agence-top.30374be.jpg     159 kB          [emitted]
2:02:18 AM:                              img/influx-accueil-bot.62a921f.jpg     148 kB          [emitted]
2:02:18 AM:                                  img/icon-technique.b4a3dda.png    5.23 kB          [emitted]
2:02:18 AM:                                   img/icon-creation.01ec130.png    3.98 kB          [emitted]
2:02:18 AM:                                     img/mlh-works-1.5a507a0.jpg     447 kB          [emitted]  [big]
2:02:18 AM:                              img/influx-accueil-top.c11aa9d.jpg    93.8 kB          [emitted]
2:02:18 AM:                                     img/art-works-3.cacb5fc.jpg     220 kB          [emitted]
2:02:18 AM:                                     img/influx-mini.ae9dc76.jpg     106 kB          [emitted]
2:02:18 AM:                                 img/mlh-works-carou.499d38b.jpg     308 kB          [emitted]  [big]
2:02:18 AM:                                     img/mlh-works-3.0e49afb.jpg     231 kB          [emitted]
2:02:18 AM:                                     img/art-works-1.c66d202.jpg     219 kB          [emitted]
2:02:18 AM:                               img/realisations-mini.b303ce3.jpg     133 kB          [emitted]
2:02:18 AM:                                   img/creation-mini.dcbd34c.jpg    78.5 kB          [emitted]
2:02:18 AM:                                     img/cdm-works-1.d570c10.jpg     251 kB          [emitted]
2:02:18 AM:                            img/influx-technique-top.26ec03b.jpg     124 kB          [emitted]
2:02:18 AM:                                     img/fin-works-1.652603b.jpg     199 kB          [emitted]
2:02:18 AM:                                     img/art-works-2.40892a0.jpg     241 kB          [emitted]
2:02:18 AM:                                     img/cdm-works-4.f44ead4.jpg     166 kB          [emitted]
2:02:18 AM:                                     img/cdm-works-2.ffb0746.jpg     227 kB          [emitted]
2:02:18 AM:                        img/influx-communication-top.14996ca.jpg     127 kB          [emitted]
2:02:18 AM:                      pages/realisations.070ceee4367c56214cbc.js    23.8 kB       0  [emitted]         pages/realisations
2:02:18 AM:                             pages/index.269b82fc4bf99751b564.js    22.9 kB       1  [emitted]         pages/index
2:02:18 AM:                          layouts/influx.c42b936244cc6d52c1b1.js    20.8 kB       2  [emitted]         layouts/influx
2:02:19 AM:                            pages/equipe.e27cf2c3838d2c7b46a6.js    13.5 kB       3  [emitted]         pages/equipe
2:02:19 AM:                         pages/technique.ed0dc46f7b18f453d593.js    12.8 kB       4  [emitted]         pages/technique
2:02:19 AM:                          pages/creation.030f87bcf26a33a652ce.js    12.6 kB       5  [emitted]         pages/creation
2:02:19 AM:                           pages/conseil.f8d2a51812de85d66830.js    12.4 kB       6  [emitted]         pages/conseil
2:02:19 AM:                     pages/communication.f3fd98346ce73bb38598.js    12.7 kB       7  [emitted]         pages/communication
2:02:19 AM:                      pages/methodologie.64f1a6c64b124ac9651a.js    29.5 kB       8  [emitted]         pages/methodologie
2:02:19 AM:                           pages/valeurs.6d094ac7a497689c85bc.js    8.02 kB       9  [emitted]         pages/valeurs
2:02:19 AM:                           pages/contact.844a612dfd0944cfcb44.js     4.2 kB      10  [emitted]         pages/contact
2:02:19 AM:                              pages/blog.f165e43900759efb922f.js     3.1 kB      11  [emitted]         pages/blog
2:02:19 AM:                             pages/_post.49f1e27b4bb28855e8c6.js  932 bytes      12  [emitted]         pages/_post
2:02:19 AM:                         layouts/default.6872e38380d49fbbce7e.js  399 bytes      13  [emitted]         layouts/default
2:02:19 AM: pages/realisations/la-cour-des-miracles.1c93d3cc7a10f8daa789.js  233 bytes      14  [emitted]         pages/realisations/la-cour-des-miracles
2:02:19 AM:                                  vendor.e17b0a1d529d065647fa.js     606 kB      15  [emitted]  [big]  vendor
2:02:19 AM:                                     app.bab01001f587c2555e3d.js    50.1 kB      16  [emitted]         app
2:02:19 AM:                                manifest.671522a5932f25b5bf36.js    2.08 kB      17  [emitted]         manifest
2:02:19 AM:                                                        LICENSES    1.47 kB          [emitted]
2:02:19 AM:                                 content/2018.premier-posts.json  312 bytes          [emitted]
2:02:19 AM:                                               content/_all.json  344 bytes          [emitted]
2:02:19 AM:  + 2 hidden assets
2:02:19 AM: WARNING in asset size limit: The following asset(s) exceed the recommended size limit (300 kB).
2:02:19 AM: This can impact web performance.
2:02:19 AM: Assets:
2:02:19 AM:   img/mlh-works-2.5f320d5.jpg (347 kB)
2:02:19 AM:   img/fin-works-2.90115db.jpg (384 kB)
2:02:19 AM:   img/fin-works-4.ca3bc24.jpg (318 kB)
2:02:19 AM:   img/mlh-works-1.5a507a0.jpg (447 kB)
2:02:19 AM:   img/mlh-works-carou.499d38b.jpg (308 kB)
2:02:19 AM:   vendor.e17b0a1d529d065647fa.js (606 kB)
2:02:19 AM: 2018-09-18T00:02:18.051Z nuxt: Call build:done hooks (2)
2:02:19 AM: opening server connection
2:02:21 AM: 2018-09-18T00:02:21.580Z nuxt:netlify-cms Bundle built!
2:02:21 AM: 2018-09-18T00:02:21.581Z nuxt: Call generate:distRemoved hooks (1)
2:02:21 AM: 2018-09-18T00:02:21.581Z nuxt:generate Destination folder cleaned
2:02:21 AM: 2018-09-18T00:02:21.614Z nuxt: Call generate:distCopied hooks (2)
2:02:21 AM: 2018-09-18T00:02:21.614Z nuxt:generate Static & build files copied
2:02:21 AM: 2018-09-18T00:02:21.620Z nuxt:netlify-cms Netlify CMS files copied
2:02:21 AM: 2018-09-18T00:02:21.623Z nuxt:render Rendering url /communication
2:02:21 AM: 2018-09-18T00:02:21.627Z nuxt:render Rendering url /valeurs
2:02:21 AM: 2018-09-18T00:02:21.627Z nuxt:render Rendering url /contact
2:02:21 AM: 2018-09-18T00:02:21.628Z nuxt:render Rendering url /conseil
2:02:21 AM: 2018-09-18T00:02:21.628Z nuxt:render Rendering url /blog
2:02:21 AM: 2018-09-18T00:02:21.628Z nuxt:render Rendering url /technique
2:02:21 AM: 2018-09-18T00:02:21.628Z nuxt:render Rendering url /creation
2:02:21 AM: 2018-09-18T00:02:21.628Z nuxt:render Rendering url /equipe
2:02:21 AM: 2018-09-18T00:02:21.628Z nuxt:render Rendering url /methodologie
2:02:21 AM: 2018-09-18T00:02:21.628Z nuxt:render Rendering url /realisations/la-cour-des-miracles
2:02:21 AM: 2018-09-18T00:02:21.629Z nuxt:render Rendering url /
2:02:21 AM: 2018-09-18T00:02:21.629Z nuxt:render Rendering url /2018/premier-posts
2:02:21 AM: 2018-09-18T00:02:21.689Z nuxt: Call generate:page hooks (1)
2:02:21 AM: 2018-09-18T00:02:21.711Z nuxt: Call generate:page hooks (1)
2:02:21 AM: 2018-09-18T00:02:21.727Z nuxt: Call generate:page hooks (1)
2:02:21 AM: 2018-09-18T00:02:21.743Z nuxt: Call generate:page hooks (1)
2:02:21 AM: 2018-09-18T00:02:21.761Z nuxt: Call generate:page hooks (1)
2:02:21 AM: 2018-09-18T00:02:21.770Z nuxt: Call generate:page hooks (1)
2:02:21 AM: 2018-09-18T00:02:21.778Z nuxt: Call generate:page hooks (1)
2:02:22 AM: 2018-09-18T00:02:21.790Z nuxt: Call generate:page hooks (1)
2:02:22 AM: 2018-09-18T00:02:21.798Z nuxt: Call generate:page hooks (1)
2:02:22 AM: 2018-09-18T00:02:21.806Z nuxt: Call generate:page hooks (1)
2:02:22 AM: 2018-09-18T00:02:21.814Z nuxt: Call generate:page hooks (1)
2:02:22 AM: 2018-09-18T00:02:21.825Z nuxt: Call generate:page hooks (1)
2:02:22 AM: 2018-09-18T00:02:21.825Z nuxt:generate Generate file: /communication/index.html
2:02:22 AM: 2018-09-18T00:02:21.825Z nuxt:generate Generate file: /valeurs/index.html
2:02:22 AM: 2018-09-18T00:02:21.825Z nuxt:generate Generate file: /contact/index.html
2:02:22 AM: 2018-09-18T00:02:21.825Z nuxt:generate Generate file: /conseil/index.html
2:02:22 AM: 2018-09-18T00:02:21.825Z nuxt:generate Generate file: /blog/index.html
2:02:22 AM: 2018-09-18T00:02:21.825Z nuxt:generate Generate file: /technique/index.html
2:02:22 AM: 2018-09-18T00:02:21.825Z nuxt:generate Generate file: /creation/index.html
2:02:22 AM: 2018-09-18T00:02:21.825Z nuxt:generate Generate file: /equipe/index.html
2:02:22 AM: 2018-09-18T00:02:21.825Z nuxt:generate Generate file: /methodologie/index.html
2:02:22 AM: 2018-09-18T00:02:21.826Z nuxt:generate Generate file: /realisations/la-cour-des-miracles/index.html
2:02:22 AM: 2018-09-18T00:02:21.826Z nuxt:generate Generate file: /index.html
2:02:22 AM: 2018-09-18T00:02:21.826Z nuxt:generate Generate file: /2018/premier-posts/index.html
2:02:22 AM: 2018-09-18T00:02:21.828Z nuxt:render Rendering url /
2:02:22 AM: 2018-09-18T00:02:21.828Z nuxt: Call generate:done hooks (2)
2:02:22 AM: 2018-09-18T00:02:21.829Z nuxt:generate HTML Files generated in 33.5s
2:02:22 AM: closing server connection
2:02:22 AM: 2018-09-18T00:02:21.829Z nuxt:generate Generate done
2:02:22 AM: Caching artifacts
2:02:22 AM: Started saving node modules
2:02:22 AM: Finished saving node modules
2:02:22 AM: Started saving pip cache
2:02:22 AM: Finished saving pip cache
2:02:22 AM: Started saving emacs cask dependencies
2:02:22 AM: Finished saving emacs cask dependencies
2:02:22 AM: Started saving maven dependencies
2:02:22 AM: Finished saving maven dependencies
2:02:22 AM: Started saving boot dependencies
2:02:22 AM: Finished saving boot dependencies
2:02:22 AM: Started saving go dependencies
2:02:22 AM: Finished saving go dependencies
2:02:22 AM: Build script success
2:02:22 AM: Starting to deploy site from 'dist'
2:02:27 AM: Starting post processing
2:02:28 AM: Post processing done
2:02:28 AM: Site is live
2:02:42 AM: Finished processing build request in 1m7.786506665s
`

**Comment by cesasol** [comment] 2018-09-18 05:56
@influx-agence I saw that you are trying to use a json content file, is not something that we consider supporting before but if you open a issue in the repo we might add it, it does seem easy enough.  What you can do in the meantime is use only markdown or yaml files depending on your needs.

**Comment by manniL** [comment] 2018-09-18 07:46
Closing this as it isn't a nuxt-scoped issue.

**Closed by manniL** 2018-09-18 07:46 UTC
Labels: cmty:bug-report

**Comment by influx-agence** [comment] 2018-09-18 13:41
Why do you allow yourself to close the subject when the problem is not solved?

**Comment by manniL** [comment] 2018-09-18 15:30
@influx-agence As I stated in my comment above, it is **not nuxt related** but related to a module. That means this is the wrong place for this issue. https://github.com/nuxt-community/nuxtent-module/issues/180 is still open and the way to go ;)

**Comment by influx-agence** [comment] 2018-09-18 15:31
ow okay, very sorry ... very very
