### ISSUE TITLE
Page level caching

### ISSUE THREAD

**Issue by Timkor** [nuxt/nuxt.js#5450] opened 2019-04-03 08:10 UTC
### What problem does this feature solve?

Reduce server side rendering time using page level caching.

### What does the proposed changes look like?

We could use component cache. But this is still quite unnecessarily slow.

Would be nice to have a page level cache built in into Nuxt. [See page level caching at Vue docs](https://ssr.vuejs.org/guide/caching.html#page-level-caching)

What would be nice is a function with accepts a `route` and returns a `cache key` if it's able to be cached.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8983">#c8983</a>)</em></sub></div>

**Comment by GillesWHC** [comment] 2019-04-03 09:32
Definitely a must for our project. Would love to see this.

**Comment by DenzoNL** [comment] 2019-04-03 09:32
+1, would be really nice to have this feature! My web application is rather slow now, and a built-in solution would be highly preferable over some random package.

**Comment by henriqemalheiros** [comment] 2019-04-03 11:55
Duplicate of #4698. Ideally, we would all be using NGINX, but @clarkdo suggested [this module](https://www.npmjs.com/package/nuxt-ssr-cache). Here's a stripped down version of that with simple queuing I wrote and use:

```js
import LRU from 'lru-cache'

const stringify = obj => JSON.stringify(obj, (k, v) =>
  typeof v === 'object' && v instanceof Set
    ? [ 'set', [ ...v ] ]
    : typeof v === 'function'
      ? [ 'func', v() ]
      : v
)

const parse = str => JSON.parse(str, (k, v) =>
  Array.isArray(v) && v.length === 2
    ? v[0] === 'set'
      ? new Set(v[1])
      : v[0] === 'func'
        ? () => v[1]
        : v
    : v
)

export default function ({ max = 100, maxAge = 3000 } = {}) {
  const cache = new LRU({
    max,
    maxAge,
  })

  const queue = new Map()

  const renderer = this.nuxt.renderer
  const renderRoute = renderer.renderRoute.bind(renderer)

  renderer.renderRoute = function (route, context) {
    if (cache.has(route)) {
      const cached = cache.get(route)

      if (cached) {
        return parse(cached)
      }
    }

    if (queue.has(route)) {
      const queued = queue.get(route)

      if (queued) {
        return queued
      }
    }

    const promise = new Promise((resolve, reject) => {
      renderRoute(route, context)
        .then((result) => {
          if (!result.error) {
            cache.set(route, stringify(result))
          }

          return resolve(result)
        })
        .catch((err) => {
          return reject(err)
        })
        .finally(() => {
          queue.delete(route)
        })
    })

    queue.set(route, promise)

    return promise
  }
}
```

**Closed** 2019-04-09 08:58 UTC
Labels: cmty:feature-request

**Comment by mauxtin** [comment] 2019-04-09 10:13
It would be great to have this supported out of the box though. Maybe we should leave it open as feature request? /cc @manniL
