### ISSUE TITLE
Cannot start project

### ISSUE THREAD

**Issue by niba1122** [nuxt/nuxt.js#3842] opened 2018-09-04 02:33 UTC
### Version

[Edge 2.0.0-25599455.3a0f094](https://github.com/nuxt.js/releases/tag/Edge 2.0.0-25599455.3a0f094)

### Reproduction link

[https://github.com/niba1122/nuxt-cannot-start-project](https://github.com/niba1122/nuxt-cannot-start-project)

### Steps to reproduce

node: 10.5.0

1. yarn install / npm install
2. yarn dev / npm run dev

### What is expected ?

Successfully compiled.

### What is actually happening?

Error occurs:

```
These dependencies were not found:

* core-js/modules/es6.array.find in ./.nuxt/client.js
* core-js/modules/es6.array.iterator in ./.nuxt/client.js
* core-js/modules/es6.date.to-string in ./.nuxt/utils.js, ./.nuxt/client.js
* core-js/modules/es6.function.name in ./.nuxt/utils.js, ./.nuxt/index.js and 1 other
* core-js/modules/es6.object.assign in ./.nuxt/index.js, ./.nuxt/client.js
* core-js/modules/es6.object.keys in ./.nuxt/client.js, ./.nuxt/utils.js
* core-js/modules/es6.promise in ./.nuxt/client.js
* core-js/modules/es6.regexp.constructor in ./.nuxt/utils.js
* core-js/modules/es6.regexp.match in ./.nuxt/client.js
* core-js/modules/es6.regexp.replace in ./.nuxt/utils.js
* core-js/modules/es6.regexp.search in ./.nuxt/utils.js
* core-js/modules/es6.regexp.split in ./.nuxt/utils.js
* core-js/modules/es6.regexp.to-string in ./.nuxt/client.js, ./.nuxt/utils.js
* core-js/modules/es6.string.repeat in ./.nuxt/utils.js
* core-js/modules/es6.symbol in ./.nuxt/client.js
* core-js/modules/es7.promise.finally in ./.nuxt/client.js
* core-js/modules/es7.symbol.async-iterator in ./.nuxt/client.js
* core-js/modules/web.dom.iterable in ./.nuxt/utils.js, ./.nuxt/client.js and 1 other
```

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7679">#c7679</a>)</em></sub></div>

**Comment by samtsai15** [comment] 2018-09-04 02:55
Node.js : v8.9.4
I clone your repo , and run it: 

```
These dependencies were not found:

* core-js/modules/es6.array.find in ./.nuxt/client.js
* core-js/modules/es6.array.iterator in ./.nuxt/client.js
* core-js/modules/es6.date.to-string in ./.nuxt/utils.js, ./.nuxt/client.js
* core-js/modules/es6.function.name in ./.nuxt/utils.js, ./.nuxt/client.js and 1 other
* core-js/modules/es6.object.assign in ./.nuxt/index.js, ./.nuxt/client.js
* core-js/modules/es6.object.keys in ./.nuxt/utils.js, ./.nuxt/client.js
* core-js/modules/es6.promise in ./.nuxt/client.js
* core-js/modules/es6.regexp.constructor in ./.nuxt/utils.js
* core-js/modules/es6.regexp.match in ./.nuxt/client.js
* core-js/modules/es6.regexp.replace in ./.nuxt/utils.js
* core-js/modules/es6.regexp.search in ./.nuxt/utils.js
* core-js/modules/es6.regexp.split in ./.nuxt/utils.js
* core-js/modules/es6.regexp.to-string in ./.nuxt/client.js, ./.nuxt/utils.js
* core-js/modules/es6.string.repeat in ./.nuxt/utils.js
* core-js/modules/es6.symbol in ./.nuxt/client.js
* core-js/modules/es7.promise.finally in ./.nuxt/client.js
* core-js/modules/es7.symbol.async-iterator in ./.nuxt/client.js
* core-js/modules/web.dom.iterable in ./.nuxt/client.js, ./.nuxt/utils.js and 1 other

To install them, you can run: npm install --save core-js/modules/es6.array.find core-js/modules/es6.array.iterator core-js/modules/es6.date.to-string core-js/modules/es6.function.name core-js/modules/es6.object.assign core-js/modules/es6.object.keys core-js/modules/es6.promise core-js/modules/es6.regexp.constructor core-js/modules/es6.regexp.match core-js/modules/es6.regexp.replace core-js/modules/es6.regexp.search core-js/modules/es6.regexp.split core-js/modules/es6.regexp.to-string core-js/modules/es6.string.repeat core-js/modules/es6.symbol core-js/modules/es7.promise.finally core-js/modules/es7.symbol.async-iterator core-js/modules/web.dom.iterable
```

I just installed core-js : `yarn add core-js` 
It's worked.

**Comment by niba1122** [comment] 2018-09-04 03:35
Exactly, if we install core-js, it works, but core-js should be required by Nuxt.js because core-js is required in scripts generated by Nuxt.js.
In fact, in other versions (for example 2.0.0-25586998.83d9dc4 and so on) it works without core-js.

**Comment by SeregPie** [comment] 2018-09-04 08:27
I have the same problem after upgraded to `2.0.0-25599455.3a0f094`.

**Comment by aldarund** [comment] 2018-09-04 17:16
Reproducible with both yarn and npm

**Comment by manniL** [comment] 2018-09-04 21:09
Resolved with https://github.com/nuxt/nuxt.js/commit/3ca2f026744b5fe760ecfe047d32d24522cbe315

We hadn't included the dependency coincidentally because `opencollective-cli` had it as dependency as well

**Closed by manniL** 2018-09-04 21:09 UTC
Labels: cmty:bug-report

**Comment by hashinteractive** [comment] 2018-10-06 17:58
Was this reintroduced in nuxt v.2.1.0? It looks like it's included in dependencies for @babel/core
```
"dependencies": {
    "@babel/core": "^7.1.2",
```
as @manniL suggested for the fix but this still throws a core-js error so is that not the necessary package?

Fixes it by `yarn add core-js` but shouldn't have to include that in our project packages?
