### ISSUE TITLE
Is there a way to reduce css bundle size by tokenizing names and reducing vendor bundle size by text compression

### ISSUE THREAD

**Issue by anandsiddharth** [nuxt/nuxt.js#7987] opened 2020-08-29 10:26 UTC
The build chunks are too large, can we have certain features like these to optimize the production builds.

Can we do something like the following in nuxt?

https://www.freecodecamp.org/news/reducing-css-bundle-size-70-by-cutting-the-class-names-and-using-scope-isolation-625440de600b/

https://www.html5rocks.com/en/tutorials/speed/txt-compression/

**Comment by saint777** [comment] 2020-08-29 13:50
You want like [this ](https://hsto.org/webt/hh/ut/5e/hhut5eodm-tw-e1wdqnecn7dxlu.png)

It made with CSS modules

**Comment by danielroe** [comment] 2020-08-30 06:51
Duplicate of https://github.com/nuxt/nuxt.js/issues/7851

And yes, the solution is to use CSS modules.

**Closed by danielroe** 2020-08-30 06:51 UTC
Labels: feature-request

**Comment by MUMUKSHMEGHWAL** [comment] 2021-06-08 08:14
@saint777 can give me more insight how you did it ?
