### ISSUE TITLE
RangeError: Array size is not a small enough positive integer on iOS browsers after now deploy

### ISSUE THREAD

**Issue by russc** [nuxt/nuxt.js#2935] opened 2018-03-02 15:30 UTC
My project is working well on desktop browsers, but when I deploy through zeit's now, some of my click events are broken on all iOS browsers and I am able to see this error in the console (using browserstack).  Everything works as it should on Android browsers.  Any help/direction on this issue would be appreciated.  I'm using "nuxtjs/apollo": "^3.0.4" and "apollo-client": "^2.2.5". Here is part of my nuxt.config.js: 

```
build: {
    maxChunkSize: 300000,
    extend (config) {
      if (process.client) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  }
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2549">#c2549</a>)</em></sub></div>

**Comment by qm3ster** [comment] 2018-03-03 19:00
Have you tested it on iOS from your computer?

**Comment by russc** [comment] 2018-03-03 22:03
I haven't tried it in the simulator. I will try that next. Thanks!

**Comment by qm3ster** [comment] 2018-03-04 16:01
I meant, have you tried connecting (a physical iOS device) to a server running directly on your computer.
If you only have an iOS device remotely, you could use ngrok/localtunnel to expose your server to it.

**Comment by russc** [comment] 2018-03-06 02:19
Thanks for the tip.  I just checked it out with ngrok and saw the same error.  Most click events are working, but a few do not and some page routes do not load until you navigate to them and refresh.  I'm going to see what happens if use Nuxt generate.

**Comment by qm3ster** [comment] 2018-03-06 11:19
Do you deploy a living server or static generated pages?

Generated pages wouldn't save you from something being broken in your project and preventing normal clientside navigation, because only the entry page `.html` is ever downloaded, the rest of navigation only downloads js bundles, like with living server.

**Comment by russc** [comment] 2018-03-06 13:43
Thank you for your help. I was deploying to a living server (now service through zeit). It looks like the generated pages feature isn't a great option anyway since I have dynamic routes and some routes are ids from graphql.  I'm also using Apollo client 2 and the page that has that error has a pretty big query on it.  Not sure if that has anything to do with it because another page also has the issue and its query is small. One thing both pages have in common are buttons from the materialize CSS components and the JavaScript for that library depends on jquery so I feel like that has created a lot of overhead that I could do without. I'm going to refactor those things out and trim this down, then update this thread.

**Comment by galvez** [comment] 2018-08-18 09:26
@russc Closing this as there's been no updates in the past 90 days. Please open a new issue with a more detailed log (and example repo) if you still need to debug this and think it's caused by Nuxt.

**Closed by galvez** 2018-08-18 09:26 UTC
