### ISSUE TITLE
The 91% chunk asset optimization problem 

### ISSUE THREAD

**Issue by Gangwolf** [nuxt/nuxt.js#2921] opened 2018-03-01 04:30 UTC
Running `npm run generate` hangs at 91% (or 92%) chunk asset optimization. Works fine on Linux (using Solus) but freezes on WSL (Bash on Ubuntu on Windows).

Possible correlated issues: 
  * webpack/webpack#4550
  * webpack/webpack#4558
  * webpack-contrib/babel-minify-webpack-plugin#49 
  * mishoo/UglifyJS2#2609
  * JeffreyWay/laravel-mix#926
  * angular/angular-cli#5775
  * gdi2290/angular-starter#1925

I disabled UglifyJS using @Atinux method in nuxt/nuxt.js#250 and it built.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt/nuxt.js/issues/c2535">#c2535</a>)</em></sub></div>

**Comment by preeteshjain** [comment] 2018-03-22 12:41
This is happening with me on my AWS EC2 instance, Ubuntu 16.04. Everything is up-to-date, sometimes it passes sometimes it just hangs at `91% additional asset processing` and quits without any feedback.

Here you can see I tried twice, but no luck. It still quits unexpectedly without any error message, so I don't even know what's wrong.

```bash
ubuntu@xyz:/var/www/app.wittypen.com$ npm run production

> @ production /var/www/app.wittypen.com
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

ubuntu@xyz:/var/www/app.wittypen.com$ npm run production

> @ production /var/www/app.wittypen.com
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

ubuntu@xyz:/var/www/app.wittypen.com$
```

**Comment by preeteshjain** [comment] 2018-03-22 12:42
This is happening with me on my AWS EC2 instance, Ubuntu 16.04. Everything is up-to-date, sometimes it passes sometimes it just hangs at `91% additional asset processing` and quits without any feedback.

Here you can see I tried twice, but no luck. It still quits unexpectedly without any error message, so I don't even know what's wrong.

```bash
ubuntu@xyz:/var/www/mywebsite.com$ npm run production

> @ production /var/www/mywebsite.com
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

ubuntu@xyz:/var/www/mywebsite.com$ npm run production

> @ production /var/www/mywebsite.com
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

ubuntu@xyz:/var/www/mywebsite.com$
```

**Comment by feryardiant** [comment] 2018-03-22 12:44
I had same issue on my local, but I don't know why it run well without any issue on [gitlab ci](https://gitlab.com/feryardiant/adonan/-/jobs/58859513)

**Comment by preeteshjain** [comment] 2018-03-22 12:47
It might be a memory issue. But on other threads I've seen people with good hardware configurations getting the same problem.

**Comment by feryardiant** [comment] 2018-03-22 15:15
Just tried to add this option to my `nuxt-config`

```js

module.exports = {
  build: {
    // ...

    uglify: {
      uglifyOptions: {
        compress: false
      },
      cache: '/path/to/cache/dir'
    },

    // ...
  },

  // ...
}
```

as suggested [here](https://github.com/webpack/webpack/issues/4558#issuecomment-352255789) and now it's working in my local.

**Comment by preeteshjain** [comment] 2018-03-23 09:40
Good for you, but I can't go without Uglify on production.

**Comment by memic84** [comment] 2018-04-26 13:19
Same issue here, solution except disabling?

**Comment by bactoria** [comment] 2018-05-11 13:06
@feryardiant 

Thanks. I solved my problem. :)

**Comment by preeteshjain** [comment] 2018-05-11 13:48
I added a swapfile on my VM and the process completed successfully. You guys should definitely give it a try.

Here are some good instructions on how to do it: [How To Add Swap on Ubuntu](https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04)

**Comment by NetBzz** [comment] 2018-07-01 13:07
Using `nuxt-edge` resolved this issue for me.

**Comment by mazyvan** [comment] 2018-08-16 16:12
Only adding swap memory it's not the solution. The process at least should stop if the system is getting out of memory. On a continuous deployment environment this process is the devil. The compilation never end and of course the system is completely out of memory so no one can't connect to it until restarting the instance

**Comment by jakeg** [comment] 2018-08-31 13:03
I'm also having this issue under WSL.

**Comment by mikehamil10** [comment] 2018-09-04 02:54
Builds hanging at 91% on WSL as well (Ubuntu 18.04)

**Comment by alanaasmaa** [comment] 2018-09-11 09:37
Build hanging at 90% (Ubuntu 16.04) not WSL

**Comment by zindont** [comment] 2018-09-18 09:32
I'm also having this issue under WSL. at 91%

**Comment by alanaasmaa** [comment] 2018-09-18 13:36
I resolved my issue by moving a lot of images from assets to static.

**Comment by siberiadev** [comment] 2018-11-22 19:18
Hey guys! Who can provide me any manuals how to migrate from nuxt 1.4 to nuxt-edge?
We have a project based on nuxt kit (I got this package from github, with some preinstalled modules and properities). Now I got the same 91% problem. So if migration to nuxt 2 will resolve my problem I will give it a try. But I can't find any manuals for migration...
Help!!! Please...

**Comment by siberiadev** [comment] 2018-11-23 15:12
resolved with migrate to nuxt edge

**Comment by alanaasmaa** [comment] 2018-11-23 18:30
I think its memory issue

**Comment by manniL** [comment] 2018-11-24 00:07
Disabling minification (`build.optimization.minimize`) can help. https://nuxtjs.org/api/configuration-build/#optimization

**Comment by siberiadev** [comment] 2018-11-24 00:11
migration on nuxt 2 resolved my problem

сб, 24 нояб. 2018 г. в 8:08, Alexander Lichter <notifications@github.com>:

**Comment by Gehbrial** [comment] 2018-11-24 16:16
> Disabling minification (`build.optimization.minimize`) can help. https://nuxtjs.org/api/configuration-build/#optimization

That's how I fixed the issue (along with updating to 2.3.2) :)

**Comment by manniL** [comment] 2018-11-29 14:01
As described in the other issues linked above, it's a RAM issue. You can fix it by:

* Adding more RAM
* Adding a Disk Swap
* Probably disabling minification

**Closed by manniL** 2018-11-29 14:01 UTC
Labels: type: discussion

**Comment by sangemi** [comment] 2018-12-06 16:11
I add 4G swap.
And then I ran nuxt build.

Before
![image](https://user-images.githubusercontent.com/8413799/49596081-d6efae80-f9bc-11e8-8590-5b7b4fecf032.png)

Building..
![image](https://user-images.githubusercontent.com/8413799/49596125-f25ab980-f9bc-11e8-82b8-75011465f5b4.png)

it was stopped at 91%.
![image](https://user-images.githubusercontent.com/8413799/49596177-11f1e200-f9bd-11e8-849c-21ce301d5272.png)

**Comment by maxneh** [comment] 2018-12-10 10:53
> As described in the other issues linked above, it's a RAM issue. You can fix it by:
> 
> * Adding more RAM
> * Adding a Disk Swap
> * Probably disabling minification

RAM 8Gb, swap 24Gb
If exclude minification - fixed, but how whithout it

**Comment by sweetim** [comment] 2019-01-03 06:44
had this problem, using nuxt `v2.3.4` on WSL

it works when i disable the minification, and my system has plenty of free memory to be used (~4GB) so cant be out of memory problem, how to solve this problem?

**Comment by zindont** [comment] 2019-01-07 03:02
Still have this issue with the latest Nuxt version (2.3.4)

**Comment by laogui** [comment] 2019-03-16 04:01
[https://nuxtjs.org/api/configuration-build/#optimization](https://nuxtjs.org/api/configuration-build/#optimization)
```
import TerserPlugin from 'terser-webpack-plugin'
build: {
    optimization: {
      minimize: true,
      minimizer: [
        new TerserPlugin({
          cache: true,
          parallel: false
        })
      ]
    }
}
```
it works in WSL.

**Comment by pachiraDIG** [comment] 2019-04-17 22:35
> https://nuxtjs.org/api/configuration-build/#optimization
> 
> ```
> import TerserPlugin from 'terser-webpack-plugin'
> build: {
>     optimization: {
>       minimize: true,
>       minimizer: [
>         new TerserPlugin({
>           cache: true,
>           parallel: false
>         })
>       ]
>     }
> }
> ```
> it works in WSL. "nuxt": "2.4.5"

@laogui Confirmed working in Nuxt 2.6.1 on WSL. The Swapfile solution higher in the thread didn't make a difference for me.

**Comment by manniL** [comment] 2019-04-19 18:23
You can also use https://nuxtjs.org/api/configuration-build/#terser I guess.

**Comment by pachiraDIG** [comment] 2019-04-19 18:28
Ah, even better. No need to install.

**Comment by pikadun** [comment] 2019-04-25 04:32
`optimization: {
            minimize: false
        }`

**Comment by SHxKM** [comment] 2019-05-02 22:57
I suddenly have this issue after switching to `postcss` instead of `scss` and installing `postcss-nested`.

**Comment by foloinfo** [comment] 2019-07-10 02:08
All the solutions above did't work for me, I ended up disabling uglify option on dev mode and now I can finally develop. It takes really long time to build on production though...

```
    extend (config, {isDev}) {
      if (isDev) { // in my case I couldn't use isDev so I used `process.env.NODE_ENV === 'development'`
        config.plugins = config.plugins.filter((plugin) => plugin.constructor.name !== 'UglifyJsPlugin')
      }
```

I took filtering uglify from another issue: [How could i disable UglifyJs in the client webpack config? · Issue #250 · nuxt/nuxt.js](https://github.com/nuxt/nuxt.js/issues/250#issuecomment-280681399)

Is this issue solved in the latest version of nuxt?

**Comment by bhavinjr** [comment] 2019-08-15 08:37
> ```js
> uglify
> ```

does not work in nuxt 2.*

**Comment by RozbehSharahi** [comment] 2020-09-01 13:52
I was stepping onto the same issue.

It seems to work when I remove the `dist` directory before running `nuxt-ts generate`

`"generate": "rm -rf dist && nuxt-ts generate",`

**Comment by whirlswirl** [comment] 2021-03-06 21:35
Doesn't work. I'm throwing Nuxt of the window. I only encounters errors with it. Nothing but errors. Just doesn't work out of the box. Developer experience 0.

**Comment by pachiraDIG** [comment] 2021-03-06 21:47
Considering most people here have built (or are building) a business that
relies on Next due to its stability and great feature set, your opinion
doesn't hold up.

**Comment by greetfish** [comment] 2021-10-09 09:46
我在本地可以正常npm run build，但是aws的ec2中会卡在90%
终极解决办法：
编辑.gitignore文件，取消.nuxt目录及dist目录的ignore，所以以后更新线上代码都通过本地先npm run build然后线上直接运行，（即线上不进行npm run build）

**Comment by dapsych0** [comment] 2021-11-02 10:47
Worked for me after making a 2GB swap file, before it was hanging and failing with memory error, with a swap file worked a like a charm.

**Comment by nav064** [comment] 2022-12-11 10:23
On my 1GB RAM machine, 2GB swap file didn't help. A 2GB RAM without swap space seems to handle it OK. Please note that swap helps to only move memory intensive processes (other than your build) out of RAM temporarily. In my case, my machine wasn't running nothing much apart from the build (and eventually server). Mine is an SSR build with Nuxt 2.6.14, in case that helps anyone.
