### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by AlanGuo** [nuxt/nuxt.js#1354] opened 2017-08-12 09:54 UTC
I have tested a lot.

when I use **asyncData** in my page，visit the page about 20k times (render in SSR).
![image](https://user-images.githubusercontent.com/727863/29256133-8d9e3f50-80da-11e7-895b-ba5de87827ce.png)

the error blow occurred, please help.

![image](https://user-images.githubusercontent.com/727863/29239717-13355e5a-7f87-11e7-88f5-57b94cd8b466.png)

The source code is here

![image](https://user-images.githubusercontent.com/727863/29239728-7397786e-7f87-11e7-80b2-3ec249180ca6.png)

**Comment by pimlie** [comment] 2017-08-13 08:52
This seems to be related to nodejs, not to nuxt. See https://stackoverflow.com/questions/20936486/node-js-maximum-call-stack-size-exceeded and/or https://stackoverflow.com/questions/11332422/how-can-i-increase-the-maximum-call-stack-size-in-node-js?

**Comment by AlanGuo** [comment] 2017-08-14 02:32
@pimlie but I think Nuxt should handle this for us.

**Comment by pimlie** [comment] 2017-08-14 08:18
@AlanGuo you are right, sorry. Actually experiencing the same issue now.

**Comment by Atinux** [comment] 2017-08-14 10:51
I did not get this error from now, could you provide a small reproduction repo so we can work on finding the bug?

**Comment by AlanGuo** [comment] 2017-08-14 11:25
@Atinux 
https://github.com/AlanGuo/callstack_exceeded
this demo repo, hope it works.

**Comment by pimlie** [comment] 2017-08-14 11:29
@Atinux as @AlanGuo mentions for me it also occurred after nuxt was running in production for a couple of days and served a couple of thousands requests.

I was able to reproduce the problem with the [async-data](https://github.com/nuxt/nuxt.js/tree/dev/examples/async-data) example. Run the example and then use apache benchmark to sent requests: `ab -n 20000 -c 5 http://127.0.0.1:3000/posts`

Somewhere around the 17.000 requests mark the errors as below should start

```
  nuxt:render Data fetching /posts: 90ms +5ms
[Vue warn]: Error in data(): "RangeError: Maximum call stack size exceeded"

found in

---> <Pages/posts/index.vue> at pages/posts/index.vue
       <Nuxt> at .nuxt/components/nuxt.vue
         <Default> at .nuxt/layouts/default.vue
           <Root>
  nuxt:render Data fetching /posts: 92ms +5ms
[Vue warn]: Error in data(): "RangeError: Maximum call stack size exceeded"

found in

---> <Pages/posts/index.vue> at pages/posts/index.vue
       <Nuxt> at .nuxt/components/nuxt.vue
         <Default> at .nuxt/layouts/default.vue
           <Root>
  nuxt:render Rendering url /posts +111ms
  nuxt:render Rendering url /posts +1ms
  nuxt:render Rendering url /posts +0ms
  nuxt:render Rendering url /posts +1ms
  nuxt:render Rendering url /posts +8ms
  nuxt:render Data fetching /posts: 77ms +96ms
[Vue warn]: Error in data(): "RangeError: Maximum call stack size exceeded"

found in

---> <Pages/posts/index.vue> at pages/posts/index.vue
       <Nuxt> at .nuxt/components/nuxt.vue
         <Default> at .nuxt/layouts/default.vue
           <Root>
  nuxt:render Data fetching /posts: 73ms +6ms
[Vue warn]: Error in data(): "RangeError: Maximum call stack size exceeded"

found in

---> <Pages/posts/index.vue> at pages/posts/index.vue
       <Nuxt> at .nuxt/components/nuxt.vue
         <Default> at .nuxt/layouts/default.vue
           <Root>
```

**Comment by pimlie** [comment] 2017-08-14 12:05
@Atinux I also tried a `nuxt generate` for 20.000 pages and experience the same issue.

**Comment by cobbcheng** [comment] 2017-08-22 09:30
I also encountered the same problem, the online environment almost every week, restart node server will be fixed
![image](https://user-images.githubusercontent.com/15278560/29558712-8a959ed0-875f-11e7-9bcc-af35d0e1012d.png)

**Comment by AlanGuo** [comment] 2017-08-23 10:50
is this bug fixed ?

**Comment by AlanGuo** [comment] 2017-08-23 10:51
still not fixed in rc6

**Comment by pi0** [comment] 2017-08-23 16:54
@AlanGuo Do you get this error even with Node 8.x?

**Comment by pimlie** [comment] 2017-08-23 17:17
@pi0 Yes, also with the latest 8.4.0. Actually with 8.4.0 the errors start a bit sooner. Before I was running 8.1.4, then I had to wait until request ~17.000 before the errors start. With 8.4.0 the errors start at ~15.000 requests.

```
# node -v
v8.4.0
```

**Comment by pi0** [comment] 2017-08-23 17:38
```
 ab -n 17000 http://127.0.0.1:5000/
This is ApacheBench, Version 2.3 <$Revision: 1757674 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)

Completed 1700 requests
Completed 3400 requests
Completed 5100 requests
Completed 6800 requests
Completed 8500 requests
Completed 10200 requests
Completed 11900 requests
Completed 13600 requests
Completed 15300 requests
Completed 17000 requests
Finished 17000 requests

Concurrency Level:      1
Time taken for tests:   131.062 seconds
Complete requests:      17000
Failed requests:        1897
   (Connect: 0, Receive: 0, Length: 1897, Exceptions: 0)
Non-2xx responses:      1897
Total transferred:      134636336 bytes
HTML transferred:       131208100 bytes
Requests per second:    129.71 [#/sec] (mean)
Time per request:       7.710 [ms] (mean)
Time per request:       7.710 [ms] (mean, across all concurrent requests)
Transfer rate:          1003.19 [Kbytes/sec] received
```

Still not getting Maximum call error with Nuxr RC6 + Node 8.3.0. @pimlie Can you please prepare a single `pages/index.vue` file to reproduce this bug after some high loads? Debugging and fix wouldn't be possible without that.

**Comment by pimlie** [comment] 2017-08-23 17:50
@pi0 You dont see the errors in the terminal that runs `ab`, not sure why but it seems nuxt is still returning 200 status codes. You need to check the 'nuxt' log. The errors start at ~17.000 so probably best to run ab upto 20.000 requests and not exactly 17.000 ;)

As i already explained above in detail, the async-data example is all you need:
- start two terminals
- in the first go to your nuxt repository and the async-data example
- run `yarn` to install dependencies
- build with `npm run build` 
- then start with `npm run start`
- in the second terminal run `ab -c 5 -n 20000 http://127.0.0.1:3000/`

Now wait until in the first terminal you see the RangeErrors flooding your screen. It is correct that ab will finish without any errors. As I said in one of my previous comments, nuxt generate shows the same issue so it appears not to be a http server issue.

**Comment by ImadBoumzaoued** [comment] 2017-08-25 08:19
@pimlie exactly what happens, thanks man

**Comment by Atinux** [comment] 2017-08-29 19:12
We found the issue with @pi0 and will be released tomorrow in `rc8`, thanks everyone for helping us finding this bug.

We added a stress test to avoid a possible regression in the future.

**Comment by pi0** [comment] 2017-08-30 18:25
Problem should be finally fixed with rc8 🎉  

https://github.com/nuxt/nuxt.js/releases/tag/v1.0.0-rc8

**Closed by pi0** 2017-08-30 18:25 UTC
Labels: available soon, bug

**Comment by AlanGuo** [comment] 2017-08-31 02:55
thank you all.

**Comment by rikoz** [comment] 2018-08-23 20:45
Hello, sorry i don't know if this issues has been fixed. However I don't know if it's an issue with my code. I'm actually trying to use asyncData to get the current URL (domain name) since I'm using multiple subdomains. I need to know which domain nuxt is currently being access from so I did this 

`asyncData: ({ req }) => ({
        portal: req ? req.headers.host : window.location.host.split(':')[0]
    }),`

Please help as I'm always experiencing a 500 range error anytime I include this in my component.
