### ISSUE TITLE
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method

### ISSUE THREAD

**Issue by nwcalvin** [nuxt/nuxt.js#7874] opened 2020-08-07 05:05 UTC
I got this error message in console on running npm run build and npm run start but no problem at npm run dev

nuxt version = 2.14.1
webpack version = 4.44.1
mode= 'universal'

The DOM which got error message looks like this, GOT ERROR
`<template>
<div>
        <div>
            <img class="logo" src="/logo.png" />            
            <div class="menu-item" v-for="m in orderedMenus" :key="m.menu_id">
                <div>{{m.menu_name}}</div>
            </div>
            <div class="login">{{login_text}}</div>    <-- I got error msg when putting this <div> after v-for="m in orderedMenus"
        </div>
    </div>
</template>`

The DOM which can get rid of the error message looks like this, NO ERROR
`<template>
<div>
        <div>
            <img class="logo" src="/logo.png" /> 
            <div class="login">{{login_text}}</div>  <-- no error msg when put in front of v-for statement, UI render is correct       
            <div class="menu-item" v-for="m in orderedMenus" :key="m.menu_id">
                <div>{{m.menu_name}}</div>
            </div>  
        </div>
    </div>
</template>`

Does anyone has idea how to get this fix? If I run npm run dev, I got no problem for both of the syntax in above.

Thank you for anyone who could help.

**Comment by manniL** [comment] 2020-08-07 08:59
Duplicate of #7203.
Feel free to also read [this blog post](https://blog.lichter.io/posts/vue-hydration-error/) about that topic.

**Closed by manniL** 2020-08-07 08:59 UTC
