### ISSUE TITLE
Duplicated meta tags on SSR

### ISSUE THREAD

**Issue by gnuletik** [nuxt/nuxt.js#4282] opened 2018-11-06 13:47 UTC
### Version

[v2.2.0](https://github.com/nuxt.js/releases/tag/v2.2.0)

### Reproduction link

[https://github.com/gnuletik/nuxt-duplicate-meta](https://github.com/gnuletik/nuxt-duplicate-meta)

### Steps to reproduce

Here is how to reproduce from the official template:

In `layouts/default.vue`
```
<script>
let tags = {
  meta: []
}

export default {
  name: 'app',
  head () {
    tags.meta.push({
      property: 'og:url',
      content: this.$router.history.current.path,
      hid: 'metaogurl'
    })
    return tags
  }
}
</script>
```

Then, refresh your pages several times or navigate through some pages.

In your browser's console, run:

```
document.querySelectorAll('meta[property="og:url"]')

1: <meta data-n-head="true" property="og:url" content="/" data-hid="metaogurl">​
2: <meta data-n-head="true" property="og:url" content="/" data-hid="metaogurl">
3: <meta data-n-head="true" property="og:url" content="/" data-hid="metaogurl">
```

The meta tag is duplicated.

I fixed it by making a copy of the arrays instead of pushing into it:

In `src/layouts/default.vue`
```
  head () {
    let tags = this.cms.tags() // Or whatever you use
    // clone is required to avoid duplicates
    let clone = {
      htmlAttrs: Object.assign({}, tags.htmlAttrs),
      link: tags.link.slice(0),
      meta: tags.meta.slice(0)
    }
    clone.meta.push({
          property: 'og:url',
          content: this.$router.history.current.path,
          hid: 'metaogurl',
    })
    return clone
  }
```

I don't know if this should be fixed by nuxt or vue-meta.

### What is expected ?

Non duplicated meta tags

### What is actually happening?

Duplicated meta tags

### Additional notes

This bug report is a duplicate of https://cmty.app/nuxt/nuxt.js/issues/c2521 as the comments in this post are not anymore reported back to github.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8094">#c8094</a>)</em></sub></div>

**Comment by manniL** [comment] 2018-11-06 15:36
This is no bug.
(Repro: https://codesandbox.io/s/527zv3no7k)

As you define state outside of the component it will be persisted through every server-side rendering. You definitely **should avoid doing that**. instead, you might want to use `VueX` or similar.

**Comment by gnuletik** [comment] 2018-11-06 15:46
I totally understand that the state is persisted through every server-side rendering.
However vue-meta shouldn't remove duplicates of meta entries who have the same `hid` ?

**Comment by manniL** [comment] 2018-11-06 16:00
Whoops. You are right, if you set duplicates on SSR it won't clear them there (updated my sandbox). Investigating

**Comment by manniL** [comment] 2018-11-06 16:19
I can confirm this only happens on SSR, not in `SPA` mode or on CSR.

**Comment by manniL** [comment] 2018-11-06 16:56
So, after testing it with `vue-meta` itself (simple test case [here](https://github.com/manniL/vue-meta/commit/4020bf1d6d7a78bf67d551d383665b50a94777a9)) it looks like that functionality is not supported by `vue-meta`. Only information that are dupes in `child` components will be merged.

Please create an issue in the `vue-meta` repository or filter your info directly in your component.

**Closed by manniL** 2018-11-06 16:56 UTC
Labels: cmty:bug-report

**Comment by gnuletik** [comment] 2018-11-06 17:33
Thanks for investigating !
