### ISSUE TITLE
Cannot read property 'props' of undefined

### ISSUE THREAD

**Issue by MLDMoritz** [nuxt/nuxt.js#7133] opened 2020-03-26 01:19 UTC
### Version

[v2.12.1](https://github.com/nuxt.js/releases/tag/v2.12.1)

### Reproduction link

[https://example.com](https://example.com)

### Steps to reproduce

An upgrade from 2.12.0 to 2.12.1 leads to this error.

I somewhat 'traced' the error and I think it has something todo with templates?

This might be the cause: https://github.com/nuxt/nuxt.js/compare/v2.12.0...v2.12.1#diff-a3c4ca4154135db3811dcc04844c06caR27

.nuxt/App.js
```js
const layouts = { "_clean": sanitizeComponent(_77263413),"_default": sanitizeComponent(_6f6c098b),"_default/footer": sanitizeComponent(_5b8eca9f),"_login": sanitizeComponent(_77a66d33),"_simple": sanitizeComponent(_ee7125b0) }

```

When I remove `sanitizeComponent` around it it works just fine.

```js
const layouts = { "_default": (_6f6c098b),"_default/footer": (_5b8eca9f),"_login": (_77a66d33),"_simple": (_ee7125b0) }
```

### What is expected ?

Working like version 2.12.0

### What is actually happening?

Error

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10441">#c10441</a>)</em></sub></div>

**Comment by romukey** [comment] 2020-03-26 05:16
the same error occurs in my project, too

**Comment by cron13** [comment] 2020-03-26 06:11
+1
At the same time i got error ```ERROR  [Vue warn]: Invalid component name: "_2d21d098". Component names should conform to valid custom element name in html5 specification.``` in server console

**Comment by ram-you** [comment] 2020-03-26 07:14
Have same problem with v2.12.1
 ERROR  [Vue warn]: Invalid component name: "_6f6c098b". Component names should conform to valid custom element name in html5 specification.   

.nuxt-dev/App.js:
```
const _6f6c098b = () => import('../layouts/default.vue'  /* webpackChunkName: "layouts/default" */).then(m => m.default || m)
const _9f305d28 = () => import('../layouts/guestLayout.vue'  /* webpackChunkName: "layouts/guestLayout" */).then(m => m.default || m)

const layouts = { "_default": sanitizeComponent(_6f6c098b),"_guestLayout": sanitizeComponent(_9f305d28) }
```

**Comment by LuXDAmore** [comment] 2020-03-26 10:46
Same here ✋

**Comment by brolnickij** [comment] 2020-03-26 13:42
I have the same problem :(

**Comment by steven0811** [comment] 2020-03-27 04:08
Same here.

In my case, I just remove
```js
build: {
    // splitChunks: {
    //   layouts: true
    // },
}
```
in nuxt.config.js, It works.

**Comment by daspete** [comment] 2020-03-27 09:47
Same here

it's a problem with the splitChunks of layouts... like @steven0811 said.

**Comment by willhalling** [comment] 2020-03-27 09:52
Same problem.

Thanks @steven0811 you've just saved my sanity. I just spent several hours trying to fix.

**Comment by ram-you** [comment] 2020-03-27 11:27
@steven0811 Thank you for sharing your solution.
But it would not be a final solution. It's just a workaround and it's a regression.

**Comment by steven0811** [comment] 2020-03-27 11:35
@ram-you Yes, you're right, I just point it out the relation with `build.splitChunks.layouts` but not solved the problem, only for investigating purpose.

**Comment by pi0** [comment] 2020-03-27 12:55
Thanks for quickly reporting the issue. It will be fixed soon by #7139. Unfortunately, non of fixtures  was using `splitChunks.layouts` that's why regression happened.

**Closed** 2020-03-27 13:08 UTC
Labels: available soon, bug, cmty:bug-report

**Comment by Alligatore3** [comment] 2020-04-15 15:53
Hei @pi0 

thanks for support, but unfortunately the problem persists even with `v2.12.2` :(

I'm having this in my console:
```
[Vue warn]: Invalid component name: "layouts/default.vue". Component names should conform to valid custom element name in html5 specification.
```

Maybe is because I'm using kind of dynamic layouts based on route.
I made a post about this where you can see my code:

https://dev.to/alligatore3/nuxt-js-dynamic-layouts-by-current-route-3jl1

**Comment by robertofd1995** [comment] 2020-04-19 18:35
@pi0 @Alligatore3 I have the same issue and I am not using dynamic layouts based on route

**Comment by dikesh** [comment] 2020-04-20 10:17
> Hei @pi0
> 
> thanks for support, but unfortunately the problem persists even with `v2.12.2` :(
> 
> I'm having this in my console:
> 
> ```
> [Vue warn]: Invalid component name: "layouts/default.vue". Component names should conform to valid custom element name in html5 specification.
> ```
> 
> Maybe is because I'm using kind of dynamic layouts based on route.
> I made a post about this where you can see my code:
> 
> https://dev.to/alligatore3/nuxt-js-dynamic-layouts-by-current-route-3jl1

I am using nuxt-vuetify template. I am getting this same warning (not every time but often) when I click on select components e.g. v-select or v-autocomponent.

**Comment by fidopaca** [comment] 2020-04-21 23:55
v2.12.2 and the problem still exists. I am just using nuxt-tailwindcss and did not changed anything on nuxt.config.js. When i route to any page that component exists i am getting that warning. Thanks for help.

**Comment by bryanspearman** [comment] 2020-04-22 14:17
Is there a resolution to this issue?  I'm getting the same error: 
`Invalid component name: "layouts/default.vue". Component names should conform to valid custom element name in html5 specification.
`

**Comment by IvanArjona** [comment] 2020-04-29 15:38
As the error message suggests, it's infering an invalid name.
This can be fixed giving a custom name to the component.

For example to `layouts/default.vue`
```js
<script>
export default {
  name: 'Default'
}
</script>
```

**Comment by Alligatore3** [comment] 2020-05-04 07:51
> As the error message suggests, it's inferring an invalid name.
> This can be fixed giving a custom name to the component.
> 
> For example to `layouts/default.vue`
> 
> ```js
> <script>
> export default {
>   name: 'Default'
> }
> </script>
> ```

Yes, as @IvanArjona said.

**UPDATE:**
One of my first issues were caused by WebStorm since when you right-click to create a new Vue component and, let's suppose, we create a new **dynamic page**, WS will automatically create a name with that underscore.
At first I didn't recognize it.

**Comment by louisluu** [comment] 2020-07-13 06:22
Running **v2.13.3** and still having this issue.

This error message is even showing in `nuxt-child` page. 

My page:

```js
<template>
  <nuxt-child />
</template>

<script>
export default {
  layout: 'admin',
}
</script>
```

Console output:`[Vue warn]: Invalid component name: "pages/settings.vue". Component names should conform to valid custom element name in html5 specification.`
