### ISSUE TITLE
nuxt build: Unable to update lock within the stale threshold

### ISSUE THREAD

**Issue by deepan1234** [nuxt/nuxt.js#5351] opened 2019-03-23 04:46 UTC
### Version

[v2.5.1](https://github.com/nuxt.js/releases/tag/v2.5.1)

### Reproduction link

[https://github.com/deepan1234/test/blob/master/package.json](https://github.com/deepan1234/test/blob/master/package.json)

### Steps to reproduce

npm run build 

### What is expected ?

Build should be successful

### What is actually happening?

 + 29 hidden assets
Entrypoint app = server.js server.js.map

 FATAL  Lock is already released                                                                    00:36:26

  at callback (node_modules/proper-lockfile/lib/lockfile.js:241:60)
  at Promise (node_modules/proper-lockfile/lib/adapter.js:39:9)
  at new Promise (<anonymous>)
  at args (node_modules/proper-lockfile/lib/adapter.js:30:25)
  at NuxtCommand.lockRelease [as _lockRelease] (node_modules/@nuxt/utils/dist/utils.js:139:11)
  at NuxtCommand.releaseLock (node_modules/@nuxt/cli/dist/cli-chunk.js:244:18)
  at NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-chunk.js:159:18)
  at <anonymous>
  at process._tickDomainCallback (internal/process/next_tick.js:228:7)

   ╭─────────────────────────────────────╮
   │                                     │
   │   ✖ Nuxt Fatal Error                │
   │                                     │
   │   Error: Lock is already released   │
   │                                     │
   ╰─────────────────────────────────────╯

### Additional comments?

npm run dev is working fine but build is erroring out with - Lock is already released.

Am I missing something? Please help in resolving the issue.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8906">#c8906</a>)</em></sub></div>

**Comment by shrpne** [comment] 2019-03-23 09:24
duplicate of #5324 and #5331

**Closed** 2019-03-23 10:22 UTC
Labels: cmty:bug-report
