### ISSUE TITLE
Can not install new nuxt application

### ISSUE THREAD

**Issue by japanes** [nuxt/nuxt.js#7873] opened 2020-08-06 12:06 UTC
I have errors today when try to install a new application

![Screenshot_20200806_150332](https://user-images.githubusercontent.com/915093/89529837-13a92400-d7f6-11ea-85e8-5f12ab166aa2.png)

Have any idea what is this?

Versions
nuxt: v2.14.1
node: v14.7.0

**Comment by danielroe** [comment] 2020-08-06 12:12
@epsy-me This is not a Nuxt issue. There are currently issues accessing npmjs.com and installing scoped packages.

https://status.npmjs.org/incidents/cksjqc1w11v5?u=yjqzk11ky282

Duplicate of #7870, #7869 and #7868

**Closed by danielroe** 2020-08-06 12:12 UTC
Labels: bug-report
