### ISSUE TITLE
Invalid component name for layout/default.vue when using layout splitChunks' option

### ISSUE THREAD

**Issue by Alphability** [nuxt/nuxt.js#7140] opened 2020-03-27 12:42 UTC
### Version

[v2.12.1](https://github.com/nuxt.js/releases/tag/v2.12.1)

### Reproduction link

[https://codesandbox.io/s/nervous-sinoussi-en5m9](https://codesandbox.io/s/nervous-sinoussi-en5m9)

### Steps to reproduce
👋 @Atinux 

- Go to nuxt.config.js
- Set the build.splitChunks.layouts property to true

### What is expected ?

The project should run without throwing a Vue error.

### What is actually happening?

The project is throwing an "Invalid component name" error.

![Capture d’écran 2020-03-27 à 12.58.30.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/8ea8c790-7028-11ea-939c-6fd883f76bd5.png)

~/.nuxt/App.js file :
![Capture d’écran 2020-03-27 à 12.58.38.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/aff14990-7028-11ea-939c-6fd883f76bd5.png)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10446">#c10446</a>)</em></sub></div>

**Comment by pi0** [comment] 2020-03-27 12:54
Hi @Alphability thanks for creating issue. It is duplicate of #7133 will be fixed ASAP (#7139)

**Closed by pi0** 2020-03-27 12:54 UTC
Labels: cmty:bug-report
