### ISSUE TITLE
[2.4.0] [npm] Unexpected token error when running in dev

### ISSUE THREAD

**Issue by eatyrghost** [nuxt/nuxt.js#4869] opened 2019-01-28 18:38 UTC
### Version

[v2.4.0](https://github.com/nuxt.js/releases/tag/v2.4.0)

### Reproduction link

[https://i-cannot-share-private-repos.com/](https://i-cannot-share-private-repos.com/)

### Steps to reproduce

1. Upgrade a codebase to Nuxt 2.4.0.
2. Run `nuxt` to build for dev.

### What is expected ?

It compiles and builds the web site.

### What is actually happening?

It throws an error:

```
ERROR  in ./.nuxt/router.js                                                                         friendly-errors 12:33:55

Module parse failed: Unexpected token (9:24)                                                         friendly-errors 12:33:55
You may need an appropriate loader to handle this file type.
| 
| var _c67eeace = function _c67eeace() {
>   return interopDefault(import('../pages/about-us.vue'
|   /* webpackChunkName: "pages/about-us" */
|   ));
                                                                                                     friendly-errors 12:33:55
 @ ./.nuxt/index.js 8:0-43 64:19-31
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
```

### Additional comments?

All I did was upgrade using `npm install -D nuxt@2.4.0` to get the latest version. Not sure if there are other changes I need to make (nothing was mentioned in the release notes).

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8553">#c8553</a>)</em></sub></div>

**Comment by pi0** [comment] 2019-01-28 19:09
@eatyrghost Would you please share us (or privatetly) the `.nuxt/router.js` file?

**Comment by pi0** [comment] 2019-01-28 19:33
This is probably related to webpack regression. Please remove `yarn.lock` / `package-lock.json` and reinstall. This should fix problem

**Comment by pi0** [comment] 2019-01-28 19:35
Link to issue: https://github.com/webpack/webpack/issues/8656

**Comment by pi0** [comment] 2019-01-28 19:38
@martymclaughlan  @eskimm @eatyrghost  for ensurance, as issue that i mentioned is related to NPM package manager. Do you confirm:

1. Are you using npm?
2. Removing lock and reinstall fixed issue?

**Comment by LeCoupa** [comment] 2019-01-28 19:44
I also have the same issue. I am using `nuxt@2.3.4`. I just removed package.lock and reinstalled packages but the error still persists.

**Comment by pi0** [comment] 2019-01-28 19:46
@LeCoupa Would you please also nuxt?

**Comment by LeCoupa** [comment] 2019-01-28 19:52
Upgrading to `nuxt@2.4.0` and removing `package-lock.json` seems to have fixed the issue. But it seems that the module `nuxt-sass-resources-loader` is not working anymore. Don't know if it's related.

**Comment by martymclaughlan** [comment] 2019-01-28 19:53
> Upgrading to `nuxt@2.4.0` and removing `package-lock.json` seems to have fixed the issue. But it seems that a module I use `nuxt-sass-resources-loader` is not working anymore. Don't know if it's related to `2.4.0`.

Yeah nuxt-sass-resources-loader is broken for me too now

**Comment by pi0** [comment] 2019-01-28 19:56
@martymclaughlan @LeCoupa regarding `nuxt-sass-resources-loader` please open a ticket in the corresponding repository. We will try to review it ASAP.

**Comment by pi0** [comment] 2019-01-28 20:09
PS: Alternative official module is [style-resources-module](https://github.com/nuxt-community/style-resources-module)

**Comment by pi0** [comment] 2019-01-28 20:38
Closing as there is a related open issue ( #4839 ) and problem added to release notes.

**Closed** 2019-01-28 20:38 UTC
Labels: cmty:bug-report

**Comment by joeyzone** [comment] 2019-01-29 06:11
“ npm should either remove package-lock.json and reinstall before upgrade or use npm update acorn --depth 20 && npm dedupe after upgrading to 2.4.0.“
i remove node_modules,  then remove package-lock.json, then update nuxt, it's work.
only remove package-lock.json it's not useful to me.
hope to help you.

**Comment by samirph** [comment] 2019-01-31 22:17
@joeyzone You are a lifesaver! None of the previous steps worked for me either.

**Comment by joeyzone** [comment] 2019-02-02 02:06
> @joeyzone You are a lifesaver! None of the previous steps worked for me either.

happy to help you.
