### ISSUE TITLE
Nested dynamic route with query string parameter does not re-render parent view

### ISSUE THREAD

**Issue by ydnar** [nuxt/nuxt.js#1548] opened 2017-08-31 15:23 UTC
Copying this from a comment on #1408:

---

Curiously, with `1.0.0-rc8` I observe the *opposite* behavior. I have a project with nested views:

```
pages/
--index.vue
--index/
----_id.vue
```

The parent view (`index.vue`) displays search results, keying off a query string parameter (`?q=<terms>`). `<nuxt-link>` links that change the query string parameter, e.g.:

> /?q=foo
> /?q=bar

**…do *not* cause the outer view to re-render.** The `asyncData`, `fetch`, and `mounted` hooks do not fire after the initial render.

Is this as-designed? Is there a way to specify that query string parameters affect a route and should cause a re-render?

**Comment by homerjam** [comment] 2017-08-31 17:32
Not sure if this is inline with your observation or not - I'm afraid it's a bit unclear to me from the above, but...

The [vue-router docs](https://router.vuejs.org/en/essentials/dynamic-matching.html
) state that params will not cause a page navigation by design, as it's most efficient to re-use the existing components. It's suggested you watch the `$route` property from your component. It's my assumption that this would be the same for query params.

However I've noticed that when I update the `query` with `$router.push()` nuxt navigates to the same page - contradicting the docs.

**Comment by ydnar** [comment] 2017-09-09 02:22
@homerjam my parent view has a watcher on `$route`, which fires, but the values it sets are overridden somewhere else.

**Comment by alexchopin** [comment] 2017-10-28 13:26
Should be fixed with the next release, feel free to comment/reopen this issue if the bug persists.

**Closed by alexchopin** 2017-10-28 13:26 UTC

**Comment by geoctrl** [comment] 2017-12-03 04:21
what's the status of this bug? I'm having the same issues - fetch/asyncData/mounted do not fire with query params...

**Comment by Ca4tkin** [comment] 2018-01-25 11:19
hi, I have the same problem, when it's going to be fixed?

**Comment by homerjam** [comment] 2018-01-25 13:38
@Ca4tkin have you tried the suggestion [here](https://github.com/nuxt/nuxt.js/issues/2591#issuecomment-357634392)?

**Comment by Ca4tkin** [comment] 2018-01-26 14:13
@homerjam yes, it helped, thanks
