### ISSUE TITLE
specific transitions for different route within page component

### ISSUE THREAD

**Issue by max-schu** [nuxt/nuxt.js#566] opened 2017-04-14 11:53 UTC
since theres no direct access to "this" in the transition object / js hooksof a page, is it even possible to create custom enter and leave transitions with javascript hooks instead of css, or different transition names?

i'm doing this with plain vue.js this way:

`router-view.view(ref='page')`

then:

```
enter (el, done) {
  this.$refs.page.enter
  ? this.$refs.page.enter(el, done)
  : TweenLite.from(el, 0.5, { alpha: 0, onComplete: done() })
}
```

**Comment by max-schu** [comment] 2017-04-14 13:22
should have mentioned before:
the issue is – "leave" hook in the transition object of nuxt doesnt trigger for the current route but for the next route.

**Comment by max-schu** [comment] 2017-04-19 23:14
@Atinux is this intended? doesn't make sense to me…

**Comment by Atinux** [comment] 2017-04-21 15:30
We don't overwrite Vue.js config as you can see here: https://github.com/nuxt/nuxt.js/blob/master/lib/app/components/nuxt-child.js

I believe this is related to Vue.js directly.

Can you provide a reproduction repository so I can take a look at it @max-schu ?

**Comment by smith64fx** [comment] 2017-05-17 11:26
@max-schu I know what you mean.

It's really strange, because when I leave the current route, the leave hook of the next route will be used for the transition =/

**Comment by smith64fx** [comment] 2017-05-17 11:36
I made a reproduction repo here:

https://github.com/smith64fx/nuxt-transition-repro

If you run it and switch the sites from About <-> Test, you will get the issue.

When I switch from About to Test, the leave hook of Test will be triggered instead of the leave hook of About. So in the About component I have no real "leave" transition. The Test component's leave hook will be used for the About components leave hook.

**Comment by max-schu** [comment] 2017-05-17 13:00
thanks alot @smith64fx for creating a repo, i honestly couldn't find the time yet to do so, and for now sadly decided to discontinue the use of nuxt for my projects.

**Comment by Atinux** [comment] 2017-05-20 22:54
Thanks @smith64fx, we'll take a look at it.

**Comment by sdras** [comment] 2017-06-11 22:51
+1, I'm seeing this as well. It's creating a problem for some more complex transitions I'm creating, let me know if you need an isolated test case, happy to provide it.

**Comment by max-schu** [comment] 2017-06-11 22:58
it might be related to transition mode not being set to 'out-in' – just a educated guess.

**Comment by sdras** [comment] 2017-06-11 23:00
Mine is set to 'out-in' so that's not the case for me, and not in the repro either

**Comment by pi0** [comment] 2017-06-12 00:35
With 549b8da transitions should be combined together so that `beforeLeave`, `leave`, `afterLeave` and `leaveCancelled` are being picked from source route. (If available). Also nuxt-child's instance is available in transitions hooks using `this` and `this.$el`. (2b2d9e5)

Demo:
![image](https://user-images.githubusercontent.com/5158436/27015777-5971a800-4f2c-11e7-950f-5e03e830aa9c.png)

**Comment by sdras** [comment] 2017-06-12 01:27
you're a rockstar, @pi0, thanks so much

**Comment by Atinux** [comment] 2017-08-01 09:09
Closing it since `rc3` is out :)

**Closed by Atinux** 2017-08-01 09:09 UTC
Labels: available soon, bug
