### ISSUE TITLE
Combining Server Side Rendering and Static Site Generation

### ISSUE THREAD

**Issue by baermathias** [nuxt/nuxt.js#9266] opened 2021-05-10 09:24 UTC
### Is your feature request related to a problem? Please describe.

Is there a way to use **SSR and SSG in combination**? 
Lets assume my web app has two main areas: 
1. `area 1` has very dynamic content
2. `area 2` has very static content. 

Using SSG is not possible, because it would not allow to use all the features from the dynamic `area 1` (e.g. bookmarks, likes, followings, etc.), but using pure SSR would be very inefficient since the static `area 2` has high traffic on their routes.

### Describe the solution you'd like
It would be great if it would be possible to configure certain routes as static content and other ones as dynamic content, so the static content would be pre-rendered at build time and the dynamic content would use a web server to compile HTML on-the-fly :
```javascript
{
    path: '/static-sites/:id',
    name: 'SomeName',
    component: SomeComponent,
    contentType: 'static'
},
{
    path: '/dynamic-area/:id',
    name: 'SomeName',
    component: SomeComponent,
    contentType: 'dynamic'
},
```
If there is already a solution to this, I would be thankful if somebody could provide a link

**Comment by silvio-e** [comment] 2021-05-12 07:19
I found recently this: https://github.com/nuxt/vercel-builder#generatestaticroutes

> To pre-render routes during the build using nuxt generate set this to true. Routes that are not generated will fallback to the server lambda. You will need to specify the routes to be generated in your nuxt.config.

I'm not sure if that helps?

**Comment by Cpaczek** [comment] 2021-05-14 15:50
I think next is adding something similar to this. Fireship did a video on it and its called ISR https://www.youtube.com/watch?v=Sklc_fQBmcs not sure if its the exact same thing but it looks close.

**Comment by baermathias** [comment] 2021-05-15 13:07
@Cpaczek Thank you for the link, I think ISR (Incremental Static Regenerating) is something else, it allows you to configure a certain timeline after which Next regenerates the page at most 1 time for every x seconds. But in Next.js as far as I understand from this video you are not limited to the static OR the server target, you can combine those paradigms.

@silvio-e Thank you for the link. I have to check vercel-builder... can it only be used with Vercel?

**Comment by saitam1** [comment] 2021-05-15 13:09
+1 for this feature

**Comment by manniL** [comment] 2021-05-15 16:41
Duplicate of https://github.com/nuxt/nuxt.js/issues/7813

**Comment by silvio-e** [comment] 2021-05-19 07:46
@baermathias @danielroe wrote me recently on following on Twitter:

> You're right, it can be done. @​nuxt/vercel-builder does it for you, but you can also do the same thing in your own project (assuming you're not using `target: static`).

**Comment by iBobik** [comment] 2022-01-12 18:08
I would do it outside of Nuxt. 2 possible solutions:

1. In generate.routes specify static pages, deploy it to a static hosting supporting dynamic 404 response (Firebase, can call Cloud Functions or Cloud Run).
2. Deploy Nuxt in Node server in SSR mode and add reverse proxy cache (Varnish), which will cache e.g. some pages for a week, some for a 5 minutes, some do not cache.

**Comment by joffreyBerrier** [comment] 2022-04-08 09:02
+1 for this feature @danielroe 🙏

**Comment by HelloAlexPan** [comment] 2022-04-08 10:36
[With nitro, the team surely have to be working on a distributed persistent rendering](https://www.netlify.com/blog/2021/04/14/distributed-persistent-rendering-a-new-jamstack-approach-for-faster-builds/) right? Would love confirmation on whether Nuxt 3 plans to support this @danielroe

**Comment by waldemarennsaed** [comment] 2022-12-27 08:59
is this ticket still relevant and being discussed? Would love to see some progress here.

**Comment by manniL** [comment] 2022-12-28 10:28
Just FYI: This is already possible in Nuxt 3 but not in Nuxt 2

**Comment by AndreasKubasa** [comment] 2022-12-28 10:39
Yes, imho, this issue can be closed, makes no sense to add it to nuxt 2 as nuxt 3 supports it.

Nuxt plugins need to be pushed to be available in nuxt 3 to make it easier to switch from nuxt 2 to 3 🙏

**Comment by manniL** [comment] 2022-12-29 10:14
Closing here then ☺️

**Closed by manniL** 2022-12-29 10:14 UTC
Labels: feature-request, 3.x

**Comment by baermathias** [comment] 2022-12-29 16:28
@manniL could you please provide a docs link in regard to this nuxt 3 feature?

**Comment by manniL** [comment] 2022-12-29 19:28
Sure. Please check https://nuxt.com/docs/guide/concepts/rendering#route-rules for mixing SSR/SPA/SWR/... and check https://nuxt.com/docs/getting-started/deployment#static-hosting regarding SSR + SSG
