### ISSUE TITLE
CSS loaded in wrong (also varying) order

### ISSUE THREAD

**Issue by pearofducks** [nuxt/nuxt.js#3851] opened 2018-09-05 12:36 UTC
### Version

[v1.4.2](https://github.com/nuxt.js/releases/tag/v1.4.2)

### Reproduction link

[https://github.com/pearofducks/nuxt-bug-reproduction](https://github.com/pearofducks/nuxt-bug-reproduction)

### Steps to reproduce

- `yarn` then `yarn dev` to bootstrap
- observe that for `div.page-content`: `foo.css` is loaded *after* `default.vue` and `index.vue` — this is 100% counter to what should be done for base CSS imports, components should be able to override these

bonus round:
- change `nuxt.config.js` CSS property to import `test.css` instead of `foo.css` (commented in file)
- observe that the CSS loading order has completely changed and `test.css` now comes *before* the components

### What is expected ?

 config.css files should always be loaded before component-based styles

### What is actually happening?

config.css is sometimes being loaded after component-based styles, and sometimes after — dependent on the file (size?)

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7688">#c7688</a>)</em></sub></div>

**Comment by damien-biasotto** [comment] 2018-09-14 07:58
I can reproduce it on legacy (1.4.2) but it seems to be fixed on nuxt edge.

**Closed** 2018-09-18 07:52 UTC
Labels: cmty:bug-report
