### ISSUE TITLE
bug on nested routes with vue-meta on .10.x release

### ISSUE THREAD

**Issue by dohomi** [nuxt/nuxt.js#449] opened 2017-03-26 01:41 UTC
Hello,
I see following error on the server side and then NUXT is shutting down:

```
/data/vuejs/students-admin/node_modules/vue-meta/lib/vue-meta.js:824
    var htmlTag = document.getElementsByTagName('html')[0];
                  ^

ReferenceError: document is not defined
    at updateClientMetaInfo (/data/example-project/node_modules/vue-meta/lib/vue-meta.js:824:19)
    at Vue$2.refresh (/data/example-project/node_modules/vue-meta/lib/vue-meta.js:885:35)
    at /data/example-project/node_modules/vue-meta/lib/vue-meta.js:1007:74
    at Timeout._onTimeout (/data/example-project/node_modules/vue-meta/lib/vue-meta.js:924:5)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by dohomi** [comment] 2017-03-26 01:45
Steps to reproduce:
* /client => renders OK
* /client/clientId/base => renders OK (click on router link)
* page reload of nested child => throws error and server stops

There seems to be an error while loading a nested child element on server start.

**Comment by alexchopin** [comment] 2017-03-27 10:46
Hi, I can't reproduce your issue.
Can you explain/show us more about your code?

**Comment by dohomi** [comment] 2017-03-28 03:36
I do not use any head specific code. My project structure is looking like this:
<img width="178" alt="screen shot 2017-03-28 at 11 34 30" src="https://cloud.githubusercontent.com/assets/489221/24388004/c6e8048c-13aa-11e7-9e55-97d180fb3cb8.png">

**Comment by alexchopin** [comment] 2017-03-28 08:00
That's weird, I still can't reproduce it.
Can you try again to reinstall your node_modules?

**Comment by dohomi** [comment] 2017-03-29 02:22
@alexchopin I removed the node_models folder without success. Here a bit more of my `_id.vue` setup:

```
<template>
<div>
(some navigation content)
</div>
<nuxt-child :model="model"/>

</template>
<script>
(...)
   apollo: {
            query: {
                variables(){
                    return {
                        id: this.$route.params.id
                    };
                },
                query: Client,
                update: ({Client}) => ({client: Client}),
                result({Client}) {
                    this.model = Object.assign({}, this.model, Client);
                }
            }
        }

</script>
```

If I wrap the nuxt-child like this
```
<template v-if="false">
<nuxt-child :model="model"/>
</template>
```
It works, but then I don't have the model context inside of my child routes. So I'm bit confused if this is the wrong structure of my code?

**Comment by alexchopin** [comment] 2017-03-29 13:01
Have you tried to use the `store` instead of `model`?

**Comment by dohomi** [comment] 2017-03-29 14:12
Not yet.. I will try this tomorrow. My question is: can I pass the model to the `nuxt-child` like how I did it in my example? 
```<nuxt-child :model="model"/>```
If not I will use vuex to archive that.. Will report tomorrow if its successful

**Comment by dohomi** [comment] 2017-03-30 07:39
I tried to split my logic into `vuex` but it feels a little troubled.. because with the use of vue-apollo the whole simplified logic will become quite complicated. This is the server output just when vue-meta breaks:
```
{ title: '',
  titleChunk: '',
  titleTemplate: '%s',
  htmlAttrs: {},
  bodyAttrs: {},
  meta: [],
  base: [],
  link: [],
  style: [],
  script: [],
  noscript: [],
  __dangerouslyDisableSanitizers: [] } { keyName: 'head',
  attribute: 'data-n-head',
  ssrAttribute: 'data-n-head-ssr',
  tagIDKeyName: 'hid' }
```
In my opinion this code should never being triggered. Any idea what could cause this?

**Comment by JiriChara** [comment] 2017-04-02 10:09
@dohomi, @alexchopin I am having the same issue, but it only seems to happen when I add some field validations using https://github.com/monterail/vuelidate

This works fine:

```js
export default {
    head: {
      title: 'Login'
    },

    data() {
      return {
        email: '',
        password: ''
      };
    },
   //---
};
```

,but following code throws error:

```js
export default {
    head: {
      title: 'Login'
    },

    data() {
      return {
        email: '',
        password: ''
      };
    },

    validations: {
      email: {
         required: true
      }
    }
   //---
};
```

```
/home/jiri/Projects/chara.vip/node_modules/vue-meta/lib/vue-meta.js:824
    var htmlTag = document.getElementsByTagName('html')[0];
                                                       ^

ReferenceError: document is not defined
    at updateClientMetaInfo (/home/jiri/Projects/chara.vip/node_modules/vue-meta/lib/vue-meta.js:824:56)
    at Vue$2.refresh (/home/jiri/Projects/chara.vip/node_modules/vue-meta/lib/vue-meta.js:885:35)
    at /home/jiri/Projects/chara.vip/node_modules/vue-meta/lib/vue-meta.js:1007:74
    at Timeout._onTimeout (/home/jiri/Projects/chara.vip/node_modules/vue-meta/lib/vue-meta.js:924:5)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by dohomi** [comment] 2017-04-02 23:31
@JiriChara interesting, I am using vuelidate as well. Didn't find a connection between these packages that this is the reason for it.

**Comment by PierreRambaud** [comment] 2017-04-10 05:57
Hi guys,

Downgrading to Vue-meta 0.5.5 fix the problem. I'm having the same issue without using validations.

Regards

**Comment by JiriChara** [comment] 2017-04-11 09:05
I am using `vue-meta@0.5.5` and still having the issue

**Comment by wushan** [comment] 2017-04-19 04:07
same error but I am not using any nested router yet.

**Comment by tforssander** [comment] 2017-04-26 08:52
Same issue here after installing `vuex-router-sync` (by following the steps by @Atinux in [#213](https://github.com/nuxt/nuxt.js/issues/213#issuecomment-278007025). Removing the plugin fixes it.

**Comment by dohomi** [comment] 2017-04-26 08:59
Its kind of weird, nested routes seem to work after page-reload again but not on initial routing. What is bugging me most is that there isn't any error thrown, the page just simply stays blank.. It might be related to vue-apollo though..

**Comment by JiriChara** [comment] 2017-04-26 09:04
@dohomi it is only failing when the page is rendered on the server, because `document` is not defined there. Only the initial load is rendered on the server

**Comment by guumaster** [comment] 2017-04-29 12:51
(I'll add the comment here too, as this issue is still opened)

The `vuex-router-sync` plugin solution that @Atinux propose on #213 makes dev/prod server crash on every page reload. I'm getting this error:

```
/my_nuxt_app_path/node_modules/vue-meta/lib/vue-meta.js:824
    var htmlTag = document.getElementsByTagName('html')[0];
                  ^

ReferenceError: document is not defined
    at updateClientMetaInfo (/my_nuxt_app_path/node_modules/vue-meta/lib/vue-meta.js:824:19)
    at Vue$2.refresh (/my_nuxt_app_path/node_modules/vue-meta/lib/vue-meta.js:885:35)
    at /my_nuxt_app_path/node_modules/vue-meta/lib/vue-meta.js:1013:74
    at Timeout._onTimeout (/my_nuxt_app_path/node_modules/vue-meta/lib/vue-meta.js:924:5)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
``` 

My route is also nested: `/something/_slug/_id`, and it works again if I remove the plugin `plugins/vue-router-sync.js` from the list.

**Comment by guumaster** [comment] 2017-04-30 12:11
I've fixed it by using `vue-router-sync` only on client side by updating my plugin config like this: 

```
// nuxt.config.js
   plugins: [
      ....
     { src: '~plugins/vuex-router-sync.js', ssr: false }
   ]
```

**Comment by corsen2000** [comment] 2017-05-09 17:14
Also running into this issue. We are not using `vue-router-sync`. Seems likely related to [vue-meta issue](https://github.com/declandewet/vue-meta/issues/82), but unfortunately issue has been opened for some time.

Does anyone have a work around?

**Comment by corsen2000** [comment] 2017-05-09 17:31
Did a little digging and found both `vue-router-sync` and our code was making use of `store.registerModule`. I think anyone using that function directly or indirectly may run into this issue.

https://github.com/declandewet/vue-meta/issues/82#issuecomment-300241412

**Comment by jazoom** [comment] 2017-05-15 10:58
A PR with a fix has been pending for a month now over in vue-meta, just waiting for a maintainer to pull it:

https://github.com/declandewet/vue-meta/issues/82

**Comment by Atinux** [comment] 2017-05-15 12:36
Should be fixed in the upcoming version of Nuxt.js

**Comment by Atinux** [comment] 2017-08-01 09:13
Closing since `rc3` is out :)

**Closed by Atinux** 2017-08-01 09:13 UTC
Labels: available soon, help wanted
